import type { InterviewQ, Topic } from "../schema.ts";

// Embedded Engineering track, levels 8-12: production firmware, embedded Linux/BSP, crossover, specializations, career.
// Versions verified on 2026-09-24: MCUboot v2.4.0, U-Boot v2026.07, Buildroot 2026.08, Yocto 6.0 "Wrynose" LTS.
const q = (question: string, a: string, level: 1 | 2 | 3 | 4 = 2, trap?: string): InterviewQ => ({ q: question, a, level, trap });

export const EMB_C: Topic[] = [
  {
    id: "emb-bootloader", title: "Bootloaders: image format, integrity and jumping to the application", phase: "e8", module: "e8a",
    priority: "must", depth: "advanced", difficulty: 4, days: 2, hours: 7, kind: "coding", skills: ["firmware"],
    why: "Every product that can be updated needs a bootloader, and 'what is a bootloader and how does it hand over to the app?' is a standard interview question.",
    problem: "Without a bootloader a bad update or a power cut during programming bricks the device; a careless bootloader can brick it just as well.",
    eli12: "The bootloader is the doorman. At power-on it checks that the program in the building is complete and genuine, and only then opens the door. If the program is broken, it waits for a new one instead.",
    tech: "Flash layout: bootloader region (small, rarely or never updated), one or two application slots, metadata. Image header: magic, version, size, load address, integrity value (CRC-32 for accidental corruption, SHA-256 plus signature for authenticity). Transport: UART, USB DFU, CAN or network. Handover: validate the image, de-initialise peripherals and clocks used, disable interrupts and clear pending bits, set VTOR to the application's vector table, load MSP from the application's vector 0, branch to its reset handler. The application must be linked for its slot address. Recovery mode on a button or failed validation; version and anti-rollback counters; never update the only bootloader without a fallback.",
    inChip: "Chips have immutable boot ROMs that load a first-stage bootloader; SoC boot flow is shared ground between VLSI and firmware teams.",
    breaks: "Jumping with interrupts still enabled, application linked at the wrong address, bootloader and app disagreeing on clock setup.",
    tested: "Corrupt the image and verify rejection; cut power during update; boot every combination of old and new images.",
    prereqs: ["emb-linker-startup", "emb-wdt-flash", "emb-uart"],
    objectives: ["Design a flash layout and image header", "Validate an image with CRC and version checks", "Hand over cleanly to an application", "Provide a recovery path"],
    terms: [["Slot", "Flash region holding one firmware image"], ["VTOR", "Vector table offset register"], ["Image header", "Metadata in front of a firmware image"], ["Recovery mode", "Bootloader state that waits for a new image"]],
    code: { lang: "c", src: `#include <stdint.h>
#include "stm32f4xx.h"                         /* CMSIS device header */
#define APP_BASE 0x08010000UL

typedef void (*entry_t)(void);

void jump_to_app(void) {
    const uint32_t *vt = (const uint32_t *)APP_BASE;
    uint32_t sp = vt[0], reset = vt[1];
    if ((sp & 0x2FF00000UL) != 0x20000000UL) return;   /* sanity check: SP in SRAM */
    __disable_irq();
    SysTick->CTRL = 0;                                  /* stop what the bootloader started */
    for (int i = 0; i < 8; i++) { NVIC->ICER[i] = 0xFFFFFFFFUL; NVIC->ICPR[i] = 0xFFFFFFFFUL; }
    SCB->VTOR = APP_BASE;                               /* application's vector table */
    __set_MSP(sp);
    __DSB(); __ISB();
    __enable_irq();                                     /* the app re-enables what it needs */
    ((entry_t)reset)();                                 /* never returns */
}`, note: "Check the SRAM range and slot address for your MCU; production bootloaders also verify the image before jumping." },
    mistakes: ["Linking the application at address 0 instead of its slot", "Leaving peripherals running that fire interrupts into the new vector table", "Using CRC as a security measure"],
    practice: ["Write a UART bootloader that receives an image, checks CRC-32 and jumps; test with a deliberately corrupted image", "Document your flash map with addresses and sizes"],
    interview: [q("What does a bootloader do before jumping to the application on Cortex-M?", "Validates the image (header, size, CRC or signature, version), disables interrupts and stops peripherals it used, clears pending interrupts, sets VTOR to the app's vector table, loads MSP from the app's first word and branches to the app's reset handler.", 3)],
    resources: ["interrupt-blog", "yiu-cortexm"], projects: ["w-uart-bootloader"],
  },
  {
    id: "emb-ota", title: "Secure boot and OTA updates with MCUboot", phase: "e8", module: "e8a",
    priority: "must", depth: "working", difficulty: 4, days: 2, hours: 8, kind: "tool", skills: ["firmware"],
    why: "Signed firmware, fail-safe updates and rollback are what make a connected device trustworthy. MCUboot is the common open bootloader for this in Zephyr and other RTOS projects.",
    problem: "Home-made update schemes often lack authenticity checks, brick on power loss or cannot roll back a bad release.",
    eli12: "Every new program arrives with a wax seal only the factory can make. The doorman checks the seal, tries the new program once, and if the program does not say 'I'm fine' before the next restart, the old one comes back.",
    tech: "MCUboot: image header plus TLV trailer containing a hash and signature (ECDSA P-256, Ed25519 or RSA), produced by imgtool with a private key; the bootloader holds the public key (or its hash). Upgrade strategies: swap (with scratch, move or offset), overwrite-only, direct-XIP and RAM-load. Test-then-confirm: a new image boots once in test mode and must mark itself confirmed, otherwise the next reset reverts. Security counter for anti-rollback. Power-loss-safe swap resumes after reset. Transport via mcumgr/SMP over serial, BLE or UDP, or your own HTTP/MQTT client. Zephyr integrates it through sysbuild; ESP-IDF has its own OTA with rollback. Latest release tag verified: v2.4.0.",
    inChip: "Secure boot starts in silicon: boot ROM and fused key hashes form the root of trust that MCUboot extends.",
    breaks: "Private keys committed to repositories, new images never confirmed so every reboot reverts, slots too small for growth.",
    tested: "Signed and unsigned images, wrong-key images, power cuts during swap, unconfirmed image revert.",
    prereqs: ["emb-bootloader", "emb-iot-proto"],
    objectives: ["Sign an image with imgtool", "Choose an upgrade strategy and slot layout", "Implement test-then-confirm with rollback", "Build an OTA client that downloads into the secondary slot"],
    terms: [["TLV", "Type-length-value metadata appended to the image"], ["imgtool", "MCUboot signing tool"], ["Image confirmation", "App marks a trial image permanent"], ["Security counter", "Monotonic value blocking downgrades"]],
    mistakes: ["Confirming the image before the app has checked connectivity and health", "Using the example development key in production", "No plan for key rotation"],
    practice: ["Build Zephyr + MCUboot with sysbuild, sign two versions, update over serial and demonstrate automatic revert", "Try to boot an image signed with the wrong key and capture the rejection log"],
    interview: [q("How does OTA rollback work?", "The new image is written to a secondary slot and booted in test mode; the application runs health checks and confirms itself. If it crashes or resets before confirming, the bootloader swaps back to the previous image on the next boot. A security counter prevents rolling back to a vulnerable version deliberately.", 3)],
    resources: ["mcuboot-docs", "gh-mcuboot", "nordic-academy-int"], projects: ["fe-secure-ota"],
  },
  {
    id: "emb-security", title: "Embedded security engineering", phase: "e8", module: "e8b",
    priority: "must", depth: "working", difficulty: 4, days: 2, hours: 7, kind: "theory", skills: ["firmware"],
    why: "Connected devices are attacked through their firmware, update path and debug ports, and regulation (for example the EU Cyber Resilience Act) now expects secure-by-design products with vulnerability handling.",
    problem: "Security added at the end (a TLS library and a password) leaves open debug ports, unsigned updates and keys in plain flash.",
    eli12: "Security is not one lock; it is a chain: a trusted first step, checks at every step after it, secrets kept in a safe, and the back door (debug port) welded shut before the device leaves the factory.",
    tech: "Threat modelling: assets, attackers, entry points, mitigations. Root of trust (immutable boot code plus fused key hash) and chain of trust through each boot stage. Key storage: secure elements, OTP/fuses, TrustZone-protected storage, never plaintext in flash. Debug lock (for example STM32 readout protection levels, Nordic APPROTECT) and its irreversibility. Secure update with rollback protection. Privilege separation with the MPU (unprivileged tasks cannot touch kernel or peripheral regions). Armv8-M TrustZone: secure and non-secure worlds, memory attribution by SAU/IDAU, non-secure-callable veneers entered with the SG instruction; Trusted Firmware-M provides PSA secure services. Cryptography basics: hashes, MACs, signatures, AEAD, a true random number generator; use vetted libraries. Awareness of side-channel (power, timing) and fault-injection (voltage or clock glitching) attacks. The VLSI road's Hardware security topic covers the silicon side.",
    inChip: "Crypto accelerators, key storage, TrustZone and secure debug are designed in hardware; firmware must configure them correctly.",
    breaks: "Readable firmware via an open debug port, keys extracted from flash, downgrade attacks to vulnerable versions.",
    tested: "Threat-model review, attempts to attach a debugger to a locked device, fuzzing of parsers, update negative tests.",
    prereqs: ["emb-ota"],
    objectives: ["Write a threat model for a device", "Explain root and chain of trust", "Configure the MPU for unprivileged tasks", "Explain TrustZone-M worlds and secure gateways"],
    terms: [["Root of trust", "Component trusted by definition that anchors all checks"], ["TrustZone-M", "Armv8-M hardware isolation of secure and non-secure software"], ["MPU", "Memory protection unit enforcing access rules per region"], ["Fault injection", "Glitching power or clocks to skip checks"]],
    mistakes: ["Leaving the debug port open in production", "One shared key across all devices", "Parsing network input without bounds checks"],
    practice: ["Write a one-page threat model for your gateway project", "Run one task unprivileged with an MPU region and show the MemManage fault when it touches a forbidden address"],
    interview: [
      q("What is secure boot?", "Each boot stage verifies the cryptographic signature of the next stage before running it, starting from an immutable root of trust (boot ROM plus a key or key hash in fuses), so only authorised firmware runs.", 2),
      q("What is a root of trust?", "The minimal hardware and immutable code that is trusted without verification (for example boot ROM and fused key hashes) and from which every later verification derives.", 2),
    ],
    resources: ["tfm-docs", "gh-tfm", "arm-armv8m", "gh-mbedtls"], projects: ["fe-secure-ota"],
  },
  {
    id: "emb-storage", title: "Flash storage and filesystems: littlefs, FAT and power-loss safety", phase: "e8", module: "e8b",
    priority: "should", depth: "working", difficulty: 3, days: 1, hours: 5, kind: "coding", skills: ["firmware"],
    why: "Configuration, logs and calibration data must survive power loss and years of writes.",
    problem: "Naive writes to flash corrupt data when power fails mid-write and wear out the same sectors repeatedly.",
    eli12: "Imagine rewriting a page in a notebook while someone may snatch the pen at any moment. You write the new version on a fresh page first, and only then cross out the old one.",
    tech: "NOR versus NAND flash; erase blocks and program units; wear levelling; bad blocks on NAND; FAT (widely compatible, not power-loss safe by design) versus littlefs (copy-on-write metadata, power-loss resilient, dynamic wear levelling, small RAM footprint). A/B record pattern for configuration: two copies with sequence numbers and CRC, write the older slot, read the newest valid one. Journaling concepts. External SPI NOR drivers (JEDEC ID, page program, sector erase, status polling). Test by cutting power at random points thousands of times.",
    inChip: "Flash controllers and external memory interfaces are SoC IP; data integrity is a product requirement.",
    breaks: "Corrupted settings after brown-outs, logs that stop when a sector wears out, FAT volumes needing repair.",
    tested: "Automated power-cut testing with a relay or supply control, then integrity checks.",
    prereqs: ["emb-wdt-flash", "emb-drivers"],
    objectives: ["Implement an A/B config record with CRC", "Mount and use littlefs on SPI NOR", "Explain wear levelling", "Run a power-loss test campaign"],
    terms: [["Copy-on-write", "Write new data elsewhere, then switch pointers"], ["Wear levelling", "Spreading erases across blocks"], ["Erase block", "Smallest erasable flash unit"], ["JEDEC ID", "Standard manufacturer/device ID command"]],
    mistakes: ["Erasing before the new copy is safely written", "Using FAT for critical config without protection", "Never testing power loss"],
    practice: ["Implement the A/B config pattern and survive 1000 random power cuts in a test loop", "Port littlefs to an SPI NOR driver"],
    interview: [q("How would you store configuration so it survives power loss during a write?", "Keep two copies with a sequence number and CRC; always write the older copy, verify it, and at boot load the newest copy whose CRC is valid. Or use a power-loss-safe filesystem such as littlefs.", 2)],
    resources: ["gh-littlefs"], projects: ["w-spi-flash-fs"],
  },
  {
    id: "emb-performance", title: "Performance engineering: profiling, code size, stack and latency", phase: "e8", module: "e8b",
    priority: "should", depth: "working", difficulty: 3, days: 1, hours: 5, kind: "coding", skills: ["firmware"],
    why: "Firmware runs on fixed hardware budgets: cycles, RAM, flash and energy. Optimisation needs measurement, not folklore.",
    problem: "Guessing at hot spots wastes effort; aggressive optimisation without measurement often makes code larger or slower.",
    eli12: "Before making a runner faster, you time each lap. Performance engineering is timing each part of the program, fixing the slowest, and timing again.",
    tech: "Cycle counting with the DWT CYCCNT counter (Cortex-M3/M4/M7/M33; not M0/M0+), GPIO markers, timers; PC sampling via SWO; compiler levels -O0/-Og/-O2/-Os/-O3 and link-time optimisation; inlining and unrolling trade size for speed; flash wait states, caches and running hot code from RAM or TCM; code size from map files; stack usage with -fstack-usage and high-water marks; ISR latency; the polling versus interrupt versus DMA benchmark; FPU versus fixed point; CMSIS-DSP kernels; energy per operation.",
    inChip: "Architecture choices studied on the VLSI road (caches, pipelines, TCM) show up directly in these measurements.",
    breaks: "Optimising the wrong function, -O3 blowing the flash budget, cache effects making benchmarks misleading.",
    tested: "Before/after tables with the method, build flags and board stated.",
    prereqs: ["emb-dma", "emb-instruments"],
    objectives: ["Measure cycles with DWT and GPIO markers", "Compare optimisation levels for size and speed", "Measure stack usage", "Benchmark polling, interrupt and DMA"],
    terms: [["DWT CYCCNT", "Cycle counter in the Data Watchpoint and Trace unit"], ["TCM", "Tightly coupled memory with single-cycle access"], ["LTO", "Link-time optimisation across files"]],
    mistakes: ["Benchmarking at -O0", "Reporting one run instead of a distribution", "Forgetting to enable the DWT counter (DEMCR.TRCENA)"],
    practice: ["Profile an FIR filter at -O0, -O2, -Os and -O3; report cycles and size", "Benchmark UART transmission by polling, interrupt and DMA and report CPU load"],
    interview: [q("How do you measure how long a function takes on a Cortex-M4?", "Enable the DWT cycle counter (TRCENA in DEMCR, CYCCNTENA in DWT_CTRL), read CYCCNT before and after, subtract; or toggle a GPIO and measure with a logic analyzer. Repeat many times and report worst case, not just average.", 2)],
    resources: ["gh-cmsis-dsp", "yiu-cortexm", "interrupt-blog"], projects: ["fe-fw-stack"],
  },
  {
    id: "emb-production", title: "Production firmware: releases, telemetry, field diagnostics and manufacturing", phase: "e8", module: "e8b",
    priority: "must", depth: "working", difficulty: 3, days: 2, hours: 6, kind: "career", skills: ["firmware"],
    why: "Shipping is where firmware engineering becomes a profession: versioned releases, signed artifacts, crash reports from the field and factory programming.",
    problem: "Hobby projects stop at 'it works on my desk'; products must be reproducible, diagnosable and maintainable for years.",
    eli12: "A product is like a car that keeps driving after it leaves the factory. You need its serial number, a record of every part, a way to read its warning lights from far away and a safe way to send it fixes.",
    tech: "Version and build ID embedded in the image (for example git hash) and reported at boot; reproducible builds with pinned toolchain containers; release branches and tags; archived artifacts (ELF with symbols, map, signed binary); signing keys in an HSM or offline system; bootloader compatibility rules; telemetry, reset-cause statistics and coredumps uploaded from the field; a diagnostics CLI; staged OTA rollouts with rollback; manufacturing: programming fixtures, per-device provisioning (serial number, keys, calibration), end-of-line tests; documentation set (hardware, firmware architecture, protocol, pinout, timing, state machines, build/flash/test instructions, debugging guide, known issues); SBOMs and vulnerability handling.",
    inChip: "Chip companies ship production programming tools and security provisioning flows; device makers integrate them into factories.",
    breaks: "Unreproducible builds, lost ELF files for released versions, factory-programmed devices with identical keys, fleets failing silently.",
    tested: "Rebuild an old release bit-for-bit; decode a field coredump; dry-run a factory provisioning script.",
    prereqs: ["emb-ota", "emb-ci-static"],
    objectives: ["Embed version and build ID and report them", "Produce and archive release artifacts", "Design a crash-reporting path", "Describe a factory provisioning flow"],
    terms: [["Build ID", "Unique identifier of an exact build"], ["Coredump", "Snapshot of memory and registers after a crash"], ["Provisioning", "Loading device-unique identity and keys"], ["SBOM", "Software bill of materials"]],
    mistakes: ["Not archiving the ELF of each release", "Shipping with debug logging that leaks secrets", "One key shared across the fleet"],
    practice: ["Add a version/build-ID command to your CLI and include it in CI artifacts", "Write the release checklist and documentation set for one project"],
    interview: [q("A device in the field reboots every few days. How would you diagnose it remotely?", "Collect reset causes and uptime from telemetry, capture a crash record or coredump in no-init RAM and upload it on next boot, symbolise it with the archived ELF for that build ID, correlate with conditions (temperature, network), reproduce with a soak test.", 3)],
    resources: ["interrupt-blog", "making-embedded"], projects: ["fe-secure-ota"],
  },
  {
    id: "emb-linux-sys", title: "Linux systems programming for embedded engineers", phase: "e9", module: "e9a",
    priority: "must", depth: "working", difficulty: 3, days: 2, hours: 7, kind: "coding", skills: ["emblinux", "linux", "cpp"],
    why: "Embedded Linux roles expect you to write reliable user-space services and to understand what the kernel does for them before you write kernel code.",
    problem: "MCU habits (busy loops, global state, no permissions) produce Linux services that waste CPU, leak resources and fail under systemd.",
    eli12: "On a microcontroller your program owns the whole machine. On Linux, many programs share it, and the kernel acts like a building manager handing out rooms, keys and time.",
    tech: "Processes and threads (fork, exec, pthreads), scheduling (default fair scheduling, SCHED_FIFO/SCHED_RR real-time policies; PREEMPT_RT has been in the mainline kernel since 6.12), virtual memory and mmap, files, permissions and capabilities, signals, pipes, message queues, shared memory, sockets, system calls (inspect with strace), /dev, /sys and /proc, udev, systemd services and logging. Hardware from user space: libgpiod (GPIO character device), i2c-dev, spidev, serial ports with termios. Cross-compiling user applications.",
    inChip: "Gateways, cameras, routers, vehicle head units and industrial controllers run Linux user-space services talking to MCU coprocessors.",
    breaks: "Zombie processes, file descriptor leaks, priority inversions with real-time threads, services that fail silently.",
    tested: "strace, valgrind or sanitizers on the host, systemd journal, long-running soak tests.",
    prereqs: ["linux-shell", "emb-c-memory", "emb-rtos-sync"],
    objectives: ["Write a multi-threaded service with clean shutdown on signals", "Use sockets and IPC", "Access GPIO and I2C from user space", "Run it as a systemd service"],
    terms: [["System call", "Request from user space to the kernel"], ["libgpiod", "Library for the GPIO character-device interface"], ["PREEMPT_RT", "Real-time preemption support, mainline since Linux 6.12"], ["systemd unit", "Service definition managed by systemd"]],
    mistakes: ["Using the deprecated sysfs GPIO interface in new code", "Busy-waiting instead of poll/select", "Running everything as root"],
    practice: ["Write a sensor daemon reading I2C via i2c-dev and publishing over a UNIX socket, with systemd unit and clean SIGTERM handling", "strace your daemon and explain each system call in its main loop"],
    interview: [q("How does a user-space program read an I2C sensor on Linux without a kernel driver?", "Open /dev/i2c-N, set the slave address with ioctl(I2C_SLAVE), then read/write or use I2C_RDWR for combined transactions. A kernel driver is preferable when the device should be shared, needs interrupts or fits an existing subsystem.", 2)],
    resources: ["kerrisk-tlpi", "mastering-emb-linux", "gh-bootlin-training"],
  },
  {
    id: "emb-linux-boot", title: "Cross-compilation and the embedded Linux boot chain", phase: "e9", module: "e9a",
    priority: "must", depth: "working", difficulty: 3, days: 2, hours: 6, kind: "theory", skills: ["emblinux", "linux"],
    why: "BSP engineers own every step from power-on to login prompt. Knowing each stage lets you localise a boot failure in minutes.",
    problem: "When a board prints nothing, or stops after 'Starting kernel...', engineers without a boot-chain model start guessing.",
    eli12: "Starting a Linux board is a relay race: a tiny runner in the chip hands the baton to the bootloader, which hands it to the kernel, which hands it to the first program, which starts everything else.",
    tech: "Toolchains and triplets (aarch64-linux-gnu, arm-linux-gnueabihf), sysroot, C libraries (glibc, musl), dynamic linking (the loader, readelf -d, ldd). Boot chain: boot ROM, first-stage loader (U-Boot SPL; on many 64-bit Arm SoCs Trusted Firmware-A), U-Boot proper, kernel image plus device tree blob (plus optional initramfs), init (systemd or BusyBox init), root filesystem. Kernel command line (console=, root=, rootwait). Serial console is the essential debug channel. Root filesystem layout, BusyBox. Practise on QEMU's virt machine before real boards.",
    inChip: "Boot ROM behaviour, boot-mode pins and first-stage loaders are defined by the SoC team; BSP engineers consume them.",
    breaks: "Wrong DTB for the board, missing root= or wrong partition, kernel lacking the storage driver, C library mismatch between toolchain and rootfs.",
    tested: "Serial console logs at each stage; boot in QEMU; compare against a known-good image.",
    prereqs: ["emb-linux-sys", "emb-toolchain"],
    objectives: ["Name each boot stage and what it loads", "Cross-compile and run an application on a target rootfs", "Read a kernel boot log", "Explain the kernel command line"],
    terms: [["SPL", "Secondary program loader: small first stage of U-Boot"], ["DTB", "Compiled device tree blob"], ["initramfs", "Early root filesystem in RAM"], ["Sysroot", "Target headers and libraries used when cross-compiling"]],
    mistakes: ["Linking against host libraries by accident", "Debugging boot without a serial console", "Mixing kernel and DTB from different builds"],
    practice: ["Boot a kernel and BusyBox rootfs in QEMU (aarch64 virt) and annotate each stage of the log", "Cross-compile a C program and run it on the QEMU target"],
    interview: [q("A board prints U-Boot messages, then 'Starting kernel ...' and nothing more. What do you check?", "Kernel console settings (console= and earlycon in bootargs), that the DTB matches the board and was loaded to the right address, that kernel and DTB come from the same build, and the kernel's UART driver; then use earlycon or a JTAG debugger to see where it stops.", 3)],
    resources: ["mastering-emb-linux", "gh-bootlin-training", "qemu-arm-docs"],
  },
  {
    id: "emb-uboot", title: "U-Boot: environment, boot scripts and recovery", phase: "e9", module: "e9b",
    priority: "should", depth: "working", difficulty: 3, days: 1, hours: 5, kind: "tool", skills: ["emblinux"],
    why: "U-Boot is the standard bootloader for embedded Linux boards; bring-up, network boot for development and field recovery all go through it.",
    problem: "Treating the bootloader as a black box leaves no way to recover boards or change boot behaviour safely.",
    eli12: "U-Boot is the board's pre-flight checklist. It can load the operating system from a card, a USB stick or the network, and it can fall back to a spare if the main one fails.",
    tech: "SPL and U-Boot proper; the console and commands; environment variables (bootcmd, bootargs, bootdelay) and saveenv; loading images (load from MMC/USB, tftp over the network) and booting (booti for arm64 Image, bootz for zImage, bootm for legacy and FIT); boot scripts built with mkimage; FIT images bundling kernel, DTB and initramfs, optionally signed for verified boot; standard boot (bootstd) and distro boot conventions; A/B booting with bootcount and altbootcmd; device-tree fixups. Latest release tag verified: v2026.07.",
    inChip: "Silicon vendors maintain U-Boot ports for their SoCs; board makers add board files and device trees.",
    breaks: "Environment corrupted or stored in the wrong place, bootargs overwritten, boot loops with no fallback.",
    tested: "Network-boot the kernel from TFTP, then switch to storage boot; simulate a failed update and verify fallback.",
    prereqs: ["emb-linux-boot"],
    objectives: ["Use the U-Boot console to load and boot a kernel", "Write a boot script", "Build a FIT image", "Implement A/B fallback with bootcount"],
    terms: [["bootcmd", "Command run automatically after the boot delay"], ["bootargs", "Kernel command line passed by U-Boot"], ["FIT", "Flattened Image Tree bundling several images"], ["bootcount", "Counter used to detect failed boots"]],
    mistakes: ["Editing bootargs on the console and forgetting saveenv", "Boot scripts without error handling", "No fallback path after an update"],
    practice: ["TFTP-boot a kernel and DTB on QEMU or a board from the U-Boot console", "Create a boot.scr that selects slot A or B based on a variable"],
    interview: [q("How do you pass kernel parameters and select a device tree from U-Boot?", "Set bootargs (the kernel command line) in the environment and load the DTB to memory, passing its address to booti/bootz, or bundle kernel and DTB in a FIT image with configurations.", 2)],
    resources: ["uboot-docs", "gh-uboot", "gh-bootlin-training"],
  },
  {
    id: "emb-devicetree", title: "Device tree: describing hardware to Linux and Zephyr", phase: "e9", module: "e9b",
    priority: "must", depth: "working", difficulty: 3, days: 2, hours: 6, kind: "coding", skills: ["emblinux", "rtos"],
    why: "On Arm Linux and in Zephyr, hardware that is not in the device tree does not exist for drivers. 'How does Device Tree work?' is a standard BSP interview question.",
    problem: "Hard-coding board details into drivers makes every board a fork of the kernel; the device tree separates description from code.",
    eli12: "The device tree is the board's floor plan. The kernel reads it to learn which chips are in which rooms, and then sends the right specialist (driver) to each one.",
    tech: "DTS and DTSI include hierarchy (SoC .dtsi, board .dts); nodes and properties; compatible strings ('vendor,device') used for driver matching; reg, interrupts, clocks, pinctrl, status = 'okay' or 'disabled'; labels and phandles; aliases and chosen; overlays (.dtbo) applied by the bootloader for add-on boards; bindings documented as YAML schemas in the kernel (validate with dtbs_check); dtc to compile and decompile; /proc/device-tree at run time. Zephyr uses the same language at build time.",
    inChip: "SoC vendors publish the SoC .dtsi; board makers write .dts files; driver writers define bindings.",
    breaks: "Typos in compatible strings (driver never probes), wrong interrupt specifiers, pinmux conflicts, nodes left disabled.",
    tested: "dtbs_check validation, boot logs showing probe success, inspection of /proc/device-tree and /sys/bus.",
    prereqs: ["emb-uboot"],
    objectives: ["Read a board .dts and its SoC .dtsi", "Enable a UART and describe an I2C device", "Write and apply an overlay", "Validate against bindings"],
    terms: [["compatible", "String list used to match a node to a driver"], ["phandle", "Reference from one node to another"], ["Overlay", "Fragment modifying a base device tree"], ["Binding", "Schema defining a node's required properties"]],
    code: { lang: "dts", src: `&i2c1 {
    status = "okay";
    clock-frequency = <400000>;

    temp_sensor: sensor@48 {
        compatible = "acme,tmp100x";      /* must match the driver's of_match_table */
        reg = <0x48>;                     /* I2C address */
        interrupt-parent = <&gpio1>;
        interrupts = <12 IRQ_TYPE_EDGE_FALLING>;
    };
};`, note: "'acme,tmp100x' is a made-up example; real bindings are documented in the kernel's devicetree bindings directory." },
    mistakes: ["Editing the SoC .dtsi instead of the board file or an overlay", "Mismatched compatible strings", "Forgetting pinctrl for the pins a peripheral uses"],
    practice: ["Enable a disabled UART on a Raspberry Pi or QEMU board through an overlay and prove it in /dev and /proc/device-tree", "Describe an I2C sensor node and bind it to an existing kernel driver"],
    interview: [q("How does a Linux driver bind to hardware described in the device tree?", "The kernel creates a device for each enabled node; bus code compares the node's compatible strings with each driver's of_match_table; on a match the driver's probe() runs and reads resources (reg, interrupts, clocks) from the node.", 3)],
    resources: ["devicetree-spec", "kernel-driver-api", "gh-bootlin-training"], projects: ["w-linux-chardrv"],
  },
  {
    id: "emb-linux-drivers", title: "Linux kernel modules and device drivers", phase: "e9", module: "e9b",
    priority: "must", depth: "working", difficulty: 4, days: 3, hours: 12, kind: "coding", skills: ["emblinux", "cpp"],
    why: "Writing and debugging drivers is the core of BSP and embedded Linux roles, and 'what is a platform driver?' is asked often.",
    problem: "Starting with complex PCI or network drivers overwhelms; the kernel's rules (contexts, locking, user-copy, managed resources) must be learned on simple drivers first.",
    eli12: "A kernel driver is a specialist who works inside the operating system's office. It must follow strict office rules: never take too long, never touch someone else's desk without permission, and clean up after itself.",
    tech: "Out-of-tree modules (Kbuild, obj-m), module_init/module_exit, logging with dev_info; character devices (misc_register), file_operations (open, read, write, poll, unlocked_ioctl, mmap), copy_to_user/copy_from_user; the device model: buses, devices, drivers; platform drivers matched through of_match_table with probe/remove; I2C and SPI client drivers; managed resources (devm_*); sysfs attributes; interrupts with devm_request_threaded_irq, top and bottom halves, workqueues, wait queues; locking: spinlocks in atomic/interrupt context, mutexes in process context; DMA API awareness. Kernel coding style and checkpatch. Practise in QEMU first.",
    inChip: "Silicon vendors write and upstream drivers for their SoCs; your own FPGA or ASIC peripheral needs one too (the crossover project).",
    breaks: "Sleeping in atomic context, missing error unwinding, races between the IRQ handler and read(), use-after-free on remove.",
    tested: "Load/unload loops, lockdep and KASAN-enabled kernels, user-space test programs, stress tests.",
    prereqs: ["emb-devicetree", "emb-drivers"],
    objectives: ["Build and load an out-of-tree module", "Write a misc character driver with read/write/ioctl", "Write a platform driver bound through device tree", "Handle interrupts and locking correctly"],
    terms: [["Platform driver", "Driver for devices not on a discoverable bus, matched via device tree"], ["probe()", "Driver function called when a device matches"], ["devm_*", "Resource allocation released automatically on unbind"], ["Atomic context", "Context where sleeping is forbidden (interrupts, spinlocks)"]],
    code: { lang: "c", src: `#include <linux/module.h>
#include <linux/platform_device.h>
#include <linux/of.h>

static int demo_probe(struct platform_device *pdev)
{
    void __iomem *base = devm_platform_ioremap_resource(pdev, 0);  /* 'reg' from DT */
    if (IS_ERR(base))
        return PTR_ERR(base);
    dev_info(&pdev->dev, "demo peripheral id 0x%08x\\n", readl(base));
    return 0;                                   /* devm_* resources are freed automatically */
}

static const struct of_device_id demo_of_match[] = {
    { .compatible = "acme,demo-periph" },       /* example compatible string */
    { }
};
MODULE_DEVICE_TABLE(of, demo_of_match);

static struct platform_driver demo_driver = {
    .probe = demo_probe,
    .driver = { .name = "demo-periph", .of_match_table = demo_of_match },
};
module_platform_driver(demo_driver);
MODULE_LICENSE("GPL");`, note: "In the crossover project, the same probe reads the ID register of the peripheral you designed in RTL." },
    mistakes: ["Starting with a PCI or network driver", "Calling a sleeping function while holding a spinlock", "Dereferencing user pointers directly"],
    practice: ["Write a misc char driver with a ring buffer and test it with cat/echo and a C program", "Write a platform driver that binds to a device-tree node in QEMU and exposes a sysfs attribute"],
    interview: [
      q("What is a platform driver?", "A driver for a device on a non-discoverable bus (memory-mapped SoC peripherals); the kernel creates platform devices from device-tree nodes and binds them to drivers whose of_match_table matches the compatible string, calling probe().", 2),
      q("Spinlock or mutex inside an interrupt handler?", "Spinlock: interrupt context cannot sleep and a mutex may sleep. Use spin_lock_irqsave in process context when the same data is shared with the IRQ handler.", 3),
    ],
    resources: ["ldd3", "linux-kernel-labs", "kernel-driver-api", "gh-bootlin-training", "gh-linux"], projects: ["w-linux-chardrv", "fe-linux-bsp"],
  },
  {
    id: "emb-buildroot", title: "Building a Linux image with Buildroot", phase: "e9", module: "e9b",
    priority: "must", depth: "working", difficulty: 3, days: 2, hours: 7, kind: "tool", skills: ["emblinux", "linux"],
    why: "Buildroot is the approachable way to build a complete, small embedded Linux system (toolchain, bootloader, kernel, rootfs) and it teaches the whole flow before Yocto.",
    problem: "Hand-assembling toolchains and root filesystems is error-prone and not reproducible.",
    eli12: "Buildroot is a kitchen robot: you tick boxes for the dishes you want, press a button, and it cooks the whole meal from raw ingredients, the same way every time.",
    tech: "Start from a defconfig (for example a QEMU virt or Raspberry Pi config); make menuconfig; internal or external toolchain; U-Boot and kernel selection and configuration; BusyBox; root filesystem overlays; post-build and post-image scripts; output/images; BR2_EXTERNAL trees for your own packages, board files and defconfigs; a custom package (Config.in plus .mk using generic-package or cmake-package); an init script; savedefconfig; clean rebuild rules and reproducibility. Releases are quarterly (latest tag verified: 2026.08); the .02 release each year is the long-term-support branch.",
    inChip: "Many silicon vendors and small product teams ship Buildroot-based SDKs because of its simplicity.",
    breaks: "Stale builds after changing toolchain options (needs a clean build), packages missing from the image, configs lost without savedefconfig.",
    tested: "Clean build from the defconfig in CI; boot in QEMU; package present and service running.",
    prereqs: ["emb-linux-boot", "emb-uboot"],
    objectives: ["Build and boot a Buildroot image in QEMU", "Add a custom package through BR2_EXTERNAL", "Add an init script and rootfs overlay", "Keep the configuration in version control"],
    terms: [["defconfig", "Minimal saved configuration"], ["BR2_EXTERNAL", "Out-of-tree directory with your packages and configs"], ["Rootfs overlay", "Files copied onto the target filesystem"], ["generic-package", "Buildroot package infrastructure"]],
    mistakes: ["Editing files inside output/ instead of the configuration", "Not running a clean build after toolchain changes", "Keeping the config only on one laptop"],
    practice: ["Build a QEMU aarch64 image, boot it and log in", "Package your sensor daemon as a Buildroot package with an init script"],
    interview: [q("Buildroot or Yocto: when would you choose each?", "Buildroot for small, simple, single-product images with fast builds and a low learning curve; Yocto for product lines needing layers, package feeds, SDKs, fine-grained customisation, SBOM and licence compliance at scale, at the cost of complexity and build resources.", 2)],
    resources: ["buildroot-manual", "gh-buildroot", "gh-bootlin-training"], projects: ["w-buildroot-image"],
  },
  {
    id: "emb-yocto", title: "The Yocto Project and OpenEmbedded", phase: "e9", module: "e9b",
    priority: "should", depth: "working", difficulty: 4, days: 3, hours: 12, kind: "tool", skills: ["emblinux", "linux"],
    why: "Yocto appears in many embedded Linux and BSP postings because it scales to product lines, SDKs and compliance. Learn it after Buildroot.",
    problem: "Yocto's layer model and vocabulary are intimidating, and old tutorials based on the poky repository are now out of date.",
    eli12: "Yocto is a factory for Linux distributions. Layers are stacks of recipe books from different suppliers; you add your own book on top that changes only what you need.",
    tech: "BitBake executes recipes (.bb) and appends (.bbappend) organised into layers: openembedded-core, meta-yocto (the Poky reference distro), BSP layers (for example meta-raspberrypi) and your own product layer. MACHINE and DISTRO configuration; image recipes and IMAGE_INSTALL; classes; tasks (fetch, unpack, configure, compile, install, package); devtool for modifying recipes; sstate cache; SDK generation (populate_sdk); licence compliance and SPDX SBOMs. Current state (verified 2026-09-24): Yocto 6.0 'Wrynose' is the current LTS release (May 2026); the combined poky repository is deprecated in favour of the bitbake-setup tool or separate clones of bitbake, openembedded-core and meta-yocto, so older 'git clone poky' tutorials need adapting. Build hosts need substantial RAM and disk.",
    inChip: "SoC vendors ship Yocto BSP layers; product teams build distributions on top.",
    breaks: "Editing upstream layers directly, layer version mismatches, following pre-Wrynose setup instructions.",
    tested: "Reproducible image builds in CI, recipe changes via devtool, image boots in QEMU.",
    prereqs: ["emb-buildroot"],
    objectives: ["Set up a build with bitbake-setup for the current release", "Create a custom layer with a recipe and a bbappend", "Build and boot a custom image in QEMU", "Generate an SDK and an SBOM"],
    terms: [["Layer", "Collection of recipes and configuration"], ["Recipe", "Instructions to build one piece of software"], [".bbappend", "Modification of another layer's recipe"], ["bitbake-setup", "Tool that fetches layers and sets up build directories"]],
    mistakes: ["Modifying openembedded-core in place", "Copying setup steps from pre-2026 tutorials without checking the release", "Ignoring the shared-state cache and rebuilding from scratch every time"],
    practice: ["Build a minimal image for QEMU with the current release and boot it", "Create meta-myproduct with your daemon's recipe, a systemd service and an image recipe"],
    interview: [q("What is the difference between a .bb and a .bbappend file?", "A .bb recipe defines how to fetch, build and package software; a .bbappend in another layer modifies an existing recipe (adding patches, files or config) without editing the original.", 2)],
    resources: ["yocto-docs", "yocto-wrynose", "bitbake-setup", "bootlin-yocto-wrynose"], projects: ["fe-linux-bsp"],
  },
  {
    id: "emb-hwsw-crossover", title: "From RTL to driver: the VLSI + Embedded crossover", phase: "e10", module: "e10x",
    priority: "must", depth: "working", difficulty: 4, days: 3, hours: 12, kind: "project", skills: ["firmware", "rtl", "protocols"],
    why: "This repository's unique strength: you can design a peripheral in SystemVerilog, verify it, put it in an SoC, and write the firmware and driver that use it. That is exactly what pre-silicon firmware and SoC teams do.",
    problem: "Hardware and firmware engineers often meet only at the register map, and mismatched assumptions there cause late, expensive bugs.",
    eli12: "You build a new machine part and also write its instruction manual and the program that uses it. Because you did both, you know every button actually does what the manual says.",
    tech: "Workflow: hardware specification, register map (SystemRDL, generating RTL with PeakRDL-regblock plus a C header and documentation), RTL (APB or AXI-Lite slave, interrupt output), verification (cocotb or SystemVerilog with assertions), synthesis and timing, SoC integration (LiteX with a RISC-V soft core, or an FPGA SoC with a hard Arm core), C driver and firmware, co-simulation (Verilator running firmware on the soft core), FPGA validation with a logic analyzer, performance measurement, documentation. Hardware/software co-design choices: what belongs in RTL (accelerators, precise timing) versus firmware (policy, flexibility). The same flow runs in industry on emulators and FPGA prototypes before tapeout.",
    inChip: "Pre-silicon firmware, SoC integration, silicon validation and hardware/software co-design teams live exactly here.",
    breaks: "Register map and header out of sync, missing interrupt clearing semantics, bus-width and endianness mismatches, reset values undocumented.",
    tested: "The same register-level test runs in cocotb against RTL and as firmware on the FPGA.",
    prereqs: ["emb-drivers", "emb-dma", "apb", "soc-buses"],
    objectives: ["Write a register map once and generate RTL and C header from it", "Integrate a custom peripheral into a small RISC-V SoC", "Write a driver and interrupt handler for it", "Validate it in simulation and on FPGA"],
    terms: [["SystemRDL", "Language for describing register maps"], ["Soft core", "CPU implemented in FPGA logic"], ["Co-simulation", "Running firmware against simulated RTL"], ["Pre-silicon firmware", "Firmware developed before chips exist, on models or FPGA"]],
    mistakes: ["Hand-writing the register header separately from the RTL", "Leaving interrupt clear semantics undocumented (write-1-to-clear or read-to-clear)", "Testing hardware and firmware separately but never together"],
    practice: ["Define a timer/PWM peripheral in SystemRDL; generate RTL and header; verify with cocotb", "Add it to a LiteX SoC, write a bare-metal driver, and show PWM on a logic analyzer"],
    interview: [q("How do you keep hardware and firmware register definitions in sync?", "Single source of truth: describe registers in SystemRDL or IP-XACT and generate RTL, C headers, documentation and verification models from it in CI; review changes to that file like an interface change.", 3)],
    resources: ["peakrdl", "litex", "cocotb", "verilator"], projects: ["fx-soc-peripheral"], roles: ["emb-firmware", "validation"],
  },
  {
    id: "emb-automotive", title: "Automotive embedded: diagnostics, AUTOSAR and functional safety", phase: "e10", module: "e10-auto",
    priority: "specialization", depth: "basic", difficulty: 4, days: 3, hours: 12, kind: "theory", skills: ["firmware", "protocols"],
    why: "Automotive is one of the largest employers of embedded engineers, with its own protocols, architecture standards and safety processes.",
    problem: "General firmware skills are not enough: automotive interviews expect diagnostics, AUTOSAR vocabulary and safety awareness.",
    eli12: "A modern car has dozens of small computers talking over shared wires. Mechanics can ask each one what went wrong, and strict rules make sure a software mistake cannot make the car unsafe.",
    tech: "Networks: CAN and CAN FD, LIN, FlexRay awareness, automotive Ethernet with SOME/IP. Diagnostics: UDS (ISO 14229) services such as 0x10 session control, 0x11 ECU reset, 0x22 read and 0x2E write data by identifier, 0x27 security access, 0x31 routine control, 0x34/0x36/0x37 download; positive responses add 0x40 to the service ID; negative responses are 0x7F plus service and a response code. ISO-TP (ISO 15765-2) segments long messages (single, first, consecutive and flow-control frames). Flash bootloaders over UDS. AUTOSAR Classic (software components, RTE, basic software, MCAL) versus Adaptive (POSIX, service-oriented). Functional safety ISO 26262 (ASIL A-D), process maturity ASPICE, MISRA C, cybersecurity ISO/SAE 21434 and UN R155. AUTOSAR stacks and certified tools are commercial; learn concepts with SocketCAN, python-can and open UDS libraries.",
    inChip: "Automotive MCUs include lockstep cores, ECC and safety mechanisms designed for ISO 26262; firmware must use them.",
    breaks: "Diagnostic timeouts, flashing sequences bricking ECUs, safety arguments that do not match the code.",
    tested: "Diagnostic test tools against an ECU simulator; MISRA checks; safety analyses (FMEA/FTA) in real projects.",
    prereqs: ["emb-can", "emb-bootloader", "emb-ci-static"],
    objectives: ["Explain common UDS services and responses", "Explain ISO-TP segmentation", "Compare AUTOSAR Classic and Adaptive", "Explain ASIL levels and what ISO 26262 demands of software"],
    terms: [["UDS", "Unified Diagnostic Services (ISO 14229)"], ["ISO-TP", "Transport protocol for long messages over CAN"], ["AUTOSAR", "Standardised automotive software architecture"], ["ASIL", "Automotive Safety Integrity Level, A (lowest) to D"]],
    mistakes: ["Claiming AUTOSAR experience from reading slides", "Ignoring security access in bootloader designs"],
    practice: ["Implement a UDS server for 0x10, 0x22 and 0x3E over ISO-TP on Linux vcan and query it from a Python client"],
    interview: [q("What does the response 0x7F 0x22 0x31 mean in UDS?", "Negative response (0x7F) to ReadDataByIdentifier (0x22) with code 0x31, requestOutOfRange: the identifier is not supported or not allowed.", 3)],
    resources: ["can-intro", "misra"], projects: ["w-uds-sim", "fe-can-ecu"], roles: ["emb-automotive"],
  },
  {
    id: "emb-control", title: "Robotics and control loops: motors, encoders, IMUs and PID", phase: "e10", module: "e10-robot",
    priority: "specialization", depth: "basic", difficulty: 4, days: 2, hours: 8, kind: "coding", skills: ["firmware", "rtos"],
    why: "Robotics, drones and motion control need firmware that closes feedback loops at fixed rates with low jitter.",
    problem: "Control loops run at irregular intervals or with poorly scaled integrators oscillate or wind up.",
    eli12: "Keeping a robot at a set speed is like steering a bicycle: look at where you are, compare with where you want to be, and correct a little, many times a second.",
    tech: "Motor drivers and PWM (H-bridges, dead time), quadrature encoders with timer encoder mode, IMUs over SPI/I2C (accelerometer, gyroscope), sensor fusion (complementary filter as a start, Kalman filter awareness), PID control with fixed sample time, derivative filtering, output limits and anti-windup, tuning; real-time scheduling of control tasks; CAN for actuator networks; micro-ROS for bridging MCUs into ROS 2.",
    inChip: "Motor-control MCUs integrate advanced timers, fast ADCs and math accelerators for these loops.",
    breaks: "Integrator windup, jitter from running the loop in a low-priority task, sign errors causing runaway.",
    tested: "Step responses logged and plotted; jitter measured with GPIO markers.",
    prereqs: ["emb-timers", "emb-realtime"],
    objectives: ["Read a quadrature encoder with a timer", "Implement a PID loop with anti-windup at a fixed rate", "Fuse IMU data with a complementary filter", "Measure loop jitter"],
    terms: [["PID", "Proportional-integral-derivative controller"], ["Anti-windup", "Stopping the integrator growing when the output saturates"], ["Quadrature encoder", "Two phase-shifted signals giving position and direction"], ["micro-ROS", "ROS 2 for microcontrollers"]],
    mistakes: ["Computing the loop from a variable time step", "No output clamping", "Tuning without logging data"],
    practice: ["Close a speed loop on a small DC motor with an encoder; plot step responses for three tunings"],
    interview: [q("What is integrator windup and how do you prevent it?", "When the actuator saturates, the integral term keeps accumulating error and causes large overshoot later; prevent it by clamping the integrator, conditional integration or back-calculation when the output is limited.", 2)],
    resources: ["gh-micro-ros", "making-embedded"], projects: ["w-pid-motor"], roles: ["emb-firmware"],
  },
  {
    id: "emb-dsp", title: "Embedded DSP: sampling, filters, FFT and fixed point", phase: "e10", module: "e10-dsp",
    priority: "specialization", depth: "basic", difficulty: 4, days: 2, hours: 8, kind: "coding", skills: ["firmware"],
    why: "Audio, vibration monitoring, motor control and sensor processing rely on filters and spectra computed on the MCU.",
    problem: "Floating-point prototypes from a PC often do not fit the MCU's budget; fixed-point versions overflow silently.",
    eli12: "A filter is a sieve for signals: it keeps the slow wiggles you want and throws away the fast noise. An FFT tells you which musical notes are hidden in a sound.",
    tech: "Sampling and Nyquist; anti-aliasing; FIR (linear phase, many taps) versus IIR biquads (efficient, can be unstable, cascade second-order sections); windowing and the FFT (bins = f_s / N); fixed-point Q15 and Q31 formats, scaling and saturation versus floating point with an FPU; CMSIS-DSP functions (FIR, biquad, real FFT, statistics); block processing with DMA double buffers; the Fixed-point topic on the VLSI road covers the same number formats in hardware.",
    inChip: "DSP extensions (Cortex-M4/M7 SIMD, Helium on M55) and hardware accelerators exist for exactly these kernels.",
    breaks: "Overflow in fixed point, unstable IIR coefficients after quantisation, aliasing.",
    tested: "Compare MCU output against a Python/NumPy reference on the same input vectors; measure cycles.",
    prereqs: ["emb-adc", "emb-dma", "emb-performance"],
    objectives: ["Design and run an FIR and a biquad filter on the MCU", "Compute and interpret an FFT", "Convert a float filter to Q15 safely", "Benchmark CMSIS-DSP kernels"],
    terms: [["FIR", "Finite impulse response filter"], ["Biquad", "Second-order IIR section"], ["Q15", "16-bit fixed point with 15 fractional bits"], ["FFT bin", "Frequency resolution f_s / N"]],
    equations: ["FFT bin width = f_s / N", "Q15 value = round(x * 2^15), x in [-1, 1)"],
    mistakes: ["Designing filters without checking stability after quantisation", "Ignoring the DC and Nyquist bins", "Comparing float and fixed results without a tolerance"],
    practice: ["Low-pass filter ADC data with CMSIS-DSP; compare against SciPy output", "Build a 512-point FFT spectrum analyzer and stream the magnitudes over UART"],
    interview: [q("Sampling at 8 kHz with a 256-point FFT: what is the bin width and highest analysable frequency?", "Bin width 8000 / 256 = 31.25 Hz; highest frequency is Nyquist, 4 kHz.", 2)],
    resources: ["gh-cmsis-dsp", "lyons-dsp"], projects: ["w-dsp-filter"],
  },
  {
    id: "emb-tinyml", title: "TinyML: machine-learning inference on microcontrollers", phase: "e10", module: "e10-ml",
    priority: "specialization", depth: "basic", difficulty: 4, days: 2, hours: 8, kind: "coding", skills: ["firmware", "aihw"],
    why: "Keyword spotting, gesture and anomaly detection increasingly run on the device. It is a useful specialization once the fundamentals are solid, never a substitute for them.",
    problem: "Models trained on a PC do not fit MCU memory or latency without quantisation and careful deployment.",
    eli12: "Instead of sending every sound to a big computer far away, a tiny chip learns to recognise a few words itself, using a very compact version of the brain the big computer trained.",
    tech: "Training happens off-device; inference runs on the MCU. Int8 post-training quantisation; model size versus flash, activations versus RAM (tensor arena); latency and energy per inference; TensorFlow Lite for Microcontrollers (tflite-micro repository; Google is rebranding TensorFlow Lite as LiteRT, so check the repository README for current naming); CMSIS-NN optimised kernels for Cortex-M; Edge Impulse for data collection to deployment; feature extraction (MFCC for audio, spectral features for vibration) is often the bigger cost. The Quantization and AI hardware topics on the VLSI road explain the same int8 arithmetic from the silicon side.",
    inChip: "NPUs such as Arm Ethos-U and vendor accelerators appear in newer MCUs; firmware integrates their runtimes.",
    breaks: "Tensor arena too small, accuracy collapse after quantisation, feature extraction that differs between training and device.",
    tested: "Compare on-device predictions with the reference model on a held-out set; measure latency, RAM and energy.",
    prereqs: ["emb-dsp"],
    objectives: ["Deploy a quantised model with TFLM", "Size the tensor arena", "Measure latency, memory and energy", "Validate on-device accuracy"],
    terms: [["Quantisation", "Representing weights and activations with low-precision integers"], ["Tensor arena", "Static RAM buffer for model activations"], ["CMSIS-NN", "Optimised neural-network kernels for Cortex-M"], ["MFCC", "Audio features commonly used for keyword spotting"]],
    mistakes: ["Skipping fundamentals to start with TinyML", "Different preprocessing in training and firmware", "Reporting accuracy only from the PC model"],
    practice: ["Train a vibration anomaly or gesture model, quantise it and run it on your board; report accuracy, latency and RAM"],
    interview: [q("Your quantised model is accurate on the PC but poor on the device. What do you check?", "Input preprocessing and feature extraction parity (scaling, windowing, normalisation), quantisation parameters of inputs and outputs, tensor arena corruption, sensor orientation and sampling rate differences, and whether the representative dataset matched real data.", 3)],
    resources: ["gh-tflm", "gh-cmsis-nn", "edge-impulse-docs", "warden-tinyml"], projects: ["w-tinyml"], roles: ["emb-edge-ai"],
  },
  {
    id: "emb-bringup", title: "Board bring-up: from first power to a stable platform", phase: "e10", module: "e10-bringup",
    priority: "specialization", depth: "working", difficulty: 4, days: 2, hours: 6, kind: "project", skills: ["firmware"],
    why: "New boards and new chips arrive with unknown faults. Bring-up is a methodical skill shared by firmware, hardware and silicon-validation teams.",
    problem: "Trying the full application on a fresh board mixes hardware faults with firmware bugs and wastes days.",
    eli12: "When a new board arrives, you do not ask it to run a marathon. You check it breathes (power), has a heartbeat (clock), can talk (UART), remembers things (memory), and only then give it real work.",
    tech: "Sequence: visual inspection and power rails (current limit, measure each rail, sequencing), clocks and reset, boot straps and boot mode, debug access (SWD/JTAG connects and reads IDs), first code (LED), UART console, clock tree configuration, external memory tests (walking ones, address-line tests), each peripheral in turn with known-good devices, stress and temperature tests, then manufacturing test firmware. Keep a bring-up log with measurements and schematic references.",
    inChip: "Silicon validation engineers do the same with first silicon on evaluation boards; the VLSI road's Silicon validation topic is the counterpart.",
    breaks: "Shorted rails, wrong strap resistors, crystals not oscillating, DDR timing, swapped TX/RX.",
    tested: "Each step has a pass criterion recorded in the bring-up log before moving on.",
    prereqs: ["emb-instruments", "emb-faults"],
    objectives: ["Follow a staged bring-up checklist", "Test memory and address lines", "Validate each peripheral in isolation", "Keep a useful bring-up log"],
    terms: [["Strap pin", "Pin sampled at reset to select boot mode or options"], ["Walking-ones test", "Memory test moving a single 1 through data lines"], ["Current limit", "Bench-supply setting that protects a faulty board"]],
    mistakes: ["Powering a new board without a current limit", "Debugging firmware before confirming clocks and rails", "No written log"],
    practice: ["Write a bring-up checklist for your dev board as if it were new, then execute and log it with measurements"],
    interview: [q("A new board: what is the order of your first steps?", "Inspect, power with current limit and check rails, check clocks and reset, connect the debugger and read the ID, run an LED test, bring up UART, configure clocks, test memory, then each peripheral, then stress tests.", 2)],
    resources: ["making-embedded", "openocd-docs"], roles: ["emb-firmware", "validation"],
  },
  {
    id: "emb-interview", title: "Embedded interviews and numericals", phase: "e10", module: "e10c",
    priority: "must", depth: "working", difficulty: 3, days: 2, hours: 8, kind: "career", skills: ["interview", "firmware"],
    why: "Embedded interviews combine C puzzles, bit manipulation, MCU internals, RTOS concepts, protocol numericals and deep questions about your own projects.",
    problem: "Candidates memorise answers but cannot connect them to projects or do the arithmetic under pressure.",
    eli12: "An interview checks three things: do you know the rules, can you use them quickly, and have you really built something with them.",
    tech: "Question families: C (volatile, const, static, pointers, UB, bit tricks), MCU (reset to main, vector table, interrupt entry, DMA), RTOS (mutex versus semaphore, priority inversion, stack sizing), debugging (HardFault, watchdog resets, I2C lock, DMA corruption), protocols (UART framing, SPI modes, I2C ACK/stretching, CAN arbitration), Linux/BSP (boot chain, device tree, platform drivers, Buildroot versus Yocto), security (secure boot, root of trust, OTA rollback). Numericals: UART baud and byte time, timer period and PWM duty, ADC resolution, sampling rates, memory and stack budgets, FIFO/buffer sizing, CPU utilisation and interrupt rates, DMA transfer sizes, CAN bit timing, schedulability, battery life. Link every answer to a project you built.",
    inChip: "Interview loops at MCU vendors, automotive suppliers and device makers follow these families; semiconductor companies add pre-silicon and bring-up questions.",
    breaks: "Answers without numbers, projects you cannot explain in depth, missing trade-offs.",
    tested: "Timed mock interviews on the Interview page (Firmware, RTOS and Embedded Linux categories) and the Practice numericals.",
    prereqs: ["emb-freertos", "emb-drivers", "emb-faults"],
    objectives: ["Answer the core question families with project examples", "Solve embedded numericals in under five minutes each", "Present one flagship project in depth", "Explain trade-offs, not just definitions"],
    terms: [["STAR", "Situation, task, action, result: structure for project stories"], ["Numerical", "Quick calculation question such as timer or baud settings"]],
    mistakes: ["Reciting definitions without numbers or examples", "Claiming skills your repositories do not show"],
    practice: ["Do the Firmware, RTOS and Embedded Linux interview categories twice, a week apart", "Solve the embedded numericals on the Practice page without notes"],
    interview: [q("Walk me through your best embedded project: what would you change?", "Structure: goal and constraints, architecture diagram, the hardest bug and how you measured and fixed it, test and CI approach, numbers (latency, power, memory), and what you would redesign with hindsight.", 2)],
    resources: ["chipcamp-embedded", "making-embedded"], roles: ["emb-firmware", "emb-linux"],
  },
  {
    id: "emb-portfolio", title: "Embedded portfolio: project quality, documentation and evidence", phase: "e10", module: "e10c",
    priority: "must", depth: "working", difficulty: 2, days: 1, hours: 4, kind: "career", skills: ["interview", "firmware"],
    why: "'Built a temperature sensor' says nothing. A portfolio proves architecture, measurement, debugging, testing and documentation.",
    problem: "Many repositories have code but no README, no hardware description, no test evidence and no explanation of decisions.",
    eli12: "A portfolio is a museum label for your work: what it is, how it works, how you know it works, and what you learned building it.",
    tech: "Quality bar example: 'Cortex-M firmware reading an I2C sensor with interrupt/DMA acquisition, ring-buffered samples processed in an RTOS task, MQTT telemetry, a diagnostics CLI, watchdog recovery, unit tests and CI, and documented hardware/firmware architecture.' Every serious project documents hardware, firmware architecture, protocol, pinout, timing, state machines, build, flash and test instructions, a debugging guide and known issues, and publishes evidence: source, diagrams, test results, logs, logic-analyzer captures, measurements, benchmarks, photos or video of the setup, firmware version. Use the 18-step embedded project template and the crossover template on the Embedded page.",
    inChip: "Hiring managers open the repository: the README and test evidence decide whether they read further.",
    breaks: "Unreproducible builds, missing wiring information, screenshots without explanation.",
    tested: "Ask someone to clone, build, flash and run your project from the README alone.",
    prereqs: ["emb-interview"],
    objectives: ["Apply the project template to one project", "Publish measurement evidence", "Write a README someone else can follow", "Choose 3-5 portfolio pieces that tell one story"],
    terms: [["Evidence", "Artefacts proving a claim: logs, captures, measurements, tests"], ["Reproducible build", "Anyone can rebuild the same binary from the repository"]],
    mistakes: ["Twenty half-finished repositories", "No photos or captures of real hardware", "Hiding bugs instead of documenting them"],
    practice: ["Rewrite one project README using the template, including a timing capture and a test report"],
    interview: [q("How do you show that your firmware works, beyond 'it runs'?", "Unit and integration test results in CI, measured timing and power with captures, fault-injection results (power loss, bus errors, watchdog), long soak-test logs, and a documented architecture with known limitations.", 2)],
    resources: ["making-embedded"], roles: ["emb-firmware"],
  },
];
