import type { InterviewQ, Topic } from "../schema.ts";

// Embedded Engineering track, levels 4-7: interrupts/DMA/drivers, debugging and testing, RTOS, communication.
const q = (question: string, a: string, level: 1 | 2 | 3 | 4 = 2, trap?: string): InterviewQ => ({ q: question, a, level, trap });

export const EMB_B: Topic[] = [
  {
    id: "emb-interrupts", title: "Interrupt-safe firmware: latency, shared data and critical sections", phase: "e4", module: "e4a",
    priority: "must", depth: "advanced", difficulty: 4, days: 2, hours: 7, kind: "coding", skills: ["firmware"],
    why: "Most intermittent firmware bugs are concurrency bugs between interrupts and the main loop or tasks. Interrupt design is the core of real-time firmware.",
    problem: "Shared variables updated from ISRs without protection produce torn reads and lost updates that appear once a day and vanish under the debugger.",
    eli12: "While you are counting coins, someone taps your shoulder and adds coins to the pile. If you were halfway through writing down the total, your number is now wrong unless you asked them to wait for a second.",
    tech: "ISR rules: short, bounded, no blocking, clear the source flag, defer work (set a flag, post an event, give a semaphore). Latency = hardware entry + higher-priority handlers + time interrupts are masked. Shared data: a 32-bit aligned word write is atomic on Cortex-M but read-modify-write is not, and 64-bit values or structs tear. Tools: disable interrupts briefly (save and restore PRIMASK), raise BASEPRI to mask only lower priorities, LDREX/STREX or C11 atomics on M3 and above, lock-free SPSC buffers. Nesting and priorities: avoid starvation of low-priority interrupts; keep critical sections measured in microseconds. Deferred work and event flags keep ISRs tiny.",
    inChip: "Interrupt latency requirements appear in product specs (motor control, audio, radio timing) and are measured on every release.",
    breaks: "Torn 64-bit timestamps, lost button events, interrupt storms from uncleared flags, missed deadlines from long critical sections.",
    tested: "Stress tests with high interrupt rates; GPIO toggles measured on a logic analyzer; code review of every shared variable.",
    prereqs: ["emb-exceptions", "emb-c-patterns", "emb-uart"],
    objectives: ["Write short ISRs that defer work", "Protect shared data with the smallest correct mechanism", "Measure interrupt latency", "Explain priorities, nesting and starvation"],
    terms: [["Critical section", "Code region where preemption is prevented"], ["PRIMASK", "Register that masks all configurable interrupts"], ["BASEPRI", "Register that masks interrupts at or below a priority"], ["Deferred work", "Processing moved out of the ISR"]],
    mistakes: ["Disabling interrupts for milliseconds", "Forgetting volatile on flags shared with ISRs", "Calling non-reentrant library functions (printf, malloc) from ISRs"],
    debug: ["A 32-bit tick counter read in two halves on an 8/16-bit part, or a 64-bit counter on Cortex-M, occasionally jumps backward: read it twice until two reads agree, or mask interrupts around the read."],
    practice: ["Increment a shared counter from an ISR and main without protection, show lost counts, then fix it three ways", "Measure ISR entry latency with a GPIO toggle and a logic analyzer"],
    interview: [
      q("How do you share a 64-bit timestamp between a timer ISR and the main loop safely?", "It is written by the ISR and read in two 32-bit halves, so the reader can tear. Either briefly mask the interrupt around the read, or read high, low, high again and retry if the high word changed.", 3),
      q("What should and should not happen inside an ISR?", "Should: clear the source, capture data, post an event or give a semaphore, return quickly. Should not: block, delay, allocate memory, call non-reentrant functions or do long processing.", 1),
    ],
    resources: ["yiu-cortexm", "interrupt-blog", "making-embedded"], projects: ["e-uart-irq", "d-race"],
  },
  {
    id: "emb-dma", title: "DMA as a first-class skill", phase: "e4", module: "e4a",
    priority: "must", depth: "advanced", difficulty: 4, days: 2, hours: 7, kind: "coding", skills: ["firmware", "arch"],
    why: "DMA moves data between peripherals and memory without the CPU, which is how firmware reaches high sample rates, low CPU load and low power. It is also a rich source of subtle bugs.",
    problem: "Per-byte interrupts at high data rates consume the CPU and miss deadlines; naive DMA use corrupts buffers through lifetime, alignment and cache mistakes.",
    eli12: "DMA is a delivery robot. You tell it 'carry 256 boxes from the loading dock to shelf A' and go do other work; it rings a bell when half and all of the boxes are delivered.",
    tech: "Channels/streams and request mapping; source and destination addresses and increment modes; data widths; transfer count; normal versus circular mode; half-transfer and transfer-complete interrupts for double buffering (ping-pong); peripheral-to-memory, memory-to-peripheral, memory-to-memory; burst transfers; priority between channels; descriptor-based (scatter-gather) engines on larger SoCs. Cache coherence on cached cores (for example Cortex-M7): clean the cache before a TX DMA, invalidate after an RX DMA, align and size buffers to the cache line (32 bytes), or place buffers in non-cacheable memory. Buffer lifetime: never point DMA at a stack buffer that goes out of scope.",
    inChip: "DMA engines are RTL blocks you can design on the VLSI road; the driver for your own DMA engine is a strong crossover project.",
    breaks: "Stale data from caches, data overwritten while being processed, DMA writing into a freed stack frame, alignment faults.",
    tested: "Known-pattern transfers, CRC over received blocks, CPU-load measurement comparing polling, interrupt and DMA.",
    prereqs: ["emb-interrupts", "emb-adc"],
    objectives: ["Configure a peripheral-to-memory circular DMA", "Implement double buffering with half/complete interrupts", "Handle cache maintenance correctly", "Benchmark polling versus interrupt versus DMA"],
    terms: [["Circular mode", "DMA restarts automatically at the end of the buffer"], ["Half-transfer interrupt", "Signals the first half of the buffer is ready"], ["Cache maintenance", "Cleaning or invalidating cache lines around DMA"], ["Scatter-gather", "DMA driven by a list of descriptors"]],
    mistakes: ["Processing the half of the buffer that DMA is currently filling", "DMA into a local array on the stack", "Invalidating a buffer that shares a cache line with other data"],
    practice: ["Sample an ADC at 10 kHz with timer-triggered circular DMA and double buffering; report CPU load", "Transmit a 4 KB block over UART by DMA and compare CPU time with the interrupt driver"],
    interview: [
      q("Why might DMA-received data be corrupted on a Cortex-M7 even though the DMA reported completion?", "The CPU may read stale lines from the data cache. Invalidate the buffer's cache lines after the transfer (and clean before TX), keep buffers cache-line aligned and sized, or put them in non-cacheable memory.", 4),
      q("Why use DMA instead of interrupts for a 1 Mbit/s SPI stream?", "At 125 KB/s a per-byte interrupt costs hundreds of thousands of interrupts per second; DMA moves blocks with one interrupt per half buffer, freeing the CPU and reducing jitter and power.", 2),
    ],
    resources: ["yiu-cortexm", "gh-pico-examples", "interrupt-blog"], projects: ["w-dma-daq", "d-dma-cache"],
  },
  {
    id: "emb-drivers", title: "Designing device drivers", phase: "e4", module: "e4a",
    priority: "must", depth: "advanced", difficulty: 4, days: 2, hours: 7, kind: "coding", skills: ["firmware"],
    why: "A driver turns a datasheet into a reliable API. Driver quality (errors, timeouts, concurrency, power) separates hobby code from production firmware.",
    problem: "Drivers that assume success, block forever, mix hardware access with application logic or cannot be tested on the host fail in the field.",
    eli12: "A driver is an interpreter between your program and a chip. A good interpreter knows the chip's language (register map), what to do when the chip does not answer, and never makes the program wait forever.",
    tech: "Workflow: read the datasheet and register map; define the API (init, read/write, configure, power states); keep state in a handle struct (no hidden globals); layer bus access (I2C/SPI transport) below device logic so the device driver can be tested with a fake bus; return error codes; bound every wait with a timeout; decide blocking versus interrupt versus DMA modes; make it safe for concurrent callers (mutex in RTOS builds); handle suspend and resume. Document the state machine and timing assumptions.",
    inChip: "Chip vendors ship reference drivers; product teams write drivers for sensors, displays, radios and custom FPGA/ASIC peripherals.",
    breaks: "Infinite loops waiting for a flag, drivers that cannot recover from a device reset, unprotected concurrent access.",
    tested: "Host unit tests with a fake bus, fault injection (NACK, timeout, bad ID), on-target integration tests.",
    prereqs: ["emb-spi-i2c", "emb-interrupts"],
    objectives: ["Design a layered driver API with handles", "Add timeouts and error handling to every bus operation", "Unit-test a device driver with a fake bus", "Document driver state and timing"],
    terms: [["Handle", "Struct holding one device instance's state"], ["Transport layer", "Bus access functions the device driver calls"], ["Fake", "Test double that simulates hardware behaviour"]],
    mistakes: ["while (!(REG & FLAG)); with no timeout", "Global state that prevents two instances of the same sensor", "Mixing register access into application code"],
    practice: ["Write a sensor driver with a transport interface; test it on the host with a fake I2C bus including NACK and timeout cases", "Write a one-page driver design note: API, state machine, error codes, timing"],
    interview: [q("How would you design a driver for an I2C temperature sensor?", "Handle struct with bus pointer and address; transport interface (read/write registers) injected at init; init checks the ID register; read converts raw to units; every call returns an error code and bounds waits with timeouts; optional interrupt/DMA mode; mutex for concurrent callers; host tests with a fake bus.", 3)],
    resources: ["making-embedded", "grenning-tdd", "gh-zephyr"], projects: ["w-uart-cli", "e-i2c-sensor"],
  },
  {
    id: "emb-power", title: "Low-power firmware: sleep modes, wake-up and energy budgets", phase: "e4", module: "e4a",
    priority: "should", depth: "working", difficulty: 3, days: 1, hours: 4, kind: "coding", skills: ["firmware"],
    why: "Battery products live or die by average current. Job postings for wearables and IoT explicitly ask for sleep modes, duty cycling and power measurement.",
    problem: "Firmware that busy-waits or leaves peripherals clocked drains batteries in days instead of years.",
    eli12: "A device saves energy the way you do on holiday: sleep as much as possible, wake only when something important happens, and switch off the lights in rooms you are not using.",
    tech: "Sleep modes from light sleep (WFI, peripherals running) to stop/standby (most clocks off, RAM retained or lost); wake sources (RTC alarm, GPIO, peripheral events); tickless RTOS idle; clock gating unused peripherals; lowering core frequency and voltage; duty cycling radios and sensors; GPIO states in sleep (floating inputs leak); measuring microamps with a power profiler or a current-sense setup; energy budget = sum over states of current x time.",
    inChip: "Power domains, retention and clock gating are VLSI low-power features; firmware decides when to use them.",
    breaks: "Floating pins leaking current, debug probes keeping the chip awake, periodic ticks preventing deep sleep.",
    tested: "Measure average current over a full duty cycle and compare with the budget.",
    prereqs: ["emb-interrupts", "emb-wdt-flash"],
    objectives: ["Enter and exit sleep modes with defined wake sources", "Compute a battery-life budget", "Measure current in each state", "Remove unnecessary wake-ups"],
    terms: [["WFI", "Wait-for-interrupt instruction entering sleep"], ["Tickless idle", "RTOS stops the periodic tick while idle"], ["Duty cycle", "Fraction of time a subsystem is active"]],
    equations: ["I_avg = sum(I_state * t_state) / T_period", "Battery life (h) ~ capacity (mAh) / I_avg (mA), derated for temperature and self-discharge"],
    example: "Active 5 mA for 20 ms each second, sleep 5 uA otherwise: I_avg = (5 mA x 0.02 + 0.005 mA x 0.98) = 0.105 mA, so a 220 mAh coin cell lasts about 2100 h (roughly 12 weeks) before derating.",
    mistakes: ["Leaving the debugger connected while measuring sleep current", "Forgetting to configure unused pins", "A 1 ms RTOS tick preventing deep sleep"],
    practice: ["Measure current in run, sleep and stop modes on your board and explain the differences", "Compute battery life for a sensor that samples once per minute"],
    interview: [q("Estimate battery life: 3 mA for 50 ms every 10 s, 10 uA otherwise, 1000 mAh battery.", "I_avg = 3 mA x 0.005 + 0.01 mA x 0.995 = 0.015 + 0.00995 = about 0.025 mA; 1000 / 0.025 = about 40,000 h, roughly 4.5 years before derating.", 2)],
    resources: ["nordic-academy", "making-embedded"],
  },
  {
    id: "emb-gdb-openocd", title: "Debugging with GDB, OpenOCD and SWD/JTAG", phase: "e5", module: "e5a",
    priority: "must", depth: "advanced", difficulty: 3, days: 2, hours: 6, kind: "tool", skills: ["firmware", "linux"],
    why: "Debugging is the job. The command-line GDB + OpenOCD + SWD/JTAG workflow works on every vendor's chip, in CI and on remote benches, not just inside one IDE.",
    problem: "printf debugging changes timing, cannot inspect a crashed system and does not scale to multi-core or production images.",
    eli12: "A debug probe is a window into the chip. GDB lets you pause time, look at every drawer (memory) and every pocket (register), and set traps that fire when something you care about changes.",
    tech: "Debug access port over SWD (SWDIO/SWCLK) or JTAG (TCK/TMS/TDI/TDO); OpenOCD runs a GDB server with interface and target config files; GDB: load, break, tbreak, continue, step/next/finish, bt, info registers, x/16wx address, print with types, watch/rwatch (hardware watchpoints via the DWT unit), display, monitor reset halt; .gdbinit scripts; semihosting and SWO/ITM trace awareness; RTT-style logging; flashing and verifying from the command line; debugging optimised code (-Og, -g3). JTAG boundary scan links to the DFT topics on the VLSI road.",
    inChip: "Silicon validation, bring-up and field-failure analysis all use JTAG/SWD; JTAG TAP controllers are RTL you can build on the VLSI road.",
    breaks: "Debugging with the wrong ELF, breakpoints in flash exhausting hardware comparators, watchdog resetting a halted core (freeze it in debug config).",
    tested: "Solve a planted bug using only GDB commands, recorded in a session log.",
    prereqs: ["emb-toolchain", "emb-lab"],
    objectives: ["Start OpenOCD and connect GDB manually", "Use breakpoints, watchpoints and memory examination", "Script repetitive debug steps", "Explain SWD versus JTAG"],
    terms: [["GDB server", "Process translating GDB commands to probe operations"], ["Hardware watchpoint", "Breaks when an address is read or written, via DWT comparators"], ["SWO/ITM", "Single-wire trace output for low-overhead logging"], ["Semihosting", "Target I/O routed through the debugger (slow)"]],
    mistakes: ["Stepping through code with the watchdog still running", "Relying on printf timing to hide a race", "Using -O0 builds only, then debugging releases blind"],
    practice: ["Find a planted out-of-bounds write using a watchpoint", "Write a .gdbinit that connects, loads, resets and breaks at main"],
    interview: [q("A global variable is corrupted at some unknown point. How do you find the culprit?", "Set a hardware watchpoint on its address (watch var) and run; the core halts at the instruction that writes it; bt shows the call chain. If it happens in an ISR, inspect the exception frame.", 2)],
    resources: ["openocd-docs", "gh-openocd", "interrupt-blog"], projects: ["d-hardfault"],
  },
  {
    id: "emb-faults", title: "Crash analysis: HardFaults, stack overflow and memory corruption", phase: "e5", module: "e5a",
    priority: "must", depth: "advanced", difficulty: 4, days: 2, hours: 6, kind: "coding", skills: ["firmware"],
    why: "'How do you debug a HardFault?' is asked in almost every firmware interview, and field crashes must be diagnosed from logs, not a live debugger.",
    problem: "A HardFault handler that is an infinite loop throws away the evidence; stack overflows silently corrupt unrelated data.",
    eli12: "When the chip trips, it leaves footprints: where it was, what it was doing and why it fell. A good fault handler photographs the footprints before anything else moves.",
    tech: "Fault escalation (MemManage, BusFault and UsageFault escalate to HardFault if not enabled). Fault status registers: CFSR (MMFSR, BFSR, UFSR bits such as PRECISERR, IMPRECISERR, UNDEFINSTR, INVSTATE, DIVBYZERO, UNALIGNED), HFSR, MMFAR/BFAR fault addresses. The stacked exception frame gives the faulting PC and LR; EXC_RETURN tells whether MSP or PSP was in use. Handler: capture registers into a no-init RAM region, reset, report at next boot (coredump). Stack overflow detection: stack painting and high-water marks, MPU guard regions, RTOS overflow hooks. Heap corruption: canaries, pool allocators. Buffer overruns: bounds checks, static analysis. Watchdog resets: breadcrumbs.",
    inChip: "Crash reporting and coredump pipelines are standard in production IoT fleets.",
    breaks: "Faults that only happen with optimisation, imprecise bus faults that point at the wrong instruction, recursive faults inside the handler.",
    tested: "Trigger each fault type deliberately and confirm the handler records the correct cause and PC.",
    prereqs: ["emb-gdb-openocd", "emb-linker-startup"],
    objectives: ["Decode CFSR and HFSR", "Recover the faulting PC from the stacked frame", "Write a fault handler that saves a crash record", "Detect stack overflow three ways"],
    terms: [["CFSR", "Configurable Fault Status Register"], ["Exception frame", "Registers stacked on exception entry"], ["Imprecise fault", "Bus fault reported after the instruction that caused it"], ["Stack painting", "Filling the stack with a pattern to measure usage"]],
    mistakes: ["for(;;) as the whole HardFault handler", "Trusting the PC of an imprecise bus fault", "Setting RTOS stack sizes by guessing"],
    practice: ["Trigger null dereference, divide-by-zero (with trapping enabled), unaligned access and invalid state faults; decode each", "Add a crash record in no-init RAM and print it after reset"],
    interview: [q("How do you debug a HardFault?", "Read HFSR (FORCED means escalation) and CFSR to classify the fault, read MMFAR/BFAR if valid, find which stack was in use from EXC_RETURN, read the stacked PC and LR, map them to source with addr2line, then reproduce. For imprecise bus faults, disable write buffering temporarily to make them precise.", 3, "Only saying 'I look at the call stack'.")],
    resources: ["interrupt-blog", "yiu-cortexm", "arm-armv7m"], projects: ["d-hardfault", "d-stack-overflow"],
  },
  {
    id: "emb-instruments", title: "Measure, don't guess: logic analyzer, oscilloscope and multimeter", phase: "e5", module: "e5a",
    priority: "must", depth: "working", difficulty: 2, days: 1, hours: 5, kind: "tool", skills: ["firmware", "protocols"],
    why: "The core principle of hardware debugging: do not guess what the hardware is doing, measure it. Postings routinely list logic analyzers and oscilloscopes.",
    problem: "Engineers who only read code blame firmware for wiring faults and blame hardware for firmware timing bugs.",
    eli12: "A logic analyzer is a video recorder for on/off signals; an oscilloscope is a slow-motion camera for the exact shape of a voltage; a multimeter is a thermometer for voltage and current.",
    tech: "Serial console for logs; logic analyzer (sample rate at least 4-10x the signal rate, triggers, protocol decoders for UART/SPI/I2C/CAN, GPIO toggles as timing markers for code sections); oscilloscope (bandwidth, probe grounding, rise times, ringing, supply ripple, analog levels); multimeter (voltage, continuity, current in series); bench supply current readout for power states; protocol analyzers for USB and CAN. Measuring interrupt latency and task timing with GPIO markers; verifying PWM duty; diagnosing slow I2C edges.",
    inChip: "Silicon validation labs are built around these instruments plus automation scripts.",
    breaks: "Undersampling produces fake glitches; long ground leads on scope probes create ringing that is not really there.",
    tested: "Every project README includes at least one capture that proves timing or protocol correctness.",
    prereqs: ["emb-spi-i2c", "emb-interrupts"],
    objectives: ["Decode UART, SPI and I2C captures", "Measure ISR latency and task timing with GPIO markers", "Measure PWM and rise times on a scope", "Measure current in different power states"],
    terms: [["Sample rate", "How often the analyzer samples each channel"], ["Trigger", "Condition that starts or centres a capture"], ["Protocol decoder", "Software interpreting a captured bus"], ["Bandwidth", "Highest frequency a scope measures accurately"]],
    mistakes: ["Sampling a 1 MHz SPI clock at 2 MS/s", "Using a 15 cm ground lead on fast edges", "Measuring current with the probe in voltage mode"],
    practice: ["Capture and decode an I2C transaction; annotate address, ACKs and data", "Measure the time from button edge to ISR GPIO toggle"],
    interview: [q("Your SPI sensor returns garbage. What do you measure?", "Capture SCLK, MOSI, MISO and CS on a logic analyzer: check mode (idle level and sampling edge), clock rate against the datasheet, CS framing, and whether MISO is driven at all; then scope the signal edges for integrity problems.", 2)],
    resources: ["sigrok-pulseview", "making-embedded"], projects: ["e-latency", "d-i2c-lock"],
  },
  {
    id: "emb-testing", title: "Unit testing firmware on the host", phase: "e5", module: "e5b",
    priority: "must", depth: "working", difficulty: 3, days: 2, hours: 6, kind: "coding", skills: ["firmware"],
    why: "Teams expect firmware logic to be tested without hardware: it is faster, runs in CI and catches regressions before they reach a board.",
    problem: "Firmware that mixes register access with logic can only be tested by hand on a board, so it is barely tested at all.",
    eli12: "Before flying a real plane, pilots practise in a simulator. Host tests let your code practise on your laptop with pretend hardware before it ever touches the chip.",
    tech: "Separate hardware access behind interfaces; test logic on the host with Unity (C, often driven by Ceedling with CMock-generated mocks), CppUTest or GoogleTest for C++; fakes (behavioural simulations of a device) versus mocks (verify expected calls) versus stubs; link-time and function-pointer substitution; test-driven development for drivers (Grenning); boundary, error-path and property-style tests; coverage with gcov; integration tests on target; regression suites in CI.",
    inChip: "Firmware teams gate merges on unit tests; safety standards require documented testing.",
    breaks: "Over-mocked tests that only restate the implementation; tests that pass on the host but assume host endianness or int size.",
    tested: "Coverage reports and deliberately injected bugs that tests must catch.",
    prereqs: ["emb-drivers"],
    objectives: ["Structure code so logic is host-testable", "Write Unity tests with fakes and mocks", "Test error paths and boundaries", "Measure coverage"],
    terms: [["Unity", "Small C unit-test framework"], ["Ceedling", "Build and test runner around Unity and CMock"], ["Mock", "Test double that checks it was called as expected"], ["Fake", "Simplified working implementation of a dependency"]],
    mistakes: ["Testing only the happy path", "Mocking everything so tests break on every refactor", "Assuming sizeof(int) matches the target"],
    practice: ["Test your ring buffer and command parser with Unity to 100% branch coverage", "TDD a small driver against a fake register bank"],
    interview: [q("How do you unit-test code that writes hardware registers?", "Put register access behind an interface or a pointer to a register struct; in tests point it at a RAM struct or inject a fake/mock; assert on the resulting register values and on behaviour. Keep logic separate from the thin hardware layer.", 2)],
    resources: ["grenning-tdd", "gh-unity", "gh-ceedling", "gh-cpputest"], projects: ["e-ringbuf", "w-ci-firmware"],
  },
  {
    id: "emb-emulation-hil", title: "Emulators and hardware-in-the-loop testing", phase: "e5", module: "e5b",
    priority: "should", depth: "working", difficulty: 3, days: 1, hours: 5, kind: "tool", skills: ["firmware", "python"],
    why: "Emulators let you start without hardware and run whole-firmware tests in CI; hardware-in-the-loop rigs test the real board automatically. The ChipCamp roadmap specifically recommends QEMU with GDB.",
    problem: "Manual on-board testing does not scale, and hardware availability blocks learning and CI.",
    eli12: "An emulator is a pretend chip on your computer. A hardware-in-the-loop rig is a robot that plugs in the real board, presses its buttons and checks the answers every night.",
    tech: "QEMU: Cortex-M machines (for example the Arm MPS2 boards) with limited peripherals; good for CPU, startup and RTOS tests with GDB. Renode: models whole boards (STM32, nRF, others), scriptable with .resc files and Robot Framework tests, used in CI. Wokwi for quick browser simulation of Pico/ESP32 circuits. Vendor simulators. HIL: target board plus debug probe plus instrumented I/O (USB-GPIO, relays, power control) driven by pytest; flash, run, capture UART, assert. Know the limits: emulators rarely model timing, analog or electrical faults.",
    inChip: "Pre-silicon firmware runs on emulators and FPGA prototypes long before chips exist; the same idea as Renode at larger scale.",
    breaks: "Passing in the emulator but failing on hardware because of timing or unmodelled peripherals.",
    tested: "The same test suite runs in Renode in CI and on a HIL board nightly.",
    prereqs: ["emb-testing", "emb-gdb-openocd"],
    objectives: ["Run firmware in QEMU and Renode with GDB attached", "Write an automated Renode test", "Design a minimal HIL rig with pytest", "Know what emulators cannot catch"],
    terms: [["HIL", "Hardware-in-the-loop: automated tests on real hardware"], ["Renode script (.resc)", "Describes machine and firmware to load"], ["Robot Framework", "Keyword-driven test framework used by Renode"]],
    mistakes: ["Treating emulator success as release sign-off", "HIL rigs without power control, so hung boards stop the run"],
    practice: ["Run your UART shell firmware in Renode and assert its prompt in an automated test", "Write a pytest script that flashes the board, sends commands and checks replies"],
    interview: [q("What can an emulator not tell you about your firmware?", "Real timing and interrupt latency, analog behaviour, electrical faults, peripheral silicon errata, power consumption and radio behaviour; emulators also model only some peripherals.", 2)],
    resources: ["gh-renode", "renode-docs", "qemu-arm-docs", "qemu-blinky-video", "wokwi"], projects: ["w-ci-firmware"],
  },
  {
    id: "emb-ci-static", title: "Firmware CI, static analysis and coding standards", phase: "e5", module: "e5b",
    priority: "must", depth: "working", difficulty: 3, days: 1, hours: 5, kind: "tool", skills: ["firmware", "linux"],
    why: "Professional firmware is built, analysed and tested on every commit. MISRA, CERT C and static analysis appear in automotive, medical and industrial postings.",
    problem: "Manual builds drift, warnings accumulate, and defects that tools find in seconds reach devices.",
    eli12: "A robot checks every change you make: it builds the firmware, runs the tests and reads the code looking for common mistakes, then tells you before anyone else sees the problem.",
    tech: "GitHub Actions (or similar) pipeline: pinned toolchain container, CMake cross-build, warnings as errors, host unit tests, static analysis (cppcheck, clang-tidy, compiler -fanalyzer), formatting check (clang-format), size report diff, artifacts (ELF, bin, map) with version, optional Renode test job, HIL stage on self-hosted runners. Coding standards: MISRA C (required in much automotive work; checked by commercial tools), SEI CERT C; awareness of Coverity and Polyspace. Static analysis finds null dereferences, out-of-bounds, uninitialised values and leaks early.",
    inChip: "The same CI discipline appears in RTL projects (lint, regressions) on the VLSI road; the Regression and CI topic there is the counterpart.",
    breaks: "CI that only builds, never tests; suppressed warnings; toolchain drift between laptops and CI.",
    tested: "A pull request with a planted bug is blocked by CI.",
    prereqs: ["emb-testing", "emb-toolchain"],
    objectives: ["Build a firmware CI pipeline with build, test, analysis and artifacts", "Run cppcheck and clang-tidy and triage findings", "Explain MISRA C's purpose and a few rules", "Track binary size per commit"],
    terms: [["MISRA C", "Coding guidelines for safety-related C"], ["cppcheck", "Open-source static analyzer for C/C++"], ["clang-tidy", "Clang-based linter and analyzer"], ["Artifact", "Build output stored by CI"]],
    mistakes: ["Letting CI stay red", "Disabling a warning class instead of fixing the code", "Not archiving the ELF and map with each release"],
    practice: ["Create a GitHub Actions workflow that cross-builds, runs Unity tests and cppcheck, and uploads ELF/bin/map", "Fix every cppcheck finding in one of your projects and write down which were real bugs"],
    interview: [q("Why does static analysis matter more for embedded than for many web projects?", "Firmware is hard to patch in the field, often safety-relevant, runs without memory protection and fails silently; static analysis finds classes of defects (overflows, null dereferences, UB) before they reach devices, and standards like MISRA require it.", 2)],
    resources: ["misra", "sei-cert-c", "gh-cppcheck"], projects: ["w-ci-firmware"],
  },
  {
    id: "emb-realtime", title: "Real-time fundamentals: deadlines, latency, jitter and scheduling", phase: "e6", module: "e6a",
    priority: "must", depth: "working", difficulty: 3, days: 1, hours: 5, kind: "theory", skills: ["rtos", "firmware"],
    why: "Real-time means correct and on time. The ChipCamp roadmap uses the Apollo 11 landing computer, which kept critical tasks running during overload, as the classic illustration of why priority scheduling matters.",
    problem: "Superloops work until a slow task delays an urgent one; without analysis you cannot promise a deadline will be met.",
    eli12: "An airbag must fire within milliseconds, every time. A real-time system is not about being fast on average; it is about never being late for the things that matter.",
    tech: "Hard, firm and soft deadlines; response time, latency, jitter; worst-case execution time (WCET) measured and bounded; periodic, sporadic and aperiodic tasks; superloop and cooperative schedulers versus preemptive priority scheduling; rate-monotonic priority assignment (shorter period, higher priority) with the Liu-Layland utilisation bound U <= n(2^(1/n) - 1), about 0.78 for 3 tasks and tending to 0.69; exact response-time analysis; earliest-deadline-first awareness; tools such as the Cheddar scheduling analyser.",
    inChip: "Automotive, motor control, audio and radio firmware all have written timing requirements verified by measurement.",
    breaks: "Missed deadlines under load, jitter in control loops, starvation of low-priority work.",
    tested: "Measure WCET and response times with GPIO markers or trace; run schedulability analysis.",
    prereqs: ["emb-interrupts"],
    objectives: ["Classify hard, firm and soft real-time", "Compute utilisation and apply the RMS bound", "Measure WCET and jitter", "Choose between superloop, cooperative and preemptive designs"],
    terms: [["WCET", "Worst-case execution time"], ["Jitter", "Variation in timing between occurrences"], ["Rate-monotonic scheduling", "Fixed priorities by period, shortest first"], ["Utilisation", "Sum of C/T over tasks"]],
    equations: ["U = sum(C_i / T_i)", "RMS sufficient bound: U <= n * (2^(1/n) - 1)  (n = 3 -> 0.7798)", "Response time: R_i = C_i + sum over higher-priority j of ceil(R_i / T_j) * C_j"],
    example: "Tasks (C, T) in ms: (1, 4), (2, 10), (3, 20): U = 0.25 + 0.2 + 0.15 = 0.60 < 0.78, schedulable under RMS.",
    mistakes: ["Measuring average rather than worst-case time", "Assigning priorities by 'importance' instead of timing", "Ignoring interrupt load in schedulability"],
    practice: ["Check schedulability of three task sets with the RMS bound and response-time analysis", "Measure the WCET of one function over 10,000 runs with a cycle counter"],
    interview: [q("Three tasks with utilisations 0.3, 0.25 and 0.3. Are they guaranteed schedulable under rate-monotonic scheduling?", "Total U = 0.85, above the 3-task bound 0.78, so the sufficient test fails; they may still be schedulable, so run exact response-time analysis.", 3, "Concluding 'not schedulable' from failing a sufficient test.")],
    resources: ["li-yao-rt", "freertos-guide", "cheddar-video"],
  },
  {
    id: "emb-rtos-kernel", title: "How an RTOS kernel works: tasks, scheduler and context switch", phase: "e6", module: "e6a",
    priority: "must", depth: "working", difficulty: 4, days: 2, hours: 6, kind: "theory", skills: ["rtos", "firmware", "arch"],
    why: "Using an RTOS well requires knowing what the kernel does on every tick and switch. The ChipCamp roadmap lists threads, scheduling, context switching and ISRs as the RTOS core.",
    problem: "Treating tasks as free threads leads to stack overflows, priority mistakes and ISR misuse of kernel APIs.",
    eli12: "An RTOS is a very strict stage manager: it decides which actor is on stage, and when a more important actor is ready, it swaps them in at once, remembering exactly where the previous actor stopped.",
    tech: "Task control block (stack pointer, priority, state); states ready, running, blocked, suspended; ready lists per priority; preemptive fixed-priority scheduling with optional time slicing among equal priorities; the tick interrupt drives timeouts (or tickless timers); the context switch on Cortex-M is performed in PendSV at lowest priority: save R4-R11 (and FPU registers if used) on the task's PSP stack, store PSP in the TCB, select the next task, restore. SVC starts the first task. Kernel objects: queues, semaphores, mutexes, event groups, timers. Interrupt-safe API variants and a maximum syscall interrupt priority.",
    inChip: "RTOS ports are written per core; semiconductor vendors ship RTOS-based SDKs for their MCUs.",
    breaks: "Calling blocking APIs from ISRs, stack overflows in tasks, interrupts above the syscall priority calling kernel functions.",
    tested: "Trace task switches with GPIO markers or a trace tool; inspect TCBs in the debugger.",
    prereqs: ["emb-realtime", "emb-exceptions"],
    objectives: ["Describe task states and the ready list", "Explain the PendSV context switch step by step", "Explain the tick and timeouts", "Explain why ISR-safe API variants exist"],
    terms: [["TCB", "Task control block"], ["Context switch", "Saving one task's registers and restoring another's"], ["PSP", "Process stack pointer used by tasks"], ["Tick", "Periodic interrupt driving time in the kernel"]],
    mistakes: ["Assuming equal-priority tasks share time without enabling time slicing", "Calling a blocking API from an ISR", "Giving every task the same large stack"],
    practice: ["Write a two-task round-robin context switcher on Cortex-M using PendSV (bare metal)", "Trace task switches of a small FreeRTOS app with GPIO markers"],
    interview: [q("What happens during a context switch on Cortex-M?", "PendSV runs at lowest priority; hardware has already stacked R0-R3, R12, LR, PC, xPSR on the task's PSP; the handler saves R4-R11 (and FPU context if active), stores PSP into the current TCB, picks the next task, loads its PSP, restores R4-R11 and returns with EXC_RETURN so hardware unstacks the rest.", 4)],
    resources: ["freertos-guide", "li-yao-rt", "yiu-cortexm"],
  },
  {
    id: "emb-freertos", title: "FreeRTOS in practice", phase: "e6", module: "e6a",
    priority: "must", depth: "working", difficulty: 3, days: 2, hours: 7, kind: "coding", skills: ["rtos", "firmware"],
    why: "FreeRTOS is the most common MCU RTOS and appears across many job postings; the ChipCamp roadmap points to its official beginner's guide.",
    problem: "Default configurations and dynamic allocation hide stack and heap limits until a field failure.",
    eli12: "FreeRTOS gives your firmware several helpers that each do one job and pass notes through mailboxes, instead of one person trying to do everything in a loop.",
    tech: "Tasks (xTaskCreate or xTaskCreateStatic), priorities where a higher number is more urgent (the opposite of NVIC numbers), queues, task notifications (lightweight and fast), semaphores and mutexes, event groups, software timers (run in the timer service task), FromISR APIs with a higher-priority-woken flag; configMAX_SYSCALL_INTERRUPT_PRIORITY; heap_1 to heap_5 schemes and static allocation; stack sizing with uxTaskGetStackHighWaterMark and overflow hooks; idle hook, tickless idle; trace with GPIO markers or tracing tools. The kernel is MIT-licensed; the current kernel line is V11.",
    inChip: "Vendor SDKs (ESP-IDF, STM32Cube, NXP MCUXpresso) ship FreeRTOS ports; many products run it for a decade.",
    breaks: "Stack overflow, heap exhaustion, priority mistakes, calling non-FromISR APIs in interrupts.",
    tested: "High-water marks logged at run time, stress tests, overflow hooks enabled in debug builds.",
    prereqs: ["emb-rtos-kernel"],
    objectives: ["Create tasks statically and size their stacks", "Pass data with queues and task notifications", "Use FromISR APIs correctly", "Build a producer/consumer and a watchdog task"],
    terms: [["Task notification", "Direct-to-task signal, lighter than a semaphore"], ["FromISR", "API variants callable from interrupts"], ["High-water mark", "Minimum free stack observed"], ["heap_4", "FreeRTOS heap with coalescing of free blocks"]],
    mistakes: ["Using NVIC priority numbers as FreeRTOS priorities", "Interrupts above configMAX_SYSCALL_INTERRUPT_PRIORITY calling kernel APIs", "Using a mutex from an ISR"],
    practice: ["Build blink, two-task queue and mutex examples from the official guide, then a sensor/logger/watchdog task system", "Log stack high-water marks for every task and right-size them"],
    interview: [
      q("How do you calculate task stack size?", "Start from an estimate (deepest call chain locals plus interrupt stacking if no separate stack, plus library calls like printf), run worst-case scenarios, read the high-water mark (stack painting), then add a margin such as 25-50%; use static analysis (-fstack-usage) for call-graph estimates.", 3),
      q("Semaphore or queue: how do you pass a sensor reading from an ISR to a task?", "A queue (xQueueSendFromISR) if the data must be carried; a task notification or binary semaphore if the task only needs to be woken and reads the data itself. Use the FromISR variant and request a context switch if a higher-priority task was woken.", 2),
    ],
    resources: ["freertos-guide", "freertos-first-project", "gh-freertos"], projects: ["w-freertos-sensor"],
  },
  {
    id: "emb-rtos-sync", title: "Synchronisation, priority inversion and deadlock", phase: "e6", module: "e6a",
    priority: "must", depth: "advanced", difficulty: 4, days: 1, hours: 5, kind: "theory", skills: ["rtos", "firmware"],
    why: "Mutex versus semaphore and priority inversion are top RTOS interview questions; the 1997 Mars Pathfinder resets are the famous real-world priority-inversion case.",
    problem: "Wrong primitive choices cause unbounded priority inversion, deadlock and starvation that only appear under load.",
    eli12: "A mutex is a single bathroom key: whoever holds it must return it. If a slow person holds it while an urgent person waits, and a third person keeps the slow one busy, the urgent one waits forever unless the slow one is hurried along.",
    tech: "Binary and counting semaphores (signalling and resource counting, no ownership); mutexes (ownership, recursive variants, priority inheritance); priority inversion: high-priority task blocked on a mutex held by a low-priority task that is preempted by medium tasks; fixes: priority inheritance or priority ceiling; deadlock conditions and prevention by lock ordering and timeouts; event groups for multiple conditions; ISR-safe signalling; lock-free alternatives for single-producer single-consumer data.",
    inChip: "Safety standards require analysis of shared resources and blocking times in RTOS designs.",
    breaks: "Missed deadlines from unbounded inversion, deadlocks with two mutexes, starvation.",
    tested: "Reproduce inversion with three tasks and show the fix with priority inheritance on a trace.",
    prereqs: ["emb-freertos"],
    objectives: ["Choose between mutex, semaphore, queue and notification", "Reproduce and fix priority inversion", "Prevent deadlock with lock ordering", "Bound blocking time"],
    terms: [["Priority inversion", "High-priority task waits on lower-priority work"], ["Priority inheritance", "Mutex holder temporarily runs at the waiter's priority"], ["Priority ceiling", "Mutex raises holder to a fixed ceiling priority"], ["Deadlock", "Tasks each waiting for a resource another holds"]],
    mistakes: ["Using a binary semaphore as a mutex (no inheritance)", "Taking two mutexes in different orders in different tasks", "Holding a mutex across a blocking call"],
    practice: ["Reproduce priority inversion with three tasks and a binary semaphore; fix it with a mutex and compare traces", "Create a deadlock with two mutexes, then prevent it by lock ordering"],
    interview: [
      q("How does a mutex differ from a binary semaphore?", "A mutex has an owner that must release it and typically implements priority inheritance; a binary semaphore has no ownership and is used for signalling (one context gives, another takes), including from ISRs.", 2),
      q("What is priority inversion, and how do you prevent it?", "A high-priority task blocks on a resource held by a low-priority task, which is then preempted by medium-priority tasks, delaying the high one without bound. Use priority-inheritance or ceiling mutexes, keep critical sections short, or avoid sharing.", 3),
    ],
    resources: ["li-yao-rt", "freertos-guide"], projects: ["d-prio-inversion"],
  },
  {
    id: "emb-zephyr", title: "Zephyr: devicetree, Kconfig, west and the driver model", phase: "e6", module: "e6b",
    priority: "should", depth: "working", difficulty: 4, days: 3, hours: 10, kind: "tool", skills: ["rtos", "firmware"],
    why: "Zephyr is a fast-growing vendor-neutral RTOS (Nordic's nRF Connect SDK and many silicon vendors build on it) and it teaches the same devicetree and Kconfig ideas used by Linux. Postings increasingly list 'FreeRTOS or Zephyr'.",
    problem: "Zephyr's build system and configuration layers overwhelm people who start it as their first RTOS; used after FreeRTOS, it maps cleanly onto concepts you already know.",
    eli12: "Zephyr is a large toolbox with a catalogue. The devicetree says what hardware is on the board, Kconfig says which tools you want, and west fetches and builds everything.",
    tech: "west (meta-tool: workspace, build, flash, debug); CMake plus Kconfig (prj.conf, menuconfig) to select features; devicetree (board .dts plus application .overlay) describing hardware, with bindings; the device model (DEVICE_DT_GET, device_is_ready, subsystem APIs like gpio, i2c, sensor); kernel objects (threads, work queues, message queues, semaphores, mutexes); logging and shell subsystems; networking and Bluetooth stacks; Twister test runner and ztest; sysbuild with MCUboot for secure update; board porting. Latest release tag verified: v4.4.2 (2026-09-24); always use the version-matched documentation.",
    inChip: "Silicon vendors contribute Zephyr drivers and board support for new chips; product teams use it for BLE, cellular and industrial devices.",
    breaks: "Mismatched devicetree and driver bindings, missing Kconfig options silently compiling features out, version-mismatched docs.",
    tested: "Twister runs tests on native_sim and real boards; build output shows the final devicetree and .config.",
    prereqs: ["emb-freertos", "emb-drivers"],
    objectives: ["Build and flash a Zephyr sample with west", "Add a devicetree overlay and use a device from it", "Enable features with Kconfig", "Run tests with Twister"],
    terms: [["west", "Zephyr's meta-tool for workspaces, builds and flashing"], ["Devicetree overlay", "Application-level changes to a board's devicetree"], ["Kconfig", "Configuration system selecting build features"], ["Twister", "Zephyr's test runner"]],
    mistakes: ["Starting Zephyr as your very first embedded project", "Editing board files instead of using overlays", "Reading 'latest' docs while building an older release"],
    practice: ["Complete the Nordic DevAcademy nRF Connect SDK Fundamentals course or the Zephyr getting-started guide", "Add an I2C sensor through a devicetree overlay and read it through the sensor API; test with Twister"],
    interview: [q("How does a Zephyr application get a handle to a GPIO or I2C device?", "The device is described in devicetree; the application uses a node label or alias with DEVICE_DT_GET or GPIO_DT_SPEC_GET, checks device_is_ready(), and calls the subsystem API; Kconfig must enable the driver.", 3)],
    resources: ["nordic-academy", "nordic-academy-int", "zephyr-docs", "gh-zephyr"], projects: ["w-zephyr-sensor"],
  },
  {
    id: "emb-can", title: "CAN and CAN FD", phase: "e7", module: "e7a",
    priority: "should", depth: "working", difficulty: 3, days: 2, hours: 6, kind: "theory", skills: ["protocols", "firmware"],
    why: "CAN is the backbone of automotive and much industrial equipment; it is the entry point to the automotive specialization.",
    problem: "Without understanding arbitration, bit timing and error states, CAN networks look randomly unreliable.",
    eli12: "CAN is a shared walkie-talkie channel where everyone can talk, but when two start at once, the message with the lower number wins without anyone losing their words.",
    tech: "Differential bus (CAN_H/CAN_L) with 120-ohm termination at each end; frames: 11-bit standard or 29-bit extended identifier, DLC, up to 8 data bytes (64 in CAN FD), CRC, ACK; bitwise arbitration where dominant 0 wins, so a lower identifier has higher priority; bit stuffing after five identical bits; bit timing (sync, propagation, phase segments, sample point around 75-87.5%); error handling with transmit/receive error counters and error-active, error-passive and bus-off states; acceptance filters; CAN FD's faster data phase; tools: SocketCAN on Linux (vcan for virtual buses, candump/cansend).",
    inChip: "CAN controllers are IP blocks in automotive MCUs; ECUs use them for everything from body control to powertrain.",
    breaks: "Missing termination, mismatched bit timing, bus-off after repeated errors, filters that drop wanted IDs.",
    tested: "SocketCAN vcan tests, a USB-CAN adapter with candump, error injection by removing termination.",
    prereqs: ["emb-uart", "emb-interrupts"],
    objectives: ["Explain arbitration and priority by identifier", "Configure bit timing for a bitrate", "Explain error states and bus-off", "Use SocketCAN tools"],
    terms: [["Arbitration", "Resolving simultaneous transmissions bit by bit"], ["Dominant/recessive", "Logic 0 overrides logic 1 on the bus"], ["Bus-off", "Node disconnected after too many errors"], ["SocketCAN", "Linux CAN networking stack"]],
    equations: ["Bit time = 1 / bitrate (500 kbit/s -> 2 us);  time quanta per bit = f_can / (prescaler * bitrate)"],
    mistakes: ["One terminator or three", "Assuming a higher ID is higher priority", "Ignoring bus-off recovery"],
    practice: ["Create a vcan network on Linux, send and log frames with cansend/candump", "Parse and pretty-print CAN IDs and DLCs from a log"],
    interview: [q("Two nodes start transmitting at the same time with IDs 0x120 and 0x0F0. Who wins and why?", "0x0F0 wins: arbitration compares identifier bits from the most significant; at the first differing bit the node sending recessive 1 sees dominant 0 on the bus and backs off. Lower ID means higher priority.", 2)],
    resources: ["can-intro", "gh-linux"], projects: ["e-can-id-parser", "w-can-logger"],
  },
  {
    id: "emb-usb", title: "USB device fundamentals", phase: "e7", module: "e7a",
    priority: "optional", depth: "basic", difficulty: 3, days: 1, hours: 4, kind: "theory", skills: ["protocols", "firmware"],
    why: "USB is how many devices talk to PCs (serial consoles, firmware update, data logging). Conceptual understanding is enough until a role needs more.",
    problem: "USB stacks look like magic until you know enumeration, descriptors and endpoints.",
    eli12: "When you plug in a USB device, the computer asks 'who are you and what can you do?', the device hands over an ID card (descriptors), and then they agree on which mailboxes (endpoints) to use.",
    tech: "Host-centric bus; speeds (full speed 12 Mbit/s common on MCUs, high speed 480 Mbit/s); enumeration: reset, address assignment, descriptor requests on control endpoint 0; descriptors (device, configuration, interface, endpoint, string); transfer types (control, bulk, interrupt, isochronous); classes (CDC-ACM virtual serial, HID, mass storage, DFU for firmware update); stacks such as TinyUSB; VID/PID and USB-IF implications; composite devices.",
    inChip: "USB PHYs and controllers are complex IP; firmware uses vendor or open stacks.",
    breaks: "Wrong descriptors (device not recognised), missing 48 MHz clock accuracy, blocking in USB callbacks.",
    tested: "Host tools (lsusb, dmesg, Wireshark usbmon) and protocol analyzers.",
    prereqs: ["emb-interrupts"],
    objectives: ["Explain enumeration and descriptors", "Choose a USB class for a use case", "Bring up a CDC-ACM device with TinyUSB", "Inspect enumeration on a PC"],
    terms: [["Enumeration", "Host discovering and configuring a device"], ["Endpoint", "Addressed data channel on a device"], ["CDC-ACM", "USB class for virtual serial ports"], ["DFU", "Device Firmware Upgrade class"]],
    mistakes: ["Using an inaccurate internal oscillator for USB timing", "Doing long work in USB callbacks"],
    practice: ["Run a TinyUSB CDC example and read its enumeration with lsusb -v and dmesg"],
    interview: [q("What happens when a USB device is plugged in?", "The host detects the connection, resets the device, requests the device descriptor on endpoint 0, assigns an address, reads configuration and interface descriptors, selects a configuration and loads a class driver.", 2)],
    resources: ["usb-nutshell", "gh-tinyusb"],
  },
  {
    id: "emb-tcpip", title: "Embedded networking: Ethernet, TCP/IP and lwIP", phase: "e7", module: "e7a",
    priority: "should", depth: "working", difficulty: 3, days: 2, hours: 6, kind: "theory", skills: ["protocols", "firmware"],
    why: "Gateways, industrial devices and IoT products speak IP. Understanding the stack on a small device lets you debug connectivity with evidence instead of restarts.",
    problem: "Networking code that ignores memory limits, timeouts and reconnection logic hangs in the field.",
    eli12: "A network is a postal system: Ethernet delivers envelopes on one street, IP gives addresses across the city, and TCP makes sure letters arrive in order and resends the lost ones.",
    tech: "Ethernet MAC and PHY (RMII/MII, link negotiation), frames; ARP; IPv4 addressing, DHCP, DNS; ICMP ping; UDP (datagrams, no delivery guarantee) versus TCP (connection, ordering, retransmission, flow control); sockets API; lwIP (raw callback API, netconn, sockets) and its memory pools (pbufs); Zephyr's native stack; keepalives, reconnect with backoff, timeouts; Wireshark captures on the PC side.",
    inChip: "Ethernet MACs are standard SoC IP; the taxi repository studied on the VLSI road contains open Ethernet MAC RTL.",
    breaks: "pbuf leaks, blocking socket calls without timeouts, reconnect storms after an outage.",
    tested: "Wireshark captures, packet loss and reconnection tests, long soak tests.",
    prereqs: ["emb-freertos"],
    objectives: ["Explain Ethernet, ARP, IP, UDP and TCP roles", "Bring up lwIP or Zephyr networking", "Implement UDP telemetry and a TCP command server", "Handle link loss and reconnection"],
    terms: [["PHY", "Physical-layer transceiver chip"], ["ARP", "Maps IP to MAC addresses"], ["pbuf", "lwIP packet buffer"], ["Backoff", "Increasing delay between retries"]],
    mistakes: ["Retrying connections in a tight loop", "Blocking socket calls in time-critical tasks", "Never testing cable unplug and replug"],
    practice: ["Send UDP telemetry to a PC and capture it in Wireshark", "Build a TCP command server that survives cable unplug and reconnects"],
    interview: [q("UDP or TCP for high-rate sensor telemetry, and why?", "Often UDP: low overhead and latency, loss of an occasional sample is acceptable, no head-of-line blocking; add sequence numbers to detect loss. Use TCP (or MQTT over TCP) when every message must arrive in order.", 2)],
    resources: ["gh-lwip", "gh-zephyr"], projects: ["w-mqtt-node"],
  },
  {
    id: "emb-iot-proto", title: "IoT protocols and TLS: MQTT, HTTP and certificates", phase: "e7", module: "e7a",
    priority: "should", depth: "working", difficulty: 3, days: 2, hours: 6, kind: "coding", skills: ["protocols", "firmware"],
    why: "Connected devices must talk securely to cloud services. MQTT over TLS with proper certificate validation is the common baseline.",
    problem: "Devices shipped with disabled certificate checks, hard-coded credentials and no reconnect logic are insecure and fragile.",
    eli12: "MQTT is a notice board: devices pin messages under topics and anyone subscribed reads them. TLS is a sealed, signed envelope so nobody can read or fake the notes on the way.",
    tech: "MQTT: broker, topics and wildcards, publish/subscribe, QoS 0/1/2, retained messages, last will, keepalive, clean and persistent sessions; HTTP/REST for configuration and OTA downloads; CoAP awareness; serialisation (JSON versus CBOR versus protobuf with nanopb); TLS with Mbed TLS or a vendor stack: certificate chains, server certificate validation, device certificates and mutual TLS, a trusted time source (certificate validity), RAM cost of handshakes; credentials in secure storage.",
    inChip: "Secure elements and crypto accelerators on MCUs exist to support exactly these handshakes.",
    breaks: "Certificate validation disabled, clocks never set so certificates look invalid, QoS misunderstandings causing duplicate commands.",
    tested: "Broker logs, Wireshark (encrypted), negative tests with a wrong certificate that must fail.",
    prereqs: ["emb-tcpip"],
    objectives: ["Design MQTT topics, QoS and last will", "Establish TLS with server certificate validation", "Serialise telemetry compactly", "Handle reconnection and offline buffering"],
    terms: [["QoS", "MQTT delivery guarantee level"], ["Last will", "Message the broker publishes if a client disconnects unexpectedly"], ["Mutual TLS", "Both sides authenticate with certificates"], ["nanopb", "Protocol Buffers for small embedded systems"]],
    mistakes: ["Setting TLS verification to 'none' to make it work", "Hard-coding credentials in firmware", "Publishing at QoS 2 everywhere"],
    practice: ["Publish sensor data to a local Mosquitto broker over TLS and prove a wrong CA certificate is rejected", "Encode telemetry with nanopb and compare size with JSON"],
    interview: [q("Why must an embedded TLS client know the current time?", "To check certificate validity periods; without a trusted time source (NTP, RTC, cellular time) it either rejects valid certificates or, if checks are disabled, accepts expired or malicious ones.", 3)],
    resources: ["mqtt-org", "gh-mbedtls", "gh-nanopb"], projects: ["w-mqtt-node"],
  },
  {
    id: "emb-wireless", title: "Wireless and ESP-IDF: Wi-Fi, Bluetooth LE and beyond", phase: "e7", module: "e7a",
    priority: "should", depth: "working", difficulty: 3, days: 2, hours: 8, kind: "tool", skills: ["protocols", "firmware"],
    why: "Wi-Fi and BLE products dominate IoT hiring, and ESP32 with ESP-IDF is an accessible, professional-grade platform. Choose depth in one radio technology based on your career direction.",
    problem: "Arduino-layer ESP32 projects skip the parts products need: partitions, NVS, OTA, secure boot and power management.",
    eli12: "Wi-Fi is a big fast road for lots of data; Bluetooth LE is a quiet footpath for small messages that saves battery. ESP-IDF is the official toolkit for building products that use them.",
    tech: "ESP-IDF: CMake and idf.py, components, menuconfig, FreeRTOS-based tasks, event loop, Wi-Fi station/AP and provisioning, BLE (GATT services and characteristics, advertising, connection intervals), NVS key-value storage, partition tables (factory, ota_0, ota_1, otadata, nvs), OTA updates, secure boot v2 and flash encryption, power save modes. Use the version-matched ESP-IDF documentation (latest tag verified v6.1 on 2026-09-24). Awareness level: Thread, Matter, Zigbee, LoRa/LoRaWAN and cellular LTE-M/NB-IoT; pick one by career direction. Zephyr/nRF Connect SDK is the other common BLE path.",
    inChip: "Radio SoCs combine RF, baseband, a CPU and security blocks; firmware integrates the vendor stack.",
    breaks: "Wi-Fi reconnect loops, BLE connection parameter mismatches, OTA partitions sized too small.",
    tested: "Range and reconnection tests, BLE sniffers or phone apps (nRF Connect), OTA rollback tests.",
    prereqs: ["emb-iot-proto"],
    objectives: ["Build, flash and monitor an ESP-IDF project", "Design a partition table with OTA slots", "Implement a BLE GATT service or Wi-Fi station with reconnection", "Explain secure boot and flash encryption at a high level"],
    terms: [["GATT", "Bluetooth LE attribute protocol profile: services and characteristics"], ["NVS", "ESP-IDF non-volatile key-value storage"], ["Partition table", "Layout of flash regions"], ["Flash encryption", "Encrypting firmware and data at rest in external flash"]],
    mistakes: ["Following old Arduino-core tutorials for product work", "Storing Wi-Fi credentials in source code", "OTA without a rollback plan"],
    practice: ["Build an ESP-IDF Wi-Fi station that reconnects with backoff and stores credentials in NVS", "Expose a BLE GATT sensor service and read it from a phone"],
    interview: [q("What goes in an ESP32 partition table for a product that supports OTA?", "At least nvs, otadata, two OTA app slots (ota_0, ota_1) sized for growth, optionally a factory app and a data/filesystem partition; otadata records which slot boots, enabling rollback.", 2)],
    resources: ["esp-idf-docs", "gh-esp-idf", "nordic-academy"], projects: ["w-mqtt-node", "w-ble-sensor"],
  },
];
