import type { Topic } from "../schema.ts";

export const P0_P1: Topic[] = [
  {
    id: "chip-journey", title: "From idea to silicon: the chip-making journey", phase: "p0", module: "m0a",
    priority: "must", depth: "awareness", difficulty: 1, days: 1, hours: 2, kind: "theory", skills: ["asic"],
    why: "Every topic in this roadmap is one step of this journey. Knowing the map first tells you why each step exists and which engineer owns it.",
    problem: "Modern chips hold billions of transistors. Nobody can draw them by hand, so the work is split into stages, each with its own abstraction, tools and checks. Early chips were drawn transistor by transistor; that stopped scaling in the 1980s, which is why HDLs, synthesis and automated layout exist.",
    eli12: "Building a chip is like building a city from a written plan. First someone writes what the city must do, then architects sketch districts, then builders describe every street, inspectors check the plans, a machine turns plans into exact blueprints, and a factory prints the city onto silicon. If the plan was wrong, you only find out after the very expensive printing.",
    analogyLimit: "A city can be repaired after it is built. A chip mostly cannot: a bug found after fabrication means a costly re-spin, which is why verification is so heavy.",
    tech: "Specification defines features, interfaces and targets (power, performance, area). Architecture and microarchitecture split the chip into blocks. RTL describes each block's registers and logic in Verilog or SystemVerilog. Verification proves the RTL matches the spec. Synthesis maps RTL to standard cells under timing constraints. Physical design floorplans, places, builds the clock tree and routes wires. Signoff runs static timing, power, and physical checks (DRC, LVS). The GDSII layout is taped out to a foundry, wafers are fabricated, dies are tested and packaged, and post-silicon validation checks real chips in a lab.",
    inChip: "The whole company is organized around this flow: architecture, RTL, DV, DFT, physical design, STA, validation and EDA teams each own a stage.",
    breaks: "A missed requirement becomes a wrong spec; an RTL bug that escapes verification can cost a mask set and months; a timing violation discovered late forces a painful redesign.",
    tested: "Each stage has its own gate: simulation and formal for RTL, equivalence checks after synthesis, STA and DRC/LVS at signoff, ATE testing for manufactured parts, and lab validation for real systems.",
    prereqs: [],
    objectives: ["Name the major stages from spec to silicon in order", "Say what artifact each stage produces", "Explain why bugs get more expensive the later they are found"],
    terms: [["RTL", "Register-transfer level: code describing registers and the logic between them"], ["Synthesis", "Turning RTL into a netlist of real logic cells"], ["Tapeout", "Sending the final layout (GDSII) to the foundry"], ["Signoff", "Final checks that the design meets timing, power and manufacturing rules"]],
    visuals: [{ title: "The flow in one picture", art: "Spec -> Architecture -> RTL -> Verification\n                          |          ^\n                          v          |  (bugs go back)\n                     Synthesis -> Floorplan -> Place -> CTS -> Route\n                                                              |\n                          Signoff (STA, power, DRC, LVS) <-----\n                                   |\n                        Tapeout -> Fab -> Test -> Package -> Validation", note: "Arrows back up the chain are normal. Finding problems early is the whole game." }],
    mistakes: ["Thinking RTL design is the whole job; most engineering effort goes into verification and implementation", "Treating the flow as one-way; real projects iterate constantly"],
    senior: ["Where would you put your effort if the schedule is fixed and the spec keeps changing?", "Which late-stage surprises can be predicted early, and how?"],
    practice: ["Draw the flow from memory and label the output of each stage", "Pick any chip you own (phone SoC, microcontroller) and list which stages you think were hardest for it"],
    interview: [{ q: "Walk me through the ASIC design flow.", a: "Spec, architecture, RTL, functional verification, synthesis with constraints, DFT insertion, floorplan, placement, clock tree synthesis, routing, extraction, signoff (STA, power, DRC/LVS), tapeout, fabrication, test, packaging, post-silicon validation. Mention that verification runs alongside design and that problems loop back.", trap: "Listing steps without saying what each produces or why it exists.", level: 1 }],
    resources: ["eth-ddca", "mutlu-yt", "fossi-open"],
    roles: ["rtl", "dv", "pd"],
  },
  {
    id: "vlsi-roles", title: "Who builds a chip: the roles map", phase: "p0", module: "m0a",
    priority: "must", depth: "awareness", difficulty: 1, days: 1, hours: 2, kind: "career", skills: ["interview"],
    why: "You will choose a specialization later. Knowing what each role does day to day keeps you from optimizing for a job you would not enjoy.",
    problem: "Job titles vary by company and the same title can mean different work. Without a map, learners collect random skills instead of the ones a role actually uses.",
    eli12: "A chip team is like a film crew. The writer (architect) plans the story, actors and camera crew (RTL designers) create scenes, editors (verification) catch every mistake, the lighting and set team (physical design) makes it fit the stage, and a safety inspector (DFT) makes sure each copy can be checked.",
    tech: "Front-end roles: architecture, RTL design, design verification (DV), formal verification. Back-end roles: synthesis, physical design (PD), static timing analysis (STA), physical verification. Test: DFT and ATPG. Post-silicon: validation and characterization. Adjacent: FPGA design, analog/mixed-signal, EDA software, performance modeling, AI hardware. In many companies DV headcount rivals or exceeds design headcount.",
    inChip: "Every block of a chip passes through several of these teams. Understanding their handoffs (RTL to DV, netlist to PD, SDC to STA) is part of being effective in any one of them.",
    breaks: "Poor handoffs cause real failures: unclear constraints between RTL and STA, untestable logic for DFT, or a spec DV never saw.",
    tested: "Your role choice is tested at the specialization gate using your quiz, project and enjoyment evidence.",
    prereqs: ["chip-journey"],
    objectives: ["Describe what RTL, DV, PD, STA, DFT, FPGA, validation and EDA engineers do", "Identify which roles fit an EE + software background", "Know where to read more (Career Paths page)"],
    terms: [["DV", "Design verification: proving RTL behaves as specified"], ["PD", "Physical design: floorplan, placement, clock tree, routing"], ["DFT", "Design for test: logic that lets factories test each chip"], ["EDA", "Electronic design automation: the software tools chips are designed with"]],
    mistakes: ["Choosing a role because of one video or a salary rumour", "Assuming only RTL design is 'real' chip design"],
    practice: ["Open the Career Paths page and rank three roles by interest, then write one sentence each on why", "Find two job postings for different roles and highlight the overlapping skills"],
    interview: [{ q: "Why do you want to work in chip design, and which role?", a: "Answer with specifics: what you enjoy (for example debugging, building, measuring), evidence from projects, and how your EE plus software background fits the role's daily work.", trap: "A generic 'semiconductors are booming' answer without personal evidence.", level: 1 }],
    resources: ["fossi-open"],
    roles: ["rtl", "dv", "pd", "dft", "fpga", "eda"],
  },
  {
    id: "starting-point", title: "Your starting point: what transfers from EE and software", phase: "p0", module: "m0a",
    priority: "must", depth: "awareness", difficulty: 1, days: 1, hours: 2, kind: "career", skills: ["interview"],
    why: "You are not starting from zero. Knowing exactly which of your skills transfer, and which habits you must unlearn, saves months.",
    problem: "Career changers either underrate their background or assume software instincts apply directly to hardware. Both slow them down.",
    eli12: "You already know how to write instructions for a computer. Hardware design is different: instead of writing a recipe that one cook follows step by step, you are designing the whole kitchen, where every cook works at the same time, every tick of a clock.",
    analogyLimit: "Some software skills transfer perfectly (testing discipline, Git, scripting, OOP for SystemVerilog classes). The execution model does not.",
    tech: "Transfers well: programming fluency, debugging method, Git, OOP (maps to SystemVerilog classes and UVM), scripting (Python), data structures (EDA tools, reference models), web skills (dashboards, tooling). From EE: circuits, signals, basic semiconductor physics, control and math maturity. Must learn: concurrency as the default (every always block runs in parallel), clocks and timing, bit-accurate thinking, synthesis (code becomes gates), and physical cost (every operator costs area and delay). Honest gaps: formal VLSI coursework, access to commercial EDA tools, and professional tapeout experience; this roadmap compensates with projects, open-source tools and documented evidence.",
    inChip: "Verification, EDA and AI-hardware teams in particular value people who write good software and understand hardware.",
    breaks: "Writing Verilog like JavaScript: sequential thinking, loops that do not synthesize, and ignoring clocks leads to designs that simulate but produce wrong or huge hardware.",
    tested: "Tested in Phase 4 when HDL code must synthesize and pass lint, not just simulate.",
    prereqs: ["vlsi-roles"],
    objectives: ["List five skills that transfer from your background", "List three habits to unlearn", "Write an honest one-paragraph positioning statement"],
    terms: [["Concurrency", "Many things happening at the same time; the default in hardware"], ["Bit-accurate", "Every signal has an exact width; nothing is 'just a number'"]],
    mistakes: ["Hiding the non-VLSI background instead of framing it as a strength", "Skipping fundamentals because the syntax looks familiar"],
    practice: ["Write your positioning statement: 'EE graduate with software engineering experience, building hardware skills through ...'", "List three software projects and describe one lesson from each that applies to hardware"],
    interview: [{ q: "You don't have a VLSI degree. Why should we consider you?", a: "Point to evidence: specific projects with verification and timing results, tools used, what you debugged and measured, and how your software skills make you effective (automation, testbenches, reference models). Acknowledge the gap honestly and show how you closed it.", trap: "Apologizing, or claiming the degree does not matter at all.", level: 2 }],
    resources: [],
    roles: ["dv", "eda", "rtl"],
  },
  {
    id: "lab-setup", title: "Set up your hardware lab (Linux, simulators, waveforms)", phase: "p0", module: "m0b",
    priority: "must", depth: "working", difficulty: 2, days: 2, hours: 4, kind: "tool", skills: ["linux", "hdl"],
    why: "You learn hardware by simulating it. A working lab on day 2 means every later topic can be tried, not just read.",
    problem: "Commercial simulators are expensive and licensed. Open-source tools (Icarus Verilog, Verilator, Yosys, GTKWave/Surfer) now cover most learning needs, but installing them one by one is fiddly; bundles like OSS CAD Suite solve that.",
    eli12: "Before building model rockets you set up a workbench: tools on the wall, a safe place to test. This topic builds your workbench: a program that pretends to be your circuit, and a screen that draws its signals over time.",
    tech: "Use Linux (native, or WSL2 on Windows). Install OSS CAD Suite (one download containing Yosys, Icarus Verilog, Verilator, GTKWave, SymbiYosys and more). Create a Git repository for all your hardware work. Simulate a tiny counter with Icarus Verilog, dump a VCD file, open it in GTKWave or Surfer. Optionally note EDA Playground for browser-based simulation with no install. Later phases add LibreLane and OpenROAD flow scripts (Nix or containers).",
    inChip: "Industry uses commercial tools (VCS, Xcelium, Questa), but the workflow is the same: compile, elaborate, simulate, inspect waveforms, script everything.",
    breaks: "Without a lab, learning stays theoretical and bugs are never experienced, which is exactly the skill interviews probe.",
    tested: "Success test: `iverilog -V` and `yosys -V` run, and you can open a waveform of your own counter.",
    prereqs: [],
    objectives: ["Install OSS CAD Suite or equivalent tools", "Simulate a counter and view its waveform", "Create a Git repo with a sensible folder layout (rtl/, tb/, docs/)"],
    terms: [["VCD", "Value change dump: a file recording signal changes for waveform viewers"], ["Testbench", "Code that drives inputs into a design and checks outputs"], ["WSL2", "Windows Subsystem for Linux: a real Linux environment inside Windows"]],
    code: { lang: "verilog", src: "module counter (input clk, input rst, output reg [3:0] q);\n  always @(posedge clk)\n    if (rst) q <= 4'd0;\n    else     q <= q + 4'd1;\nendmodule\n\n// tb: iverilog -o sim counter.v tb.v && vvp sim && gtkwave dump.vcd", note: "Your first design: a 4-bit counter with synchronous reset." },
    mistakes: ["Installing tools one by one from different sources and mixing versions", "Working outside Git and losing experiments"],
    practice: ["Simulate the counter, then change it to count by 2 and confirm in the waveform", "Write a README describing how to rebuild your lab from scratch"],
    interview: [{ q: "Which simulators and tools have you used, and how do you run a simulation?", a: "Name the tools honestly (Icarus Verilog, Verilator, GTKWave/Surfer, Yosys) and describe the loop: compile sources, run the testbench, dump waves, inspect, fix, rerun, all scripted with a Makefile.", trap: "Claiming commercial tool experience you do not have.", level: 1 }],
    resources: ["oss-cad-suite", "iverilog", "gtkwave", "surfer", "edaplayground", "missing-semester"],
    projects: ["m-counter"],
  },
  {
    id: "circuit-laws", title: "Voltage, current, resistance and power in a chip", phase: "p1", module: "m1a",
    priority: "must", depth: "basic", difficulty: 1, days: 1, hours: 2, kind: "theory", skills: ["digital"],
    why: "Every logic gate is an electrical circuit. Power budgets, IR drop and drive strength are all Ohm's law and KCL in disguise.",
    problem: "Digital abstractions (0 and 1) hide the physics. When chips fail from voltage droop or overheating, engineers reason with these basic laws again.",
    eli12: "Voltage is how hard water is pushed, current is how much water flows, resistance is how narrow the pipe is. Power is how much work the flowing water does every second.",
    analogyLimit: "Water analogies break for capacitors and fields at high frequency, which is where chip behaviour gets interesting.",
    tech: "V = IR. Power P = VI = I^2 R = V^2/R. KCL: currents into a node sum to zero. KVL: voltages around a loop sum to zero. Voltage dividers set intermediate levels. In chips, supply rails deliver current through resistive metal; a big current burst causes a voltage drop (IR drop) that slows gates.",
    inChip: "Power-grid design, IR-drop analysis and electromigration checks in physical design are direct applications. Power engineers and PD engineers use these daily.",
    breaks: "An undersized power grid causes IR drop, slower gates and timing failures that only appear under heavy activity.",
    tested: "IR drop and EM analysis tools at signoff; in labs, measuring supply rails with scopes.",
    prereqs: ["electricity-basics", "logic-levels"],
    objectives: ["Apply Ohm's law and power formulas", "Use KCL/KVL on small circuits", "Explain IR drop in a power grid"],
    terms: [["IR drop", "Voltage lost across resistive supply wiring"], ["Rail", "A supply line such as VDD or ground"]],
    equations: ["V = I x R", "P = V x I", "Sum of currents at a node = 0 (KCL)"],
    example: "A block draws 2 A through a supply path of 25 milliohms: IR drop = 2 x 0.025 = 50 mV. On a 0.8 V supply that is over 6%, enough to slow gates noticeably.",
    mistakes: ["Forgetting that on-chip wires have resistance", "Treating power as constant when it changes with activity"],
    practice: ["Compute the IR drop if the current doubles; what does that mean for timing?", "Solve a two-resistor divider and state the output voltage"],
    interview: [{ q: "What is IR drop and why does it matter?", a: "Voltage lost across the resistance of the power delivery network when current flows. Lower effective supply slows gates, so IR drop can cause timing failures and must be analysed at signoff.", level: 1 }],
    resources: ["falstad"],
  },
  {
    id: "rc-delay", title: "Capacitance and RC delay: why nothing is instant", phase: "p1", module: "m1a",
    priority: "must", depth: "working", difficulty: 2, days: 2, hours: 4, kind: "theory", skills: ["digital", "timing"],
    why: "Gate delay, wire delay, clock frequency and power all come from charging and discharging capacitance through resistance. This is the root of timing.",
    problem: "Ideal logic switches instantly. Real signals must charge wires and transistor gates, which takes time. The RC model is the simplest tool that predicts that time well enough to design with.",
    eli12: "Imagine filling a bucket through a thin straw. The bucket is capacitance, the straw is resistance. A bigger bucket or a thinner straw means it takes longer to fill. A logic signal 'filling up' to a 1 works the same way.",
    analogyLimit: "Real gates are not fixed resistors, so RC gives estimates, not exact delays.",
    tech: "A capacitor charged through a resistor rises as V(t) = VDD(1 - e^(-t/RC)). The time constant tau = RC. The 50% delay is about 0.69 RC. Every gate output drives the capacitance of wires and the inputs of other gates, so delay grows with load. Energy per charge-discharge cycle is C x VDD^2, which leads directly to dynamic power.",
    inChip: "Timing libraries model each cell's delay as a function of input slew and output load capacitance. STA engineers reason about RC; PD engineers fight wire RC with buffering and sizing.",
    breaks: "Too much load on a net: slow edges, setup violations, higher power. Long unbuffered wires can dominate path delay.",
    tested: "Extraction tools compute parasitic R and C; STA uses them to compute delays.",
    prereqs: ["circuit-laws", "capacitor-basics"],
    objectives: ["Explain tau = RC and 50% delay", "Predict how load changes delay", "Connect CV^2 to energy per transition"],
    terms: [["Time constant", "tau = R x C, how fast an RC circuit responds"], ["Load capacitance", "Capacitance a gate output must charge"], ["Slew", "How long a signal takes to transition"]],
    visuals: [{ title: "Charging curve", art: "V\nVDD |          ______________\n    |      __/\n50% |....o\n    |  _/ |\n  0 |_/___|_________________ t\n        0.69RC", note: "The delay we care about is usually to the 50% point." }],
    equations: ["V(t) = VDD (1 - e^(-t/RC))", "t50 = ln(2) x RC ~ 0.69 RC", "E per 0->1->0 cycle = C x VDD^2"],
    example: "R = 2 kOhm, C = 10 fF: tau = 20 ps, t50 ~ 14 ps. Doubling the load to 20 fF doubles the delay to ~28 ps.",
    mistakes: ["Forgetting wire capacitance, which can exceed gate capacitance on long nets", "Assuming delay is fixed per gate regardless of load"],
    practice: ["Plot V(t) in Python for two RC values", "A gate drives 4 identical inputs of 2 fF plus 6 fF of wire. What is its total load?"],
    interview: [{ q: "Why does increasing fanout increase delay?", a: "Each driven input adds capacitance. The driver must charge a larger total load through its output resistance, so delay (about 0.69 RC) grows.", level: 1 }],
    resources: ["falstad", "weste-harris"],
  },
  {
    id: "semiconductors", title: "Semiconductors, doping and the PN junction", phase: "p1", module: "m1b",
    priority: "should", depth: "basic", difficulty: 2, days: 1, hours: 2, kind: "theory", skills: ["digital"],
    why: "Transistors, leakage and variation all start with doped silicon. You need the intuition, not the full device physics, for digital roles.",
    problem: "Metals always conduct and insulators never do. Computing needs a material whose conduction can be controlled electrically. Semiconductors with deliberate impurities (doping) provide that control.",
    eli12: "Pure silicon is like a crowded parking lot where no car can move. Adding a few special atoms either brings extra cars (n-type) or leaves empty spaces (p-type), so traffic can flow. Where the two kinds meet, a no-traffic zone forms that we can widen or shrink.",
    tech: "Doping silicon with donors (phosphorus) gives n-type material with free electrons; acceptors (boron) give p-type with holes. At a PN junction, carriers diffuse and leave a depletion region that blocks current until forward-biased. MOSFETs use this physics: source and drain regions, and a channel controlled by the gate.",
    inChip: "Device engineers and analog designers need depth here; digital engineers need it to understand leakage, threshold voltage and process corners.",
    breaks: "Process variation in doping shifts threshold voltage, changing speed and leakage from chip to chip.",
    tested: "Process monitors and corner characterization at the foundry and in silicon test.",
    prereqs: ["circuit-laws"],
    objectives: ["Explain n-type vs p-type doping", "Describe the depletion region intuitively", "Connect doping to threshold voltage variation"],
    terms: [["Doping", "Adding impurity atoms to control conductivity"], ["Depletion region", "Zone near a junction with no free carriers"], ["Hole", "An absent electron that behaves like a positive carrier"]],
    mistakes: ["Spending weeks on device physics before learning digital design", "Confusing holes with protons"],
    practice: ["Draw an NMOS cross-section and label source, drain, gate, channel", "Explain in two sentences why a PN junction conducts one way"],
    interview: [{ q: "What is the difference between n-type and p-type silicon?", a: "N-type is doped with donors that add free electrons; p-type with acceptors that create holes. Majority carriers differ, which is how transistors form controllable channels.", level: 1 }],
    resources: ["weste-harris", "rabaey"],
  },
  {
    id: "mosfet", title: "The MOSFET as a switch", phase: "p1", module: "m1b",
    priority: "must", depth: "basic", difficulty: 2, days: 2, hours: 4, kind: "theory", skills: ["digital"],
    why: "Every digital gate is built from MOSFETs. Their switching behaviour sets speed, power and leakage.",
    problem: "Relays and vacuum tubes were large, slow and power-hungry. The MOSFET is a tiny voltage-controlled switch that can be fabricated by the billion.",
    eli12: "A MOSFET is a gate in a fence. Put the right voltage on the control handle and the gate opens so current flows; remove it and the gate closes. An NMOS opens with a high voltage, a PMOS opens with a low voltage.",
    analogyLimit: "The switch is never perfectly off (leakage) and never perfectly on (resistance), and it takes time to open.",
    tech: "NMOS conducts when Vgs > Vt (threshold voltage); PMOS conducts when Vgs < -|Vt|. Regions: cutoff (off, small leakage), linear (acts like a resistor), saturation (current roughly set by gate voltage). Drive current grows with width/length (W/L). Smaller transistors switch faster and use less energy, which is Moore's-law scaling, but leak more.",
    inChip: "Standard cell designers size transistors; digital engineers see the result as cell speed, drive strength (X1, X2, X4 cells) and leakage.",
    breaks: "Low Vt cells are fast but leak; high Vt cells save power but are slow. Wrong mix breaks power or timing targets.",
    tested: "Cell characterization produces timing and power tables (Liberty files) from transistor-level simulation.",
    prereqs: ["semiconductors"],
    objectives: ["Explain NMOS and PMOS switching", "Relate W/L to drive strength", "Explain the Vt speed/leakage tradeoff"],
    terms: [["Threshold voltage (Vt)", "Gate voltage at which the channel turns on"], ["Drive strength", "How much current a cell can supply; bigger cells drive faster"], ["Leakage", "Current flowing when the transistor is nominally off"]],
    visuals: [{ title: "NMOS and PMOS as switches", art: "NMOS:  gate=1 -> ON   (passes 0 well)\nPMOS:  gate=0 -> ON   (passes 1 well)\n\n  drain            source\n    |                |\n  --||--  gate     --o||--  gate (bubble = PMOS)\n    |                |\n  source           drain" }],
    mistakes: ["Thinking 'off' means zero current", "Ignoring that PMOS is weaker than NMOS for the same size"],
    practice: ["Why is a PMOS usually drawn wider than an NMOS in a cell?", "Explain why multi-Vt libraries exist"],
    interview: [{ q: "Why do NMOS transistors pass a strong 0 but a weak 1?", a: "An NMOS needs Vgs > Vt to conduct. Passing a 1, the source rises toward VDD - Vt and the transistor turns off, so the output stops one threshold below VDD. Passing 0 keeps Vgs large, so the 0 is strong.", level: 2 }],
    resources: ["weste-harris", "falstad"],
  },
  {
    id: "cmos-inverter", title: "The CMOS inverter", phase: "p1", module: "m1b",
    priority: "must", depth: "working", difficulty: 2, days: 2, hours: 4, kind: "theory", skills: ["digital"],
    why: "The inverter is the atom of digital circuits. Its transfer curve explains noise margins, switching power and delay for every gate.",
    problem: "NMOS-only logic burned power continuously through pull-up resistors. CMOS pairs an NMOS and PMOS so that in a stable state one is always off, making static power nearly zero. That efficiency is why CMOS won.",
    eli12: "An inverter has two doors: one to the power supply and one to ground. When the input is 1, the ground door opens and the supply door shuts, so the output falls to 0. When the input is 0, it is the other way around. Only one door is open at a time, so almost no water leaks through.",
    tech: "PMOS connects output to VDD, NMOS to ground, both gates tied to the input. The voltage transfer characteristic (VTC) has a sharp transition around the switching threshold VM. Noise margins NMH and NML measure how much noise a signal tolerates. During switching both transistors briefly conduct (short-circuit current), and the output capacitance is charged or discharged (dynamic power).",
    inChip: "Buffers and clock trees are chains of inverters. Cell libraries offer many inverter sizes for driving loads.",
    breaks: "Poorly balanced sizing shifts VM and reduces noise margin; slow input edges increase short-circuit power.",
    tested: "SPICE simulation of the VTC during cell design; library characterization for delay and power.",
    prereqs: ["mosfet", "rc-delay"],
    objectives: ["Draw a CMOS inverter", "Read a VTC and define VM and noise margins", "Explain why static power is near zero"],
    terms: [["VTC", "Voltage transfer characteristic: output voltage vs input voltage"], ["Noise margin", "How much noise an input can take without being misread"], ["Short-circuit current", "Current that flows while both transistors are partly on during switching"]],
    visuals: [{ title: "Inverter and its transfer curve", art: "      VDD                Vout\n       |                 VDD |____\n    --o| PMOS                |    \\\nin--|  |--- out              |     \\\n    --| NMOS                 |      \\____\n       |                   0 +-----------  Vin\n      GND                        VM" }],
    mistakes: ["Assuming static power is zero at advanced nodes (leakage matters)", "Ignoring input slew when estimating power"],
    practice: ["Simulate a CMOS inverter in Falstad and observe current during switching", "Explain what happens to VM if the PMOS is made wider"],
    interview: [{ q: "Why does a CMOS inverter consume almost no static power?", a: "In either steady state one transistor is off, so there is no DC path from VDD to ground. Only leakage flows. Power is consumed mainly when switching.", level: 1 }],
    resources: ["weste-harris", "falstad", "rabaey"],
  },
  {
    id: "cmos-gates", title: "Building gates from transistors", phase: "p1", module: "m1b",
    priority: "must", depth: "basic", difficulty: 2, days: 1, hours: 2, kind: "theory", skills: ["digital"],
    why: "Knowing that NAND and NOR are the natural CMOS gates explains why synthesis prefers certain cells and why some logic is faster.",
    problem: "Logic equations must become transistor networks. CMOS uses complementary pull-up and pull-down networks, which naturally produce inverted functions.",
    eli12: "A NAND gate has two doors to ground in a row (both must open to pull the output down) and two doors to the supply side by side (either can open to pull it up). Stack doors in a row to mean AND; place them side by side to mean OR.",
    tech: "The pull-down network (NMOS) implements the function's complement: series for AND, parallel for OR. The pull-up (PMOS) is the dual. NAND2: series NMOS, parallel PMOS. NOR2: parallel NMOS, series PMOS. Because PMOS are slower, stacked PMOS (in NOR) hurt speed, so NAND is usually preferred. Complex gates like AOI/OAI implement AND-OR-INVERT in one stage.",
    inChip: "Standard cell libraries contain NAND, NOR, AOI, OAI, XOR and flops in many sizes. Synthesis picks among them to meet timing and area.",
    breaks: "Tall transistor stacks become slow; synthesis avoids them, but custom designers must watch for them.",
    tested: "Transistor-level simulation and library characterization.",
    projects: ["m-inverter-spice"],
    prereqs: ["cmos-inverter"],
    objectives: ["Draw NAND2 and NOR2 in CMOS", "Explain series vs parallel networks", "Explain why NAND is usually preferred to NOR"],
    terms: [["Pull-up network", "PMOS network connecting output to VDD"], ["Pull-down network", "NMOS network connecting output to ground"], ["AOI", "AND-OR-INVERT complex gate"]],
    mistakes: ["Building non-inverting gates directly (AND needs NAND plus inverter)", "Forgetting the duality between pull-up and pull-down"],
    practice: ["Draw a CMOS AOI21 gate for Y = not((A and B) or C)", "Count transistors in NAND2, NOR2 and XOR2"],
    interview: [{ q: "Why are NAND gates generally faster than NOR gates in CMOS?", a: "NOR puts PMOS transistors in series; PMOS have lower mobility, so a series stack is slow unless made much wider. NAND stacks the faster NMOS instead.", level: 2 }],
    resources: ["weste-harris"],
  },
  {
    id: "gate-delay", title: "Gate delay, load and fanout", phase: "p1", module: "m1c",
    priority: "must", depth: "working", difficulty: 3, days: 2, hours: 4, kind: "theory", skills: ["timing"],
    why: "Timing closure is the art of controlling delay. Every fix (sizing, buffering, restructuring) comes from this model.",
    problem: "Designers need to predict delay without running SPICE on billions of transistors. Simple models (RC, logical effort) and characterized tables (Liberty) make that possible.",
    eli12: "A gate is a runner carrying a heavy box to several friends. More friends waiting (fanout) means a heavier load and a slower runner. A stronger runner (bigger gate) is faster but eats more food (area and power) and is itself heavier for whoever sends it the message.",
    tech: "Delay depends on input slew and output load. Delay = intrinsic delay + drive resistance x load capacitance, roughly. Logical effort captures how much harder a gate is to drive than an inverter; optimal chains of gates have equal effort per stage (a fanout of about 4 per stage is a classic rule of thumb). Upsizing a gate speeds it up but loads its driver.",
    inChip: "STA reads delay tables from Liberty files indexed by slew and load. Synthesis and PD tools size cells and insert buffers automatically.",
    breaks: "Weak drivers on big loads: slow transitions, setup violations, higher short-circuit power. Over-upsizing wastes area and power.",
    tested: "STA reports slew and capacitance violations (max_transition, max_capacitance) along with path delays.",
    prereqs: ["rc-delay", "cmos-gates"],
    objectives: ["Explain delay as a function of slew and load", "Use the fanout-of-4 intuition", "Explain the upsizing tradeoff"],
    terms: [["Fanout", "Number of gate inputs a signal drives"], ["Logical effort", "Relative difficulty of driving a gate compared to an inverter"], ["FO4 delay", "Delay of an inverter driving four copies of itself; a technology speed unit"]],
    equations: ["d ~ d_intrinsic + R_drive x C_load", "Path effort F = G x B x H; optimal stage effort ~ F^(1/N)"],
    example: "An inverter drives a 64x larger load. One stage: fanout 64 (slow). Three stages of 4x each: 4 x 4 x 4 = 64 with much smaller total delay.",
    mistakes: ["Upsizing the last gate only, which slows the previous stage", "Ignoring slew propagation along a path"],
    practice: ["How many stages minimize delay for a total fanout of 256 using FO4?", "Explain why buffering a long wire can reduce delay"],
    interview: [{ q: "How would you speed up a gate driving a very large load?", a: "Insert a buffer chain with geometric sizing (about 4x per stage), upsize the driver within limits, or split the load. Consider wire RC and the effect on the previous stage.", level: 2 }],
    resources: ["weste-harris", "bhasker-sta"],
  },
  {
    id: "power", title: "Where power goes: dynamic, short-circuit and leakage", phase: "p1", module: "m1c",
    priority: "must", depth: "working", difficulty: 2, days: 2, hours: 3, kind: "theory", skills: ["timing", "asic"],
    why: "Power is often the binding constraint: battery life, heat and packaging cost. PPA thinking starts here.",
    problem: "As clock speeds rose, chips hit a power wall (early 2000s). Designers could no longer raise frequency freely, which pushed the industry toward multicore, clock gating and voltage scaling.",
    eli12: "Every time a signal flips, it spends a little energy, like flicking a light switch. Chips flip billions of switches per second, so the energy adds up. Even switches that are off leak a tiny bit, like a dripping tap.",
    tech: "Dynamic power P = alpha x C x VDD^2 x f, where alpha is the activity factor. Voltage matters quadratically, which is why lowering VDD is the most effective lever. Short-circuit power occurs during transitions. Leakage power flows even when idle, grows with temperature, and is larger for low-Vt devices. Techniques: clock gating (reduce alpha), multi-Vt cells, power gating (cut leakage), DVFS (scale V and f).",
    inChip: "Power architects budget power; RTL designers add clock gating; PD engineers use multi-Vt and power grids; low-power verification checks power intent (UPF).",
    breaks: "Exceeding thermal limits causes throttling or failure; high activity can cause IR drop and timing failure.",
    tested: "Power estimation with activity files (SAIF/VCD) at RTL and gate level; silicon power measurement.",
    prereqs: ["cmos-inverter"],
    objectives: ["Apply P = alpha C V^2 f", "Rank the power levers by effectiveness", "Explain why leakage matters at small nodes"],
    terms: [["Activity factor", "Fraction of clock cycles a node switches"], ["Clock gating", "Stopping the clock to idle logic"], ["DVFS", "Dynamic voltage and frequency scaling"]],
    equations: ["P_dyn = alpha x C x VDD^2 x f", "P_total = P_dyn + P_short + P_leak"],
    example: "Reducing VDD from 1.0 V to 0.8 V at the same frequency cuts dynamic power to 0.64x (a 36% saving) but slows gates, which may force a lower frequency.",
    mistakes: ["Ignoring that the clock network itself is a major power consumer", "Assuming clock gating is free (it adds logic and timing checks)"],
    practice: ["Compute dynamic power for C = 1 nF effective, 0.9 V, 1 GHz, alpha = 0.1", "List three RTL choices that reduce switching activity"],
    interview: [{ q: "What are the components of power in CMOS and how do you reduce each?", a: "Dynamic (reduce activity via clock gating, reduce voltage, reduce capacitance), short-circuit (sharper slews), leakage (high-Vt cells, power gating, lower temperature).", level: 2 }],
    resources: ["weste-harris", "rabaey"],
  },
  {
    id: "wires-variation", title: "Wires, variation and noise (PVT, IR drop, crosstalk)", phase: "p1", module: "m1c",
    priority: "should", depth: "basic", difficulty: 3, days: 1, hours: 2, kind: "theory", skills: ["timing", "pd"],
    why: "Real chips are not identical and wires are not ideal. Timing signoff exists because of variation, and wire delay dominates at advanced nodes.",
    problem: "Designing for one 'typical' chip would make many real chips fail. Engineers design for corners: combinations of process, voltage and temperature that bound behaviour.",
    eli12: "No two cookies from the same recipe are identical: some are baked a bit hotter, some have less sugar. Chip factories are similar, so engineers make sure the design works for the slowest cookie and the fastest cookie, on hot days and cold days.",
    tech: "PVT: process (fast/slow transistors), voltage (supply tolerance and IR drop), temperature. Corners like SS (slow-slow, low voltage, high temperature) check setup; FF corners check hold. On-chip variation (OCV) models differences within one die. Wires have resistance and capacitance per length; as wires shrink, resistance rises. Crosstalk: a switching neighbour couples charge onto a victim wire, changing its delay or causing glitches.",
    inChip: "STA engineers run multi-corner analysis; PD engineers handle wire RC, spacing and shielding; signal integrity (SI) analysis catches crosstalk.",
    breaks: "A design closed only at typical corner fails on slow silicon or at high temperature; crosstalk causes rare, hard-to-debug failures.",
    tested: "Multi-corner multi-mode STA, SI analysis, IR/EM analysis, silicon characterization across temperature.",
    prereqs: ["gate-delay"],
    objectives: ["Define PVT corners", "Explain why setup uses slow corners and hold uses fast corners", "Describe crosstalk intuitively"],
    terms: [["PVT", "Process, voltage, temperature"], ["Corner", "A combination of PVT extremes used in analysis"], ["Crosstalk", "Coupling between neighbouring wires"]],
    mistakes: ["Checking only one corner", "Assuming smaller technology means faster wires (wire resistance increases)"],
    practice: ["Explain which corner is worst for a hold check and why", "Why might temperature inversion make a design slower when cold at low voltage? (Research it)"],
    interview: [{ q: "Why do we check setup at the slow corner and hold at the fast corner?", a: "Setup fails when data arrives too late, most likely with slow gates. Hold fails when data arrives too early, most likely with fast gates. So each check uses the corner that stresses it.", level: 2 }],
    resources: ["bhasker-sta", "weste-harris"],
  },
  {
    id: "fabrication", title: "How chips are manufactured (wafers, lithography, nodes)", phase: "p1", module: "m1c",
    priority: "optional", depth: "awareness", difficulty: 1, days: 1, hours: 2, kind: "theory", skills: ["asic"],
    why: "Design rules, PDKs, yield and cost come from manufacturing. Knowing the basics helps you read PDK documentation and talk to foundry-facing teams.",
    problem: "Designers need an abstraction of the fab: the PDK encodes what the factory can build as rules, device models and cell libraries.",
    eli12: "Chips are printed in layers, like a very precise stencil painting repeated dozens of times. Light shines through a mask onto a coated silicon disk, then chemicals carve or add material. Tiny mistakes (dust!) can ruin a chip, so factories are cleaner than hospitals.",
    tech: "Wafer processing: oxidation, photolithography (masks, resist, exposure), etching, deposition, ion implantation, chemical-mechanical polishing, and metal layers built in a back-end-of-line stack. The node name (e.g., 130 nm, 3 nm) is now more a marketing label than a physical dimension. The PDK provides design rules (DRC), device models, layer definitions and standard cells. Yield depends on defect density and die area.",
    inChip: "Open PDKs (SkyWater SKY130, GF180MCU, IHP SG13G2) let you see real design rules and tape out through shuttles.",
    breaks: "DRC violations make a layout unmanufacturable; large dies suffer lower yield and higher cost.",
    tested: "DRC/LVS before tapeout; wafer test and yield analysis after fabrication.",
    prereqs: ["mosfet"],
    objectives: ["Describe the lithography loop", "Explain what a PDK contains", "Relate die area to yield and cost"],
    terms: [["PDK", "Process design kit: rules, models and libraries for a process"], ["Mask", "A stencil defining one layer's pattern"], ["Yield", "Fraction of dies that work"]],
    mistakes: ["Reading node names as literal transistor dimensions"],
    practice: ["Open the SKY130 PDK documentation and list its metal layers", "Explain why a large die costs more than proportionally"],
    interview: [{ q: "What is a PDK?", a: "The process design kit a foundry provides: design rules, device models for simulation, technology files, layer maps and usually standard cell and IO libraries, so designers can target that process.", level: 1 }],
    resources: ["sky130-pdk", "ihp-pdk", "gf180-pdk"],
  },
  {
    id: "linux-shell", title: "Linux and the shell for hardware engineers", phase: "p1", module: "m1d",
    priority: "must", depth: "working", difficulty: 2, days: 2, hours: 4, kind: "tool", skills: ["linux"],
    why: "EDA tools run on Linux, flows are driven from the shell, and logs are huge. Shell fluency is expected from day one in any VLSI job.",
    problem: "GUI-only work does not scale to regressions of thousands of tests or flows with hundreds of steps. The shell makes work repeatable and scriptable.",
    eli12: "The shell is like texting the computer precise orders instead of pointing at pictures. Once you can text it, you can also save the messages and replay them, so the computer does boring work for you.",
    tech: "Essentials: navigation, permissions, environment variables (PATH, license variables), pipes and redirection, grep/sed/awk for logs, find, xargs, Makefiles for build flows, tmux or screen for long jobs, ssh to compute servers, and version control with Git. Typical tasks: grep a simulation log for UVM_ERROR, count failing seeds, extract slack from a timing report.",
    inChip: "Every VLSI engineer uses this daily: launching simulations, parsing reports, running regressions on compute farms.",
    breaks: "Manual, unrepeatable steps lead to errors: the wrong file version synthesized, a regression missed, results you cannot reproduce.",
    tested: "Practically: can you rebuild any result with one command? That is what employers check in take-home tasks and on-the-job.",
    prereqs: ["lab-setup"],
    objectives: ["Use pipes, grep and awk to extract data from logs", "Write a Makefile that compiles and runs a simulation", "Use Git branches for experiments"],
    terms: [["Pipe", "Sending one command's output into another"], ["Makefile", "A recipe file that rebuilds outputs when inputs change"], ["Regression", "Running a large set of tests to catch breakage"]],
    code: { lang: "bash", src: "# count errors per test log\ngrep -c \"UVM_ERROR\" logs/*.log | awk -F: '$2>0 {print $1, $2}'\n\n# worst slack from a report\ngrep -E \"^\\s*slack\" timing.rpt | sort -k2 -n | head -1" },
    mistakes: ["Editing files on shared servers without version control", "Copy-pasting commands instead of scripting them"],
    practice: ["Write a Makefile with targets sim, waves and clean for your counter", "Write a one-liner that lists the three slowest tests from a log directory"],
    interview: [{ q: "How would you find all failing tests in a directory of 500 simulation logs?", a: "Use grep for the failure signature (for example UVM_ERROR or 'TEST FAILED'), list matching files with grep -l, and count or summarize with awk or a short Python script. Mention automating it in the regression flow.", level: 1 }],
    resources: ["missing-semester", "oss-cad-suite"],
  },
];
