import type { Topic } from "../schema.ts";

/**
 * Module m1z: electronics from zero.
 * Assumes no prior electronics at all. Everything later in Phase 1 builds on these five days.
 */
export const P1_BASICS: Topic[] = [
  {
    id: "electricity-basics", title: "What electricity actually is: charge, voltage and current", phase: "p1", module: "m1z",
    priority: "must", depth: "basic", difficulty: 1, days: 1, hours: 2, kind: "theory", skills: ["digital"],
    why: "Every signal in a chip is a voltage, and every delay comes from moving charge. If these three words are fuzzy, everything later (delay, power, noise) stays fuzzy too.",
    problem: "People often learn formulas like V = IR without a picture of what is moving. That works until something behaves oddly, and then there is nothing to reason with. Starting from charge gives you a mental model you can fall back on for the rest of the roadmap.",
    eli12: "Electric charge is like water. Voltage is the water pressure pushing it, current is how much water flows past a point each second, and a wire is a pipe. A battery is a pump that keeps one side at higher pressure than the other. Nothing flows unless there is a complete loop back to the pump.",
    analogyLimit: "Water is a substance you can lose; charge in a circuit is not used up. The same electrons keep circulating, and what actually travels fast is the electric field, not individual electrons, which drift surprisingly slowly.",
    tech: "Charge (Q, in coulombs) is a property of electrons and protons. Current (I, in amperes) is the rate of charge flow: I = dQ/dt, so one ampere is one coulomb per second. Voltage (V, in volts) is the energy per unit charge between two points: moving one coulomb across one volt takes one joule. Voltage is always measured between two points, which is why every circuit needs a reference node called ground (0 V). Conductors such as copper let charge move freely; insulators such as silicon dioxide do not; semiconductors sit in between and can be persuaded to do either, which is the entire basis of chip design. In a chip, a logic 1 is simply a node held near the supply voltage VDD, and a logic 0 is a node held near ground.",
    inChip: "The supply network (VDD and ground) is designed by power and physical design engineers, and every signal you will ever design is a voltage on a node measured against that ground.",
    breaks: "Confusing voltage with current leads to wrong reasoning everywhere: people say a node 'has current' when they mean it is driven high, then cannot explain why a long wire is slow or why leakage burns power while nothing switches.",
    tested: "By measurement: a multimeter reads voltage across two points and current through a break in the loop, and a simulator shows the same quantities as waveforms.",
    prereqs: [],
    objectives: ["Say what charge, voltage and current are in your own words", "Explain why voltage is always between two points and what ground means", "State the units and the common prefixes used in chips (m, u, n, p, f)", "Explain what a conductor, an insulator and a semiconductor do"],
    terms: [["Charge (Q)", "The quantity of electricity, measured in coulombs"], ["Current (I)", "Rate of charge flow, in amperes: one coulomb per second"], ["Voltage (V)", "Energy per unit charge between two points, in volts"], ["Ground", "The reference node defined as 0 V that all other voltages are measured against"], ["VDD", "The positive supply voltage that represents logic 1"], ["Conductor / insulator", "A material that lets charge move easily / one that does not"]],
    visuals: [
      { title: "A complete loop", art: "      +-----[ resistor ]-----+\n      |                      |\n   [ battery ]            (current I flows\n    + |  - |               around the loop)\n      |                      |\n      +----------------------+\n                |\n              ground (0 V reference)", note: "No complete loop means no current, however high the voltage." },
      { title: "Prefixes you will meet constantly", art: "  1 V   = 1 volt\n  1 mV  = 0.001 V           (milli, 10^-3)\n  1 uV  = 0.000001 V        (micro, 10^-6)\n  1 ns  = 10^-9 seconds     (nano)\n  1 ps  = 10^-12 seconds    (pico)   <- gate delays live here\n  1 fF  = 10^-15 farads     (femto)  <- chip capacitances live here" },
    ],
    equations: ["I = Q / t (current is charge per second)", "Energy = Q x V (joules)", "1 A = 1 C/s"],
    example: "A chip node holds 10 fF of capacitance and swings from 0 V to 1.0 V. The charge moved is Q = C x V = 10e-15 x 1.0 = 10 femtocoulombs. If that transition takes 20 ps, the average current is I = Q/t = 10e-15 / 20e-12 = 0.5 mA, for a single tiny node. Multiply by millions of nodes switching and you see why chips get hot.",
    mistakes: ["Saying 'the voltage through a wire': voltage is across two points, current is through something", "Forgetting that a circuit needs a return path to ground, not just a supply", "Mixing up prefixes: a femtofarad is a million times smaller than a nanofarad, and that factor matters"],
    practice: ["Write one sentence each for charge, voltage and current without using the other two words", "A node with 20 fF charges to 1.2 V. How much charge moved? If it happens in 50 ps, what is the average current?", "List three conductors and three insulators you can see from where you are sitting"],
    interview: [
      { q: "What is the difference between voltage and current?", a: "Voltage is the energy per unit charge between two points, the push. Current is the rate of charge flow past a point, the flow. Voltage exists between two nodes; current flows through an element.", level: 1, trap: "Saying 'voltage flows'. It does not; it is a difference, never a flow." },
      { q: "Why does every chip need a ground network as well as a power network?", a: "Voltage is only meaningful relative to a reference, and current needs a return path. Ground provides both: the 0 V reference for every signal and the return route for all the charge the supply delivers.", level: 2 },
    ],
    resources: ["falstad"],
  },
  {
    id: "circuit-reading", title: "Reading a circuit: series, parallel and the voltage divider", phase: "p1", module: "m1z",
    priority: "must", depth: "basic", difficulty: 1, days: 1, hours: 2, kind: "theory", skills: ["digital"],
    why: "Schematics are the language of hardware. Once you can see series and parallel paths, transistor circuits such as the CMOS gates you meet in a few days stop looking like spaghetti and start looking like obvious on/off switches.",
    problem: "Before you can analyse anything you have to see the structure: which parts share a current, which share a voltage, and where the current can go. Ohm's law on its own does not tell you that; reading the topology does.",
    eli12: "Series is a single-file queue: everyone passes through one after another, so the same flow goes through each one. Parallel is several checkout lanes side by side: the flow splits between them, and adding lanes makes it easier to get through. A voltage divider is a tall water tower with a tap halfway up: the pressure at the tap is a predictable fraction of the pressure at the top.",
    analogyLimit: "Queues and lanes have no equivalent of a capacitor, which stores charge rather than passing it, so this picture only holds for resistors and steady currents.",
    tech: "Two elements are in series if they share one node and nothing else connects there, so the same current flows through both: R_series = R1 + R2. They are in parallel if both ends connect to the same two nodes, so they see the same voltage and the current splits: 1/R_parallel = 1/R1 + 1/R2, which for two resistors is R1 x R2 / (R1 + R2). Kirchhoff's two laws formalise this: currents entering a node sum to zero, and voltages around any loop sum to zero. The most useful consequence is the voltage divider: two resistors in series across a supply produce Vout = VDD x R2 / (R1 + R2) at their midpoint. A short circuit is a zero-resistance path that steals all the current; an open circuit is a broken path where no current flows. In CMOS gates you will read exactly these structures: transistors in series form an AND-like condition (all must be on), transistors in parallel form an OR-like condition (any one will do).",
    inChip: "Circuit designers and library developers read these structures in every standard cell, and physical design engineers see parallel resistance in power grids, where many paths in parallel keep the supply voltage steady.",
    breaks: "Misreading topology gives answers that are wrong by orders of magnitude, and in real hardware an accidental short between power and ground turns the supply into a heater and can destroy the chip.",
    tested: "By simulation: label every node, compute the expected voltages by hand, then compare with the simulator's readings.",
    prereqs: ["electricity-basics"],
    objectives: ["Identify series and parallel connections in a schematic", "Combine resistors in series and parallel", "Compute a voltage divider output", "Say what a short circuit and an open circuit mean"],
    terms: [["Node", "A point where components connect; everything on a node shares one voltage"], ["Series", "Sharing a single path, so the same current flows through each element"], ["Parallel", "Connected across the same two nodes, so each element sees the same voltage"], ["Kirchhoff's current law", "Current into a node equals current out of it"], ["Voltage divider", "Two series resistors producing a fraction of the supply at their midpoint"], ["Short / open", "A zero-resistance path / a broken path with no current"]],
    visuals: [
      { title: "Series and parallel", art: "SERIES (same current)        PARALLEL (same voltage)\n\n  o--[R1]--[R2]--o            o--+--[R1]--+--o\n                                 |         |\n  R = R1 + R2                     +--[R2]--+\n                               1/R = 1/R1 + 1/R2" },
      { title: "Voltage divider", art: "   VDD\n    |\n   [R1]\n    |\n    +----o Vout = VDD x R2 / (R1 + R2)\n    |\n   [R2]\n    |\n   GND\n\n  R1 = R2  ->  Vout = VDD / 2" },
    ],
    equations: ["R_series = R1 + R2", "R_parallel = R1 x R2 / (R1 + R2)", "Vout = VDD x R2 / (R1 + R2)"],
    example: "VDD = 1.8 V, R1 = 10 kOhm, R2 = 20 kOhm in series to ground. Vout at the midpoint = 1.8 x 20/(10+20) = 1.2 V. Now put another 20 kOhm in parallel with R2: the pair becomes 10 kOhm, and Vout drops to 1.8 x 10/(10+10) = 0.9 V. Adding a parallel path lowered the resistance and pulled the midpoint down.",
    mistakes: ["Calling two components in series 'parallel' because they are drawn side by side: it is the connections that decide, not the drawing", "Adding parallel resistors directly instead of using the reciprocal rule", "Forgetting that anything connected to the same node is at the same voltage, however far apart it is drawn"],
    practice: ["Compute the total resistance of 1 kOhm and 3 kOhm in series, then in parallel", "Design a divider that turns 3.3 V into 1.65 V, then into 1.1 V", "Draw two switches in series and two in parallel, and write the logic condition each one represents"],
    interview: [
      { q: "Two resistors are in parallel. What do they share, and what splits between them?", a: "They share the same voltage across them, because both ends sit on the same pair of nodes. The current splits between them in inverse proportion to their resistances.", level: 1, trap: "Answering 'they share current': that is the series case." },
      { q: "Why do power grids in chips use many parallel metal paths?", a: "Parallel paths lower the total resistance between the pad and the cells, which reduces IR drop, so the supply voltage stays closer to nominal and gates keep their expected speed.", level: 2 },
    ],
    resources: ["falstad"],
  },
  {
    id: "capacitor-basics", title: "Capacitors: storing charge and resisting sudden change", phase: "p1", module: "m1z",
    priority: "must", depth: "basic", difficulty: 2, days: 1, hours: 2, kind: "theory", skills: ["digital", "timing"],
    why: "Capacitance is the single most important idea in chip timing and power. Every wire, every transistor gate and every input you drive is a small capacitor, and charging them is what takes time and burns energy.",
    problem: "In ideal logic, a signal changes instantly. Real nodes cannot: charge has to be delivered before a voltage can change. Understanding capacitance before RC delay means the timing chapter becomes obvious instead of magical.",
    eli12: "A capacitor is a bucket for electric charge. Pouring charge in raises the voltage, like water raising the level in a bucket. A big bucket takes longer to fill, and it cannot change level instantly no matter how hard you push. Every wire in a chip is a small bucket you must fill or empty every time the signal changes.",
    analogyLimit: "A bucket holds water even if you tip it; a capacitor holds charge only while nothing drains it, and real chip capacitors leak slowly. Also, both plates matter: the charge is stored in the field between them, not sitting in a container.",
    tech: "A capacitor is two conductors separated by an insulator. Its capacitance is C = Q/V, measured in farads: the charge stored per volt. The defining behaviour is I = C x dV/dt, which says a voltage change requires a current, and a faster change requires more current. Equivalently, voltage cannot jump instantly across a capacitor with finite current. Energy stored is (1/2) C V^2, and a full 0-to-1-to-0 cycle on a node moves C x VDD^2 of energy from the supply, which is where dynamic power comes from. On a chip, capacitance appears whether you want it or not: the gate of every MOSFET is a capacitor by construction, and every wire has capacitance to its neighbours and to the substrate. Typical on-chip values are in femtofarads, which is why picosecond delays are possible at all.",
    inChip: "Extraction tools compute the capacitance of every net after layout, and timing and power tools use those numbers for every delay and every switching-power figure in sign-off.",
    breaks: "Underestimating capacitance means a design that is slower and hotter than predicted: a long wire with heavy load produces slow edges, late signals and setup failures that only appear after layout.",
    tested: "By parasitic extraction after layout, which produces the real capacitance of each net, and by simulation of charge and discharge waveforms.",
    prereqs: ["circuit-reading"],
    objectives: ["Define capacitance as charge per volt", "Explain why voltage across a capacitor cannot change instantly", "Compute the charge and energy for a node transition", "List the sources of capacitance on a chip node"],
    terms: [["Capacitance (C)", "Charge stored per volt, in farads"], ["Farad", "One coulomb per volt; on-chip values are femtofarads"], ["Gate capacitance", "The capacitance of a MOSFET gate terminal, which every driver must charge"], ["Wire capacitance", "Capacitance of a net to neighbouring wires and the substrate"], ["Dynamic energy", "C x VDD^2 moved per full switching cycle of a node"]],
    visuals: [
      { title: "Filling the bucket", art: "  current in ->  +-------+\n                 |       |   V rises as charge arrives\n                 | C     |   V = Q / C\n                 +-------+\n                     |\n                    GND\n\n  I = C x dV/dt   (fast change needs big current)" },
      { title: "Where a node's capacitance comes from", art: "   driver                      load\n  [gate]---------- wire ---------[gate inputs]\n     |              |                 |\n   output      wire C to           input gate C\n   self C      neighbours\n                and substrate\n\n  C_total = C_self + C_wire + sum(C_inputs)" },
    ],
    equations: ["C = Q / V", "I = C x dV/dt", "E_stored = 0.5 x C x V^2", "E per 0->1->0 cycle = C x VDD^2"],
    example: "A net has 12 fF of wire capacitance and drives three gate inputs of 2 fF each, so C_total = 18 fF. Swinging it to VDD = 1.0 V moves Q = 18 fC. If the node switches 500 million times per second, the dynamic power is roughly C x VDD^2 x f = 18e-15 x 1 x 5e8 = 9 microwatts, for one net. A chip has millions.",
    mistakes: ["Ignoring wire capacitance, which on long nets can exceed all the gate capacitance put together", "Thinking a capacitor blocks current entirely: it blocks steady current but passes changing current", "Confusing stored energy (0.5 C V^2) with the energy drawn from the supply per cycle (C V^2)"],
    practice: ["Compute the total load of a gate driving 5 inputs of 1.5 fF plus 8 fF of wire", "Explain in two sentences why a bigger load makes a signal edge slower", "Estimate the dynamic power of that net switching at 200 MHz with VDD = 0.9 V"],
    interview: [
      { q: "Why can a node's voltage not change instantly?", a: "Changing the voltage on a capacitance requires moving charge, and I = C dV/dt means an instantaneous change would need infinite current. Real drivers supply finite current, so every transition takes time.", level: 2 },
      { q: "A designer adds a long wire to a signal and the path fails timing. Why?", a: "The wire adds capacitance and resistance to the net, so the driver takes longer to charge it. The edge becomes slower and the delay of the path grows, eating the slack that used to be there.", level: 2, trap: "Blaming the logic depth when nothing logical changed; the load did." },
    ],
    resources: ["falstad", "weste-harris"],
  },
  {
    id: "logic-levels", title: "From voltage to 0 and 1: logic levels and noise margin", phase: "p1", module: "m1z",
    priority: "must", depth: "basic", difficulty: 2, days: 1, hours: 2, kind: "theory", skills: ["digital"],
    why: "Digital design is a useful fiction built on analog voltages. Knowing exactly how that fiction is maintained explains why chips are reliable at all, and why they stop being reliable when noise, IR drop or slow edges get out of hand.",
    problem: "Analog signals degrade a little at every stage, so errors would accumulate without limit. Digital logic solves this by agreeing that a range of voltages means 0 and another range means 1, and by making every gate clean up its input before passing it on.",
    eli12: "Imagine passing a whispered message down a line of people. If everyone whispers exactly what they heard, small mistakes pile up and the message turns to nonsense. Now imagine everyone must shout either YES or NO, and anything they hear that is closer to YES gets shouted as a full, clear YES. Small errors are wiped out at every step. That is what digital logic does with voltages.",
    analogyLimit: "People can hesitate and say nothing; a gate given a voltage in the forbidden middle region still produces some output, and a flip-flop in that situation can go metastable, which you will meet in Phase 2.",
    tech: "A logic family defines four thresholds: VOL and VOH are the worst-case output voltages a gate promises for 0 and 1, and VIL and VIH are the input voltages a gate promises to interpret as 0 and 1. Because a gate outputs a cleaner signal than it is required to accept (VOH > VIH and VOL < VIL), every stage restores the signal. The difference is the noise margin: NM_high = VOH - VIH and NM_low = VIL - VOL. Any interference smaller than the margin is ignored completely. The region between VIL and VIH is undefined: a static input there wastes power because both transistors conduct, and the output may be neither 0 nor 1. This is why slow, sloppy edges are a real problem and why inputs are never left floating. In modern CMOS the supply is typically around 0.8 to 1.2 V and the switching threshold sits near VDD/2.",
    inChip: "Library characterisation defines these levels for each standard cell, and signal integrity and IR-drop analysis exist to prove that noise on real nets stays inside the margins.",
    breaks: "When noise exceeds the margin or an input sits in the forbidden region, gates produce wrong values or oscillate, floating inputs pick up interference, and the chip fails intermittently in ways that are painful to debug.",
    tested: "By noise and signal-integrity analysis, by checking slew rates against library limits, and by simulating gates at the worst-case supply and temperature.",
    prereqs: ["electricity-basics", "circuit-reading"],
    objectives: ["Explain why digital logic tolerates noise but analog does not", "Define VOH, VOL, VIH, VIL and compute noise margins", "Explain why the region between VIL and VIH must be crossed quickly", "Explain why floating inputs are dangerous"],
    terms: [["VOH / VOL", "Output high / low voltage a gate guarantees to produce"], ["VIH / VIL", "Input high / low voltage a gate guarantees to interpret correctly"], ["Noise margin", "How much interference a signal can absorb before being misread"], ["Forbidden region", "The input band between VIL and VIH where the value is undefined"], ["Signal restoration", "Each gate outputting a cleaner level than it accepts"], ["Floating input", "An input connected to nothing, free to drift into the forbidden region"]],
    visuals: [
      { title: "Voltage bands and margins", art: "  VDD  ---------------------------  logic 1 region\n        VOH  ----------------\n                             } noise margin high\n        VIH  ----------------\n             ~~~ forbidden ~~~   (undefined: cross quickly)\n        VIL  ----------------\n                             } noise margin low\n        VOL  ----------------\n  GND  ---------------------------  logic 0 region" },
      { title: "Restoration down a chain", art: "  clean --> [gate] --> slightly noisy --> [gate] --> clean again\n\n  Each stage pulls the level back to full VDD or full GND,\n  so errors do not accumulate the way analog errors do." },
    ],
    equations: ["NM_high = VOH - VIH", "NM_low = VIL - VOL"],
    example: "A family specifies VOH = 0.95 V, VIH = 0.70 V, VIL = 0.30 V, VOL = 0.05 V at VDD = 1.0 V. The margins are NM_high = 0.25 V and NM_low = 0.25 V, so crosstalk of 0.15 V is harmlessly ignored, while a 0.3 V glitch could be read as the wrong value.",
    mistakes: ["Assuming logic 1 means exactly VDD: it means anything above VIH", "Leaving unused inputs floating instead of tying them to VDD or ground", "Ignoring slow edges: a signal lingering in the forbidden region wastes power and can cause glitches"],
    practice: ["Compute both noise margins for VOH = 1.1, VIH = 0.8, VIL = 0.35, VOL = 0.1", "Explain in your own words why a chain of 20 gates does not gradually blur the signal", "List two things in a real chip that inject noise onto a neighbouring wire"],
    interview: [
      { q: "What is a noise margin and why does it matter?", a: "It is the gap between what a gate guarantees to output and what the next gate guarantees to accept: VOH - VIH for a high level, VIL - VOL for a low. Any noise smaller than that gap cannot change the interpreted value, which is what makes long digital chains reliable.", level: 2 },
      { q: "Why is a floating input dangerous?", a: "It is not driven, so it drifts and can settle in the forbidden region. The gate may then produce an undefined output, both transistors can conduct and burn power, and the behaviour changes with noise and temperature, which makes failures intermittent.", level: 2, trap: "Saying a floating input is simply read as 0; it is undefined, not low." },
    ],
    resources: ["falstad", "weste-harris"],
  },
  {
    id: "first-simulation", title: "Your first circuit simulation (no hardware needed)", phase: "p1", module: "m1z",
    priority: "must", depth: "basic", difficulty: 1, days: 1, hours: 2, kind: "tool", skills: ["digital"],
    why: "You learn electronics by watching circuits behave, not by reading about them. A browser simulator gives you a lab with no components to buy, and it builds the habit that carries through the whole roadmap: predict first, simulate second, explain the difference.",
    problem: "Reading formulas gives no intuition for how a voltage actually rises, or what happens when you double a resistor. Simulation closes that loop in seconds, and the predict-then-check discipline is exactly how engineers debug real chips later.",
    eli12: "It is a sandbox where you can wire up a circuit by dragging parts, press play, and watch the electricity move. Nothing burns out, nothing costs money, and you can undo any mistake, so you can be curious without being careful.",
    analogyLimit: "A simulator only models what it was told to model. Real boards have stray capacitance, resistance and interference that the sandbox ignores, which is why silicon still surprises people.",
    tech: "Falstad's browser simulator solves the circuit equations at small time steps and animates the result, showing current as moving dots and voltage as colour, with a scope for plotting any node over time. The workflow to build now is: draw the circuit, predict the node voltages by hand using the divider and RC rules, run it, then explain every difference between prediction and result. That last step is the whole point. Three circuits are worth building on day one: a voltage divider, an RC charging circuit where you watch the curve and measure the time to reach 63% of the final value, and a switch driving a load so you can see a node take real time to rise. Later phases replace this tool with Verilator and a waveform viewer, but the loop stays identical: predict, simulate, compare, explain.",
    inChip: "Every engineer works this way. Circuit designers use SPICE, RTL designers use simulators and waveform viewers, and nobody trusts a change until they have watched the result and can explain it.",
    breaks: "Skipping the prediction turns simulation into guess-and-check. The tool then tells you what happens but never why, and that habit fails badly when a chip-scale regression produces thousands of waveforms.",
    tested: "By whether your hand prediction matched the simulation, and by whether you can explain any mismatch without hand-waving.",
    prereqs: ["circuit-reading", "capacitor-basics"],
    objectives: ["Build a working circuit in a browser simulator", "Predict node voltages before running, then compare", "Measure an RC time constant from a plotted curve", "Write down what surprised you and why"],
    terms: [["Simulator", "Software that solves circuit equations over time and shows the result"], ["Scope / probe", "A view that plots a node's voltage or current against time"], ["Time constant (tau)", "R x C: the time to reach about 63% of the final voltage"], ["Predict-then-check", "Writing your expected answer before running the tool"]],
    visuals: [
      { title: "The loop you will use for the next year", art: "   predict (by hand)\n        |\n        v\n     simulate\n        |\n        v\n   compare -----> matched? -> understand why, move on\n        |\n        +--------> differed? -> find the wrong assumption\n                                (this is where learning happens)" },
      { title: "RC charging: what to look for", art: "  V\n  VDD |            _________________\n      |        __/\n  63% |.....__/\n      |   _/ :\n    0 |__/   :\n      +------+------------------- t\n             tau = R x C" },
    ],
    example: "Build a 10 kOhm resistor in series with a 1 uF capacitor across 5 V. Predicted tau = R x C = 10e3 x 1e-6 = 10 ms, so the node should reach about 3.15 V (63% of 5 V) after 10 ms and be nearly full after about 50 ms. Run it, put a scope on the capacitor node, and read the curve: it should match closely. If it does not, check the units, which is the usual culprit.",
    mistakes: ["Running first and predicting afterwards, which teaches nothing", "Mixing up units so tau is out by a factor of a thousand", "Building only circuits that work: deliberately breaking one (removing the ground connection, shorting the divider) teaches more"],
    practice: ["Build a voltage divider that outputs a quarter of the supply and verify it in the simulator", "Build an RC circuit, measure tau from the scope and compare with R x C", "Break one circuit on purpose (remove ground, or short a resistor) and write down what you observed and why", "Save or screenshot your three circuits with a sentence each: this is the first entry in your lab notebook"],
    interview: [
      { q: "How do you approach a circuit or design you do not understand?", a: "Predict the behaviour from first principles first, then simulate, then explain every difference between the two. The mismatches are where the wrong assumption lives, and that is the fastest way to find it.", level: 2 },
      { q: "Why is simulation not enough on its own?", a: "A simulator only models what it was given, so it can be confidently wrong about parasitics, corners and effects that were not included. It supports judgement rather than replacing it, which is why designs also go through analysis and sign-off checks.", level: 3 },
    ],
    resources: ["falstad"],
  },
];
