import type { Topic } from "../schema.ts";

export const P10_P12: Topic[] = [
  {
    id: "superscalar-ooo", title: "Superscalar and out-of-order execution", phase: "p10", module: "m10a",
    priority: "should", depth: "basic", difficulty: 4, days: 2, hours: 5, kind: "theory", skills: ["arch"],
    why: "Modern high-performance cores are out-of-order. Architecture and CPU DV interviews assume this vocabulary.",
    problem: "In-order pipelines stall on long-latency instructions. Executing independent instructions out of order, then committing in order, keeps units busy while preserving precise exceptions.",
    eli12: "In a kitchen, if one dish waits for the oven, cooks start other dishes that are ready, but serve everything in the order it was ordered.",
    tech: "Superscalar fetch/decode/issue of multiple instructions per cycle; register renaming removes WAR/WAW hazards; issue queues and wakeup/select; reorder buffer (ROB) commits in order; load/store queues handle memory ordering; branch recovery via checkpoints. Examples: BOOM (Berkeley), CVA6 is in-order but useful for comparison.",
    inChip: "Application processors; CPU DV verifies these structures.",
    breaks: "Rename leaks, memory ordering violations, recovery bugs.",
    tested: "Random instruction streams with co-simulation against an ISS.",
    prereqs: ["hazards", "branch-prediction"],
    objectives: ["Explain renaming and the ROB", "Explain why commit is in order", "Explain memory disambiguation"],
    terms: [["ROB", "Reorder buffer"], ["Register renaming", "Mapping architectural to physical registers"], ["Precise exception", "State reflects all older and no younger instructions"]],
    mistakes: ["Confusing out-of-order execution with out-of-order commit"],
    practice: ["Trace five instructions with a WAW hazard through rename and the ROB on paper"],
    interview: [{ q: "Why do out-of-order cores commit in order?", a: "To keep precise exceptions and a consistent architectural state: if an older instruction faults, younger ones that executed early must be discarded.", level: 3 }],
    resources: ["hennessy-patterson", "mutlu-yt"],
  },
  {
    id: "coherence", title: "Multicore, cache coherence and memory consistency", phase: "p10", module: "m10a",
    priority: "should", depth: "basic", difficulty: 4, days: 2, hours: 5, kind: "theory", skills: ["arch", "verification"],
    why: "Coherence and consistency bugs are among the hardest to verify; senior DV and architecture roles discuss them.",
    problem: "Private caches can hold stale copies of shared data. Coherence protocols keep copies consistent; consistency models define what orderings software may observe.",
    eli12: "Several people keep photocopies of the same page. When one writes on theirs, the others must be told their copy is out of date.",
    tech: "Snooping vs directory coherence, MSI/MESI/MOESI states, invalidation vs update, false sharing, memory consistency models (sequential consistency, TSO, RISC-V RVWMO), fences and atomics.",
    inChip: "Multicore SoCs, GPUs, coherent accelerators.",
    breaks: "Deadlocks and races in protocols; software seeing reordered memory.",
    tested: "Litmus tests, formal protocol verification, stress tests.",
    prereqs: ["caches"],
    objectives: ["Walk through MESI transitions", "Explain false sharing", "Explain why fences exist"],
    terms: [["MESI", "Modified, Exclusive, Shared, Invalid states"], ["Litmus test", "Tiny program probing ordering"]],
    mistakes: ["Confusing coherence (one address) with consistency (ordering across addresses)"],
    practice: ["Draw MESI transitions for two cores reading then writing the same line"],
    interview: [{ q: "What is the difference between coherence and consistency?", a: "Coherence ensures all cores agree on the order of writes to a single address; consistency defines allowed orderings of accesses across different addresses.", level: 3 }],
    resources: ["hennessy-patterson", "mutlu-yt"],
  },
  {
    id: "noc", title: "Networks-on-chip", phase: "p10", module: "m10a",
    priority: "optional", depth: "awareness", difficulty: 3, days: 1, hours: 2, kind: "theory", skills: ["arch", "protocols"],
    why: "Large SoCs and AI chips use NoCs instead of buses.",
    problem: "Crossbars scale poorly; packet-switched networks connect many blocks efficiently.",
    eli12: "Instead of one big road junction, the chip gets a grid of small crossroads, and messages travel in packets like mail.",
    tech: "Topologies (mesh, ring, torus), routers, flits, virtual channels, credit-based flow control, deadlock avoidance (dimension-order routing), QoS.",
    inChip: "Many-core CPUs, AI accelerators, large SoCs.",
    breaks: "Deadlock, where packets wait on each other forever, and congestion that quietly destroys throughput once traffic rises.",
    tested: "Traffic simulation and formal deadlock checks.",
    prereqs: ["soc-buses", "valid-ready"],
    objectives: ["Explain flits and credits", "Explain dimension-order routing"],
    terms: [["Flit", "Flow-control unit of a packet"], ["Virtual channel", "Separate buffers sharing a physical link"]],
    mistakes: ["Ignoring deadlock"],
    practice: ["Explain why XY routing on a mesh avoids deadlock"],
    interview: [{ q: "Why use a NoC instead of a bus?", a: "Buses and crossbars do not scale in bandwidth, wiring and timing for many agents; NoCs provide scalable parallel links with packet routing.", level: 2 }],
    resources: ["hennessy-patterson"],
  },
  {
    id: "high-speed-io", title: "High-speed interfaces: DDR, PCIe, SerDes and chiplets", phase: "p10", module: "m10b",
    priority: "should", depth: "awareness", difficulty: 3, days: 2, hours: 4, kind: "theory", skills: ["protocols"],
    why: "Job postings frequently list PCIe, DDR, Ethernet, USB and UCIe. Awareness lets you discuss them credibly.",
    problem: "Moving data off-chip at high rates needs serial links, equalization and layered protocols.",
    eli12: "Inside a chip data travels on wide slow roads; between chips it travels on very fast single-lane highways with strict traffic rules.",
    tech: "SerDes (serialization, clock recovery, equalization), PCIe layers (PHY, data link, transaction), DDR memory controllers and PHY training, Ethernet MAC/PCS, USB, chiplet interconnect (UCIe), 2.5D/3D packaging.",
    inChip: "Controller IP (RTL/DV) and PHY (mixed-signal) teams.",
    breaks: "Link training failures, protocol compliance issues.",
    tested: "Protocol VIP, compliance testing.",
    prereqs: ["soc-buses"],
    objectives: ["Describe PCIe layering", "Describe what a DDR controller does", "Explain why chiplets exist"],
    terms: [["SerDes", "Serializer/deserializer"], ["UCIe", "Chiplet interconnect standard"], ["Link training", "Negotiation of link parameters"]],
    mistakes: ["Claiming protocol experience from reading specs only"],
    practice: ["Summarize PCIe TLP, DLLP and ordered sets in one page"],
    interview: [{ q: "What does a DDR memory controller do?", a: "Converts read/write requests into DRAM commands (activate, read, write, precharge, refresh), schedules them for bandwidth and latency, and meets DRAM timing parameters, with a PHY handling signalling and training.", level: 2 }],
    resources: ["hennessy-patterson"],
  },
  {
    id: "low-power-arch", title: "Low-power architecture: DVFS, power gating, dark silicon", phase: "p10", module: "m10b",
    priority: "should", depth: "basic", difficulty: 3, days: 1, hours: 3, kind: "theory", skills: ["arch", "asic"],
    why: "System power decisions shape every modern chip.",
    problem: "Power limits mean not all transistors can be active at once; architectures must spend energy wisely.",
    eli12: "A house can only draw so much electricity, so you switch appliances on only when needed and slow them down when possible.",
    tech: "DVFS operating points, power states, power gating domains, race-to-idle vs slow-and-steady, specialization (accelerators) for efficiency, dark silicon.",
    inChip: "Power architects, firmware power management.",
    breaks: "Thermal throttling, missed battery targets.",
    tested: "Power modeling and silicon measurements.",
    prereqs: ["power", "low-power-rtl"],
    objectives: ["Explain DVFS", "Compare race-to-idle and DVFS"],
    terms: [["Dark silicon", "Chip area that cannot be powered simultaneously"], ["Operating point", "Voltage-frequency pair"]],
    mistakes: ["Ignoring leakage when choosing race-to-idle"],
    practice: ["Compute energy for a task at two voltage/frequency points"],
    interview: [{ q: "Why do accelerators improve energy efficiency?", a: "Specialized datapaths avoid instruction fetch/decode overheads and move less data, spending most energy on useful computation.", level: 2 }],
    resources: ["hennessy-patterson"],
  },
  {
    id: "hw-security", title: "Hardware security: side channels and roots of trust", phase: "p10", module: "m10b",
    priority: "optional", depth: "awareness", difficulty: 3, days: 1, hours: 2, kind: "theory", skills: ["arch", "verification"],
    why: "Security verification and silicon root-of-trust projects (like OpenTitan) are growing areas.",
    problem: "Attackers exploit timing, power, speculation and debug interfaces to leak secrets.",
    eli12: "Even if a safe is locked, a thief might listen to the clicks. Hardware security stops the clicks from giving away the code.",
    tech: "Side channels (timing, power, cache), speculative execution attacks, fault injection, secure boot, roots of trust, debug lockdown, constant-time crypto hardware, security verification with formal and information flow.",
    inChip: "Security IP teams; OpenTitan is an open-source silicon root of trust.",
    breaks: "Key leakage, bypassed secure boot.",
    tested: "Threat modeling, formal security properties, penetration testing.",
    prereqs: ["caches"],
    objectives: ["Explain a timing side channel", "Explain a root of trust"],
    terms: [["Root of trust", "Hardware anchor for secure boot and keys"], ["Side channel", "Leakage through physical or timing effects"]],
    mistakes: ["Treating security as software-only"],
    practice: ["Read the OpenTitan documentation overview and list its security features"],
    interview: [{ q: "What is a timing side channel?", a: "Secret-dependent execution time (for example cache hits vs misses or early-exit comparisons) lets an attacker infer secrets by measuring timing.", level: 2 }],
    resources: ["opentitan"],
  },
  {
    id: "reliability", title: "Reliability and safety: ECC, parity, functional safety", phase: "p10", module: "m10b",
    priority: "optional", depth: "awareness", difficulty: 3, days: 1, hours: 2, kind: "theory", skills: ["rtl", "verification"],
    why: "Automotive and data-centre chips require error protection and safety processes.",
    problem: "Radiation and aging flip bits; safety-critical systems must detect and handle faults.",
    eli12: "Like adding a check digit to a bank account number so typos are caught.",
    tech: "Parity, Hamming SECDED ECC, scrubbing, lockstep cores, watchdogs, ISO 26262 safety processes, fault injection campaigns.",
    inChip: "Memories, automotive MCUs, servers.",
    breaks: "Silent data corruption: the chip keeps running and produces wrong answers that nobody notices until much later.",
    tested: "By fault injection: flip bits deliberately in simulation and check that the protection detects or corrects them.",
    prereqs: ["memory-basics"],
    objectives: ["Implement SECDED concept", "Explain lockstep"],
    terms: [["SECDED", "Single-error correct, double-error detect"], ["Lockstep", "Duplicate cores compared each cycle"]],
    mistakes: ["Parity where correction is required"],
    practice: ["Encode and decode a (7,4) Hamming code in Python"],
    interview: [{ q: "How does SECDED work at a high level?", a: "Extra check bits computed over data locate a single-bit error for correction; an overall parity bit distinguishes double-bit errors so they are detected but not miscorrected.", level: 3 }],
    resources: ["hennessy-patterson"],
  },
  {
    id: "hw-sw-codesign", title: "Hardware/software co-design: drivers, register maps, firmware", phase: "p10", module: "m10b",
    priority: "must", depth: "working", difficulty: 3, days: 2, hours: 5, kind: "coding", skills: ["cpp", "rtl", "arch"],
    why: "Accelerators are only useful with software. Your software background makes co-design a differentiator.",
    problem: "Hardware and software teams make assumptions about each other; co-design aligns interfaces, performance and debug.",
    eli12: "A new machine needs a user manual and buttons that make sense; co-design builds both together.",
    tech: "Register map design from software use cases, DMA descriptors, interrupts vs polling, memory-mapped vs custom instructions (RISC-V custom opcodes), driver structure, benchmarking end-to-end speedup including data movement, simulation of firmware on RTL (Verilator) or FPGA.",
    inChip: "SoC and accelerator teams; firmware engineers.",
    breaks: "Accelerators that are faster in isolation but slower end-to-end due to data movement.",
    tested: "End-to-end benchmarks with software.",
    prereqs: ["io-interrupts", "c-for-hw"],
    objectives: ["Design a driver-friendly register interface", "Measure end-to-end speedup", "Compare MMIO vs custom instructions"],
    terms: [["Descriptor", "Memory structure telling a DMA what to move"], ["Custom instruction", "ISA extension implemented in hardware"]],
    mistakes: ["Measuring kernel time only"],
    practice: ["Write a C driver for your accelerator register map and measure speedup vs software"],
    interview: [{ q: "Your accelerator is 10x faster but the application only speeds up 1.3x. Why?", a: "Amdahl's law and overheads: data movement, driver and synchronization costs, and the unaccelerated portion dominate. Measure end-to-end and optimize the interface.", level: 3 }],
    resources: ["litex", "riscv-gnu-toolchain"],
    projects: ["fp-capstone"],
  },
  {
    id: "design-tradeoffs", title: "Engineering judgment: design reviews and tradeoff analysis", phase: "p10", module: "m10b",
    priority: "must", depth: "advanced", difficulty: 4, days: 2, hours: 4, kind: "theory", skills: ["interview", "arch", "rtl"],
    why: "Senior-level understanding shows up as judgment: asking the right questions and choosing the simplest design that meets requirements.",
    problem: "Engineers often optimize what is easy to measure instead of what matters. Structured tradeoff analysis prevents that.",
    eli12: "Good engineers ask 'what problem are we really solving?' before choosing the fanciest tool.",
    tech: "Requirements first; alternatives with pros/cons; PPA, verification cost, schedule, risk, reuse; decision records; review checklists (clocks, resets, CDC, testability, debug, power, corner cases); pre-mortems.",
    inChip: "Architecture and design reviews at every company.",
    breaks: "Overengineering, late surprises, unverifiable designs.",
    tested: "Review outcomes and post-silicon results.",
    prereqs: ["ppa"],
    objectives: ["Write a decision record", "Run a self-review with a checklist", "Answer 'why this design?' clearly"],
    terms: [["Decision record", "Short document of a choice and its rationale"], ["Pre-mortem", "Imagining failure to find risks early"]],
    mistakes: ["Presenting a single option"],
    senior: ["What would make you choose a simpler, slower design?", "What is the verification cost of this feature?"],
    practice: ["Write decision records for three choices in your flagship project"],
    interview: [{ q: "Choose between a deep pipeline at 1.5 GHz and a shallow one at 1 GHz for an accelerator.", a: "Ask about throughput needs, latency sensitivity, power budget, area, verification complexity and data dependencies. Compare throughput per watt and per area; pick the simplest meeting requirements with margin.", level: 4 }],
    resources: ["hennessy-patterson"],
  },
  {
    id: "nn-compute", title: "What neural networks compute (MACs, tensors, layers)", phase: "p11", module: "m11a",
    priority: "should", depth: "basic", difficulty: 2, days: 1, hours: 3, kind: "theory", skills: ["aihw"],
    why: "AI hardware starts by counting the work: multiply-accumulates and bytes moved.",
    problem: "To design hardware for AI, you must translate layers into operation counts, data sizes and access patterns.",
    eli12: "A neural network is mostly lots of 'multiply then add' steps, like a gigantic spreadsheet of weighted sums.",
    tech: "Fully connected layers are matrix-vector products; convolutions become matrix multiplications (im2col); attention is matmuls plus softmax. Count MACs and parameters, activations and their reuse; inference vs training differences.",
    inChip: "AI accelerator architecture and performance modeling.",
    breaks: "Designing for MACs while ignoring memory traffic.",
    tested: "Operation-count models versus measured performance.",
    prereqs: ["fixed-point", "python-hw"],
    objectives: ["Count MACs for a conv layer", "Estimate weights and activation sizes"],
    terms: [["MAC", "Multiply-accumulate"], ["Activation", "Intermediate layer output"]],
    equations: ["Conv MACs = H_out x W_out x C_out x K x K x C_in"],
    mistakes: ["Ignoring activation memory"],
    practice: ["Count MACs and parameters for a small CNN in Python"],
    interview: [{ q: "How many MACs in a 3x3 conv with 64 input and 64 output channels on a 56x56 output?", a: "56 x 56 x 64 x 3 x 3 x 64 ~ 115.6 million MACs.", level: 2 }],
    resources: ["sze-book", "mutlu-yt"],
    papers: ["sze-tutorial"],
  },
  {
    id: "matmul-mac", title: "Matrix multiplication in hardware: MAC arrays", phase: "p11", module: "m11a",
    priority: "should", depth: "working", difficulty: 3, days: 2, hours: 5, kind: "coding", skills: ["aihw", "rtl"],
    why: "Matrix multiply is the core kernel of AI. Building a MAC array is the entry point to accelerator design.",
    problem: "CPUs execute MACs one or a few at a time; arrays of MACs with local data reuse do thousands per cycle.",
    eli12: "Instead of one person doing all the multiplications, a whole classroom does them at once and passes partial sums along.",
    tech: "Tiling to fit on-chip buffers, loop ordering, accumulator widths, fixed-point/INT8 MACs, pipelined MAC units, utilization.",
    inChip: "NPUs, TPUs, GPU tensor cores, DSP blocks.",
    breaks: "Accumulator overflow; low utilization from poor tiling.",
    tested: "Bit-accurate NumPy reference models.",
    prereqs: ["fixed-point", "pipelined-rtl"],
    objectives: ["Implement a pipelined INT8 MAC", "Tile a matmul for a buffer size"],
    terms: [["Tiling", "Splitting matrices into blocks"], ["Utilization", "Fraction of MACs doing useful work"]],
    mistakes: ["Undersized accumulators"],
    practice: ["Implement a 4x4 MAC array computing a tiled matmul and verify against NumPy"],
    interview: [{ q: "Why tile a matrix multiplication?", a: "To fit blocks into on-chip memory and reuse each loaded element many times, reducing off-chip traffic.", level: 2 }],
    resources: ["sze-book", "gemmini"],
    projects: ["m-systolic-py", "fp-fpga-accel"],
  },
  {
    id: "systolic", title: "Systolic arrays and dataflows", phase: "p11", module: "m11a",
    priority: "should", depth: "working", difficulty: 4, days: 2, hours: 5, kind: "coding", skills: ["aihw", "rtl"],
    why: "Systolic arrays (for example in TPUs) and dataflow choices determine accelerator efficiency.",
    problem: "Moving data dominates energy; systolic arrays pass data between neighbours rhythmically so each value is reused without going back to memory.",
    eli12: "Like a bucket brigade where each person does a little work on each bucket before passing it along, in a steady rhythm.",
    tech: "Weight-stationary, output-stationary, row-stationary dataflows; skewed input timing; array fill/drain overhead; mapping convolutions; Kung's systolic principles; Eyeriss dataflow analysis.",
    inChip: "Google TPU, many NPUs, open Gemmini generator.",
    breaks: "Skew errors, poor utilization for small matrices.",
    tested: "Cycle-accurate models versus RTL.",
    prereqs: ["matmul-mac"],
    objectives: ["Simulate a systolic array in Python", "Compare dataflows"],
    terms: [["Weight-stationary", "Weights stay in PEs while activations flow"], ["PE", "Processing element"]],
    mistakes: ["Forgetting input skew"],
    practice: ["Write a cycle-level Python systolic simulator, then an RTL 4x4 version"],
    interview: [{ q: "What is a weight-stationary dataflow?", a: "Weights are preloaded into PEs and stay there while input activations stream through and partial sums move, maximizing weight reuse.", level: 3 }],
    resources: ["gemmini", "sze-book"],
    papers: ["kung-systolic", "tpu-isca", "eyeriss"],
    projects: ["m-systolic-py", "fp-fpga-accel"],
  },
  {
    id: "roofline", title: "Memory bandwidth, on-chip memory and the roofline model", phase: "p11", module: "m11a",
    priority: "should", depth: "working", difficulty: 3, days: 2, hours: 4, kind: "theory", skills: ["aihw", "arch"],
    why: "The roofline tells you whether a design is compute-bound or memory-bound, the first question in any accelerator review.",
    problem: "Peak compute is meaningless if data cannot be delivered fast enough.",
    eli12: "A factory with many machines is useless if the delivery truck brings materials too slowly.",
    tech: "Attainable performance = min(peak compute, bandwidth x arithmetic intensity). Arithmetic intensity = operations/byte. Increase intensity with reuse (tiling, buffers). Memory hierarchy energy costs dominate.",
    inChip: "Accelerator architecture and performance analysis.",
    breaks: "Overbuilt compute starved by memory.",
    tested: "Roofline plots with measured kernels.",
    prereqs: ["matmul-mac", "memory-hierarchy"],
    objectives: ["Plot a roofline", "Compute arithmetic intensity"],
    terms: [["Arithmetic intensity", "Operations per byte moved"], ["Ridge point", "Intensity where compute and bandwidth limits meet"]],
    equations: ["P = min(P_peak, BW x I)"],
    mistakes: ["Using peak bandwidth that is never achieved"],
    practice: ["Plot rooflines for your FPGA accelerator and a laptop CPU with measured numbers"],
    interview: [{ q: "How do you know if a kernel is memory-bound?", a: "Compute its arithmetic intensity; if below the machine's ridge point (peak ops / bandwidth), bandwidth limits performance.", level: 2 }],
    resources: ["hennessy-patterson"],
    papers: ["roofline"],
  },
  {
    id: "quantization-sparsity", title: "Quantization (INT8/INT4) and sparsity", phase: "p11", module: "m11a",
    priority: "should", depth: "working", difficulty: 3, days: 2, hours: 5, kind: "coding", skills: ["aihw", "python"],
    why: "Lower precision and skipping zeros are the biggest efficiency levers in AI hardware.",
    problem: "FP32 is expensive in area, energy and bandwidth; many networks keep accuracy with 8-bit or lower integers and with many zeros.",
    eli12: "Rounding prices to the nearest rupee makes arithmetic much easier and rarely changes the total much.",
    tech: "Scale/zero-point quantization, per-channel scaling, integer-only inference, INT4 and mixed precision, accuracy evaluation; structured vs unstructured sparsity, compressed formats, zero-skipping hardware.",
    inChip: "Edge NPUs, datacentre inference accelerators.",
    breaks: "Accuracy collapse from bad calibration; sparse formats with high overhead.",
    tested: "Accuracy vs bit width curves with bit-accurate models.",
    prereqs: ["fixed-point", "nn-compute"],
    objectives: ["Quantize a model to INT8", "Measure accuracy loss", "Explain structured sparsity"],
    terms: [["Scale", "Real value per integer step"], ["Structured sparsity", "Zeros in regular patterns hardware can exploit"]],
    mistakes: ["Evaluating quantization on training data"],
    practice: ["Quantize a small MLP to INT8 in NumPy and compare accuracy"],
    interview: [{ q: "Why does INT8 save energy compared with FP32?", a: "Integer multipliers are much smaller and lower energy, and 4x fewer bits must be moved and stored, which reduces memory energy.", level: 2 }],
    resources: ["sze-book"],
    papers: ["jacob-quant", "deep-compression"],
  },
  {
    id: "accelerators", title: "Accelerator architectures: NPUs, TPUs, GPUs and FPGA/edge AI", phase: "p11", module: "m11a",
    priority: "should", depth: "basic", difficulty: 3, days: 2, hours: 4, kind: "theory", skills: ["aihw", "arch"],
    why: "Understanding the landscape lets you position your projects and talk to AI hardware teams.",
    problem: "Different workloads and deployment settings favour different architectures.",
    eli12: "GPUs are big kitchens with many general cooks; NPUs are kitchens designed for one type of dish; FPGAs are kitchens you can rearrange.",
    tech: "GPU SIMT and tensor cores; TPU-style systolic accelerators; NPU designs with scratchpads and DMA; FPGA inference (hls4ml, FINN); open designs (NVDLA, Gemmini); software stacks and compilers.",
    inChip: "AI hardware startups and large companies.",
    breaks: "Hardware without a usable software stack.",
    tested: "By benchmark suites such as MLPerf-style workloads, measuring end-to-end throughput rather than peak paper numbers.",
    prereqs: ["systolic", "roofline"],
    objectives: ["Compare GPU, TPU and NPU designs", "Name open accelerator projects"],
    terms: [["SIMT", "Single instruction, multiple threads"], ["Scratchpad", "Software-managed on-chip memory"]],
    mistakes: ["Ignoring the compiler/runtime"],
    practice: ["Read the NVDLA or Gemmini documentation and draw its block diagram"],
    interview: [{ q: "Why do accelerators use scratchpads instead of caches?", a: "Access patterns are predictable, so software-managed buffers give deterministic, lower-energy access without tag overhead.", level: 3 }],
    resources: ["gemmini", "nvdla", "hls4ml", "finn"],
    papers: ["tpu-isca", "gemmini-paper"],
  },
  {
    id: "transformer-hw", title: "Transformer and LLM inference hardware", phase: "p11", module: "m11a",
    priority: "specialization", depth: "basic", difficulty: 4, days: 2, hours: 5, kind: "theory", skills: ["aihw"],
    why: "LLM inference is a major driver of current AI hardware work.",
    problem: "Attention and large weights make LLM inference memory-bound; KV caches grow with context length.",
    eli12: "An LLM rereads its notes (KV cache) for every new word it writes; the notes get longer and heavier with every word.",
    tech: "Attention = softmax(QK^T/sqrt(d))V; prefill (compute-bound) vs decode (memory-bound); KV cache size; IO-aware algorithms (FlashAttention's tiling with online softmax); weight quantization; batching; specialized attention accelerators.",
    inChip: "Datacentre and edge LLM accelerators.",
    breaks: "Bandwidth-starved decode; softmax numerical overflow.",
    tested: "Throughput and latency per token benchmarks.",
    prereqs: ["roofline", "quantization-sparsity"],
    objectives: ["Explain prefill vs decode", "Compute KV cache size", "Explain online softmax"],
    terms: [["KV cache", "Stored keys/values from previous tokens"], ["Online softmax", "Computing softmax incrementally over tiles"]],
    mistakes: ["Treating decode as compute-bound"],
    practice: ["Compute the KV cache size for a model with 32 layers, 32 heads, d=128, 4k context, FP16"],
    interview: [{ q: "Why is LLM decode memory-bound?", a: "Each token needs all weights and the KV cache read from memory but performs relatively few operations per byte, so bandwidth limits speed.", level: 3 }],
    resources: ["sze-book"],
    papers: ["flashattention", "spatten"],
    projects: ["fp-attention"],
  },
  {
    id: "ml-for-eda", title: "Where machine learning fits in the chip flow", phase: "p11", module: "m11b",
    priority: "specialization", depth: "awareness", difficulty: 2, days: 1, hours: 3, kind: "theory", skills: ["eda", "aihw"],
    why: "AI for EDA combines your software, ML and hardware interests. Knowing the landscape keeps expectations realistic.",
    problem: "EDA steps are slow and heuristic; ML can predict outcomes early, tune flows, and assist verification.",
    eli12: "Instead of waiting hours for the robot to finish a chip layout to see if it is good, a trained model makes a quick, educated guess.",
    tech: "Prediction (congestion, timing, IR), optimization (design-space exploration, flow tuning, placement), generation (LLMs for RTL, assertions, scripts), verification (coverage-directed test generation, bug triage). Data availability is the main constraint; open datasets like CircuitNet help.",
    inChip: "EDA vendors and in-house CAD teams.",
    breaks: "Models that do not generalize to new designs.",
    tested: "By evaluation on held-out designs the model never saw in training, which is the only honest test of generalization.",
    prereqs: ["open-flow", "python-hw"],
    objectives: ["Map ML techniques to flow stages", "Explain data challenges"],
    terms: [["DSE", "Design-space exploration"], ["Generalization", "Performance on unseen designs"]],
    mistakes: ["Evaluating on the same designs used for training"],
    practice: ["Write a one-page landscape of ML in EDA with one paper per flow stage"],
    interview: [{ q: "What is the biggest challenge for ML in EDA?", a: "Limited, proprietary, heterogeneous data and the need to generalize to new designs and technologies; also integrating predictions into flows with trustworthy error bounds.", level: 2 }],
    resources: ["circuitnet"],
    papers: ["circuitnet-paper"],
  },
  {
    id: "ml-prediction", title: "ML for timing, congestion and PPA prediction", phase: "p11", module: "m11b",
    priority: "research", depth: "research", difficulty: 4, days: 2, hours: 6, kind: "coding", skills: ["eda", "python"],
    why: "A reproducible prediction project is a strong research-flavoured portfolio piece. Research / Optional.",
    problem: "Knowing routability or slack before running full flows saves iterations.",
    eli12: "Like predicting traffic jams from the city map before the roads are built.",
    tech: "Features from netlists and placements (images or graphs), CNNs for congestion maps (RouteNet-style), GNNs for timing (for example timing-engine-inspired GNNs), datasets from CircuitNet or your own ORFS sweeps, evaluation with held-out designs.",
    inChip: "Research and advanced CAD teams.",
    breaks: "Data leakage; misleading metrics.",
    tested: "Held-out designs and baselines.",
    prereqs: ["ml-for-eda", "graphs-in-eda"],
    objectives: ["Build a dataset from flow runs", "Train and evaluate a baseline model"],
    terms: [["GNN", "Graph neural network"], ["Data leakage", "Test information influencing training"]],
    mistakes: ["No baseline comparison"],
    practice: ["Reproduce one CircuitNet congestion baseline"],
    interview: [{ q: "How would you evaluate a timing prediction model fairly?", a: "Train on some designs, test on unseen designs, compare to simple baselines, report error distributions on critical endpoints, and check whether predictions improve flow decisions.", level: 3 }],
    resources: ["circuitnet", "timingpredict", "orfs"],
    papers: ["circuitnet-paper", "routenet", "timing-gnn"],
    projects: ["fp-ml-eda"],
  },
  {
    id: "rl-placement", title: "Reinforcement learning for placement (and the debate around it)", phase: "p11", module: "m11b",
    priority: "research", depth: "research", difficulty: 5, days: 1, hours: 4, kind: "theory", skills: ["eda", "aihw"],
    why: "One of the most discussed AI-for-EDA results; understanding the debate teaches research literacy. Research / Optional.",
    problem: "Macro placement is hard and slow; RL was proposed to learn placement policies.",
    eli12: "A game-playing AI learning to arrange furniture in a room; experts then argued about how well it really plays.",
    tech: "Google's 2021 Nature paper proposed RL macro placement (open-sourced as Circuit Training). A later independent study (TILOS MacroPlacement, ISPD 2023) compared it with classical methods and raised reproducibility concerns; the original authors responded. Learn to read claims, baselines and reproduction evidence.",
    inChip: "Research; commercial tools use many methods.",
    breaks: "Unfair baselines and unreproducible claims.",
    tested: "Open reproductions and benchmarks.",
    prereqs: ["floorplan", "eda-algorithms"],
    objectives: ["Summarize the method", "Summarize the critique and response", "Explain what fair evaluation requires"],
    terms: [["Macro placement", "Placing large blocks like SRAMs"], ["Reproducibility", "Independent confirmation of results"]],
    mistakes: ["Taking claims at face value in either direction"],
    practice: ["Read the MacroPlacement repository README and write a balanced one-page summary"],
    interview: [{ q: "What makes an ML-for-EDA comparison fair?", a: "Same designs, constraints, compute budgets, and strong classical baselines, with full-flow metrics (timing, power, wirelength after routing) and reproducible code.", level: 4 }],
    resources: ["circuit-training", "macroplacement"],
    papers: ["alphachip-nature", "macroplacement-ispd"],
    projects: ["fp-macro-placement"],
  },
  {
    id: "llm-hardware", title: "LLMs for RTL generation and verification", phase: "p11", module: "m11b",
    priority: "research", depth: "research", difficulty: 4, days: 2, hours: 6, kind: "coding", skills: ["eda", "verification", "python"],
    why: "LLM-assisted hardware design is an active area; rigorous evaluation work is valuable and suits your background. Research / Optional.",
    problem: "LLMs can draft RTL, tests and assertions, but correctness is not guaranteed; measuring quality needs benchmarks and verification.",
    eli12: "An AI can write a first draft of a circuit, but someone must test it carefully, like checking a student's homework.",
    tech: "Benchmarks (VerilogEval, RTLLM), pass@k metrics with simulation, domain adaptation (ChipNeMo), conversational design (Chip-Chat), LLM-generated assertions evaluated by mutation testing, safety of using generated code.",
    inChip: "Research teams at EDA and chip companies; internal productivity tools.",
    breaks: "Plausible but wrong RTL; benchmark contamination.",
    tested: "Simulation-based benchmarks and formal checks.",
    prereqs: ["ml-for-eda", "sva"],
    objectives: ["Run a VerilogEval subset", "Evaluate assertions with mutations", "Discuss limitations honestly"],
    terms: [["pass@k", "Probability at least one of k samples is correct"], ["Contamination", "Benchmark data seen in training"]],
    mistakes: ["Reporting only successful examples"],
    practice: ["Run 20 VerilogEval problems with an LLM and report pass@1 with failure analysis"],
    interview: [{ q: "How would you evaluate LLM-generated RTL?", a: "Use held-out problems with testbenches, measure pass@k, lint and synthesize outputs, analyze failure types, and check for data contamination.", level: 3 }],
    resources: ["verilog-eval", "rtllm"],
    papers: ["verilogeval", "rtllm-paper", "chipnemo", "chip-chat"],
    projects: ["fp-llm-hw"],
  },
  {
    id: "portfolio-strategy", title: "Building a signature portfolio", phase: "p12", module: "m12a",
    priority: "must", depth: "working", difficulty: 2, days: 2, hours: 4, kind: "career", skills: ["interview"],
    why: "Without a VLSI degree, your portfolio is your strongest evidence. Curating it matters as much as building it.",
    problem: "Twenty tiny projects look like coursework. A few deep, documented projects prove capability.",
    eli12: "An art portfolio shows your best eight paintings, not every doodle from class.",
    tech: "Target 3-5 strong supporting projects, 3-5 flagship projects and 1-3 research or open-source items, around 8-12 polished pieces. Each: README, diagram, results, verification evidence, lessons. Align with target role. Pin repos, write summaries.",
    inChip: "Recruiters and interviewers skim quickly; clarity wins.",
    breaks: "Unfinished repos, missing results, exaggerated claims.",
    tested: "By asking someone else to open your portfolio cold and seeing whether they can tell what you built within a minute.",
    prereqs: ["e2e-report"],
    objectives: ["Select portfolio pieces", "Map each to a target role", "Complete showcase checklists"],
    terms: [["Flagship", "Deep project showing multiple skills"], ["Supporting project", "Smaller but complete project"]],
    mistakes: ["Showcasing tutorials"],
    practice: ["Fill the Portfolio page slots and mark gaps"],
    interview: [{ q: "Which project are you proudest of and why?", a: "Pick one with measurable results and real debugging; explain problem, architecture, verification, results, tradeoffs and what you learned.", level: 2 }],
    resources: [],
  },
  {
    id: "github-showcase", title: "Turning projects into evidence: README, reports, demos", phase: "p12", module: "m12a",
    priority: "must", depth: "working", difficulty: 2, days: 2, hours: 4, kind: "career", skills: ["interview"],
    why: "A reviewer spends minutes on your repo. Structure decides whether they see the depth.",
    problem: "Good work hidden in messy repos is invisible.",
    eli12: "A museum exhibit needs a clear sign, a picture and a short story, not just the object.",
    tech: "README template: one-line summary, diagram, features, results table, how to run (one command), verification summary, repo layout, limitations, next steps. CI badges, waveform screenshots, GDS images, short demo video or GIF.",
    inChip: "Mirrors internal design documentation practices.",
    breaks: "No run instructions; broken builds.",
    tested: "Fresh clone and run test by a friend.",
    prereqs: ["portfolio-strategy"],
    objectives: ["Rewrite a README to the template", "Add CI and results", "Record a short demo"],
    terms: [["Reproducible build", "One command reproduces results"]],
    mistakes: ["Screenshots without context"],
    practice: ["Apply the template to your best project and ask someone to run it from scratch"],
    interview: [{ q: "How do you document a hardware project?", a: "Spec and architecture docs, clear README with results and run instructions, verification report, implementation reports, and lessons learned.", level: 1 }],
    resources: [],
  },
  {
    id: "certifications-eval", title: "Evaluating certifications (and when to skip them)", phase: "p12", module: "m12a",
    priority: "should", depth: "basic", difficulty: 1, days: 1, hours: 2, kind: "career", skills: ["interview"],
    why: "Some credentials help; many do not. Spending time and money wisely matters.",
    problem: "Marketing makes every certificate sound essential. Employers mostly hire on skills and evidence.",
    eli12: "A certificate is a receipt that you did a course. Employers care more about what you can build.",
    tech: "Evaluate by employer mentions, depth, hands-on labs, tool access, cost, time, and whether it produces project evidence. See the Certifications page for evidence-based classifications.",
    inChip: "Hiring managers weigh projects and interviews more heavily.",
    breaks: "Spending months on certificates instead of projects.",
    tested: "Certification decision recorded with rationale.",
    prereqs: ["portfolio-strategy"],
    objectives: ["Classify options with the rubric", "Pick at most one or two with clear value"],
    terms: [["Credential", "Proof of completing a course or exam"]],
    mistakes: ["Assuming expensive means valuable"],
    practice: ["Review the Certifications page and record decisions"],
    interview: [{ q: "Do you have certifications?", a: "Mention relevant ones briefly and redirect to project evidence that shows the same skills in use.", level: 1 }],
    resources: ["rvfa", "nptel-verilog"],
  },
  {
    id: "resume", title: "The VLSI resume for a non-traditional background", phase: "p12", module: "m12b",
    priority: "must", depth: "working", difficulty: 2, days: 2, hours: 4, kind: "career", skills: ["interview"],
    why: "Your resume must make the EE-plus-software path read as a strength in six seconds.",
    problem: "Generic resumes list tools; strong ones show results and engineering decisions.",
    eli12: "A resume is a movie trailer: the best scenes, quickly, with proof.",
    tech: "Structure: summary (positioning), skills grouped (HDL, verification, flow tools, scripting), projects with metrics (frequency, coverage, area, bugs found), software experience framed for hardware (automation, testing), education, certifications if relevant, links. One page for entry level. See weak vs strong bullets on the Portfolio page.",
    inChip: "ATS filters and recruiter screens.",
    breaks: "Buzzword lists without evidence; overclaiming tools.",
    tested: "By peer review and mock screening calls: if a recruiter cannot find your evidence in ten seconds, the resume has failed.",
    prereqs: ["portfolio-strategy"],
    objectives: ["Write metric-driven project bullets", "Frame software experience", "Tailor per role"],
    terms: [["ATS", "Applicant tracking system"]],
    mistakes: ["Listing every tool touched once"],
    practice: ["Write three bullets per flagship project using the strong-bullet formula"],
    interview: [{ q: "Tell me about your background.", a: "A 60-second story: EE degree, software experience, why hardware, what you built and measured, what you want to do next.", level: 1 }],
    resources: [],
  },
  {
    id: "linkedin-networking", title: "LinkedIn, networking and referrals", phase: "p12", module: "m12b",
    priority: "must", depth: "working", difficulty: 2, days: 2, hours: 4, kind: "career", skills: ["interview"],
    why: "Many semiconductor hires come through referrals; thoughtful outreach works, spam does not.",
    problem: "Cold applications without a degree signal are easy to skip; a referral or a conversation gets your evidence seen.",
    eli12: "Networking is making friends with people who do the job you want, by being genuinely curious and sharing what you build.",
    tech: "Profile: headline with target role and evidence, featured projects, about section. Find engineers, alumni and recruiters; ask specific technical questions; request referrals only after context; follow up politely; share progress. Templates on the Build in Public page.",
    inChip: "Hiring teams notice consistent, credible work.",
    breaks: "Mass generic messages; asking for jobs in the first message.",
    tested: "Response rates and conversations logged.",
    prereqs: ["resume"],
    objectives: ["Optimize your profile", "Send five thoughtful messages", "Track conversations"],
    terms: [["Referral", "An employee recommending you internally"]],
    mistakes: ["Asking strangers for referrals immediately"],
    practice: ["Use the templates to contact three engineers with specific questions"],
    interview: [{ q: "How did you hear about this role?", a: "Be honest and specific; mention conversations with team members if any and what attracted you.", level: 1 }],
    resources: [],
  },
  {
    id: "build-in-public", title: "Building in public without hype", phase: "p12", module: "m12b",
    priority: "should", depth: "working", difficulty: 1, days: 1, hours: 2, kind: "career", skills: ["interview"],
    why: "Technical posts create visibility and show communication skill.",
    problem: "Hype posts damage credibility; silent work is invisible.",
    eli12: "Share what you learned and built, like a science-fair poster, not an advertisement.",
    tech: "Post types: learning, build, debugging, benchmark, research, launch. Show evidence (waveforms, tables), claim precisely, credit sources. See templates on the Build in Public page.",
    inChip: "Engineers and recruiters read technical posts.",
    breaks: "Exaggeration and vague claims.",
    tested: "Engagement from engineers, not just likes.",
    prereqs: ["github-showcase"],
    objectives: ["Write one debugging post", "Use evidence in every post"],
    terms: [["Evidence", "Artifacts proving a claim"]],
    mistakes: ["Claiming 'built a chip' for a simulation"],
    practice: ["Draft a debugging post from your bug log"],
    interview: [{ q: "I saw your post about the CDC bug. Tell me more.", a: "Explain the bug, how you found it, the fix, and what check now prevents it.", level: 2 }],
    resources: [],
  },
  {
    id: "interview-system", title: "How VLSI interviews work and how to practice", phase: "p12", module: "m12c",
    priority: "must", depth: "working", difficulty: 3, days: 2, hours: 5, kind: "career", skills: ["interview"],
    why: "Interviews test fundamentals, coding, debugging and reasoning under time pressure. Practice turns knowledge into performance.",
    problem: "Knowing material is different from explaining it live and coding on a whiteboard.",
    eli12: "Like a music exam: knowing the song is not enough; you must play it in front of the examiner.",
    tech: "Typical rounds: online test (digital, aptitude, sometimes C), technical rounds (digital logic, Verilog/SV coding, FSMs, timing, CDC, protocols, verification concepts, project deep-dive), sometimes a manager/HR round. Practice: mock mode here, whiteboard FSMs, explain projects in 2 and 10 minutes, review weak categories weekly.",
    inChip: "Campus and lateral hiring processes.",
    breaks: "Memorized answers collapse under follow-ups.",
    tested: "Mock interview accuracy by category.",
    prereqs: ["portfolio-strategy"],
    objectives: ["Run weekly mock interviews", "Prepare project deep-dives", "Track weak areas"],
    terms: [["Deep-dive", "Detailed discussion of your project"]],
    mistakes: ["Only reading answers without answering aloud"],
    practice: ["Do a 20-question mock session and record weak categories"],
    interview: [{ q: "Explain your flagship project in two minutes.", a: "Problem, architecture, your role, verification approach, key results with numbers, one hard bug, one tradeoff, what you would improve.", level: 2 }],
    resources: ["indiabix", "gfg-puzzles", ],
  },
  {
    id: "job-search", title: "Job search strategy without an M.Tech", phase: "p12", module: "m12c",
    priority: "must", depth: "working", difficulty: 2, days: 2, hours: 4, kind: "career", skills: ["interview"],
    why: "A deliberate plan beats mass applications, especially with a non-traditional background.",
    problem: "Some roles and companies prefer M.Tech or specific curricula; others hire on evidence. You need to target well.",
    eli12: "Instead of knocking on every door, you find the doors most likely to open and show them exactly what you can do.",
    tech: "Target roles where evidence matters (DV, FPGA, validation, EDA software, RTL at startups and services companies), use referrals, campus/off-campus drives, internships, government-backed programs (C-DAC diplomas, C2S-affiliated institutions), and services companies as a path. Track applications, tailor resumes, prepare for online tests. Be honest about gaps.",
    inChip: "Indian and global semiconductor hiring.",
    breaks: "Applying only to roles that explicitly require an M.Tech; giving up after few responses.",
    tested: "By tracking applications and outcomes: response rate, interview rate, and where in the process you lose momentum.",
    prereqs: ["resume", "linkedin-networking"],
    objectives: ["Build a target list", "Track applications", "Choose one structured program if needed"],
    terms: [["Services company", "Firm providing design/verification services to chip companies"]],
    mistakes: ["No tracking or follow-up"],
    practice: ["Create a target list of 20 roles with requirements mapped to your evidence (Job Readiness page)"],
    interview: [{ q: "Where do you see yourself in three years?", a: "Growing depth in your chosen area, owning blocks or environments, and specific learning goals, tied to the company's work.", level: 1 }],
    resources: ["cdac-pg", "c2s-pib"],
  },
  {
    id: "growth-plan", title: "Knowing what you don't know: your senior growth plan", phase: "p12", module: "m12c",
    priority: "should", depth: "basic", difficulty: 2, days: 1, hours: 2, kind: "career", skills: ["interview"],
    why: "Seniority comes from professional experience; a clear plan shows maturity and guides your first years.",
    problem: "Self-study can reach deep understanding but not the experience of production tapeouts, large teams and real schedules.",
    eli12: "You have learned to swim well in a pool. The ocean has waves you will learn from only by swimming there.",
    tech: "List skills that need professional experience: production tapeouts, commercial tool flows at scale, team process, silicon debug, customer interaction. Plan the first 1-2 years: mentorship, owning small blocks, learning internal flows, continuing projects.",
    inChip: "Career progression from junior to senior.",
    breaks: "Overclaiming seniority in interviews.",
    tested: "Honest self-assessment in the Skills page.",
    prereqs: ["job-search"],
    objectives: ["Write an honest 'known gaps' list", "Write a two-year learning plan"],
    terms: [["Tapeout experience", "Participation in a production chip release"]],
    mistakes: ["Claiming senior-level experience from self-study"],
    practice: ["Write your two-year growth plan and store it in notes"],
    interview: [{ q: "What are your weaknesses technically?", a: "Name real gaps (for example no production tapeout or commercial PD tools), and show how you are closing them with evidence.", level: 1 }],
    resources: [],
  },
];
