import type { Topic } from "../schema.ts";

export const P2: Topic[] = [
  {
    id: "number-systems", title: "Binary, hex and two's complement", phase: "p2", module: "m2a",
    priority: "must", depth: "working", difficulty: 1, days: 2, hours: 3, kind: "theory", skills: ["digital"],
    why: "Every bus, register and arithmetic unit is bits. Width and sign errors are among the most common RTL bugs.",
    problem: "Hardware only has two stable voltage levels, so numbers must be binary. Sign-magnitude representation needs special adder logic and has two zeros; two's complement lets one adder handle both signed and unsigned arithmetic.",
    eli12: "Binary is counting with only two fingers per position. Two's complement is a trick for negative numbers: like a car odometer rolling backwards from 000 to 999, the biggest numbers wrap around to mean 'minus a little'.",
    tech: "An N-bit unsigned number spans 0 to 2^N - 1. Two's complement signed spans -2^(N-1) to 2^(N-1) - 1; negate by inverting bits and adding 1. Sign extension copies the MSB when widening. Overflow for signed addition happens when two operands of the same sign produce a result of the other sign. Hex groups four bits per digit.",
    inChip: "Datapaths, address calculation, DSP, and every counter. Verification checks corner values (0, max, min negative).",
    breaks: "Mixing signed and unsigned in Verilog silently zero-extends; truncation drops carry bits; overflow goes unnoticed.",
    tested: "Directed tests on boundary values plus random tests with a reference model.",
    prereqs: [],
    objectives: ["Convert between binary, hex and decimal", "Negate and sign-extend two's complement numbers", "Detect signed overflow"],
    terms: [["MSB", "Most significant bit"], ["Sign extension", "Copying the sign bit when widening a signed value"], ["Overflow", "Result does not fit in the available bits"]],
    visuals: [{ title: "4-bit two's complement wheel", art: "0000=0  0001=1 ... 0111=7\n1000=-8 1001=-7 ... 1111=-1\n\n  7 + 1 = 0111 + 0001 = 1000 = -8  (signed overflow)" }],
    equations: ["-x = ~x + 1", "Range (signed N-bit): -2^(N-1) .. 2^(N-1)-1"],
    mistakes: ["Forgetting that 4'b1111 is 15 unsigned but -1 signed", "Adding two N-bit numbers into an N-bit result and losing the carry"],
    practice: ["Write -13 in 8-bit two's complement", "Add 0x7F and 0x01 in 8 bits and state whether signed overflow occurred", "Solve the HDLBits vector problems"],
    interview: [{ q: "How do you detect overflow when adding two signed numbers?", a: "Overflow occurs if both operands have the same sign and the result's sign differs. Equivalently, the carry into the MSB differs from the carry out of the MSB.", level: 1 }],
    resources: ["hdlbits", "harris-harris", "eth-ddca"],
  },
  {
    id: "boolean-algebra", title: "Boolean algebra, logic gates and De Morgan", phase: "p2", module: "m2a",
    priority: "must", depth: "working", difficulty: 1, days: 2, hours: 3, kind: "theory", skills: ["digital"],
    why: "Boolean algebra is the language synthesis tools think in. Simplifying and transforming logic is daily RTL and debug work.",
    problem: "Circuits built directly from truth tables are large. Boolean identities let designers and tools rewrite logic into cheaper or faster equivalent forms.",
    eli12: "Boolean algebra is arithmetic for yes and no. AND means both must be yes, OR means at least one is yes, NOT flips the answer. De Morgan's trick says 'not (A and B)' is the same as 'not A or not B', like saying 'it is not true that both lights are on' equals 'at least one light is off'.",
    tech: "Operators AND, OR, NOT, XOR; identities (idempotent, absorption, distributive); De Morgan: !(A&B) = !A | !B and !(A|B) = !A & !B. Sum-of-products and product-of-sums canonical forms. NAND and NOR are universal: any function can be built from either. XOR is key for adders, parity and comparisons.",
    inChip: "Synthesis tools represent logic as graphs (such as AND-inverter graphs) and apply these rewrites at massive scale. Designers use them to read netlists and reason about bugs.",
    breaks: "Wrong simplification introduces functional bugs; misreading an inverted signal (active-low) is a classic error.",
    tested: "Equivalence checking proves two logic descriptions match; simulation with exhaustive vectors for small blocks.",
    prereqs: ["number-systems"],
    objectives: ["Apply De Morgan's laws", "Convert a truth table to sum-of-products", "Build any gate from NAND only"],
    terms: [["SOP", "Sum of products: OR of AND terms"], ["Universal gate", "A gate type that can build any logic function"], ["Active-low", "A signal that means 'true' when it is 0"]],
    mistakes: ["Forgetting operator precedence", "Confusing XOR with OR in parity logic"],
    practice: ["Implement XOR using only NAND gates", "Prove !(A|B|C) = !A & !B & !C"],
    interview: [{ q: "Implement a 2-input XOR using only NAND gates.", a: "Four NANDs: n1 = NAND(A,B); n2 = NAND(A,n1); n3 = NAND(B,n1); Y = NAND(n2,n3).", level: 2 }],
    resources: ["hdlbits", "harris-harris", "digital-sim"],
  },
  {
    id: "logic-minimization", title: "Logic minimization: K-maps to synthesis", phase: "p2", module: "m2a",
    priority: "should", depth: "basic", difficulty: 2, days: 1, hours: 2, kind: "theory", skills: ["digital"],
    why: "You rarely minimize by hand at work, but K-maps build intuition for don't-cares, glitches and what synthesis optimizes.",
    problem: "Truth tables grow as 2^N. K-maps make small minimization visual; for real designs, algorithms (Quine-McCluskey, Espresso, and modern AIG rewriting in tools like ABC) take over.",
    eli12: "A K-map is a grid where neighbouring boxes differ by one switch. Circling big groups of 1s finds the shortest rule that still gives the right answers.",
    tech: "K-maps use Gray-code ordering so adjacent cells differ in one variable. Group 1s in powers of two to form prime implicants; don't-cares (X) can join any group. Minimal SOP reduces gates and inputs. Static hazards (glitches) occur when adjacent groups are not covered by a common term; adding a consensus term removes them in hand-built async logic.",
    inChip: "Synthesis performs this automatically; designers pass don't-care information through careful RTL (for example default assignments and unique case).",
    breaks: "Relying on glitch-free combinational outputs for clocks or async resets leads to real failures.",
    tested: "Equivalence checking after optimization; glitch analysis matters mainly for async paths.",
    prereqs: ["boolean-algebra"],
    objectives: ["Minimize 3- and 4-variable functions with K-maps", "Use don't-cares", "Explain why glitches happen"],
    terms: [["Prime implicant", "A largest possible group in a K-map"], ["Don't-care", "An input combination whose output does not matter"], ["Static hazard", "A momentary glitch when output should stay constant"]],
    mistakes: ["Using combinational outputs directly as clocks", "Forgetting wrap-around adjacency in K-maps"],
    practice: ["Minimize F(A,B,C,D) = sum of minterms 0,2,5,7,8,10,13,15", "Complete the HDLBits K-map problems"],
    interview: [{ q: "What is a glitch and why is it dangerous?", a: "A short unwanted pulse from unequal path delays. It is harmless on synchronous data sampled at clock edges, but dangerous on clocks, async resets or outputs to other domains.", level: 2 }],
    resources: ["hdlbits", "harris-harris"],
  },
  {
    id: "mux-decoder", title: "Multiplexers, decoders and encoders", phase: "p2", module: "m2b",
    priority: "must", depth: "working", difficulty: 1, days: 2, hours: 3, kind: "coding", skills: ["digital", "rtl"],
    why: "Muxes are everywhere in datapaths (forwarding, operand select, bus arbitration). Case statements in RTL become muxes and decoders.",
    problem: "Hardware needs to route one of many sources to a destination and select one of many destinations. Muxes and decoders are the standard, synthesizable answers.",
    eli12: "A multiplexer is a TV remote: many channels come in, the remote's number picks which one you see. A decoder is a mailroom: it reads an address and lights exactly one mailbox.",
    tech: "An N:1 mux needs log2(N) select bits. Large muxes become trees; wide muxes cost area and add delay. A decoder converts n bits to 2^n one-hot outputs. A priority encoder outputs the index of the highest-priority active input and is central to arbiters and interrupt controllers. One-hot muxes (AND-OR) are often faster than binary-select muxes.",
    inChip: "Pipeline forwarding muxes, register file read ports, bus interconnects, address decoders for memory-mapped registers.",
    breaks: "Incomplete case statements infer latches; priority where none is needed adds delay; missing default arms cause X propagation in simulation.",
    tested: "Exhaustive tests of select values for small muxes; formal or assertions for one-hot properties.",
    prereqs: ["boolean-algebra"],
    objectives: ["Write a parameterized mux in Verilog", "Build a decoder and a priority encoder", "Explain one-hot vs binary select"],
    terms: [["One-hot", "Exactly one bit is 1"], ["Priority encoder", "Outputs the index of the highest-priority active input"]],
    code: { lang: "verilog", src: "module mux4 #(parameter W=8) (\n  input  [W-1:0] a, b, c, d,\n  input  [1:0]   sel,\n  output reg [W-1:0] y);\n  always @(*) begin\n    case (sel)\n      2'd0: y = a;\n      2'd1: y = b;\n      2'd2: y = c;\n      default: y = d;\n    endcase\n  end\nendmodule" },
    mistakes: ["No default branch: a latch appears", "Using if-else chains where a parallel case expresses no priority"],
    practice: ["Write an 8-to-3 priority encoder and test all 256 inputs", "HDLBits: Mux256to1 and Mux256to1v"],
    interview: [{ q: "How does a case statement differ from an if-else chain in synthesized hardware?", a: "An if-else chain implies priority (a chain of muxes), while a case with mutually exclusive items can become a parallel mux. Synthesis can optimize both, but intent and timing differ.", level: 2 }],
    resources: ["hdlbits", "chipverify"],
  },
  {
    id: "adders", title: "Adders: from half adder to carry-lookahead", phase: "p2", module: "m2b",
    priority: "must", depth: "working", difficulty: 2, days: 2, hours: 4, kind: "coding", skills: ["digital", "rtl"],
    why: "Adders sit on critical paths in ALUs, address generation and accumulators. They are the classic PPA tradeoff example.",
    problem: "A ripple-carry adder is small but its carry must travel through every bit, so delay grows linearly with width. Faster schemes (carry-lookahead, prefix adders) compute carries in parallel at the cost of area and wiring.",
    eli12: "Adding by hand, you carry the 1 to the next column. A ripple adder does this one column at a time, so a 64-column sum waits for 64 carries. A lookahead adder has helpers who peek ahead and figure out the carries all at once.",
    tech: "Half adder: sum = a^b, carry = a&b. Full adder adds carry-in. Ripple carry: O(N) delay. Carry-lookahead uses generate (g = a&b) and propagate (p = a^b): c(i+1) = g + p c(i), expanded in groups. Prefix adders (Kogge-Stone, Brent-Kung, Sklansky) compute carries in O(log N) levels with different area and fanout tradeoffs. Synthesis chooses adder architectures based on timing constraints.",
    inChip: "ALUs, program counters, address generators, MAC units in AI accelerators.",
    breaks: "Too-slow adders cause setup violations; oversized fast adders waste area and power.",
    tested: "Random plus boundary tests against a reference model; equivalence checks between architectures.",
    prereqs: ["number-systems", "boolean-algebra"],
    objectives: ["Build half and full adders", "Explain ripple-carry delay", "Explain generate and propagate"],
    terms: [["Generate", "A bit position creates a carry on its own (a&b)"], ["Propagate", "A bit position passes an incoming carry (a^b)"], ["Prefix adder", "Adder computing carries with a logarithmic-depth tree"]],
    equations: ["s = a ^ b ^ cin", "cout = a&b | cin&(a^b)", "c(i+1) = g(i) | p(i)&c(i)"],
    visuals: [{ title: "Ripple carry: carries travel bit to bit", art: "a0b0   a1b1   a2b2   a3b3\n |      |      |      |\n[FA]-c->[FA]-c->[FA]-c->[FA]-> cout\n |      |      |      |\n s0     s1     s2     s3" }],
    mistakes: ["Forgetting the carry-out bit width in RTL", "Hand-building fast adders when synthesis would choose well from 'a + b'"],
    practice: ["Write a 4-bit ripple adder from full adders and test it exhaustively", "Synthesize 'a + b' at 32 bits in Yosys and compare cell counts to your ripple version"],
    interview: [{ q: "Why is a carry-lookahead adder faster than a ripple-carry adder?", a: "It computes carries from generate and propagate signals in parallel (group or prefix logic) instead of waiting for each carry to ripple through every bit, reducing delay from O(N) to about O(log N) at the cost of area.", level: 2 }],
    resources: ["hdlbits", "harris-harris", "weste-harris"],
    projects: ["m-alu", "fp-ppa-arith"],
  },
  {
    id: "alu", title: "Designing an ALU (with shifters and comparators)", phase: "p2", module: "m2b",
    priority: "must", depth: "working", difficulty: 2, days: 2, hours: 4, kind: "coding", skills: ["digital", "rtl"],
    why: "The ALU combines adders, logic, shifters and comparators under a control code. It is the first real datapath block and the core of the CPU you will build.",
    problem: "A processor needs many operations but cannot afford separate hardware for each. An ALU shares resources (one adder handles add, subtract and compare) selected by an opcode.",
    eli12: "An ALU is a calculator chip with a menu. The opcode picks the menu item: add, subtract, AND, OR, shift, or compare. Inside, many items share the same machinery.",
    tech: "Subtraction reuses the adder: a - b = a + ~b + 1. Comparisons use the subtraction result and flags (zero, negative, carry, overflow); signed vs unsigned compare differ. Barrel shifters shift by any amount in log2(N) mux stages. Result selection is a mux controlled by the opcode.",
    inChip: "Every CPU core; also address generation and DSP datapaths.",
    breaks: "Signed/unsigned compare mix-ups, wrong overflow flags, and shift amounts wider than the data are classic bugs.",
    tested: "Constrained-random operands with a reference model in Python or SystemVerilog; directed tests for corner values.",
    prereqs: ["adders", "mux-decoder"],
    objectives: ["Implement add, sub, logic ops, shifts and compares", "Generate flags correctly", "Build a barrel shifter"],
    terms: [["Opcode", "Code selecting the operation"], ["Flags", "Status bits such as zero, carry, negative, overflow"], ["Barrel shifter", "Shifts by any amount in one cycle using mux stages"]],
    mistakes: ["Using the unsigned carry for signed comparison", "Forgetting arithmetic right shift must replicate the sign bit"],
    practice: ["Build the RV32I ALU subset (ADD, SUB, AND, OR, XOR, SLL, SRL, SRA, SLT, SLTU)", "Test SLT vs SLTU with values like 0xFFFFFFFF and 0x1"],
    interview: [{ q: "How would you implement both SLT and SLTU with one subtractor?", a: "Compute a - b. SLTU is the borrow (inverted carry-out). SLT uses the sign of the result corrected for overflow: less = negative XOR overflow.", level: 3 }],
    resources: ["hdlbits", "harris-harris", "riscv-isa-manual"],
    projects: ["m-alu"],
  },
  {
    id: "latches-flipflops", title: "Latches and flip-flops: how hardware remembers", phase: "p2", module: "m2c",
    priority: "must", depth: "working", difficulty: 2, days: 2, hours: 4, kind: "theory", skills: ["digital", "timing"],
    why: "Every register, pipeline stage and state machine is built from flip-flops. Their timing rules define how fast a chip can run.",
    problem: "Combinational logic forgets instantly. To hold state, circuits need feedback. Latches are simple but transparent while enabled, which makes timing hard; edge-triggered flip-flops capture only at a clock edge, giving clean, analyzable timing.",
    eli12: "A latch is a door that stays open while you hold the button, so anything walking by gets in. A flip-flop is a camera: it takes one snapshot at the exact moment of the click and ignores everything else until the next click.",
    analogyLimit: "A real flip-flop needs the input to be steady slightly before and after the click; that is setup and hold time.",
    tech: "An SR latch uses cross-coupled gates. A D latch is transparent when enable is high. A D flip-flop is two latches in master-slave arrangement, capturing D at the clock edge. Key parameters: clock-to-Q delay, setup time, hold time. Flip-flops may include reset, enable and scan inputs.",
    inChip: "Millions of flops per chip; register banks, pipeline registers, state, counters. Scan flops enable manufacturing test.",
    breaks: "Unintended latches from incomplete RTL cause timing and testability problems; flop timing violations cause wrong captured values.",
    tested: "STA checks every flop's setup and hold; lint flags inferred latches.",
    prereqs: ["boolean-algebra"],
    objectives: ["Explain latch transparency vs edge-triggering", "Describe master-slave flip-flops", "Define clock-to-Q, setup and hold"],
    terms: [["Transparent", "Output follows input while enabled"], ["Clock-to-Q", "Delay from clock edge to output change"], ["Master-slave", "Two latches in series with opposite enables forming a flip-flop"]],
    visuals: [{ title: "Latch vs flip-flop", art: "clk   _|‾‾‾|___|‾‾‾|___\nD     __|‾|___|‾‾‾‾‾‾‾‾\nQlat  ___|‾|___|‾‾‾‾‾‾‾   (follows D while clk high)\nQff   _______|‾‾‾‾‾‾‾‾‾   (samples D only at rising edges)" }],
    mistakes: ["Assuming latches are always bad (some high-performance designs use them deliberately)", "Ignoring clock-to-Q in timing calculations"],
    practice: ["Build a D latch and a D flip-flop in the Digital simulator and compare outputs", "HDLBits: Dff, Dff8, Dlatch"],
    interview: [{ q: "What is the difference between a latch and a flip-flop?", a: "A latch is level-sensitive and transparent while enabled; a flip-flop is edge-triggered and samples only at the clock edge. Flip-flops make timing analysis simpler; latches allow time borrowing but are harder to analyze and test.", level: 1 }],
    resources: ["hdlbits", "harris-harris", "digital-sim"],
  },
  {
    id: "clocking", title: "Clocks and synchronous design", phase: "p2", module: "m2c",
    priority: "must", depth: "working", difficulty: 2, days: 1, hours: 2, kind: "theory", skills: ["digital", "timing"],
    why: "Synchronous design is the discipline that makes billion-transistor chips analyzable. Nearly every rule in RTL coding follows from it.",
    problem: "Asynchronous circuits race and glitch in ways that are hard to reason about. A global clock makes every register update at the same instant, so designers only need to check that logic settles between edges.",
    eli12: "A clock is an orchestra conductor. Nobody plays a new note until the baton drops. Between beats, everyone gets ready; on the beat, everyone moves together.",
    tech: "All state changes on clock edges; combinational logic between registers must settle within one period. Clock period T and frequency f = 1/T. The clock is distributed by a clock tree; its arrival differences (skew) and edge uncertainty (jitter) eat into timing margin. Rules: do not generate clocks with random logic, use clock enables instead of gating in RTL (let tools insert integrated clock gating cells), and treat each clock as a separate domain.",
    inChip: "Clock architects plan domains and frequencies; PD builds clock trees; STA checks every path relative to its clock.",
    breaks: "Logic-generated clocks and glitchy gating cause unpredictable failures and untestable designs.",
    tested: "STA with clock definitions; CDC tools check crossings; lint flags clock misuse.",
    prereqs: ["latches-flipflops"],
    objectives: ["State the synchronous design discipline", "Explain skew and jitter", "Use clock enables instead of gated clocks in RTL"],
    terms: [["Clock domain", "Logic driven by one clock"], ["Skew", "Difference in clock arrival time between flops"], ["Jitter", "Cycle-to-cycle variation of clock edges"]],
    mistakes: ["Dividing a clock with a counter and using it as a clock without constraints", "Gating clocks with AND gates in RTL"],
    practice: ["Rewrite a design that uses a divided clock to use a clock enable instead", "Explain why a clock enable is safer than a gated clock"],
    interview: [{ q: "Why use a clock enable instead of gating the clock in RTL?", a: "A gated clock built from random logic can glitch and creates new, hard-to-constrain clock domains. A clock enable keeps a single clean clock; tools can later insert proper integrated clock gating cells safely.", level: 2 }],
    resources: ["harris-harris", "sunburst"],
  },
  {
    id: "registers-counters", title: "Registers, shift registers and counters", phase: "p2", module: "m2c",
    priority: "must", depth: "working", difficulty: 1, days: 2, hours: 3, kind: "coding", skills: ["digital", "rtl"],
    why: "Counters and shift registers are the building blocks of timers, protocols (UART, SPI), LFSRs and pipelines.",
    problem: "Designs need to count events, delay data, serialize and deserialize. These standard structures solve those needs with predictable timing.",
    eli12: "A shift register is a line of people passing notes: every clock tick, each passes their note to the next person. A counter is a person clicking a tally counter on every tick.",
    tech: "Registers with enable and reset; shift registers for serial-parallel conversion; binary counters, up/down counters, modulo-N counters, Gray counters (one bit changes per step, useful in CDC), ring and Johnson counters, and LFSRs for pseudo-random sequences and CRC.",
    inChip: "Timers, baud generators, FIFO pointers, PRBS generators in SerDes test, CRC checkers.",
    breaks: "Off-by-one terminal counts, missing enables, and reset values that do not match the spec.",
    tested: "Directed tests for wrap-around and terminal counts; assertions on counter range.",
    prereqs: ["latches-flipflops", "clocking"],
    objectives: ["Write counters with enable, load and wrap", "Build a shift register for serial-to-parallel", "Implement an LFSR"],
    terms: [["LFSR", "Linear feedback shift register producing pseudo-random sequences"], ["Modulo-N counter", "Counter that wraps after N states"], ["Gray code", "Sequence where consecutive values differ by one bit"]],
    mistakes: ["Terminal count off by one", "Using a counter output as a clock"],
    practice: ["HDLBits: Count10, Countslow, Shift4, Lfsr5", "Write a Gray counter and verify only one bit changes per step"],
    interview: [{ q: "Design a modulo-10 counter with enable and synchronous reset.", a: "4-bit register; on reset load 0; on enable, if count == 9 load 0 else increment. Mention the terminal-count output and testing wrap-around.", level: 1 }],
    resources: ["hdlbits", "chipverify"],
    projects: ["m-counter", "m-lfsr"],
  },
  {
    id: "setup-hold", title: "Setup and hold time", phase: "p2", module: "m2c",
    priority: "must", depth: "advanced", difficulty: 3, days: 2, hours: 5, kind: "theory", skills: ["timing", "digital"],
    why: "Setup and hold are the two rules every flip-flop in every chip must obey. STA, timing closure and many interview questions are built on them.",
    problem: "A flip-flop needs a moment to decide whether its input is 0 or 1. If the input changes too close to the clock edge, the captured value is wrong or undefined. Setup and hold windows turn that physical limit into rules tools can check.",
    eli12: "Imagine a camera taking a picture of a moving object. The object must be still for a moment before and after the shutter clicks, or the photo is blurry. A flip-flop is the camera: data must be stable a little before the clock edge (setup time) and a little after it (hold time).",
    analogyLimit: "A blurry photo is still a photo. A flip-flop that is violated can go metastable, hovering between 0 and 1 for an unpredictable time.",
    tech: "Setup: data must arrive at least Tsetup before the capturing edge. Hold: data must stay stable for Thold after the edge. For a path from launch flop to capture flop: setup requires Tclk-q + Tcomb,max + Tsetup <= Tclk + (capture skew). Hold requires Tclk-q + Tcomb,min >= Thold + (capture skew). Slack is required time minus arrival time; negative slack is a violation. Setup violations can be fixed by lowering frequency; hold violations cannot, and must be fixed by adding delay.",
    inChip: "STA checks every register-to-register, input-to-register and register-to-output path for setup and hold at multiple corners. RTL designers pipeline to fix setup; PD engineers insert buffers to fix hold.",
    breaks: "Setup violations: wrong data at high frequency. Hold violations: wrong data at any frequency, a silicon-killer because slowing the clock does not help.",
    tested: "Static timing analysis at signoff across corners; gate-level simulation with SDF back-annotation as a secondary check.",
    prereqs: ["latches-flipflops", "clocking", "rc-delay"],
    objectives: ["Write setup and hold inequalities for a path", "Compute slack", "Explain why hold violations cannot be fixed by slowing the clock"],
    terms: [["Setup time", "Minimum stable time before the clock edge"], ["Hold time", "Minimum stable time after the clock edge"], ["Slack", "Required time minus arrival time; negative means violation"], ["Critical path", "The path with the worst setup slack"]],
    visuals: [{ title: "The setup/hold window", art: "clk   ____________|‾‾‾‾‾‾‾‾\n                  ^ capture edge\nD     ====X=======.=======X====\n            |<-Ts->|<-Th->|\n            data must be stable here" }, { title: "A timing path", art: "[FF1] --clk->q--> [ comb logic ] --> [FF2]\n  ^                                    ^\n clk (launch)                    clk (capture)" }],
    equations: ["Setup: Tcq + Tcomb_max + Tsu <= Tclk + Tskew", "Hold:  Tcq + Tcomb_min >= Th + Tskew", "Setup slack = (Tclk + Tskew - Tsu) - (Tcq + Tcomb_max)"],
    example: "Tclk = 2 ns, Tcq = 0.15 ns, Tcomb_max = 1.6 ns, Tsu = 0.1 ns, skew = 0: arrival 1.75 ns, required 1.9 ns, slack +0.15 ns (met). If logic grows to 1.8 ns, slack is -0.05 ns (violated): pipeline, restructure, or lower the frequency to at least 2.05 ns period.",
    mistakes: ["Thinking positive skew always helps (it helps setup but hurts hold)", "Trying to fix hold by lowering frequency"],
    senior: ["When is it acceptable to borrow time or use multicycle paths?", "How do you trade pipeline depth against latency and area to meet frequency?", "Which hold fixes are risky late in the flow and why?"],
    ladder: { beginner: "Data must be steady around the clock edge.", junior: "Write the setup and hold inequalities and compute slack for a path.", mid: "Read STA reports, find the critical path, and propose fixes (pipelining, restructuring, sizing).", senior: "Balance frequency, latency, area and power across a block; decide constraints and exceptions; predict closure risk at architecture time.", research: "Explore statistical timing, ML-based slack prediction, or adaptive clocking." },
    practice: ["Compute setup and hold slack for three paths given in a table", "Explain in writing why a 20 MHz clock cannot fix a hold violation", "Find the maximum frequency for a path with Tcq=0.2, Tcomb=3.1, Tsu=0.15 (ns)"],
    interview: [{ q: "What happens if hold time is violated, and how do you fix it?", a: "The new data races through and overwrites the value being captured, so the flop may capture wrong data or go metastable. Because hold does not depend on clock period, fix it by adding delay on the data path (buffers, sizing), reducing clock skew, or adjusting useful skew.", trap: "Saying 'reduce the clock frequency'.", level: 2 }, { q: "Your design fails setup at 800 MHz. How do you investigate?", a: "Read the worst paths in the STA report: startpoint, endpoint, clock, each cell delay. Classify the problem (long logic, big fanout, wire delay, skew). Fix by restructuring logic, retiming or pipelining, reducing fanout, upsizing, or revisiting constraints if the path is false or multicycle.", level: 3 }],
    resources: ["bhasker-sta", "harris-harris", "mutlu-yt"],
    projects: ["fp-ppa-arith"],
  },
  {
    id: "metastability", title: "Metastability and synchronizers", phase: "p2", module: "m2c",
    priority: "must", depth: "working", difficulty: 3, days: 2, hours: 4, kind: "theory", skills: ["timing", "rtl"],
    why: "Every signal that crosses between clock domains or comes from outside the chip risks metastability. Synchronizers are mandatory knowledge for RTL and DV.",
    problem: "When an asynchronous input changes inside the setup/hold window, a flop can hang between 0 and 1. You cannot prevent this for truly asynchronous signals, but you can make the chance of failure astronomically small with synchronizer flops.",
    eli12: "A ball balanced on the very top of a hill will eventually roll left or right, but you cannot know when. A two-flop synchronizer gives the ball a whole clock cycle to roll off before anyone looks at it.",
    tech: "Metastable flops resolve with time constant tau; probability of still being unresolved after time t decays as e^(-t/tau). MTBF = e^(t_r/tau) / (T0 x f_clk x f_data). A two-flop synchronizer gives almost one clock period of resolution time. Only single-bit, level-stable signals should pass through a simple synchronizer; multi-bit values need handshakes, Gray codes or async FIFOs.",
    inChip: "Reset synchronizers, interrupt inputs, button inputs, and every CDC crossing.",
    breaks: "Missing synchronizers cause rare, intermittent failures that are nearly impossible to reproduce in the lab.",
    tested: "CDC structural analysis tools; metastability injection in simulation; MTBF calculations.",
    prereqs: ["setup-hold"],
    objectives: ["Explain metastability", "Build a two-flop synchronizer", "Explain why multi-bit buses cannot be synchronized bit by bit"],
    terms: [["Metastability", "An unstable intermediate state after a timing violation"], ["MTBF", "Mean time between failures"], ["Synchronizer", "Flops that give a metastable signal time to resolve"]],
    equations: ["MTBF = e^(t_r / tau) / (T0 x f_clk x f_data)"],
    code: { lang: "verilog", src: "module sync2 (input clk, input rst_n, input async_in, output sync_out);\n  reg s1, s2;\n  always @(posedge clk or negedge rst_n)\n    if (!rst_n) {s2, s1} <= 2'b00;\n    else        {s2, s1} <= {s1, async_in};\n  assign sync_out = s2;\nendmodule" },
    mistakes: ["Synchronizing each bit of a counter separately", "Putting combinational logic between synchronizer flops"],
    practice: ["Compute MTBF for tau = 20 ps, T0 = 100 ps, 1 GHz clock, 10 MHz data, t_r = 900 ps", "Explain why a pulse shorter than the destination clock period can be lost"],
    interview: [{ q: "Why can't you synchronize a multi-bit bus with a two-flop synchronizer per bit?", a: "Each bit may resolve on a different cycle, so the destination can see a mix of old and new bits: a value that never existed. Use Gray coding (one bit changes at a time), a handshake with a stable bus, or an async FIFO.", level: 2 }],
    resources: ["sunburst", "harris-harris"],
    papers: ["ginosar-sync"],
  },
  {
    id: "resets", title: "Resets: synchronous, asynchronous and reset synchronizers", phase: "p2", module: "m2c",
    priority: "must", depth: "working", difficulty: 2, days: 1, hours: 2, kind: "theory", skills: ["rtl", "timing"],
    why: "Reset bugs are common, hard to find, and can brick silicon. Every RTL designer must choose and justify a reset strategy.",
    problem: "Chips power up in random states. Reset puts state into known values. Synchronous resets are timing-friendly but need a running clock; asynchronous resets act immediately but their release must be synchronized to avoid metastability.",
    eli12: "Reset is the 'start the game over' button. An asynchronous reset works instantly, even if the game is frozen. A synchronous reset waits for the next tick. The danger is letting go of the button at a bad moment, so we release it carefully in time with the clock.",
    tech: "Synchronous reset: checked in the clocked always block; needs clock running; reset path is timed like data. Asynchronous reset: in the sensitivity list; asserts immediately; deassertion must meet recovery/removal timing. Standard practice: asynchronous assert, synchronous deassert via a reset synchronizer. Not every flop needs reset (datapath registers often do not), which saves area and routing.",
    inChip: "Reset controllers, power-on reset, per-domain reset synchronizers, reset sequencing in SoCs.",
    breaks: "Asynchronous reset released asynchronously: some flops leave reset a cycle later than others, corrupting state machines. Missing resets on control flops cause X-propagation and random start states.",
    tested: "Recovery/removal checks in STA; RDC tools; reset-sequence tests in simulation.",
    prereqs: ["metastability"],
    objectives: ["Compare sync and async resets", "Build an async-assert, sync-deassert reset synchronizer", "Decide which flops need reset"],
    terms: [["Recovery time", "Like setup, for reset deassertion"], ["Removal time", "Like hold, for reset deassertion"], ["Reset synchronizer", "Flops that align reset release to the clock"]],
    mistakes: ["Resetting large datapaths unnecessarily", "Deasserting an async reset without synchronization"],
    practice: ["Write a reset synchronizer and explain each flop", "List which registers in your ALU project actually need reset"],
    interview: [{ q: "Compare synchronous and asynchronous resets.", a: "Sync reset: timed like data, glitch-tolerant, needs a clock, may add logic in the data path. Async reset: immediate, works without a clock, but release must be synchronized (recovery/removal) and the reset net is sensitive to glitches. Common practice: async assert, sync deassert.", level: 2 }],
    resources: ["sunburst", "chipverify"],
  },
  {
    id: "fsm", title: "Finite state machines (Moore and Mealy)", phase: "p2", module: "m2d",
    priority: "must", depth: "working", difficulty: 2, days: 2, hours: 6, kind: "coding", skills: ["digital", "rtl"],
    why: "Control logic is FSMs: protocol controllers, arbiters, handshakes, CPU control units. Interviews almost always include an FSM design.",
    problem: "Complex control behaviour needs a structured way to express 'what happens next given where we are and what we see'. FSMs make control explicit, testable and synthesizable.",
    eli12: "A traffic light is a state machine. It is always in one state (green, yellow, red), and rules say when to move to the next state. The rules only look at the current state and the inputs, like a timer or a pedestrian button.",
    tech: "State register plus next-state logic plus output logic. Moore: outputs depend only on state (glitch-free, one cycle later). Mealy: outputs depend on state and inputs (faster response, may glitch, can create combinational paths through the FSM). Design steps: define states, draw the diagram, write the transition table, choose encoding, code in RTL with separate sequential and combinational blocks, and cover all states and transitions in tests.",
    inChip: "UART/SPI/I2C controllers, bus protocol engines, DMA controllers, power-management sequencers.",
    breaks: "Unreachable or lock-up states, missing transitions, outputs that glitch, or unhandled illegal states after a bit flip.",
    tested: "State and transition coverage, assertions for illegal states, formal proofs of no deadlock.",
    prereqs: ["registers-counters"],
    objectives: ["Design Moore and Mealy machines from a spec", "Draw state diagrams and tables", "Code FSMs in the standard two-block style"],
    terms: [["Moore", "Outputs depend only on the current state"], ["Mealy", "Outputs depend on state and inputs"], ["Next-state logic", "Combinational logic computing the next state"]],
    visuals: [{ title: "Sequence detector for 101 (Moore)", art: "      0          1          0          1\n(S0)---->(S0)  (S0)--1-->(S1)--0-->(S2)--1-->(S3:out=1)\n  ^                        |          |          |\n  |--------0---------------+    0     |   1->S1  |0->S2" , note: "Draw it yourself: every state needs an arc for every input." }],
    mistakes: ["Forgetting default next-state assignment (latches)", "Mixing sequential and combinational logic in one block carelessly"],
    practice: ["Design a 1011 sequence detector (overlapping) as Moore and Mealy and compare timing", "HDLBits: Fsm1 through Fsm3onehot, Lemmings series"],
    interview: [{ q: "Design an FSM that detects the sequence 1011 with overlap. Moore or Mealy?", a: "Draw states tracking the longest matched prefix (S0, S1='1', S2='10', S3='101', S4 detected for Moore). Explain overlap transitions (after 1011, next '0' goes to '10'). Mealy needs one fewer state and asserts output one cycle earlier; Moore output is registered and glitch-free.", level: 2 }],
    resources: ["hdlbits", "harris-harris", "sunburst"],
    projects: ["m-traffic-fsm"],
  },
  {
    id: "fsm-encoding", title: "FSM state encoding and safety", phase: "p2", module: "m2d",
    priority: "should", depth: "basic", difficulty: 2, days: 1, hours: 2, kind: "theory", skills: ["rtl"],
    why: "Encoding choices trade area, speed and power. Safe FSM recovery matters in automotive and space designs.",
    problem: "The same FSM can be encoded in binary (fewest flops), one-hot (fastest decode), or Gray (fewest toggles). Illegal states from glitches or radiation must be handled.",
    eli12: "You can label rooms in a building with numbers (binary) or give each room its own light switch where exactly one is on (one-hot). Numbers save switches; one light per room makes it instantly obvious where you are.",
    tech: "Binary: log2(N) flops, more decode logic. One-hot: N flops, simple next-state logic, common in FPGAs. Gray: minimal toggles for sequential state sequences. Safe FSMs add recovery from illegal states. Output registers remove glitches from Mealy outputs.",
    inChip: "Encoding is often chosen by synthesis; designers override for power, timing, or safety requirements.",
    breaks: "Unsafe FSMs can lock up after a single-event upset; poor encoding causes timing violations in fast control paths.",
    tested: "Formal checks for reachability and illegal-state recovery; fault injection in safety flows.",
    prereqs: ["fsm"],
    objectives: ["Compare binary, one-hot and Gray encodings", "Add illegal-state recovery", "Register FSM outputs"],
    terms: [["One-hot", "One flop per state; exactly one is high"], ["Illegal state", "An encoding that should never occur"]],
    mistakes: ["Assuming synthesis always handles illegal states safely"],
    practice: ["Encode a 5-state FSM in binary and one-hot; count flops and estimate decode logic"],
    interview: [{ q: "When would you choose one-hot encoding?", a: "When speed matters and flops are cheap (for example FPGAs): next-state and output decoding are simple. Binary saves flops; Gray reduces switching for sequential transitions.", level: 2 }],
    resources: ["sunburst", "chipverify"],
  },
  {
    id: "critical-path", title: "Timing paths, critical path and maximum frequency", phase: "p2", module: "m2d",
    priority: "must", depth: "working", difficulty: 3, days: 2, hours: 4, kind: "theory", skills: ["timing"],
    why: "Frequency is set by the slowest path. Knowing how to find and shorten it is the core of performance-oriented design.",
    problem: "In a design with millions of paths, you need a way to identify the one that limits speed and to reason about fixes before running long tools.",
    eli12: "A relay team is only as fast as its slowest leg. The critical path is that slowest runner. Making the fast runners faster does nothing; you must help the slowest one or split the leg in two.",
    tech: "Path types: input-to-register, register-to-register, register-to-output, input-to-output. Fmax = 1 / (Tcq + Tcomb,max + Tsu + Tskew margin). Fixes: pipelining (split logic with registers), retiming (move registers), parallelism, logic restructuring (balance trees), reducing fanout, better architecture (for example carry-lookahead). Each fix trades latency, area or power.",
    inChip: "RTL architects plan logic depth per stage (often in gate levels or FO4 units); STA reports quantify it.",
    breaks: "Designs that cannot reach target frequency force architecture changes late in the project.",
    tested: "STA reports; early synthesis runs for timing feasibility.",
    prereqs: ["setup-hold"],
    objectives: ["Identify path types", "Compute Fmax", "Propose fixes and state their costs"],
    terms: [["Logic depth", "Number of gate levels on a path"], ["Pipelining", "Inserting registers to split long paths"], ["Retiming", "Moving registers across logic to balance stages"]],
    equations: ["Fmax = 1 / (Tcq + Tcomb_max + Tsu + Tuncertainty)"],
    mistakes: ["Optimizing non-critical paths", "Adding pipeline stages without handling the extra latency in control logic"],
    practice: ["Given a 4-stage path table, find Fmax and propose where to pipeline", "Explain the latency cost of adding one pipeline stage to an adder chain"],
    interview: [{ q: "How do you improve the maximum frequency of a design?", a: "Find the critical path, then shorten it: pipeline or retime, restructure logic, reduce fanout, choose faster arithmetic architectures, or relax constraints if a path is false or multicycle. State the latency, area and power costs.", level: 2 }],
    resources: ["bhasker-sta", "harris-harris"],
  },
  {
    id: "memory-basics", title: "Memories: SRAM, DRAM, register files and ROM", phase: "p2", module: "m2d",
    priority: "must", depth: "basic", difficulty: 2, days: 1, hours: 2, kind: "theory", skills: ["digital", "arch"],
    why: "Memories often take more than half of a chip's area and dominate power and performance in AI hardware.",
    problem: "Flops are too big for large storage. Dense memory structures (SRAM, DRAM) store bits in far smaller cells at the cost of special peripheral circuits and access rules.",
    eli12: "Flip-flops are like individual lockers with their own lock: fast but bulky. SRAM is a big cabinet of small drawers opened by an address. DRAM is even denser but its drawers slowly leak and must be refreshed.",
    tech: "SRAM: 6-transistor cell, fast, on-chip caches and buffers; accessed through word lines and bit lines with sense amplifiers. DRAM: 1 transistor + 1 capacitor, dense, needs refresh, usually off-chip. Register files: multi-ported flop or custom arrays for CPU registers. ROM/flash for non-volatile storage. In ASICs, SRAMs come as generated macros with fixed ports, sizes and timing.",
    inChip: "Caches, scratchpads, FIFOs, weight buffers in accelerators. Memory compilers generate SRAM macros; MBIST tests them.",
    breaks: "Reading and writing the same address in one cycle behaves per macro spec, not intuition; wrong assumptions cause data hazards.",
    tested: "Memory BIST in silicon; simulation models from memory compilers; read-during-write tests.",
    prereqs: ["latches-flipflops"],
    objectives: ["Compare SRAM, DRAM, register files and ROM", "Explain why memories are macros", "Describe read latency and ports"],
    terms: [["SRAM", "Static RAM: fast, no refresh, 6T cell"], ["DRAM", "Dynamic RAM: dense, needs refresh"], ["Macro", "A pre-designed block placed as a unit"]],
    mistakes: ["Assuming single-cycle reads from any memory size", "Ignoring port limits (one read and one write per cycle)"],
    practice: ["Estimate how many 6T SRAM transistors a 32 KB cache needs (data only)", "Describe read-during-write behaviour options"],
    interview: [{ q: "Why is SRAM used for caches and DRAM for main memory?", a: "SRAM is fast and needs no refresh but uses about six transistors per bit; DRAM is much denser (one transistor and a capacitor) and cheaper per bit but slower and needs refresh. Caches need speed; main memory needs capacity.", level: 1 }],
    resources: ["harris-harris", "mutlu-yt"],
  },
  {
    id: "python-hw", title: "Python for hardware engineers", phase: "p2", module: "m2e",
    priority: "must", depth: "working", difficulty: 2, days: 2, hours: 4, kind: "coding", skills: ["python"],
    why: "Python is the glue of modern hardware work: reference models, cocotb testbenches, log parsing, plots, ML for EDA. Your software background makes this fast.",
    problem: "Hardware teams used Perl and Tcl for automation; Python became dominant for its libraries (NumPy, pandas, matplotlib) and verification frameworks (cocotb).",
    eli12: "Python is your lab assistant: it checks results, draws graphs and does repetitive work while you think about the design.",
    tech: "Focus: integers and bit manipulation (masks, shifts, two's complement helpers), file and regex parsing of logs and reports, subprocess to run tools, argparse for small CLIs, dataclasses for transactions, NumPy for vectors and fixed-point models, matplotlib for plots, pytest for model tests. Skip what you already know (general syntax); focus on bit-accurate modeling.",
    inChip: "Reference models in DV, regression dashboards, timing report analysis, validation scripts, ML for EDA.",
    breaks: "Python ints are unbounded; models that forget to mask to N bits disagree with RTL in subtle ways.",
    tested: "Unit tests on models; cross-checking models against RTL simulation.",
    prereqs: ["number-systems"],
    objectives: ["Write bit-accurate helper functions (wrap, sign-extend)", "Parse a report with regex", "Drive a tool with subprocess"],
    terms: [["Reference model", "Software model that predicts correct hardware outputs"], ["Bit-accurate", "Matching hardware widths and overflow exactly"]],
    code: { lang: "python", src: "def wrap(x, n):  # keep n bits\n    return x & ((1 << n) - 1)\n\ndef to_signed(x, n):\n    x = wrap(x, n)\n    return x - (1 << n) if x >> (n - 1) else x\n\nassert to_signed(0xFF, 8) == -1" },
    mistakes: ["Forgetting to mask Python integers", "Writing throwaway scripts that nobody can rerun"],
    practice: ["Write a Python model of your ALU and compare it to RTL outputs dumped to a file", "Parse a Yosys stats report into a dictionary of cell counts"],
    interview: [{ q: "How have you used Python in hardware work?", a: "Give concrete examples: bit-accurate reference model, cocotb tests, regression summary scripts, report parsing and plots. Mention masking and signedness handling.", level: 1 }],
    resources: ["python-docs", "cocotb"],
  },
];
