import type { Topic } from "../schema.ts";

export const P3: Topic[] = [
  {
    id: "isa", title: "Instruction set architecture: the hardware/software contract", phase: "p3", module: "m3a",
    priority: "must", depth: "basic", difficulty: 2, days: 1, hours: 2, kind: "theory", skills: ["arch"],
    why: "The ISA is the boundary between software and hardware. Every CPU, compiler and verification plan starts from it.",
    problem: "Without a stable contract, every new chip would need new software. An ISA fixes the visible behaviour (instructions, registers, memory model) so microarchitecture can change underneath.",
    eli12: "An ISA is the menu a restaurant promises. The kitchen (microarchitecture) can be rebuilt, faster or cheaper, as long as every dish on the menu still comes out the same.",
    tech: "An ISA defines instruction formats, registers, addressing modes, memory ordering, privilege levels and exceptions. RISC ISAs (RISC-V, Arm) use fixed-length, load/store instructions; CISC (x86) has variable-length and memory operands. Microarchitecture is the implementation: pipelines, caches, predictors. Compatibility means old binaries run on new cores.",
    inChip: "CPU architects define or extend ISAs; DV teams verify cores against the ISA spec using instruction set simulators like Spike.",
    breaks: "A core that deviates from the ISA runs some programs wrong; subtle memory-ordering deviations cause rare multicore bugs.",
    tested: "Architectural compliance tests (for example RISCOF and riscv-tests) and co-simulation against a golden model.",
    prereqs: ["alu"],
    objectives: ["Distinguish ISA from microarchitecture", "Compare RISC and CISC", "Explain why ISA compatibility matters"],
    terms: [["ISA", "Instruction set architecture"], ["Microarchitecture", "How a specific core implements the ISA"], ["Load/store", "Only loads and stores access memory"]],
    mistakes: ["Confusing a core (implementation) with the ISA it implements"],
    practice: ["List what the RV32I spec defines and what it leaves to implementers", "Name two cores implementing the same ISA with very different microarchitectures"],
    interview: [{ q: "What is the difference between ISA and microarchitecture?", a: "The ISA is the programmer-visible contract (instructions, registers, memory model). Microarchitecture is the implementation (pipeline, caches, predictors). Many microarchitectures can implement one ISA.", level: 1 }],
    resources: ["riscv-isa-manual", "patterson-hennessy", "mutlu-yt"],
  },
  {
    id: "riscv-isa", title: "RISC-V RV32I in practice", phase: "p3", module: "m3a",
    priority: "must", depth: "working", difficulty: 2, days: 2, hours: 6, kind: "coding", skills: ["riscv", "arch"],
    why: "RISC-V is open, widely used in industry and academia, and ideal for portfolio CPUs. Several job postings now name RISC-V explicitly.",
    problem: "Proprietary ISAs require licenses. RISC-V is an open standard, so anyone can build, verify and publish a compliant core, which makes it perfect for learning and for real products.",
    eli12: "RISC-V is a free recipe book for processors. Anyone can cook from it, and because everyone uses the same recipes, the tools (compilers, simulators) work for everyone's kitchen.",
    tech: "RV32I: 32 integer registers (x0 hardwired to zero), 32-bit instructions in R, I, S, B, U, J formats. Immediates are sign-extended and scattered across fields (B and J types especially). Extensions: M (multiply/divide), A (atomics), F/D (float), C (compressed), Zicsr (CSRs), V (vector). Privilege spec defines machine/supervisor/user modes and traps. Toolchain: riscv-gnu-toolchain; simulator: Spike.",
    inChip: "Microcontrollers, accelerator control cores, SoC management cores; many companies ship RISC-V cores.",
    breaks: "Immediate decoding errors (especially branch and jump offsets) are the most common student core bugs.",
    tested: "riscv-tests, RISCOF architectural tests, random instruction streams (riscv-dv), and lockstep comparison with Spike.",
    prereqs: ["isa"],
    objectives: ["Decode all RV32I formats including immediates", "Hand-assemble short programs", "Run code on Spike or Ripes"],
    terms: [["x0", "Register that always reads zero"], ["CSR", "Control and status register"], ["Extension", "Optional ISA feature set (M, A, C, ...)"]],
    visuals: [{ title: "RV32I instruction formats", art: "R: funct7 | rs2 | rs1 | f3 | rd  | opcode\nI: imm[11:0]   | rs1 | f3 | rd  | opcode\nS: imm[11:5] | rs2 | rs1 | f3 | imm[4:0] | opcode\nB: imm[12|10:5] | rs2 | rs1 | f3 | imm[4:1|11] | opcode\nU: imm[31:12]              | rd  | opcode\nJ: imm[20|10:1|11|19:12]   | rd  | opcode" }],
    mistakes: ["Forgetting that branch offsets are in multiples of 2 bytes (imm[0] is implicit 0)", "Writing to x0 and expecting it to change"],
    practice: ["Decode 0x00A30333 by hand and verify with a disassembler", "Write a loop summing an array in RV32I and step through it in Ripes"],
    interview: [{ q: "Why are RISC-V immediates scattered across instruction fields?", a: "To keep rs1, rs2 and rd in the same bit positions across formats and keep the sign bit always at bit 31. That simplifies decode and lets register reads start before the format is fully known.", level: 3 }],
    resources: ["riscv-isa-manual", "ripes", "spike", "riscv-gnu-toolchain", "harris-harris"],
    certs: ["rvfa", "lfd111x"],
    projects: ["m-rv-single", "fp-rv-pipeline"],
  },
  {
    id: "c-for-hw", title: "C for hardware engineers (bits, pointers, memory-mapped I/O)", phase: "p3", module: "m3a",
    priority: "must", depth: "working", difficulty: 2, days: 2, hours: 4, kind: "coding", skills: ["cpp"],
    why: "C is how software talks to hardware: drivers, firmware, reference models and DPI in verification. Many DV and validation roles list C/C++.",
    problem: "High-level languages hide memory layout. Hardware interaction needs exact control of addresses, bit fields and volatile accesses.",
    eli12: "C lets you point at an exact mailbox number in memory and flip exact bits in it. That is how software presses the buttons on a chip.",
    tech: "Key skills: fixed-width types (uint32_t), bitwise operations and masks, pointers and arrays, structs and alignment, volatile for memory-mapped registers, endianness, compiling for RISC-V with GCC and reading the disassembly. For DV: C/C++ reference models connected through SystemVerilog DPI. Skip: GUI, most of the standard library beyond basics.",
    inChip: "Boot code, drivers for accelerators, bare-metal tests on CPU models, DPI models in UVM environments.",
    breaks: "Missing volatile lets the compiler remove register polls; wrong masks clobber neighbouring control bits.",
    tested: "Bare-metal tests on simulators or FPGA; code review; compiler warnings on strict settings.",
    prereqs: ["riscv-isa"],
    objectives: ["Read and write registers through volatile pointers", "Set, clear and test bit fields", "Compile C for RV32I and read the generated assembly"],
    terms: [["volatile", "Tells the compiler every access matters"], ["MMIO", "Memory-mapped I/O: registers accessed like memory"], ["DPI", "SystemVerilog Direct Programming Interface to call C"]],
    code: { lang: "c", src: "#define UART_BASE 0x10000000u\n#define UART_TX   (*(volatile uint32_t *)(UART_BASE + 0x0))\n#define UART_STAT (*(volatile uint32_t *)(UART_BASE + 0x4))\n#define TX_READY  (1u << 0)\n\nvoid putc_hw(char c) {\n  while (!(UART_STAT & TX_READY)) { }\n  UART_TX = (uint32_t)c;\n}" },
    mistakes: ["Forgetting volatile", "Read-modify-write races on shared control registers"],
    practice: ["Write set_bits/clear_bits helpers and test them", "Compile a small function with riscv64-unknown-elf-gcc -march=rv32i -O2 and annotate the assembly"],
    interview: [{ q: "Why is volatile needed when accessing hardware registers?", a: "Hardware can change a register or react to a read/write independently of program flow. volatile forces the compiler to perform every access in order instead of caching or removing it.", level: 2 }],
    resources: ["riscv-gnu-toolchain", "patterson-hennessy"],
  },
  {
    id: "single-cycle", title: "A single-cycle datapath and control unit", phase: "p3", module: "m3a",
    priority: "must", depth: "working", difficulty: 3, days: 2, hours: 5, kind: "theory", skills: ["arch", "rtl"],
    why: "Building the simplest complete CPU makes every later concept (pipelining, hazards, caches) concrete. It is also your first real RTL system.",
    problem: "A CPU must fetch, decode, execute, access memory and write back. The single-cycle design does all of it in one long clock cycle: easy to understand, but its clock is set by the slowest instruction.",
    eli12: "A single-cycle CPU is a kitchen where every order, from toast to a three-course meal, is given the same long time slot. It never gets confused, but it is slow because the slot fits the biggest order.",
    tech: "Datapath: PC, instruction memory, register file (2 read, 1 write), immediate generator, ALU, data memory, write-back mux, next-PC logic. Control decodes opcode/funct fields into signals (RegWrite, ALUSrc, MemRead, MemWrite, MemToReg, Branch, Jump). CPI = 1 but period = longest instruction path (usually loads).",
    inChip: "Real cores are pipelined, but microcontrollers and teaching cores start here; the datapath/control split is universal.",
    breaks: "Control signal errors for specific instruction types, wrong immediate selection, PC update bugs.",
    tested: "Per-instruction directed tests, riscv-tests, and comparison against Spike trace logs.",
    prereqs: ["riscv-isa", "alu", "memory-basics"],
    objectives: ["Draw the RV32I single-cycle datapath", "Derive control signals per instruction type", "Explain why its clock is slow"],
    terms: [["Datapath", "Hardware that moves and transforms data"], ["Control unit", "Logic that sets datapath controls per instruction"], ["Write-back", "Writing results into the register file"]],
    visuals: [{ title: "Single-cycle RV32I datapath", art: "PC -> IMEM -> decode -> RegFile(rs1,rs2) -> ALU -> DMEM -> WB mux -> RegFile(rd)\n |                  |         imm gen --^                          |\n +--- PC+4 / branch target <-- branch cmp ------------------------+" }],
    mistakes: ["Forgetting that loads are the critical path (memory plus ALU plus write-back)", "Not handling x0 writes"],
    practice: ["Fill a control-signal table for add, addi, lw, sw, beq, jal", "Estimate the clock period from component delays"],
    interview: [{ q: "Why is a single-cycle processor inefficient?", a: "The clock period must fit the slowest instruction (typically a load), so fast instructions waste time. Pipelining or multi-cycle designs let the clock follow the slowest stage instead.", level: 1 }],
    resources: ["harris-harris", "patterson-hennessy", "ripes"],
    projects: ["m-rv-single"],
  },
  {
    id: "performance", title: "Measuring performance: the iron law and Amdahl's law", phase: "p3", module: "m3b",
    priority: "must", depth: "working", difficulty: 2, days: 1, hours: 2, kind: "theory", skills: ["arch"],
    why: "Every architecture decision must be justified with numbers. The iron law and Amdahl's law are how engineers argue about speedups honestly.",
    problem: "Clock frequency alone misleads (a faster clock with worse CPI can be slower). Engineers need a formula that separates instruction count, CPI and cycle time.",
    eli12: "Travel time depends on how many stops you make, how long each stop takes, and how fast you drive between them. Speeding up only one part of the trip helps only as much as that part matters.",
    tech: "Time = instructions x CPI x cycle time. Speedup = old time / new time. Amdahl: speedup = 1 / ((1 - f) + f / s) for fraction f improved by s. Benchmarks (CoreMark, Dhrystone, SPEC) measure workloads; report methodology and averages honestly (geometric mean for ratios).",
    inChip: "Performance architects model changes before RTL; your projects should report CPI, speedup and methodology.",
    breaks: "Optimizing a rarely used path; reporting speedups with cherry-picked benchmarks.",
    tested: "Performance counters, simulation traces, benchmark runs.",
    prereqs: ["single-cycle"],
    objectives: ["Apply the iron law", "Compute Amdahl speedups", "Report performance honestly"],
    terms: [["CPI", "Cycles per instruction"], ["Speedup", "Old time divided by new time"], ["Amdahl's law", "Limit on speedup from improving part of a workload"]],
    equations: ["T = IC x CPI x Tclk", "Speedup = 1 / ((1-f) + f/s)"],
    example: "An accelerator makes 60% of runtime 10x faster: speedup = 1 / (0.4 + 0.06) = 2.17x, not 10x.",
    mistakes: ["Comparing MHz across different microarchitectures", "Ignoring the serial part of a workload"],
    practice: ["Compute speedup for f = 0.9, s = 100", "Compare two designs: 1 GHz CPI 1.5 vs 1.3 GHz CPI 2.0"],
    interview: [{ q: "A design doubles clock frequency but CPI rises from 1.2 to 2.0. Is it faster?", a: "Time per instruction goes from 1.2 x T to 2.0 x T/2 = 1.0 x T, so yes, about 1.2x faster for the same instruction count. Always compare full iron-law products.", level: 2 }],
    resources: ["hennessy-patterson", "coremark"],
  },
  {
    id: "pipelining", title: "Pipelining", phase: "p3", module: "m3b",
    priority: "must", depth: "working", difficulty: 3, days: 2, hours: 5, kind: "theory", skills: ["arch", "rtl"],
    why: "Pipelining is how nearly every high-performance digital system (CPUs, DSP, AI accelerators) reaches high throughput.",
    problem: "The single-cycle design wastes time. Splitting work into stages lets several instructions overlap, raising throughput while each instruction's latency stays similar.",
    eli12: "Laundry has three steps: wash, dry, fold. Doing one load completely before starting the next is slow. Pipelining starts washing the next load while the first one dries, so the machines are always busy.",
    tech: "Classic 5 stages: IF, ID, EX, MEM, WB with pipeline registers between them. Ideal CPI approaches 1 with a shorter clock period. Costs: pipeline register overhead, hazards, more complex control, and deeper pipelines increase branch penalties. Throughput vs latency tradeoff is central in every pipelined datapath, not only CPUs.",
    inChip: "CPUs, video codecs, SerDes datapaths, MAC arrays.",
    breaks: "Control signals not carried along with data through stages; stalls that drop or duplicate instructions.",
    tested: "Pipeline visualizers and trace comparison; directed tests for back-to-back dependent instructions.",
    prereqs: ["single-cycle", "critical-path"],
    objectives: ["Explain throughput vs latency", "Draw a 5-stage pipeline diagram", "Explain pipeline register overhead"],
    terms: [["Throughput", "Results per unit time"], ["Latency", "Time for one item end to end"], ["Pipeline register", "Register separating two stages"]],
    visuals: [{ title: "Five instructions in a 5-stage pipeline", art: "cycle:  1  2  3  4  5  6  7  8  9\ni1     IF ID EX ME WB\ni2        IF ID EX ME WB\ni3           IF ID EX ME WB\ni4              IF ID EX ME WB\ni5                 IF ID EX ME WB" }],
    mistakes: ["Assuming N stages give N times speedup (register overhead and hazards)", "Forgetting to pipeline control signals"],
    practice: ["Compute throughput for 5 stages of 200 ps plus 20 ps register overhead", "Step through a program in Ripes' 5-stage view"],
    interview: [{ q: "Why doesn't a 10-stage pipeline give 10x speedup over single-cycle?", a: "Stages are not perfectly balanced, each adds register overhead (clock-to-q plus setup), hazards cause stalls and flushes, and branch mispredictions cost more with deeper pipelines.", level: 2 }],
    resources: ["harris-harris", "ripes", "mutlu-yt"],
    projects: ["fp-rv-pipeline"],
  },
  {
    id: "hazards", title: "Pipeline hazards, forwarding and stalls", phase: "p3", module: "m3b",
    priority: "must", depth: "advanced", difficulty: 4, days: 3, hours: 6, kind: "theory", skills: ["arch", "rtl"],
    why: "Hazard handling is where pipelined CPUs get hard, and it is a favourite interview and debugging topic.",
    problem: "Overlapping instructions can need data that is not written yet, or fetch the wrong path after a branch. Hazard logic keeps the pipeline correct with minimal lost cycles.",
    eli12: "In the laundry pipeline, if the next load needs a sock that is still in the dryer, you must either wait (stall) or grab it straight from the dryer (forwarding). If you started the wrong load, you throw it out (flush).",
    tech: "Data hazards (RAW): solved by forwarding from EX/MEM and MEM/WB to EX inputs; load-use needs a one-cycle stall. Control hazards: branches resolved in EX cause flushes of younger instructions; prediction reduces penalty. Structural hazards: resource conflicts (for example a single memory port). Hazard unit compares register indices between stages.",
    inChip: "Every pipelined core's hazard/forwarding unit; similar interlocks in accelerator pipelines.",
    breaks: "Missed forwarding cases give wrong results only for specific instruction sequences; flush bugs execute wrong-path instructions.",
    tested: "Directed dependent-instruction sequences, random instruction streams, and co-simulation with Spike.",
    prereqs: ["pipelining"],
    objectives: ["Identify RAW, control and structural hazards", "Design forwarding and stall logic", "Compute CPI with stalls and flushes"],
    terms: [["RAW hazard", "Read after write dependence"], ["Forwarding", "Passing a result directly to a later stage"], ["Flush", "Cancelling wrong-path instructions"], ["Load-use hazard", "Using a loaded value in the next instruction"]],
    visuals: [{ title: "Forwarding paths", art: "        EX/MEM.rd == ID/EX.rs1 ? -> forward ALU result\n        MEM/WB.rd == ID/EX.rs1 ? -> forward WB value\n [ID/EX] --rs1,rs2--> [ALU] <--+-- EX/MEM result\n                              +-- MEM/WB result" }],
    code: { lang: "verilog", src: "// forwarding select for ALU operand A\nalways @(*) begin\n  if (exmem_regwrite && exmem_rd != 0 && exmem_rd == idex_rs1) fwd_a = 2'b10;\n  else if (memwb_regwrite && memwb_rd != 0 && memwb_rd == idex_rs1) fwd_a = 2'b01;\n  else fwd_a = 2'b00;\nend" },
    mistakes: ["Forwarding from x0", "Wrong priority when both EX/MEM and MEM/WB match (the newer value must win)"],
    practice: ["Find all hazards in a 6-instruction sequence and mark forwarding or stalls", "Compute CPI for 20% loads with 30% load-use, 15% branches with 2-cycle penalty"],
    interview: [{ q: "Why can't forwarding eliminate the load-use hazard in a 5-stage pipeline?", a: "The loaded data is available only at the end of MEM, but the dependent instruction needs it at the start of EX in the same cycle. One stall cycle is required, then forwarding from MEM/WB.", level: 3 }],
    resources: ["harris-harris", "patterson-hennessy", "ripes"],
    projects: ["fp-rv-pipeline"],
  },
  {
    id: "branch-prediction", title: "Branch prediction", phase: "p3", module: "m3b",
    priority: "should", depth: "working", difficulty: 3, days: 2, hours: 4, kind: "theory", skills: ["arch"],
    why: "Branch prediction is one of the biggest performance levers in modern cores and a great research-style portfolio project.",
    problem: "Deep pipelines fetch many instructions before a branch resolves. Stalling wastes cycles; guessing correctly most of the time keeps the pipeline full.",
    eli12: "On your way to school you guess which road will be open based on what happened the last few days. If you guess right you save time; if wrong you turn back.",
    tech: "Static: predict not-taken or backward-taken. Dynamic: 1-bit and 2-bit saturating counters (bimodal), BTB for target addresses, global history (gshare XORs history with PC), tournament predictors (McFarling), perceptron predictors, TAGE-family predictors in modern cores. Metrics: accuracy, MPKI (mispredictions per kilo-instructions), storage bits.",
    inChip: "Front-end of every high-performance CPU; architects trade predictor accuracy against area, power and timing.",
    breaks: "Aliasing in small tables, predictor timing on the fetch critical path, wrong-path recovery bugs.",
    tested: "Trace-driven simulators (for example ChampSim) for accuracy; RTL tests for update and recovery logic.",
    prereqs: ["hazards"],
    objectives: ["Explain 2-bit counters and BTBs", "Compare bimodal, gshare and tournament predictors", "Compute misprediction cost"],
    terms: [["BTB", "Branch target buffer: caches branch targets"], ["MPKI", "Mispredictions per thousand instructions"], ["gshare", "Global-history predictor using PC XOR history"]],
    mistakes: ["Measuring accuracy on tiny programs only", "Ignoring the predictor's own timing and area"],
    practice: ["Simulate a 2-bit predictor in Python on a synthetic branch trace", "Explain why a loop exit branch mispredicts once per loop"],
    interview: [{ q: "Why use 2-bit saturating counters instead of 1-bit?", a: "A 1-bit predictor mispredicts twice per loop (exit and re-entry). Two bits add hysteresis, so one anomalous outcome does not flip a strongly biased prediction.", level: 2 }],
    resources: ["hennessy-patterson", "champsim"],
    papers: ["mcfarling-combining", "perceptron-bp"],
    projects: ["fp-branch-pred"],
  },
  {
    id: "memory-hierarchy", title: "Memory hierarchy, locality and virtual memory", phase: "p3", module: "m3c",
    priority: "must", depth: "working", difficulty: 3, days: 2, hours: 4, kind: "theory", skills: ["arch"],
    why: "The memory wall dominates performance in CPUs and AI hardware. Understanding locality explains caches, prefetchers and accelerator buffers.",
    problem: "Processors got faster much faster than DRAM. A hierarchy of small fast memories near the core, exploiting locality, hides most of the gap.",
    eli12: "You keep your most-used books on your desk, more on a shelf, and the rest in the library across town. Most of the time the book you need is on the desk, so you rarely make the long trip.",
    tech: "Temporal locality (reuse soon) and spatial locality (nearby addresses). Levels: registers, L1, L2, L3, DRAM, storage. AMAT = hit time + miss rate x miss penalty. Virtual memory gives each process an address space; page tables translate virtual to physical; TLBs cache translations; page faults are handled by the OS.",
    inChip: "Cache hierarchy design, memory controllers, MMUs, accelerator scratchpads and DMA.",
    breaks: "Poor locality workloads thrash caches; TLB misses hurt large-memory applications.",
    tested: "Performance simulators, cache miss counters, MMU verification with page-table walks.",
    prereqs: ["memory-basics", "performance"],
    objectives: ["Explain locality", "Compute AMAT", "Explain virtual-to-physical translation and TLBs"],
    terms: [["AMAT", "Average memory access time"], ["TLB", "Translation lookaside buffer"], ["Page table", "Map from virtual pages to physical frames"]],
    equations: ["AMAT = hit_time + miss_rate x miss_penalty"],
    example: "L1 hit 1 cycle, miss rate 5%, L2 hit 10 cycles, L2 miss rate 20%, DRAM 200 cycles: AMAT = 1 + 0.05 x (10 + 0.2 x 200) = 3.5 cycles.",
    mistakes: ["Using global miss rate where local miss rate is meant", "Ignoring TLB effects"],
    practice: ["Compute AMAT for a three-level hierarchy", "Explain why matrix multiplication loop order changes performance"],
    interview: [{ q: "What is a TLB and why is it needed?", a: "A small cache of recent virtual-to-physical translations. Without it, every memory access would need page-table walks through memory, multiplying access time.", level: 2 }],
    resources: ["hennessy-patterson", "mutlu-yt"],
  },
  {
    id: "caches", title: "Caches: mapping, associativity, replacement and writes", phase: "p3", module: "m3c",
    priority: "must", depth: "advanced", difficulty: 4, days: 3, hours: 6, kind: "coding", skills: ["arch", "rtl"],
    why: "Caches are among the most common blocks in SoCs, and cache design is a classic interview and flagship-project topic.",
    problem: "Main memory is slow. A cache keeps recently used lines close to the core, but must decide where each line may live, what to evict, and how to handle writes.",
    eli12: "A cache is a small desk with labelled spots. Direct-mapped means each book has exactly one allowed spot; set-associative means a few allowed spots, so books fight less over the same place.",
    tech: "Address split: tag | index | offset. Direct-mapped: one way per set; set-associative: N ways; fully associative: any line anywhere. Replacement: LRU, pseudo-LRU, random. Write policies: write-through vs write-back, write-allocate vs no-write-allocate. Miss types: compulsory, capacity, conflict (the three Cs), plus coherence in multicore. Hardware: tag arrays, data arrays, comparators, valid/dirty bits, refill FSM.",
    inChip: "L1/L2 caches in CPUs, instruction caches in microcontrollers, texture caches, accelerator buffers.",
    breaks: "Tag/index bit-slicing errors, dirty lines lost on eviction, refill races with new requests.",
    tested: "Random address streams with a reference model, targeted conflict patterns, performance counters.",
    prereqs: ["memory-hierarchy"],
    objectives: ["Split an address into tag, index and offset", "Compare associativity and replacement options", "Design a write-back cache controller FSM"],
    terms: [["Set", "Group of lines an address can map to"], ["Way", "One slot within a set"], ["Dirty bit", "Line was modified and must be written back"], ["Conflict miss", "Miss caused by limited associativity"]],
    visuals: [{ title: "Address breakdown (32 KB, 4-way, 64 B lines)", art: "sets = 32K / (64 x 4) = 128 -> 7 index bits\n offset = log2(64) = 6 bits\n |<---- tag (19) ---->|<- index (7) ->|<- offset (6) ->|" }],
    mistakes: ["Getting index width wrong for set-associative caches", "Forgetting to write back dirty victims"],
    senior: ["How do you choose associativity given area, latency and hit-rate targets?", "What happens under back-to-back misses to the same line?", "How would you verify replacement without a golden cycle-accurate model?"],
    practice: ["Write a Python cache simulator supporting ways, LRU and write policies", "Measure hit rate on a matrix-multiply trace for 1, 2 and 4 ways"],
    interview: [{ q: "Explain the three Cs of cache misses and how to reduce each.", a: "Compulsory (first access; prefetching, larger lines), capacity (working set too large; bigger cache), conflict (mapping collisions; higher associativity, victim cache). Each fix has area, latency or power costs.", level: 2 }],
    resources: ["hennessy-patterson", "harris-harris", "mutlu-yt"],
    papers: ["jouppi-victim"],
    projects: ["m-cache-sim", "fp-cache"],
  },
  {
    id: "io-interrupts", title: "I/O, memory-mapped registers and interrupts", phase: "p3", module: "m3d",
    priority: "must", depth: "working", difficulty: 2, days: 2, hours: 3, kind: "theory", skills: ["arch", "protocols"],
    why: "Every peripheral and accelerator you build needs a register map and usually interrupts. This is where hardware meets software.",
    problem: "CPUs need to control devices and learn about events. Polling wastes cycles; interrupts let devices signal the CPU; DMA moves data without the CPU.",
    eli12: "Memory-mapped registers are buttons and lights on a machine that the CPU presses and reads by address. An interrupt is the machine ringing a doorbell when it needs attention.",
    tech: "Register maps define address offsets, bit fields, access types (RW, RO, W1C), and reset values. Interrupts: level vs edge, masking, status and clear registers, interrupt controllers (for example RISC-V PLIC/CLINT). DMA engines transfer blocks and interrupt on completion. Register descriptions are often generated from a single source (for example SystemRDL) to keep RTL, C headers and docs in sync.",
    inChip: "Every IP block: UART, timers, accelerators. Verification uses register models (UVM RAL).",
    breaks: "Mismatch between documented and implemented fields; write-1-to-clear races; interrupts lost or stuck.",
    tested: "Register access tests (reset values, access types), interrupt sequencing tests, firmware bring-up.",
    prereqs: ["c-for-hw"],
    objectives: ["Design a register map", "Explain level vs edge interrupts and W1C", "Explain DMA"],
    terms: [["W1C", "Write-1-to-clear register bit"], ["PLIC", "RISC-V platform-level interrupt controller"], ["DMA", "Direct memory access"]],
    mistakes: ["Clearing interrupt status with a read-modify-write that clears other bits", "No single source of truth for the register map"],
    practice: ["Write a register map for a timer peripheral (control, count, compare, status)", "Explain how software handles a UART receive interrupt"],
    interview: [{ q: "What is a write-1-to-clear register and why is it used?", a: "Writing 1 to a bit clears it, writing 0 leaves it unchanged. It lets software clear specific status flags without disturbing others, avoiding read-modify-write races with hardware setting bits.", level: 2 }],
    resources: ["peakrdl", "riscv-isa-manual"],
    projects: ["fp-axi-apb"],
  },
  {
    id: "soc-buses", title: "SoC organization, buses and interconnects", phase: "p3", module: "m3d",
    priority: "must", depth: "basic", difficulty: 2, days: 1, hours: 2, kind: "theory", skills: ["arch", "protocols"],
    why: "Real chips are SoCs: CPUs, memories, accelerators and peripherals joined by interconnects. AMBA protocols appear in most RTL and DV job descriptions.",
    problem: "Point-to-point wiring does not scale. Standard buses and interconnects let IP blocks from different teams and vendors plug together.",
    eli12: "An SoC is a small city. The interconnect is its road network, with rules (protocols) so every car knows how to merge, stop and deliver packages.",
    tech: "Managers (initiators) and subordinates (targets); address decoding; arbitration. AMBA family: APB (simple, low-power peripherals), AHB (older pipelined bus), AXI (high-performance, separate read/write channels, bursts, outstanding transactions), AXI-Stream (data streaming), plus crossbars and NoCs for large systems.",
    inChip: "Every SoC; integration engineers and DV teams live in these protocols.",
    breaks: "Deadlocks in interconnects, wrong address maps, protocol violations between IP blocks.",
    tested: "Protocol assertions, verification IP, SoC-level integration tests.",
    projects: ["fx-soc-peripheral"],
    prereqs: ["io-interrupts"],
    objectives: ["Describe manager/subordinate roles", "Compare APB, AHB, AXI and AXI-Stream", "Draw a simple SoC address map"],
    terms: [["Manager", "Initiates transactions (formerly 'master')"], ["Subordinate", "Responds to transactions (formerly 'slave')"], ["Crossbar", "Interconnect allowing parallel paths"]],
    mistakes: ["Assuming one protocol fits all traffic types"],
    practice: ["Draw a small SoC with a RISC-V core, SRAM, UART, timer and accelerator, with an address map"],
    interview: [{ q: "Why would a peripheral use APB rather than AXI?", a: "APB is simple, low-power and small; peripherals with low bandwidth needs (UART, GPIO, timers) do not need AXI's bursts, outstanding transactions and separate channels.", level: 1 }],
    resources: ["amba", "pulp-axi"],
  },
];
