import type { Topic } from "../schema.ts";

export const P4: Topic[] = [
  {
    id: "hdl-mindset", title: "HDL mindset: describing hardware, not running code", phase: "p4", module: "m4a",
    priority: "must", depth: "working", difficulty: 2, days: 1, hours: 2, kind: "theory", skills: ["hdl"],
    why: "This is the single biggest shift for a software developer. Get it right and Verilog becomes easy; get it wrong and every design is a bug farm.",
    problem: "Schematics do not scale and software languages are sequential. HDLs describe concurrent hardware structures that simulators can execute and synthesis tools can turn into gates.",
    eli12: "In JavaScript you write a recipe that one cook follows line by line. In Verilog you draw the kitchen: every station works at the same time, all the time. The code is a blueprint, not a to-do list.",
    analogyLimit: "Testbench code does run sequentially like software. The hard part is knowing which code is hardware and which is test scaffolding.",
    tech: "Every always block and assign statement runs concurrently. Synthesizable code maps to registers (clocked blocks) and combinational logic (assigns, always @*). Loops unroll into parallel hardware; they do not iterate over time. Variables do not 'hold values between calls'; registers hold state only across clock edges. Delays (#10) are ignored by synthesis. Before writing code, sketch the hardware: registers, muxes, adders, FSMs.",
    inChip: "Every RTL engineer thinks in hardware first; code reviews ask 'what does this synthesize to?'.",
    breaks: "Software-style code: huge unrolled loops, unintended latches, simulation/synthesis mismatches, designs that cannot meet timing.",
    tested: "Synthesis reports (cell counts, inferred latches), lint, and simulation vs gate-level comparison.",
    prereqs: ["registers-counters", "fsm"],
    objectives: ["Explain concurrency in HDLs", "Predict hardware from simple code", "Separate synthesizable design code from testbench code"],
    terms: [["Synthesizable", "Code a synthesis tool can turn into gates"], ["Elaboration", "Building the design hierarchy before simulation"], ["Unrolling", "A loop becomes repeated parallel hardware"]],
    visuals: [{ title: "Software vs hardware reading of the same idea", art: "Software: for i in 0..7: sum += a[i]   -> 8 steps in time\nHardware: sum = a0+a1+...+a7           -> an adder tree in space\n          (all additions exist at once; a register stores the result)" }],
    mistakes: ["Writing Verilog without first sketching the circuit", "Using #delays in design code"],
    practice: ["For five small snippets, draw the hardware before simulating", "Rewrite a software-style accumulation loop as a pipelined adder tree"],
    interview: [{ q: "What hardware does a for loop in synthesizable Verilog create?", a: "It unrolls at elaboration into replicated parallel logic; it does not execute over multiple cycles. Iterating over time requires a counter and a state machine.", level: 2 }],
    resources: ["hdlbits", "nptel-verilog", "lowrisc-style"],
  },
  {
    id: "verilog-basics", title: "Verilog modules, ports, nets and variables", phase: "p4", module: "m4a",
    priority: "must", depth: "working", difficulty: 1, days: 2, hours: 4, kind: "coding", skills: ["hdl"],
    why: "Modules and ports are the structure of every design. Net versus variable semantics cause many beginner compile errors.",
    problem: "Designs need hierarchy and clear interfaces. Modules encapsulate blocks; ports define their connections; nets model wires and variables hold procedural values.",
    eli12: "A module is a LEGO brick with pegs (ports). Wires connect pegs between bricks. A reg is a spot where a value is written by a procedure, which may or may not become a real flip-flop.",
    tech: "Module declaration with ANSI-style ports and widths. wire (net) is driven by assign or ports; reg (variable) is assigned in always/initial blocks; reg does not necessarily mean a register. Vectors [MSB:LSB], part-selects, arrays. Instantiation by named port connection. Four-state logic: 0, 1, X (unknown), Z (high impedance).",
    inChip: "All RTL. Named port connections prevent integration bugs in large SoCs.",
    breaks: "Positional port connection mistakes; multiple drivers on a net; X values spreading from uninitialized regs.",
    tested: "Lint catches width mismatches and multiple drivers; simulation shows X propagation.",
    prereqs: ["hdl-mindset"],
    objectives: ["Declare modules with typed, sized ports", "Distinguish wire and reg", "Instantiate modules with named connections"],
    terms: [["Net", "A connection driven continuously (wire)"], ["Variable", "Storage assigned procedurally (reg, logic)"], ["X", "Unknown value in simulation"]],
    mistakes: ["Thinking reg always means flip-flop", "Leaving outputs undriven"],
    practice: ["HDLBits: all Basics and Vectors problems", "Build a top module instantiating two adders by named ports"],
    interview: [{ q: "Does declaring a signal as reg create a flip-flop?", a: "No. reg is a variable type assigned in procedural blocks. It becomes a flip-flop only if assigned in an edge-triggered block; in an always @* block it becomes combinational logic.", level: 1 }],
    resources: ["hdlbits", "chipverify", "nptel-verilog"],
  },
  {
    id: "verilog-operators", title: "Operators, bit widths, signedness and concatenation", phase: "p4", module: "m4a",
    priority: "must", depth: "working", difficulty: 2, days: 2, hours: 3, kind: "coding", skills: ["hdl"],
    why: "Width and sign bugs compile without error and silently produce wrong hardware. They are among the top causes of RTL bugs.",
    problem: "Verilog's expression sizing rules extend or truncate operands implicitly. Engineers must control widths explicitly to get the intended arithmetic.",
    eli12: "Verilog is like pouring liquid between cups of different sizes. Pour a big cup into a small one and some spills (truncation). Mix a signed and an unsigned cup and Verilog quietly treats both as unsigned.",
    tech: "Bitwise (& | ^ ~), logical (&& || !), reduction (&a, |a, ^a), shifts (<< >> >>>), arithmetic, comparison, concatenation {a,b}, replication {4{a}}. Expression width is context-dependent: the largest operand or the assignment target. If any operand is unsigned, the whole expression is unsigned. Use $signed(), explicit widths, and sized literals (8'hFF).",
    inChip: "Datapaths, address arithmetic, DSP. Lint rules enforce width matching in industry flows.",
    breaks: "Lost carry bits, wrong signed comparisons, arithmetic shift acting as logical shift.",
    tested: "Lint width warnings, corner-value tests, reference-model comparison.",
    prereqs: ["verilog-basics", "number-systems"],
    objectives: ["Predict expression widths", "Use signed arithmetic correctly", "Use concatenation and replication for sign extension"],
    terms: [["Reduction operator", "Combines all bits of a vector into one bit"], ["Sized literal", "A constant with explicit width, like 8'd5"]],
    code: { lang: "verilog", src: "wire signed [7:0] a = -8'sd3;\nwire [15:0] ext  = {{8{a[7]}}, a};   // sign extension by replication\nwire [8:0]  sum  = a + 8'd5;          // 9 bits keep the carry\nwire lt_signed   = $signed(a) < $signed(8'd5);" },
    mistakes: ["Comparing a signed wire to an unsigned literal", "Using >> on signed data expecting sign fill (use >>>)"],
    practice: ["Predict the result of ten width/sign expressions, then simulate to check", "HDLBits: Vector4, Vector5, Popcount255, Reduction"],
    interview: [{ q: "What is the result width of a + b where a and b are 8 bits and the result is assigned to a 16-bit wire?", a: "The expression is evaluated at 16 bits (context-determined by the assignment target), so the carry is kept. If assigned to 8 bits, the carry is lost.", level: 2 }],
    resources: ["hdlbits", "chipverify"],
  },
  {
    id: "comb-modeling", title: "Modeling combinational logic (assign and always @*)", phase: "p4", module: "m4a",
    priority: "must", depth: "working", difficulty: 2, days: 2, hours: 3, kind: "coding", skills: ["hdl", "rtl"],
    why: "Most logic between registers is combinational. Writing it cleanly avoids latches, X issues and simulation/synthesis mismatches.",
    problem: "Combinational logic must produce outputs for every input combination with no memory. Procedural code makes it easy to forget a branch, which silently creates memory (a latch).",
    eli12: "Combinational logic is a vending machine that answers instantly based only on the buttons you press now. If some button combination has no answer written down, the machine 'remembers' the last answer, which is a bug.",
    tech: "Continuous assign for simple expressions. always @(*) (or always_comb in SystemVerilog) for complex logic, with blocking assignments (=), default assignments at the top, and complete case/if coverage. Avoid feedback loops (combinational loops).",
    inChip: "Decoders, next-state logic, muxes, arithmetic between pipeline registers.",
    breaks: "Latches from incomplete assignment; combinational loops; sensitivity-list mismatches in old-style always blocks.",
    tested: "Lint (latch and loop checks), synthesis reports, simulation.",
    prereqs: ["verilog-operators"],
    objectives: ["Write combinational always blocks with defaults", "Avoid combinational loops", "Choose between assign and always @*"],
    terms: [["Combinational loop", "Output feeds back to its own input without a register"], ["Sensitivity list", "Signals that trigger an always block"]],
    code: { lang: "verilog", src: "always @(*) begin\n  y     = 8'd0;      // default first: no latch\n  valid = 1'b0;\n  if (en) begin\n    y     = a & b;\n    valid = 1'b1;\n  end\nend" },
    mistakes: ["Missing defaults", "Manual sensitivity lists that miss a signal"],
    practice: ["HDLBits: Always blocks (combinational), Always case, Always nolatches"],
    interview: [{ q: "How do you avoid latches in combinational always blocks?", a: "Assign every output on every path: set defaults at the top, cover all case items or add default, and use always_comb so tools warn when a latch is inferred.", level: 1 }],
    resources: ["hdlbits", "sunburst"],
  },
  {
    id: "seq-modeling", title: "Modeling sequential logic (always @(posedge clk))", phase: "p4", module: "m4a",
    priority: "must", depth: "working", difficulty: 2, days: 2, hours: 3, kind: "coding", skills: ["hdl", "rtl"],
    why: "Registers hold all state. Correct sequential templates are the foundation of reliable RTL.",
    problem: "Flip-flops must update only on clock edges, with well-defined reset behaviour. Standard coding templates make synthesis infer exactly the intended flops.",
    eli12: "Sequential code describes what the memory boxes should hold after the next tick. Everything inside the block happens together at the tick.",
    tech: "Edge-triggered always blocks with non-blocking assignments (<=). Templates: sync reset, async reset (in sensitivity list), enable, and combinations. Keep next-state computation in combinational logic or simple expressions; one clock per block. Registers without reset are fine for datapaths where reset is not required.",
    inChip: "Pipeline registers, state registers, counters, CSRs.",
    breaks: "Mixing blocking and non-blocking causes races; async reset without proper template synthesizes wrong.",
    tested: "Simulation, lint, and equivalence checking after synthesis.",
    prereqs: ["comb-modeling", "resets"],
    objectives: ["Write sync and async reset flop templates", "Add enables", "Separate state from next-state logic"],
    terms: [["Non-blocking assignment", "<= : all right-hand sides sampled, then all updated together"], ["Enable", "Condition under which a register loads a new value"]],
    code: { lang: "verilog", src: "always @(posedge clk or negedge rst_n) begin\n  if (!rst_n)   q <= '0;\n  else if (en)  q <= d;\nend" },
    mistakes: ["Using blocking (=) in clocked blocks", "Assigning the same register in two always blocks"],
    practice: ["HDLBits: Dff with reset variants, Edge detection, Edgecapture"],
    interview: [{ q: "Write a positive-edge detector in Verilog.", a: "Register the input each clock (prev <= in) and output in & ~prev (one-cycle pulse). Mention registering the output if glitch-free timing matters.", level: 1 }],
    resources: ["hdlbits", "sunburst"],
  },
  {
    id: "blocking-nonblocking", title: "Blocking vs non-blocking assignments", phase: "p4", module: "m4a",
    priority: "must", depth: "advanced", difficulty: 3, days: 2, hours: 4, kind: "coding", skills: ["hdl", "rtl"],
    why: "The most famous Verilog pitfall. Misuse creates simulation races and simulation/synthesis mismatches that only appear in some simulators or orderings.",
    problem: "Hardware registers all update simultaneously at a clock edge, but simulators execute statements one at a time. Non-blocking assignments model simultaneous updates; blocking assignments model immediate, ordered computation.",
    eli12: "Blocking is like passing a note that the next person reads immediately. Non-blocking is like everyone writing their note at the same moment and swapping only after everyone has written.",
    tech: "Blocking (=) updates immediately; later statements see the new value. Non-blocking (<=) evaluates right-hand sides now and schedules updates in the NBA region of the time step. Guidelines (Cummings): use <= in sequential blocks, = in combinational blocks, do not mix in one block, do not assign a variable from multiple blocks. Swapping registers with <= works; with = it overwrites.",
    inChip: "Every RTL code review checks this; lint rules enforce it.",
    breaks: "Race conditions that change behaviour with simulator or file order; shift registers collapsing into one flop.",
    tested: "Lint rules, simulation across simulators, gate-level comparison.",
    prereqs: ["seq-modeling"],
    objectives: ["Explain the scheduling difference", "Predict results of blocking vs non-blocking code", "Apply the coding guidelines"],
    terms: [["NBA region", "Simulator phase where non-blocking updates are applied"], ["Race condition", "Result depends on execution order"]],
    code: { lang: "verilog", src: "// correct 3-stage shift register\nalways @(posedge clk) begin\n  q1 <= d;\n  q2 <= q1;\n  q3 <= q2;\nend\n// with '=' all three would get d in one edge (one flop after synthesis)" },
    mistakes: ["Blocking assignments in clocked blocks", "Mixing = and <= to the same variable"],
    practice: ["Simulate the shift register with = and <= and compare waveforms", "Read Cummings' 'Nonblocking Assignments in Verilog Synthesis, Coding Styles That Kill!' and summarize the eight guidelines"],
    interview: [{ q: "What happens if you swap two registers using blocking assignments in a clocked block?", a: "a = b; b = a; makes both equal to the old b because the first assignment is visible immediately. With non-blocking (a <= b; b <= a;) both right-hand sides are sampled first, so values swap correctly.", level: 2 }],
    resources: ["sunburst", "chipverify", "hdlbits"],
  },
  {
    id: "latch-inference", title: "Unintended latches and how synthesis reads your code", phase: "p4", module: "m4a",
    priority: "must", depth: "working", difficulty: 2, days: 1, hours: 2, kind: "coding", skills: ["hdl", "rtl"],
    why: "Synthesis turns code into hardware literally. Knowing its rules lets you predict gates, flops and latches from code.",
    problem: "If code implies a variable must remember its old value in some combinational path, synthesis must build a latch. Latches complicate timing and testing.",
    eli12: "If your instructions say 'sometimes, keep what you had', the factory must build a memory box there. Many beginners ask for memory boxes by accident.",
    tech: "Latch inference: combinational block where some path does not assign a variable. Flop inference: edge-triggered block. Mux inference: if/case. Priority logic from nested if. Don't-cares from default x assignments may help optimization but can hide bugs in simulation. Read Yosys 'stat' and 'show' output to see inferred structure.",
    inChip: "Lint and synthesis logs are reviewed for latches in every project; intentional latches are rare and documented.",
    breaks: "Timing tools treat latches specially; DFT scan becomes harder; glitches can pass through transparent latches.",
    tested: "Synthesis latch warnings; lint rules; netlist inspection.",
    prereqs: ["comb-modeling"],
    objectives: ["Predict when a latch is inferred", "Read synthesis statistics", "Fix latch inference three ways"],
    terms: [["Inference", "Synthesis deducing hardware from code patterns"], ["Yosys stat", "Command listing cell counts by type"]],
    mistakes: ["Suppressing latch warnings instead of fixing code"],
    practice: ["Write three latch-inferring snippets, synthesize with Yosys, then fix each", "Use Yosys 'show' to view the netlist of a 4:1 mux"],
    interview: [{ q: "Why are unintended latches bad?", a: "They make timing analysis harder (transparency and time borrowing), can pass glitches, complicate scan testing, and usually indicate a coding mistake where some input combination was not handled.", level: 1 }],
    resources: ["yosys", "hdlbits"],
  },
  {
    id: "hierarchy-generate", title: "Hierarchy, parameters and generate", phase: "p4", module: "m4a",
    priority: "must", depth: "working", difficulty: 2, days: 2, hours: 3, kind: "coding", skills: ["hdl", "rtl"],
    why: "Reusable, parameterized IP is how real teams work: one FIFO module used with many widths and depths.",
    problem: "Copy-pasting modules for each size creates maintenance bugs. Parameters and generate blocks create configurable, correct-by-construction hardware.",
    eli12: "Parameters are dials on a machine: set width to 8 or 32 and the same design builds the right size. Generate is a factory robot that builds many copies of a part automatically.",
    tech: "parameter and localparam; overriding at instantiation (#(.W(32))); $clog2 for pointer widths; generate for loops and if/case generate for conditional structure; named generate blocks for hierarchy paths. Keep parameter legality checks (for example depth must be a power of two) with assertions.",
    inChip: "IP libraries, FIFOs, arbiters, crossbars, register banks.",
    breaks: "Parameter combinations never tested; $clog2 edge cases (depth 1); hierarchical names changing with generate.",
    tested: "Tests across parameter sets in regression; elaboration-time checks.",
    projects: ["m-crc-rtl"],
    prereqs: ["verilog-basics"],
    objectives: ["Write parameterized modules", "Use generate loops and conditionals", "Test multiple parameter sets"],
    terms: [["localparam", "Parameter that cannot be overridden"], ["$clog2", "Ceiling log2, used for address widths"]],
    mistakes: ["Testing only the default parameters", "Hard-coding widths inside parameterized modules"],
    practice: ["Build a parameterized N-input AND reduction with generate and test N = 1, 2, 7, 32", "HDLBits: Adder100i, Bcdadd100"],
    interview: [{ q: "What is the difference between parameter and localparam?", a: "parameter can be overridden when the module is instantiated; localparam is derived internally (for example from other parameters) and cannot be overridden.", level: 1 }],
    resources: ["chipverify", "hdlbits"],
  },
  {
    id: "testbench-basics", title: "Your first testbench", phase: "p4", module: "m4b",
    priority: "must", depth: "working", difficulty: 2, days: 2, hours: 4, kind: "coding", skills: ["hdl", "verification"],
    why: "Untested RTL is unfinished RTL. Even RTL designers must write testbenches, and verification is often the largest job category for freshers.",
    problem: "Looking at waveforms by eye does not scale. Testbenches generate stimulus, check results automatically and report pass/fail.",
    eli12: "A testbench is a robot that presses the buttons on your circuit and checks every answer, so you do not have to stare at signals yourself.",
    tech: "Top-level module with no ports; clock generation; reset sequence; stimulus via initial blocks and tasks; checking with if comparisons or assertions; $display/$error; waveform dumping ($dumpfile/$dumpvars); $finish. Drive inputs away from active clock edges (or use clocking blocks later) to avoid races. Self-checking with expected values from a model.",
    inChip: "Unit tests for every block; DV environments grow from this.",
    breaks: "Testbenches that only print values and never fail; races between testbench and DUT; tests that never exercise corner cases.",
    tested: "A good testbench fails when you inject a bug. Always test your test.",
    prereqs: ["seq-modeling"],
    objectives: ["Generate clock and reset", "Drive stimulus with tasks", "Self-check outputs and report pass/fail"],
    terms: [["DUT", "Design under test"], ["Self-checking", "Testbench decides pass/fail automatically"], ["Stimulus", "Input patterns applied to the DUT"]],
    code: { lang: "verilog", src: "module tb;\n  reg clk = 0, rst = 1; wire [3:0] q;\n  counter dut(.clk(clk), .rst(rst), .q(q));\n  always #5 clk = ~clk;\n  initial begin\n    $dumpfile(\"dump.vcd\"); $dumpvars(0, tb);\n    repeat (2) @(posedge clk); rst = 0;\n    repeat (20) @(posedge clk);\n    if (q !== 4'd4) $error(\"expected 4, got %0d\", q); // 20 cycles wrap mod 16\n    else $display(\"PASS\");\n    $finish;\n  end\nendmodule" },
    mistakes: ["No automatic checking", "Changing inputs exactly at the clock edge"],
    practice: ["Make your ALU testbench self-checking against a table", "Inject a bug in the ALU and confirm the test fails"],
    interview: [{ q: "How do you know your testbench is good?", a: "It checks results automatically, covers corner cases, and fails when a bug is injected (mutation testing). Coverage metrics later make this measurable.", level: 2 }],
    resources: ["chipverify", "iverilog", "hdlbits"],
    projects: ["m-alu"],
  },
  {
    id: "waveform-debug", title: "Reading waveforms and debugging in simulation", phase: "p4", module: "m4b",
    priority: "must", depth: "working", difficulty: 2, days: 2, hours: 3, kind: "tool", skills: ["hdl", "verification"],
    why: "Debugging from waveforms is the core daily skill of RTL and DV engineers, and a common interview exercise.",
    problem: "A failing test tells you something is wrong, not what. Waveforms let you trace cause and effect back through time and hierarchy.",
    eli12: "A waveform viewer is a slow-motion replay of your circuit. You rewind to the moment it went wrong and follow the signals backwards to find who caused it.",
    tech: "Load VCD/FST in GTKWave or Surfer; add signals by hierarchy; group and color; use markers and cursors; search for value changes; show buses in hex; trace backwards from the first wrong value to its drivers; compare expected vs actual. X-propagation: find the first X. Save view files for repeatable debug sessions.",
    inChip: "Daily work in Verdi/SimVision/Visualizer in industry; same skills.",
    breaks: "Debugging from the symptom instead of the first divergence wastes hours.",
    tested: "Practice with bug-injected designs; interview waveform questions.",
    prereqs: ["testbench-basics"],
    objectives: ["Navigate hierarchy in a waveform viewer", "Find the first divergence", "Trace X values to their source"],
    terms: [["FST", "Compressed waveform format"], ["First divergence", "Earliest point where actual differs from expected"]],
    mistakes: ["Looking only at outputs", "Not saving waveform setups"],
    practice: ["Debug three injected bugs in a FIFO using only waveforms", "HDLBits: Bugs section and 'Sim/circuit' problems"],
    interview: [{ q: "A signal becomes X at time 500 ns. How do you debug it?", a: "Find its drivers, check which input was X at that time, and repeat backwards until the source (uninitialized register, missing reset, multiple drivers, or undriven input). Fix the root cause, not the symptom.", level: 2 }],
    resources: ["gtkwave", "surfer", "hdlbits"],
  },
  {
    id: "sim-semantics", title: "How simulators work: events, delta cycles and races", phase: "p4", module: "m4b",
    priority: "should", depth: "advanced", difficulty: 4, days: 1, hours: 3, kind: "theory", skills: ["hdl", "verification"],
    why: "Understanding the scheduler explains races, #0 hacks, and why clocking blocks exist. Senior engineers debug simulator-order issues quickly.",
    problem: "Many processes are triggered by the same event. The simulator must order them; where the language leaves order undefined, races appear.",
    eli12: "A simulator is a referee handling many players who all move at the same instant. It processes them one at a time in rounds. If two players depend on each other's move within the same round, the result depends on who goes first.",
    tech: "Event-driven simulation with time steps split into regions (active, inactive, NBA, observed, reactive in SystemVerilog). Delta cycles: zero-time iterations until signals settle. Races: testbench and DUT reading and writing the same signal at the same time. Cycle-based simulators like Verilator evaluate differently and may expose or hide races.",
    inChip: "Mixed-language simulation, testbench timing, and simulator performance tuning.",
    breaks: "Tests passing in one simulator and failing in another; flaky tests.",
    tested: "Running on multiple simulators; lint; clocking blocks and program blocks in SV.",
    prereqs: ["blocking-nonblocking", "testbench-basics"],
    objectives: ["Describe the main scheduling regions", "Explain delta cycles", "Recognize and fix testbench/DUT races"],
    terms: [["Delta cycle", "Zero-time evaluation step"], ["Scheduling region", "Ordered phase within a simulation time step"]],
    mistakes: ["Using #0 to 'fix' races"],
    practice: ["Write a deliberate race between testbench and DUT and fix it by driving on the opposite edge"],
    interview: [{ q: "What is a delta cycle?", a: "A zero-time simulation step. When an event triggers processes that change signals at the same time, the simulator iterates in delta cycles until no more changes occur before advancing time.", level: 3 }],
    resources: ["sunburst", "chipverify"],
  },
  {
    id: "verilator-lint", title: "Verilator, linting and fast simulation", phase: "p4", module: "m4b",
    priority: "should", depth: "working", difficulty: 2, days: 1, hours: 3, kind: "tool", skills: ["hdl", "cpp"],
    why: "Lint catches bugs before simulation. Verilator is the fastest open-source simulator and is used in real projects, CI and with cocotb.",
    problem: "Event-driven simulators are slow for large designs. Verilator compiles RTL into optimized C++ models, making long tests (like booting software on a CPU) practical.",
    eli12: "Lint is a spelling-and-grammar checker for hardware code. Verilator is a translator that turns your circuit into a very fast program.",
    tech: "verilator --lint-only -Wall for lint. Build models with a C++ or SystemVerilog testbench; trace to FST. Verilator is two-state by default and cycle-based, so X behaviour differs from four-state simulators. Recent versions support timing constructs and have growing UVM support (upstream UVM 2017 elaborates as of late 2025).",
    inChip: "Open-source core projects (Ibex, CVA6) use Verilator; industry uses it for fast software-driven tests and CI.",
    breaks: "Relying only on two-state simulation can hide reset and X bugs.",
    tested: "Lint in CI; cross-simulation with Icarus or a commercial simulator.",
    prereqs: ["testbench-basics"],
    objectives: ["Run Verilator lint with -Wall and fix warnings", "Build and run a Verilator simulation", "Explain two-state vs four-state implications"],
    terms: [["Lint", "Static analysis for coding problems"], ["Two-state", "Only 0 and 1; no X or Z"]],
    mistakes: ["Silencing warnings globally instead of fixing code"],
    practice: ["Lint all your Phase 4 code with -Wall and reach zero warnings or documented waivers"],
    interview: [{ q: "Why might a design pass in Verilator but fail in a four-state simulator?", a: "Verilator is two-state, so uninitialized registers become 0 or random instead of X. A four-state simulator shows X propagation from missing resets or undriven signals.", level: 3 }],
    resources: ["verilator", "verilator-docs", "verilator-uvm"],
  },
  {
    id: "sv-design", title: "SystemVerilog for design: logic, enums, structs, always_ff/always_comb", phase: "p4", module: "m4c",
    priority: "must", depth: "working", difficulty: 2, days: 2, hours: 5, kind: "coding", skills: ["hdl", "rtl"],
    why: "Most modern RTL is SystemVerilog. Its design features prevent whole classes of Verilog bugs.",
    problem: "Verilog's reg/wire split, weak typing and generic always blocks make intent unclear. SystemVerilog adds types and intent-specific blocks so tools can catch mistakes.",
    eli12: "SystemVerilog is Verilog with labels and safety rails. You can name states instead of using numbers, group related signals, and tell the tools 'this block must be a flop' so they complain if it is not.",
    tech: "logic replaces reg/wire in most places. typedef enum for FSM states (visible names in waveforms). packed structs and unions for buses and packets. always_ff, always_comb, always_latch declare intent; tools warn on mismatches. unique/priority case with checks. $bits, $clog2, streaming operators. Keep design code synthesizable.",
    inChip: "Industry RTL style guides (for example lowRISC) are SystemVerilog-based.",
    breaks: "Misusing unique case (claiming exclusivity that is not true) causes simulation warnings and synthesis optimizations that differ from intent.",
    tested: "Lint and simulation warnings; formal checks of unique/priority properties.",
    prereqs: ["latch-inference", "fsm"],
    objectives: ["Rewrite a Verilog FSM with enums and always_ff/always_comb", "Use packed structs for bus fields", "Apply unique and priority case correctly"],
    terms: [["logic", "Four-state variable type usable as wire or reg"], ["typedef enum", "Named set of values, ideal for states"], ["packed struct", "Struct laid out as a contiguous bit vector"]],
    code: { lang: "systemverilog", src: "typedef enum logic [1:0] {IDLE, BUSY, DONE} state_t;\nstate_t state, next;\n\nalways_ff @(posedge clk or negedge rst_n)\n  if (!rst_n) state <= IDLE;\n  else        state <= next;\n\nalways_comb begin\n  next = state;\n  unique case (state)\n    IDLE: if (start) next = BUSY;\n    BUSY: if (fin)   next = DONE;\n    DONE:            next = IDLE;\n  endcase\nend" },
    mistakes: ["Using always_comb but still leaving outputs unassigned", "unique case without full coverage"],
    practice: ["Convert your traffic-light FSM to SystemVerilog with enums", "Define a packed struct for a RISC-V R-type instruction and decode with it"],
    interview: [{ q: "What does always_comb add compared to always @(*)?", a: "It declares combinational intent (tools warn if a latch is inferred), is sensitive to all read signals including those in called functions, executes once at time zero, and disallows other processes writing the same variables.", level: 2 }],
    resources: ["lowrisc-style", "chipverify", "sv2v"],
  },
  {
    id: "sv-interfaces-packages", title: "Interfaces, modports and packages", phase: "p4", module: "m4c",
    priority: "should", depth: "working", difficulty: 2, days: 1, hours: 2, kind: "coding", skills: ["hdl"],
    why: "Interfaces bundle protocol signals and are the bridge between design and UVM testbenches (virtual interfaces).",
    problem: "Protocols like AXI have dozens of signals. Repeating them in every port list is error-prone. Interfaces group them; packages share types and constants across files.",
    eli12: "An interface is a cable with a standard plug: instead of connecting 30 separate wires, you plug in one cable. A package is a shared dictionary so every module uses the same words.",
    tech: "interface ... endinterface with modports defining direction per side; clocking blocks for testbench timing; packages for typedefs, parameters and functions, imported with import pkg::*. Some synthesis tools have limited interface support; many teams use interfaces mainly in verification and packed structs in design.",
    inChip: "UVM agents connect via virtual interfaces; shared packages define protocol types.",
    breaks: "Package compile-order issues; modport direction mistakes.",
    tested: "Compile and lint; protocol assertions placed inside interfaces.",
    prereqs: ["sv-design"],
    objectives: ["Create an interface with modports for a valid/ready channel", "Share types via a package", "Understand virtual interfaces conceptually"],
    terms: [["modport", "Direction view of an interface for one side"], ["Virtual interface", "Handle to an interface used by class-based testbenches"]],
    mistakes: ["Duplicating typedefs across files instead of a package"],
    practice: ["Write a valid/ready interface with producer and consumer modports and connect two modules"],
    interview: [{ q: "What is a modport?", a: "A named view of an interface that specifies signal directions for one side (for example master and slave), so connected modules get the correct input/output roles.", level: 1 }],
    resources: ["chipverify", "va-sv-oop"],
  },
  {
    id: "sv-oop", title: "Classes and OOP in SystemVerilog", phase: "p4", module: "m4d",
    priority: "must", depth: "working", difficulty: 2, days: 2, hours: 4, kind: "coding", skills: ["verification", "hdl"],
    why: "UVM is built on SystemVerilog classes. Your software OOP experience is a genuine advantage here.",
    problem: "Testbenches need reusable, extensible components and transaction objects. Classes provide encapsulation, inheritance and polymorphism for verification code.",
    eli12: "A class is a blueprint for objects, like a form template. A transaction class is a form describing one bus operation; you fill in many forms with different values to test the design.",
    tech: "Classes with properties and methods; constructors (new); handles (like object references); inheritance (extends), virtual methods and polymorphism; static members; shallow vs deep copy; parameterized classes; abstract (virtual) classes. Classes are dynamic and not synthesizable. Compare to JavaScript: handles resemble references; there is no garbage-collection concern in typical use; strong typing everywhere.",
    inChip: "Transactions, drivers, monitors, scoreboards in UVM testbenches.",
    breaks: "Shallow copies sharing handles, forgotten virtual keywords, null handle errors.",
    tested: "Runtime errors in simulation; unit tests of verification components.",
    prereqs: ["sv-interfaces-packages"],
    objectives: ["Write a transaction class with methods", "Use inheritance and virtual methods", "Explain handles and copying"],
    terms: [["Handle", "Reference to a class object"], ["Polymorphism", "Calling the derived-class method through a base handle"]],
    mistakes: ["Forgetting new() and dereferencing a null handle", "Missing virtual on methods meant to be overridden"],
    practice: ["Write base and derived packet classes with a virtual print()", "Demonstrate shallow vs deep copy bugs"],
    interview: [{ q: "What is the difference between a shallow and a deep copy in SystemVerilog?", a: "A shallow copy duplicates the object's properties but nested class handles still point to the same objects; a deep copy also duplicates nested objects so the copies are independent.", level: 2 }],
    resources: ["va-sv-oop", "chipverify", "spear-sv"],
  },
  {
    id: "sv-random", title: "Constrained randomization", phase: "p4", module: "m4d",
    priority: "must", depth: "working", difficulty: 3, days: 2, hours: 4, kind: "coding", skills: ["verification"],
    why: "Constrained-random stimulus finds bugs humans do not think of. It is the core of modern verification.",
    problem: "Directed tests cover only scenarios someone imagined. Fully random stimulus is mostly illegal. Constraints produce random but legal and interesting stimulus.",
    eli12: "Instead of writing each test question yourself, you give a machine rules ('numbers between 1 and 100, and every fifth one must be even') and it invents thousands of questions that follow the rules.",
    tech: "rand and randc properties; constraint blocks (ranges with inside, implications ->, if-else, dist weightings, solve before); randomize() with inline constraints (with {}); pre/post_randomize; seeds for reproducibility. Solvers pick values satisfying all constraints. Over-constraining causes randomization failures; check the return value.",
    inChip: "Every UVM sequence item; stimulus for protocol and datapath tests.",
    breaks: "Constraints too tight (missing scenarios) or conflicting (failures); unseeded runs that cannot be reproduced.",
    tested: "Functional coverage shows whether randomization reaches the intended space.",
    prereqs: ["sv-oop"],
    objectives: ["Write constraints with ranges, implications and distributions", "Use inline constraints", "Reproduce failures with seeds"],
    terms: [["randc", "Random-cyclic: cycles through all values before repeating"], ["dist", "Weighted distribution constraint"], ["Seed", "Starting value making random runs reproducible"]],
    code: { lang: "systemverilog", src: "class bus_txn;\n  rand bit [31:0] addr;\n  rand bit [7:0]  len;\n  rand bit        write;\n  constraint c_align { addr[1:0] == 2'b00; }\n  constraint c_len   { len inside {[1:16]}; len dist {1 := 40, [2:16] :/ 60}; }\n  constraint c_space { addr inside {[32'h1000:32'h1FFF]}; }\nendclass" },
    mistakes: ["Not checking randomize() return value", "Using dist without understanding := vs :/"],
    practice: ["Write constraints for legal AXI burst lengths and aligned addresses", "Force a constraint conflict and read the solver error"],
    interview: [{ q: "What is the difference between rand and randc?", a: "rand picks values independently each time (repeats allowed); randc cycles through all possible values in random order before repeating, useful for covering small spaces.", level: 1 }],
    resources: ["chipverify", "spear-sv", "verilator-uvm"],
  },
  {
    id: "sv-concurrency", title: "Processes, fork/join, mailboxes and events", phase: "p4", module: "m4d",
    priority: "should", depth: "working", difficulty: 3, days: 1, hours: 3, kind: "coding", skills: ["verification"],
    why: "Testbench components run in parallel (drivers, monitors, scoreboards). Coordinating them is essential and similar to async programming you know.",
    problem: "A testbench must drive and observe several interfaces at once and pass transactions between components safely.",
    eli12: "Testbench components are like coworkers in different rooms. fork starts several of them working at once, mailboxes are the trays where they pass notes, and events are doorbells saying 'I'm done'.",
    tech: "fork...join (wait all), join_any (wait first), join_none (do not wait); disable fork; mailbox #(T) for typed FIFOs between processes (put/get blocking, try_get non-blocking); semaphores for shared resources; events (->, @, wait triggered). JavaScript analogy: join is Promise.all, join_any is Promise.race, but SystemVerilog processes run in simulation time, not an event loop over I/O.",
    inChip: "Non-UVM testbenches directly; inside UVM these are wrapped by TLM ports and phases.",
    breaks: "Processes left running after a test, deadlocks on mailboxes, race-y event triggers.",
    tested: "Timeouts and end-of-test checks; watchdogs.",
    prereqs: ["sv-oop"],
    objectives: ["Use fork/join variants correctly", "Pass transactions with mailboxes", "Add a watchdog timeout"],
    terms: [["mailbox", "Thread-safe FIFO between processes"], ["join_none", "Start processes and continue immediately"]],
    mistakes: ["Forgetting disable fork after join_any", "Missing timeouts, so a hang wastes a regression slot"],
    practice: ["Build a generator-driver-monitor-scoreboard testbench for a FIFO using mailboxes (no UVM)"],
    interview: [{ q: "Explain fork...join_any and a common pitfall.", a: "It resumes when any child process finishes; the others keep running. Pitfall: forgetting to disable remaining processes, which then interfere with later test phases.", level: 2 }],
    resources: ["chipverify", "spear-sv"],
  },
  {
    id: "rtl-hw-mapping", title: "RTL-to-hardware mapping: predict the circuit before synthesis", phase: "p4", module: "m4a",
    priority: "must", depth: "working", difficulty: 3, days: 2, hours: 5, kind: "coding", skills: ["hdl", "rtl"],
    why: "Interviewers show code and ask what hardware it becomes, and RTL designers must predict area and timing from code. The ChipCamp VLSI roadmap recommends keeping a table that maps each Verilog construct to its hardware.",
    problem: "Writing Verilog like software produces surprise latches, long priority chains, oversized muxes, multiple drivers and silent width truncation that only show up after synthesis, or in silicon.",
    eli12: "Every line of Verilog is an order to a factory. 'case' orders a selector switch, 'if/else' orders a queue where the first in line wins, and '+' orders an adding machine. Good designers can picture the machines before the factory builds them.",
    analogyLimit: "Synthesis tools optimise aggressively, so the final gates may be restructured; the prediction is about the kind and rough size of hardware, not exact gates.",
    tech: "Common mappings: assign with ?: and a full case -> multiplexer; if/else-if chains -> priority multiplexer chain (first true condition wins); casez or a loop that finds the first set bit -> priority encoder; ==, <, > -> comparators; + and - -> adders (architecture chosen by synthesis for timing); * -> multiplier array; always_ff with non-blocking assignments -> flip-flops, with enable -> a feedback mux or clock-gating cell, with async or sync reset -> different flop types; shifting registers -> shift register; FSM with a state register -> extracted state machine; arrays read and written synchronously -> RAM inference on FPGAs or flop arrays/SRAM macros on ASICs; constant tables -> ROM or logic; for loops unroll into parallel hardware; generate replicates instances. Hazards: an output not assigned on every path in combinational logic -> latch; two always blocks driving one signal -> multiple drivers; assigning a wider result to a narrower signal -> silent truncation; mixing signed and unsigned -> unsigned extension; combinational feedback -> loops. Workflow: RTL -> predict -> simulate -> synthesize (Yosys synth; stat; show) -> inspect -> compare -> explain.",
    inChip: "Every RTL review includes 'what does this infer?'; synthesis logs and lint reports are read for latches, multiple drivers, width mismatches and loops.",
    breaks: "Unexpected latches break timing and DFT, deep priority chains fail timing, truncation corrupts arithmetic, multiple drivers become X in simulation and errors in synthesis.",
    tested: "Yosys stat/show compared with predictions; Verilator lint warnings (WIDTH, LATCH, MULTIDRIVEN, UNOPTFLAT); self-checking testbenches.",
    prereqs: ["latch-inference", "hierarchy-generate", "seq-modeling"],
    objectives: ["Predict the hardware for twelve common constructs", "Explain case versus if/else in hardware terms", "Recognise latch, multiple-driver, truncation, signedness and loop hazards from code", "Use Yosys to confirm predictions"],
    terms: [["Priority encoder", "Outputs the index of the highest-priority active input"], ["Inference", "Synthesis deducing hardware from code patterns"], ["Multiple drivers", "Two processes assigning the same signal"], ["Width truncation", "Upper bits silently dropped on assignment"]],
    code: { lang: "verilog", src: `// Same function, different hardware
always @(*) begin               // parallel mux: select is one-hot or fully decoded
  case (sel)
    2'd0: y = a;  2'd1: y = b;  2'd2: y = c;  default: y = d;
  endcase
end

always @(*) begin               // priority chain: req[0] wins over req[1] over req[2]
  if (req[0])      g = 3'b001;
  else if (req[1]) g = 3'b010;
  else if (req[2]) g = 3'b100;
  else             g = 3'b000;   // default assignment: no latch
end`, note: "Synthesize both with Yosys and compare the structure shown by 'show'." },
    mistakes: ["Assuming if/else and case always produce the same hardware", "Ignoring WIDTH warnings", "Using loops as if they run sequentially in time"],
    practice: ["Build the construct-to-hardware table for twelve constructs and verify each with Yosys (micro project m-rtl-map)", "Write three snippets with hidden hazards (latch, truncation, multiple drivers) and find them from lint output alone"],
    interview: [
      { q: "What hardware does an if/else-if chain infer, and when would you prefer a case statement?", a: "A priority multiplexer chain in which earlier conditions win; its delay grows with the number of conditions. Prefer case (or unique/parallel case in SystemVerilog) when conditions are mutually exclusive, which gives a balanced mux.", level: 2, trap: "Saying they are always identical after synthesis." },
      { q: "What does a for loop in synthesizable RTL become?", a: "The loop is unrolled at elaboration into parallel copies of the logic; it describes structure, not steps in time. Its bound must be a constant.", level: 2 },
    ],
    resources: ["nptel-verilog", "palnitkar-verilog", "chipcamp-vlsi", "yosys", "hdlbits"], projects: ["m-rtl-map", "m-crc-rtl"],
  },
];
