import type { Topic } from "../schema.ts";

export const P5: Topic[] = [
  {
    id: "rtl-guidelines", title: "Synthesizable RTL: coding guidelines that matter", phase: "p5", module: "m5a",
    priority: "must", depth: "working", difficulty: 2, days: 2, hours: 4, kind: "coding", skills: ["rtl"],
    why: "Teams use style guides so RTL is readable, lint-clean, synthesizable and reviewable. Following one shows professional habits in your portfolio.",
    problem: "Legal Verilog can still be bad RTL: ambiguous intent, simulation/synthesis mismatches, untestable structures. Guidelines encode decades of failure lessons.",
    eli12: "Style rules are like traffic rules. You could drive however you want, but rules make everyone predictable, so fewer crashes happen.",
    tech: "Key rules: one clock per always_ff; non-blocking in sequential, blocking in combinational; defaults in always_comb; no latches unless intended; explicit widths; named port connections; no initial blocks in design; avoid tri-states internally; synchronous design with clean reset strategy; meaningful naming (_q/_d or _r/_nxt suffixes, _n for active-low); parameterize; comment intent, not syntax. Pass lint and CDC checks.",
    inChip: "Code reviews and sign-off checklists enforce guidelines before RTL freeze.",
    breaks: "Mismatches between simulation and silicon; unmaintainable IP; lint failures blocking integration.",
    tested: "Lint (Verilator, commercial tools like SpyGlass), code review, synthesis checks.",
    prereqs: ["sv-design", "blocking-nonblocking"],
    objectives: ["Adopt a published style guide", "Refactor a messy module to guideline-clean code", "Run lint as part of your Makefile"],
    terms: [["RTL freeze", "Point after which RTL changes need approval"], ["Lint waiver", "Documented exception to a lint rule"]],
    mistakes: ["Inconsistent naming for registered vs next-state signals", "Initial blocks in synthesizable code"],
    practice: ["Refactor your ALU and FSM code to the lowRISC style guide", "Add a 'make lint' target and fix all warnings"],
    interview: [{ q: "What makes RTL 'good' beyond functional correctness?", a: "Readable and consistent, lint-clean, synthesizable without surprises, timing-aware (reasonable logic depth), testable (resets, scan-friendly), parameterized where useful, and documented intent.", level: 2 }],
    resources: ["lowrisc-style", "sunburst", "verilator"],
  },
  {
    id: "datapath-control", title: "Datapath and control partitioning", phase: "p5", module: "m5a",
    priority: "must", depth: "working", difficulty: 3, days: 2, hours: 4, kind: "coding", skills: ["rtl"],
    why: "Separating what moves data from what decides is how complex blocks stay understandable and verifiable.",
    problem: "Mixing control decisions into datapath code makes designs hard to change and debug. Partitioning isolates concerns: the datapath is regular and wide; control is narrow and sequential.",
    eli12: "A factory has conveyor belts and machines (datapath) and a supervisor with a clipboard deciding what each machine does next (control).",
    tech: "Datapath: registers, muxes, arithmetic, memories. Control: FSMs or microcode generating select, enable and load signals, reacting to status (zero, full, done). Document the control signals in a table. Examples: multiplier (shift-add datapath + counter control), GCD engine, DMA.",
    inChip: "Every block from CPUs to DMA engines. Microarchitecture documents describe both parts.",
    breaks: "Control and data getting out of step by a cycle (off-by-one pipeline alignment).",
    tested: "Unit tests for datapath, FSM coverage for control, integration tests.",
    prereqs: ["rtl-guidelines", "fsm"],
    objectives: ["Split a design into datapath and control", "Write a control-signal table", "Implement a multi-cycle algorithm (for example GCD)"],
    terms: [["Status signal", "Datapath output informing control (zero, overflow)"], ["Control word", "Set of control signals for one cycle"]],
    mistakes: ["Letting control logic grow inside datapath always blocks"],
    practice: ["Design a GCD engine with separate datapath and FSM; verify against a Python model"],
    interview: [{ q: "Design a sequential multiplier. What goes in the datapath and what in control?", a: "Datapath: multiplicand, multiplier and product registers, adder, shifters. Control: counter and FSM deciding add/shift each cycle and asserting done. Discuss latency (N cycles) vs a combinational array multiplier's area.", level: 2 }],
    resources: ["harris-harris"],
  },
  {
    id: "fsm-rtl", title: "FSM coding styles in RTL", phase: "p5", module: "m5a",
    priority: "must", depth: "working", difficulty: 2, days: 1, hours: 2, kind: "coding", skills: ["rtl"],
    why: "FSM style affects glitch behaviour, timing and readability. Interviewers often ask you to code an FSM live.",
    problem: "There are one-, two- and three-process FSM styles, with registered or combinational outputs. The choice affects correctness and timing.",
    eli12: "Writing an FSM is like writing a board-game rulebook. One style puts all rules in one paragraph; another separates 'where do I move next' from 'what do I say out loud'.",
    tech: "Two-process: always_ff for state, always_comb for next state and outputs. Three-process: separate output logic, optionally registered outputs for glitch-free timing. Use enums, a default next = state, and handle all states. Registered outputs add a cycle of latency but cut combinational paths out of the FSM.",
    inChip: "Protocol controllers where outputs drive other blocks directly.",
    breaks: "Mealy outputs creating long combinational paths through multiple blocks; missing defaults.",
    tested: "State/transition coverage; assertions on illegal transitions.",
    prereqs: ["sv-design", "fsm"],
    objectives: ["Write two- and three-process FSMs", "Register outputs when needed", "Explain the latency tradeoff"],
    terms: [["Registered output", "Output taken from a flop, glitch-free"]],
    mistakes: ["Outputs computed from next-state without care, creating timing loops"],
    practice: ["Implement the same FSM in two- and three-process styles and compare synthesized logic"],
    interview: [{ q: "Why might you register FSM outputs?", a: "To remove glitches and break long combinational paths between blocks, improving timing and making interfaces clean. The cost is one cycle of output latency.", level: 2 }],
    resources: ["sunburst", "lowrisc-style"],
  },
  {
    id: "valid-ready", title: "Valid/ready handshakes and backpressure", phase: "p5", module: "m5a",
    priority: "must", depth: "advanced", difficulty: 3, days: 2, hours: 5, kind: "coding", skills: ["rtl", "protocols"],
    why: "Valid/ready is the universal flow-control pattern (AXI channels, streams, accelerators). Getting it right is a hallmark of a good RTL designer.",
    problem: "Producers and consumers run at different rates. Without flow control, data is lost or duplicated. Valid/ready lets the consumer apply backpressure safely.",
    eli12: "A waiter (producer) holds up a plate (valid). The table (consumer) says 'I have space' (ready). The plate is handed over only when both are true at the same tick.",
    tech: "Transfer occurs when valid && ready at a clock edge. Rules (AXI-style): once valid is asserted, data must stay stable until accepted; valid must not depend combinationally on ready (to avoid loops); ready may depend on valid. Pipeline stages with backpressure need skid buffers to register ready without losing data. Throughput: 100% when both are high every cycle.",
    inChip: "AXI channels, AXI-Stream, NoCs, accelerator pipelines.",
    breaks: "Data changing while valid is high, combinational ready/valid loops, lost beats when ready is registered naively.",
    tested: "Protocol assertions (stability, no-drop), random backpressure tests, formal proofs.",
    prereqs: ["rtl-guidelines"],
    objectives: ["State the handshake rules", "Build a registered pipeline stage with backpressure", "Build a skid buffer"],
    terms: [["Backpressure", "Consumer slowing the producer"], ["Skid buffer", "Two-entry buffer allowing registered ready without data loss"], ["Beat", "One transfer on a channel"]],
    visuals: [{ title: "Handshake timing", art: "clk    _|‾|_|‾|_|‾|_|‾|_|‾|_\nvalid  ___|‾‾‾‾‾‾‾‾‾‾‾|______\nready  _______|‾‾‾‾‾‾‾‾‾‾‾|__\ndata   ===<  A  >=<B>======\n                 ^ A transfers here (valid & ready)" }],
    code: { lang: "systemverilog", src: "// SVA: data must hold while valid && !ready\nproperty p_stable;\n  @(posedge clk) disable iff (!rst_n)\n    valid && !ready |=> valid && $stable(data);\nendproperty\nassert property (p_stable);" },
    mistakes: ["Deasserting valid before the transfer", "Making valid depend on ready"],
    senior: ["Where do you register ready vs valid to close timing across a long pipeline?", "How do you guarantee no deadlock when two handshakes depend on each other?"],
    practice: ["Build a pipeline stage and a skid buffer; test with random valid and ready patterns and a scoreboard"],
    interview: [{ q: "Why shouldn't valid depend combinationally on ready?", a: "It can create a combinational loop between producer and consumer (ready depending on valid and vice versa) and deadlock. AXI requires the source not to wait for ready before asserting valid.", level: 3 }],
    resources: ["amba", "zipcpu"],
  },
  {
    id: "pipelined-rtl", title: "Pipelined RTL, stalls and retiming", phase: "p5", module: "m5a",
    priority: "must", depth: "advanced", difficulty: 4, days: 2, hours: 5, kind: "coding", skills: ["rtl", "timing"],
    why: "Meeting frequency targets usually means pipelining. Doing it with correct stall and flush behaviour is a senior-level skill.",
    problem: "Long combinational paths fail timing. Adding registers splits them but requires every related signal (valid bits, control) to move in lockstep, and stalls must freeze stages safely.",
    eli12: "Pipelining a factory line means adding stations. Every box must carry its label to the next station, and if the end of the line is blocked, stations must hold their boxes instead of dropping them.",
    tech: "Each stage carries data plus a valid bit (and control). Stall: hold stage registers when downstream is not ready (global stall or per-stage handshakes). Flush: clear valid bits. Retiming moves registers across logic to balance stage delays (synthesis can retime in some flows). Latency increases; throughput can reach one result per cycle.",
    inChip: "CPU pipelines, MAC arrays, video/DSP datapaths.",
    breaks: "Misaligned control and data, bubbles counted as valid data, stalls that drop data.",
    tested: "Random stall injection with scoreboards; latency assertions.",
    prereqs: ["valid-ready", "critical-path"],
    objectives: ["Pipeline a datapath with valid bits", "Implement stall and flush", "Explain retiming"],
    terms: [["Bubble", "Empty pipeline slot (valid = 0)"], ["Retiming", "Moving registers to balance logic delay"]],
    mistakes: ["Forgetting to stall the valid bits with the data", "Resetting data registers but not valid registers"],
    practice: ["Pipeline a 4-tap FIR filter into 2 stages with backpressure; verify with random stalls"],
    interview: [{ q: "How do you add a pipeline stage to a design with backpressure without losing data?", a: "Carry valid with data, stall the stage when downstream ready is low, and either propagate ready combinationally (timing risk) or use a skid buffer to register ready.", level: 3 }],
    resources: ["zipcpu", "harris-harris"],
  },
  {
    id: "sync-fifo", title: "Synchronous FIFO", phase: "p5", module: "m5b",
    priority: "must", depth: "advanced", difficulty: 3, days: 2, hours: 5, kind: "coding", skills: ["rtl", "verification"],
    why: "FIFOs are the most common buffering structure in SoCs and the most common RTL interview design.",
    problem: "Producers and consumers burst at different times. A FIFO absorbs rate differences while preserving order.",
    eli12: "A FIFO is a queue at a ticket counter: people join at the back and leave from the front, in order. If the queue is full, nobody else can join; if empty, nobody leaves.",
    tech: "Memory array plus read and write pointers. Full/empty detection: count register, or pointers with an extra wrap bit (full when MSBs differ and the rest match). Options: registered vs combinational read data (first-word fall-through), almost-full/empty thresholds, simultaneous read and write. Depth sizing from burst analysis.",
    inChip: "Between pipeline stages, bus interfaces, DMA, network-on-chip routers.",
    breaks: "Off-by-one full/empty, writing when full, reading when empty, wrong behaviour on simultaneous read/write at boundaries.",
    tested: "Scoreboard against a queue model, assertions (no overflow/underflow), coverage of full/empty and simultaneous operations.",
    prereqs: ["valid-ready", "memories-rtl"],
    objectives: ["Implement a parameterized FIFO", "Derive full/empty logic with a wrap bit", "Size FIFO depth for a burst scenario"],
    terms: [["FWFT", "First-word fall-through: data visible before the read strobe"], ["Almost full", "Early warning threshold"]],
    visuals: [{ title: "Pointers with a wrap bit (depth 4)", art: "wptr = 1_01, rptr = 0_01  -> MSBs differ, rest equal -> FULL\nwptr = 0_10, rptr = 0_10  -> identical              -> EMPTY" }],
    mistakes: ["Using depth-1 comparisons that waste one entry", "Not defining behaviour for write-when-full"],
    senior: ["Sync FIFO vs async FIFO: when do you need each?", "How does depth affect area and power, and how do you size it from traffic?", "What happens under backpressure and during reset?", "Which assertions prove no data loss?"],
    ladder: { beginner: "A queue in hardware.", junior: "Implement it with pointers, full/empty and a testbench.", mid: "Debug boundary conditions and prove no-overflow with assertions and coverage.", senior: "Size depth from traffic models, choose FWFT vs registered output for timing, trade flops vs SRAM macros for area.", research: "Explore elastic buffers and latency-insensitive design." },
    practice: ["Write a FIFO with a Python model-based testbench and full coverage of full/empty transitions", "Compute the minimum depth for a 64-word burst written at 100 MHz and read at 80 MHz"],
    interview: [{ q: "Design a synchronous FIFO. How do you detect full and empty?", a: "Use N+1-bit pointers for depth 2^N: empty when pointers are equal; full when MSBs differ and the lower bits are equal. Alternatively keep an occupancy counter. Discuss simultaneous read/write and registered outputs.", level: 2 }],
    resources: ["sunburst", "chipverify", "zipcpu"],
    projects: ["m-sync-fifo"],
  },
  {
    id: "arbiters", title: "Arbiters: fixed priority and round robin", phase: "p5", module: "m5b",
    priority: "must", depth: "working", difficulty: 3, days: 1, hours: 3, kind: "coding", skills: ["rtl"],
    why: "Shared resources (buses, memories, crossbar outputs) need arbiters. Fairness and starvation are classic interview and design review topics.",
    problem: "Several requesters want one resource. Fixed priority is simple but can starve low-priority requesters; round-robin guarantees fairness.",
    eli12: "Several kids want the one swing. Fixed priority always lets the oldest go first, so the youngest might never swing. Round-robin takes turns in a circle.",
    tech: "Fixed priority: priority encoder. Round-robin: rotate priority after each grant (mask-based or double-width priority encoder trick). Grants are one-hot. Variants: weighted round-robin, lock/hold for multi-beat transfers. Timing concerns for many requesters.",
    inChip: "Bus interconnects, memory controllers, NoC routers, interrupt controllers.",
    breaks: "Starvation, multiple grants, grant changing mid-transaction.",
    tested: "Assertions: one-hot grants, no grant without request, bounded waiting (fairness).",
    prereqs: ["mux-decoder", "fsm-rtl"],
    objectives: ["Implement fixed-priority and round-robin arbiters", "Write fairness assertions", "Explain starvation"],
    terms: [["Starvation", "A requester never gets granted"], ["One-hot grant", "Exactly one requester is granted"]],
    mistakes: ["Rotating priority even when no grant occurred", "Allowing a grant to switch during a burst"],
    practice: ["Build a 4-way round-robin arbiter and prove one-hot grants with SVA or formal"],
    interview: [{ q: "Design a round-robin arbiter.", a: "Keep a pointer to the last granted requester; mask requests at or below it and pick the lowest set bit of the masked requests, falling back to unmasked requests. Update the pointer on grant. Mention one-hot grant assertions and fairness.", level: 3 }],
    resources: ["chipverify"],
  },
  {
    id: "memories-rtl", title: "Memories in RTL: inference, register files and SRAM macros", phase: "p5", module: "m5b",
    priority: "should", depth: "working", difficulty: 2, days: 1, hours: 2, kind: "coding", skills: ["rtl"],
    why: "Large storage cannot be flops. Coding memories so tools infer block RAM or connect macros correctly matters for area and timing.",
    problem: "Arrays of registers explode area. FPGAs provide block RAMs and ASIC flows provide SRAM macros from memory compilers; RTL must match their templates and timing.",
    eli12: "Small notes fit on sticky pads (flops). A big stack of notes goes in a filing cabinet (SRAM). You must use the cabinet's rules: one drawer at a time, and it takes a moment to open.",
    tech: "Synchronous-read RAM templates infer block RAM; asynchronous read infers LUT RAM or flops. ASIC SRAM macros are instantiated as black boxes with behavioural models. Read-during-write behaviour (old data, new data, undefined). Register files may be flops or custom macros. Consider byte enables and ECC.",
    inChip: "Caches, FIFOs, buffers in accelerators.",
    breaks: "Asynchronous reads preventing RAM inference; mismatched read-latency assumptions.",
    tested: "Memory models in simulation; MBIST in silicon; equivalence checks with black boxes.",
    prereqs: ["memory-basics", "rtl-guidelines"],
    objectives: ["Write inferable RAM templates", "Handle read latency in control logic", "Explain read-during-write modes"],
    terms: [["Block RAM", "Dedicated FPGA memory"], ["Memory compiler", "Tool generating SRAM macros"]],
    mistakes: ["Resetting memory arrays (prevents RAM inference)"],
    practice: ["Write a dual-port RAM template and check Yosys infers memory, not flops"],
    interview: [{ q: "What is read-during-write behaviour?", a: "What a memory returns when reading an address being written in the same cycle: old data, new data, or undefined. Designs must follow the macro's spec or add bypass logic.", level: 2 }],
    resources: ["yosys", "chipverify"],
  },
  {
    id: "fixed-point", title: "Fixed-point arithmetic and multipliers", phase: "p5", module: "m5b",
    priority: "should", depth: "working", difficulty: 3, days: 2, hours: 4, kind: "coding", skills: ["rtl", "aihw"],
    why: "DSP and AI accelerators run on fixed-point and integer math. Quantization and MAC design depend on it.",
    problem: "Floating-point hardware is large and power-hungry. Fixed-point represents fractions with integers and an implied binary point, trading range for efficiency.",
    eli12: "Fixed-point is like pricing everything in paise instead of rupees: all whole numbers, and you just remember that 100 means one rupee.",
    tech: "Qm.n format; multiplication doubles widths (Qa.b x Qc.d = Q(a+c).(b+d)); rounding modes; saturation vs wrap; accumulators need guard bits. Multipliers: array, Booth, Wallace/Dadda trees; pipelined multipliers; DSP blocks in FPGAs.",
    inChip: "Filters, image pipelines, MAC arrays, audio codecs.",
    breaks: "Overflow wrap-around producing huge errors; truncation bias; mismatched binary points between blocks.",
    tested: "Bit-accurate Python models (NumPy), error statistics vs floating-point reference.",
    prereqs: ["adders", "python-hw"],
    objectives: ["Multiply and scale Q-format numbers", "Implement rounding and saturation", "Compare multiplier architectures"],
    terms: [["Q format", "Notation for integer and fraction bits"], ["Saturation", "Clamping to max/min instead of wrapping"], ["Guard bits", "Extra accumulator bits preventing overflow"]],
    mistakes: ["Forgetting to realign binary points after multiply", "No overflow handling in accumulators"],
    practice: ["Implement a Q1.15 multiply with rounding and saturation and compare to NumPy"],
    interview: [{ q: "How many bits does an accumulator need to sum 256 products of two 8-bit signed numbers?", a: "Each product needs 16 bits; summing 256 terms adds log2(256) = 8 guard bits, so 24 bits avoids overflow.", level: 3 }],
    resources: ["harris-harris"],
  },
  {
    id: "uart", title: "UART", phase: "p5", module: "m5c",
    priority: "must", depth: "working", difficulty: 2, days: 2, hours: 5, kind: "coding", skills: ["rtl", "protocols"],
    why: "UART is the simplest real protocol: FSMs, baud timing, oversampling and a synchronizer in one small design. It is also how FPGA projects talk to your PC.",
    problem: "Devices need a simple serial link with no shared clock. UART frames each byte with start and stop bits and relies on both sides agreeing on the baud rate.",
    eli12: "UART is like two people tapping Morse-like signals at an agreed speed. A start tap says 'listen now', then eight data taps, then a stop tap.",
    tech: "Frame: idle high, start bit (0), 8 data bits LSB first, optional parity, stop bit(s). TX: baud tick generator plus shift register FSM. RX: synchronize input, detect start edge, sample mid-bit using 16x oversampling, check stop bit, flag framing errors.",
    inChip: "Debug consoles, microcontrollers, bring-up interfaces.",
    breaks: "Sampling at bit edges instead of centre; unsynchronized RX input; baud mismatch.",
    tested: "Loopback tests, random bytes with baud jitter, framing error injection.",
    prereqs: ["fsm-rtl", "metastability"],
    objectives: ["Implement UART TX and RX", "Use oversampling for mid-bit sampling", "Detect framing errors"],
    terms: [["Baud rate", "Symbols per second"], ["Oversampling", "Sampling faster than the bit rate to find bit centres"], ["Framing error", "Stop bit not detected where expected"]],
    mistakes: ["Forgetting the RX synchronizer", "Counting baud ticks off by one"],
    practice: ["Build UART loopback and test 1,000 random bytes", "Run it on an FPGA or in simulation with a 2% baud mismatch"],
    interview: [{ q: "Why do UART receivers oversample?", a: "There is no shared clock, so the receiver must find the bit centres. Oversampling (for example 16x) lets it detect the start edge and sample in the middle of each bit, tolerating small baud mismatch.", level: 1 }],
    resources: ["nandland", "chipverify"],
    projects: ["m-uart"],
  },
  {
    id: "spi-i2c", title: "SPI and I2C", phase: "p5", module: "m5c",
    priority: "should", depth: "working", difficulty: 2, days: 1, hours: 3, kind: "coding", skills: ["protocols", "rtl"],
    why: "SPI and I2C connect sensors, flash and peripherals. They appear in RTL job descriptions for peripheral IP.",
    problem: "Chips need cheap, few-wire links to peripherals. SPI trades wires for speed; I2C uses two shared wires with addressing.",
    eli12: "SPI is a teacher tapping a rhythm while talking to one student at a time (chip select). I2C is a classroom where everyone shares one line and must say the student's name first.",
    tech: "SPI: SCLK, MOSI, MISO, CS_n; modes 0-3 (CPOL/CPHA); full duplex; no acknowledgement. I2C: SDA, SCL open-drain with pull-ups; start/stop conditions; 7-bit addressing; ACK/NACK; clock stretching; multi-master arbitration.",
    inChip: "Flash boot interfaces (SPI), sensor hubs and PMICs (I2C).",
    breaks: "Wrong SPI mode, I2C timing violations, missing handling of clock stretching.",
    tested: "Protocol checkers, model devices in the testbench (flash or sensor models).",
    prereqs: ["uart"],
    objectives: ["Implement an SPI master for mode 0", "Describe I2C start/stop, addressing and ACK", "Compare SPI and I2C tradeoffs"],
    terms: [["CPOL/CPHA", "SPI clock polarity and phase"], ["Open-drain", "Output can only pull low; pull-up provides high"], ["Clock stretching", "I2C slave holding SCL low to pause"]],
    mistakes: ["Sampling on the wrong SPI edge"],
    practice: ["Implement an SPI master and verify against a simple SPI slave model"],
    interview: [{ q: "Compare SPI and I2C.", a: "SPI: faster, full duplex, separate chip select per device, no ack, simple. I2C: two wires shared by many devices, addressing and ack, slower, open-drain with pull-ups, supports multi-master.", level: 1 }],
    resources: ["chipverify", "nandland"],
  },
  {
    id: "apb", title: "AMBA APB", phase: "p5", module: "m5c",
    priority: "must", depth: "working", difficulty: 2, days: 2, hours: 4, kind: "coding", skills: ["protocols", "rtl"],
    why: "APB is how peripheral registers are accessed in most Arm-style SoCs. It is the ideal first bus protocol to implement and verify.",
    problem: "Peripherals need a simple, low-power register interface. APB uses a two-phase (setup/access) protocol without pipelining or bursts.",
    eli12: "APB is a polite doorbell protocol: first you announce which door and whether you are dropping off or picking up (setup), then you do it (access), and the door can say 'wait a moment' (PREADY).",
    tech: "Signals: PCLK, PRESETn, PADDR, PSEL, PENABLE, PWRITE, PWDATA, PRDATA, PREADY, PSLVERR (APB4 adds PPROT, PSTRB). Setup phase: PSEL=1, PENABLE=0. Access phase: PENABLE=1, transfer completes when PREADY=1. A register block decodes PADDR and implements access types.",
    inChip: "Timers, UARTs, GPIO, configuration registers of accelerators.",
    breaks: "Responding in setup phase, ignoring PREADY, wrong error handling for unmapped addresses.",
    tested: "Protocol assertions, register tests (reset values, RW/RO/W1C), randomized access sequences.",
    prereqs: ["io-interrupts", "fsm-rtl"],
    objectives: ["Implement an APB register block", "Write APB protocol assertions", "Test register access types"],
    terms: [["PSEL", "Selects the target peripheral"], ["PENABLE", "Marks the access phase"], ["PSLVERR", "Error response"]],
    visuals: [{ title: "APB write with one wait state", art: "PCLK    _|‾|_|‾|_|‾|_|‾|_\nPSEL    ___|‾‾‾‾‾‾‾‾‾‾‾|__\nPENABLE _______|‾‾‾‾‾‾‾|__\nPREADY  ___________|‾‾‾|__\n        setup  access  done" }],
    mistakes: ["Treating PENABLE as the start of the transfer"],
    practice: ["Build an APB timer peripheral with a register map and test all access types"],
    interview: [{ q: "Describe an APB write transfer.", a: "Setup phase: PSEL high, PENABLE low, address, data and PWRITE valid. Access phase: PENABLE high; the transfer completes on the clock edge where PREADY is high. Signals stay stable until then.", level: 1 }],
    resources: ["amba", "chipverify"],
    projects: ["fp-axi-apb"],
  },
  {
    id: "axi", title: "AMBA AXI4 and AXI4-Lite", phase: "p5", module: "m5c",
    priority: "must", depth: "advanced", difficulty: 4, days: 3, hours: 7, kind: "coding", skills: ["protocols", "rtl", "verification"],
    why: "AXI is the dominant on-chip interconnect protocol. It appears in most RTL and DV job descriptions for SoC work.",
    problem: "High-performance systems need to overlap many transactions, burst data and keep reads and writes independent. AXI uses five independent channels with valid/ready handshakes.",
    eli12: "AXI is a restaurant with five separate counters: one to order food (read address), one to receive it (read data), one to order a delivery drop-off (write address), one to hand over the goods (write data), and one to get a receipt (write response). Counters work independently, so many orders can be in flight.",
    tech: "Channels: AW, W, B (write), AR, R (read). Each uses valid/ready. Bursts (INCR, WRAP, FIXED) with AxLEN/AxSIZE; 4 KB boundary rule; IDs allow outstanding and out-of-order responses across IDs; WSTRB byte strobes; RLAST/WLAST; responses OKAY, SLVERR, DECERR. AXI4-Lite: single beats, no IDs or bursts, for registers. Dependencies: write response only after both address and last data are accepted.",
    inChip: "CPU-memory paths, DMA, accelerators, interconnects; verification IP for AXI is standard in DV teams.",
    breaks: "Handshake dependency violations causing deadlock, bursts crossing 4 KB, wrong WSTRB handling, ID ordering bugs.",
    tested: "Protocol assertion checkers, VIP (for example cocotbext-axi in open source), randomized traffic with scoreboards.",
    prereqs: ["valid-ready", "apb"],
    objectives: ["Explain all five channels and their dependencies", "Implement an AXI4-Lite subordinate", "Explain bursts, IDs and outstanding transactions"],
    terms: [["Burst", "Multiple data beats for one address"], ["Outstanding transaction", "Issued but not yet completed"], ["WSTRB", "Byte-lane write enables"]],
    visuals: [{ title: "AXI channel independence", art: "Manager                     Subordinate\n  AW (addr) ----valid/ready---->\n  W  (data) ----valid/ready---->\n  B  (resp) <---valid/ready-----\n  AR (addr) ----valid/ready---->\n  R  (data) <---valid/ready-----" }],
    mistakes: ["Waiting for AWREADY before asserting WVALID (allowed dependency is the other way)", "Ignoring WSTRB"],
    senior: ["How many outstanding transactions does a DMA need to saturate a memory with 100-cycle latency?", "Where do you put register slices in an interconnect and why?"],
    practice: ["Implement an AXI4-Lite register slave and verify it with cocotbext-axi random traffic", "Read the AXI dependency rules and draw the allowed handshake dependencies"],
    interview: [{ q: "Why does AXI have separate address and data channels?", a: "Decoupling lets addresses be issued ahead of data, enables multiple outstanding transactions and pipelining, and allows reads and writes to proceed independently, increasing throughput and hiding latency.", level: 2 }, { q: "Can a burst cross a 4 KB boundary?", a: "No. AXI bursts must not cross 4 KB address boundaries, so a subordinate's address decode never splits a burst across two devices or pages.", level: 2 }],
    resources: ["amba", "verilog-axi", "cocotbext-axi", "pulp-axi", "zipcpu"],
    projects: ["fp-axi-apb", "fp-uvm-env"],
  },
  {
    id: "axi-stream", title: "AXI4-Stream", phase: "p5", module: "m5c",
    priority: "should", depth: "working", difficulty: 2, days: 1, hours: 2, kind: "coding", skills: ["protocols", "rtl"],
    why: "Streaming interfaces connect DSP and AI pipelines, especially on FPGAs.",
    problem: "Data pipelines do not need addresses. AXI-Stream keeps only the handshake, data and framing signals.",
    eli12: "AXI-Stream is a conveyor belt with a 'last item in this box' flag. No addresses, just items flowing in order.",
    tech: "TVALID, TREADY, TDATA, TLAST (packet end), optional TKEEP/TSTRB, TUSER, TID, TDEST. Same valid/ready rules as AXI. Width converters and FIFOs are standard building blocks.",
    inChip: "Video pipelines, network packet paths, accelerator dataflows, FPGA IP.",
    breaks: "TLAST misalignment, TKEEP mishandling on partial beats.",
    tested: "Packet-level scoreboards, random backpressure.",
    prereqs: ["valid-ready"],
    objectives: ["Build a streaming filter with backpressure", "Handle packet boundaries with TLAST"],
    terms: [["TLAST", "Marks the final beat of a packet"], ["TKEEP", "Marks valid bytes in a beat"]],
    mistakes: ["Dropping TLAST through a pipeline stage"],
    practice: ["Build a stream stage that adds a constant to each beat and preserves TLAST"],
    interview: [{ q: "What is TLAST used for?", a: "It marks the last transfer of a packet or frame so downstream logic can detect packet boundaries.", level: 1 }],
    resources: ["amba", "verilog-axi"],
  },
  {
    id: "cdc", title: "Clock domain crossing (CDC)", phase: "p5", module: "m5d",
    priority: "must", depth: "advanced", difficulty: 4, days: 3, hours: 7, kind: "coding", skills: ["rtl", "timing", "verification"],
    why: "Almost every SoC has many clocks. CDC bugs escape simulation and cause silicon failures, so CDC skill is prized in RTL, DV and interviews.",
    problem: "Signals moving between unrelated clocks can be sampled mid-transition. Timing analysis cannot fix this, so designers use proven synchronization structures and CDC tools check them.",
    eli12: "Two drummers play at different speeds. If one shouts a number while the other is mid-beat, the second might hear it wrong. CDC techniques are agreed ways to pass messages safely between drummers.",
    tech: "Single-bit level signals: two-flop synchronizer. Pulses: toggle synchronizer or pulse stretcher (fast to slow). Multi-bit data: handshake (req/ack with stable data), Gray-coded counters, or asynchronous FIFOs. Rules: register signals in the source domain before crossing (no combinational logic feeding synchronizers), avoid reconvergence of separately synchronized bits, constrain crossings as false paths or with max-delay constraints in STA. CDC tools (SpyGlass CDC, Questa CDC, Meridian) perform structural and functional checks.",
    inChip: "Every interface between clock domains: CPU to peripheral, SerDes to core, debug logic.",
    breaks: "Metastability failures, data incoherence (mixed old/new bits), lost pulses, reconvergence bugs.",
    tested: "Structural CDC tools, formal CDC protocol checks, metastability-injection simulation, and review.",
    prereqs: ["metastability", "valid-ready"],
    objectives: ["Choose the right synchronizer for each signal type", "Design a req/ack handshake crossing", "Explain reconvergence and how to avoid it"],
    terms: [["Reconvergence", "Separately synchronized signals recombined, possibly inconsistent"], ["Toggle synchronizer", "Converts a pulse to a level toggle for safe crossing"], ["Quasi-static", "Signal that rarely changes (configuration)"]],
    visuals: [{ title: "Handshake crossing for a bus", art: "src domain                dst domain\n data_q (stable) ================> sampled when req seen\n req  ----> [sync2] ----> req_s --> capture data\n ack_s <--- [sync2] <---- ack\n (src holds data until ack_s)" }],
    mistakes: ["Combinational logic before a synchronizer", "Synchronizing each bit of a counter", "Losing short pulses going to a slower domain"],
    senior: ["How do you decide between a handshake and an async FIFO?", "Which CDC violations are safe to waive and how do you justify them?", "How do resets interact with CDC?"],
    practice: ["Implement a pulse synchronizer and a req/ack handshake; test with unrelated clock ratios", "Read Cummings' CDC paper and list the recommended techniques"],
    interview: [{ q: "How do you transfer a single-cycle pulse from a 500 MHz domain to a 50 MHz domain?", a: "A two-flop synchronizer could miss it. Convert the pulse to a level toggle in the source domain, synchronize the toggle, and edge-detect it in the destination (toggle synchronizer), or stretch the pulse with a handshake.", level: 3 }],
    resources: ["sunburst", "zipcpu"],
    papers: ["ginosar-sync"],
    projects: ["fp-async-fifo"],
  },
  {
    id: "async-fifo", title: "Asynchronous FIFO with Gray-code pointers", phase: "p5", module: "m5d",
    priority: "must", depth: "advanced", difficulty: 4, days: 2, hours: 6, kind: "coding", skills: ["rtl", "verification"],
    why: "The async FIFO is the standard way to move streaming data between clock domains and a top interview design question.",
    problem: "Binary pointers change several bits at once and cannot be safely synchronized. Gray-coded pointers change one bit per increment, so a synchronized pointer is always either the old or new value.",
    eli12: "Two people in different time zones share a notebook. Each writes page numbers in a special code where only one digit changes per page, so even if you glance at the number mid-change you read either the old page or the new page, never nonsense.",
    tech: "Dual-clock memory; write pointer in write domain, read pointer in read domain; convert to Gray; synchronize each Gray pointer into the other domain with two flops; full computed in write domain (compare with synchronized read pointer, MSBs inverted), empty in read domain. Flags are pessimistic (safe): full may assert late to deassert, never late to assert. Depth must be a power of two for simple Gray wrap.",
    inChip: "Between PHYs and cores, display pipelines, network interfaces, AI accelerator front-ends.",
    breaks: "Binary pointer synchronization, flags computed in the wrong domain, reset not synchronized per domain.",
    tested: "Multi-clock random tests with a scoreboard across many clock ratios, assertions, formal on the flag logic, CDC tool checks.",
    prereqs: ["cdc", "sync-fifo"],
    objectives: ["Implement a Cummings-style async FIFO", "Explain why flags are pessimistic but safe", "Verify across clock ratios"],
    terms: [["Gray code", "Adjacent values differ by one bit"], ["Pessimistic flag", "May report full/empty conservatively but never falsely non-full/non-empty"]],
    equations: ["gray = bin ^ (bin >> 1)"],
    mistakes: ["Comparing a synchronized binary pointer", "Using non-power-of-two depth without special handling"],
    practice: ["Build and verify an async FIFO at clock ratios 1:1, 3:7, 10:1 with random bursts", "Inject a binary-pointer bug and show which check catches it"],
    interview: [{ q: "Why are Gray codes used for async FIFO pointers?", a: "Only one bit changes per increment, so when the pointer is sampled in another clock domain the synchronizer yields either the previous or the new value, never an invalid mix. Binary pointers can change many bits at once and be captured inconsistently.", level: 2 }],
    resources: ["sunburst", "chipverify"],
    projects: ["fp-async-fifo"],
  },
  {
    id: "reset-architecture", title: "Reset architecture and reset domain crossing", phase: "p5", module: "m5d",
    priority: "should", depth: "working", difficulty: 3, days: 1, hours: 2, kind: "theory", skills: ["rtl"],
    why: "SoCs have many reset sources and domains. Reset ordering and reset crossings (RDC) cause real silicon issues.",
    problem: "Different blocks reset at different times (warm reset, watchdog, power domains). Asserting reset in one domain while another is running can corrupt the running domain's state.",
    eli12: "If one room in a house restarts its game while the next room keeps playing, messages between rooms can get garbled. Reset architecture decides who restarts together and how messages are protected.",
    tech: "Reset tree design, per-domain reset synchronizers, reset sequencing, isolating paths from a domain being reset into a running domain (RDC), glitch-free reset distribution, and reset for DFT (test mode controls).",
    inChip: "SoC integration and power management; RDC tools are increasingly part of sign-off.",
    breaks: "Metastability from asynchronous reset assertion reaching running logic; wrong sequencing causing bus hangs.",
    tested: "RDC analysis tools, reset-sequence simulations.",
    prereqs: ["resets", "cdc"],
    objectives: ["Draw a reset tree with synchronizers", "Explain an RDC hazard", "Plan reset sequencing"],
    terms: [["RDC", "Reset domain crossing"], ["Warm reset", "Reset without power cycling"]],
    mistakes: ["Assuming reset only matters at power-on"],
    practice: ["Draw the reset architecture for a small SoC with CPU, bus and two peripherals"],
    interview: [{ q: "What is a reset domain crossing issue?", a: "When a flop in one reset domain is reset asynchronously while a flop in another domain samples it, the sampling flop can go metastable or capture corrupted data. Fixes include isolation, gating the path during reset, or synchronizing resets.", level: 3 }],
    resources: ["sunburst"],
  },
  {
    id: "low-power-rtl", title: "Low-power RTL: clock gating and power intent", phase: "p5", module: "m5d",
    priority: "should", depth: "basic", difficulty: 3, days: 1, hours: 2, kind: "theory", skills: ["rtl", "asic"],
    why: "Power is a first-class goal in mobile and AI chips. RTL decisions drive most switching power.",
    problem: "Clock trees and idle logic waste power. Clock gating, operand isolation and power domains cut it, but they need careful RTL and a separate description of power intent (UPF).",
    eli12: "Turning off lights in empty rooms saves electricity. Clock gating stops the heartbeat of idle circuits; power gating unplugs whole rooms.",
    tech: "Clock gating through enables (tools insert ICG cells), operand isolation to prevent useless toggling, memory light sleep, power gating with isolation cells, retention registers and level shifters defined in UPF (IEEE 1801). DVFS at system level.",
    inChip: "Mobile SoCs, AI accelerators, IoT devices; low-power verification is a specialty.",
    breaks: "Missing isolation causes X propagation from powered-off domains; wrong retention loses state.",
    tested: "Power-aware simulation with UPF, static low-power checks, power estimation with activity files.",
    prereqs: ["power", "rtl-guidelines"],
    objectives: ["Write RTL enabling clock gating inference", "Explain isolation, retention and level shifting", "Explain UPF's role"],
    terms: [["ICG", "Integrated clock gating cell"], ["UPF", "Unified Power Format (IEEE 1801)"], ["Isolation cell", "Clamps outputs of a powered-down domain"]],
    mistakes: ["Hand-gating clocks with AND gates"],
    practice: ["Add enables to a register bank and check that Yosys or a synthesis log reports gating opportunities"],
    interview: [{ q: "How does clock gating save power?", a: "It stops the clock to registers that are not changing, removing switching in those flops and in the clock tree branch feeding them, which is a large fraction of dynamic power.", level: 1 }],
    resources: ["chipverify", "weste-harris"],
  },
];
