import type { Topic } from "../schema.ts";

export const P6: Topic[] = [
  {
    id: "why-verification", title: "Why verification exists", phase: "p6", module: "m6a",
    priority: "must", depth: "basic", difficulty: 1, days: 1, hours: 2, kind: "theory", skills: ["verification"],
    why: "Verification is often the largest engineering effort on a chip project and a very common entry point for freshers. Understanding its purpose shapes how you test everything.",
    problem: "Silicon bugs are expensive: a re-spin costs mask sets and months, and some bugs reach customers (the 1994 Pentium FDIV bug led to a large recall charge). Simulation-based and formal verification exist to find bugs before tapeout.",
    eli12: "Before a bridge opens, engineers try every kind of load on a model to be sure it holds. Verification is trying everything on the chip's model, because once the real chip is built you cannot fix it with a patch.",
    tech: "Goals: functional correctness against spec, confidence measured by coverage, and bug discovery rate trending to zero. Approaches: directed tests, constrained-random with coverage, assertions, formal property checking, emulation and FPGA prototyping for scale, and post-silicon validation. Verification is planned from the spec, independently of the designer's implementation.",
    inChip: "DV teams per block and at SoC level; industry surveys (for example the Wilson Research Group functional verification studies hosted on Verification Academy) track how much effort goes into verification.",
    breaks: "Escaped bugs: re-spins, recalls, security holes, lost customers.",
    tested: "Sign-off criteria: test plan complete, coverage goals met, bug rate converged, reviews done.",
    prereqs: ["testbench-basics"],
    objectives: ["Explain the cost of escaped bugs", "Name the main verification approaches", "Explain why verification should be independent of design"],
    terms: [["Re-spin", "Fabricating a corrected chip version"], ["Coverage closure", "Reaching agreed coverage goals"], ["Sign-off", "Formal approval that verification is complete"]],
    mistakes: ["Letting the designer's understanding define what is tested", "Measuring progress by number of tests instead of coverage and bug trends"],
    practice: ["Read about the Pentium FDIV bug and write what verification approach could have caught it", "Watch one part of the Wilson Research verification study series on Verification Academy"],
    interview: [{ q: "Why is verification needed if the designer tested their code?", a: "Designers test what they intended; independent verification tests what the spec requires, including corner cases the designer did not imagine. Bugs found late are extremely costly, so systematic, measurable verification is required.", level: 1 }],
    resources: ["va-courses", "spear-sv"],
  },
  {
    id: "verification-plan", title: "Verification planning", phase: "p6", module: "m6a",
    priority: "must", depth: "working", difficulty: 2, days: 1, hours: 3, kind: "theory", skills: ["verification"],
    why: "A verification plan turns a spec into measurable goals. Employers look for evidence you can plan, not just write tests.",
    problem: "Without a plan, testing is random and 'done' is undefined. A plan lists features, how each is checked, and the coverage that proves it.",
    eli12: "A verification plan is a checklist made from the rulebook: for every rule, how will we test it, and how will we know we tested it enough?",
    tech: "Extract features from the spec; for each: stimulus strategy (directed/random), checking method (scoreboard, assertion), coverage items (cover points, crosses, assertion covers), priority. Include error cases, resets, clocks, configurations. Track to closure with regression dashboards. Keep it living as the spec changes.",
    inChip: "Every DV project starts with a plan reviewed by design and architecture.",
    breaks: "Missing features, untested error paths, false 'done' declarations.",
    tested: "Plan reviews; coverage mapped back to plan items.",
    prereqs: ["why-verification"],
    objectives: ["Write a feature-based verification plan", "Map features to checks and coverage", "Prioritize features by risk"],
    terms: [["Feature list", "Spec behaviours to verify"], ["Traceability", "Linking tests and coverage to spec features"]],
    mistakes: ["Writing the plan after the tests"],
    practice: ["Write a verification plan for your synchronous FIFO with at least 12 features and coverage items"],
    interview: [{ q: "How would you create a verification plan for a new block?", a: "Read the spec and design docs, list features and interfaces, identify corner and error cases, define checkers, stimulus and coverage for each, prioritize by risk, review with designers, then track closure.", level: 2 }],
    resources: ["va-courses", "spear-sv"],
  },
  {
    id: "self-checking-tb", title: "Self-checking testbenches and reference models", phase: "p6", module: "m6a",
    priority: "must", depth: "working", difficulty: 2, days: 2, hours: 4, kind: "coding", skills: ["verification", "python"],
    why: "Automated checking is what makes thousands of tests useful. Reference models are where your software skills shine.",
    problem: "Random stimulus produces too much output to inspect by eye. A reference model predicts correct results so the testbench can compare automatically.",
    eli12: "The reference model is an answer key. The testbench grades every answer from the chip against it and shouts when one is wrong.",
    tech: "Checking styles: expected-value tables, transaction-level reference models (in SV, C via DPI, or Python via cocotb), and scoreboards that compare predicted and observed transactions (in-order or out-of-order). Models are usually untimed; comparison happens at transaction boundaries.",
    inChip: "Scoreboards in every UVM environment; ISS models (Spike) for CPUs.",
    breaks: "A model with the same bug as the design (shared misunderstanding) hides errors; timing-coupled models are brittle.",
    tested: "Mutation testing: inject RTL bugs and confirm the checker catches them.",
    prereqs: ["testbench-basics", "python-hw"],
    objectives: ["Write a transaction-level reference model", "Build an in-order scoreboard", "Test the checker with injected bugs"],
    terms: [["Scoreboard", "Component comparing expected and actual transactions"], ["Mutation testing", "Injecting bugs to measure checker strength"]],
    mistakes: ["Writing the model by copying RTL logic", "Comparing cycle by cycle when only order matters"],
    practice: ["Add a Python reference model and scoreboard to your ALU and FIFO testbenches"],
    interview: [{ q: "What makes a good reference model?", a: "Written independently from the spec, at transaction level, simpler than the RTL, and deterministic; it predicts outputs for any legal input so random tests can be checked automatically.", level: 2 }],
    resources: ["cocotb", "spear-sv"],
  },
  {
    id: "constrained-random", title: "Constrained-random verification methodology", phase: "p6", module: "m6a",
    priority: "must", depth: "working", difficulty: 3, days: 1, hours: 3, kind: "theory", skills: ["verification"],
    why: "Coverage-driven constrained-random verification is the industry standard for complex blocks.",
    problem: "Directed tests grow linearly with effort and miss unknown corner cases. Random stimulus explores more, but needs constraints (legality), checkers (correctness) and coverage (measurement).",
    eli12: "Instead of planning every route through a maze yourself, you send many robots on random but sensible routes, and a map shows which corridors nobody has visited yet.",
    tech: "Loop: randomize legal stimulus, run many seeds, check automatically, measure functional coverage, analyze holes, add constraints or directed tests to reach holes, repeat. Keep failures reproducible with seeds. Balance random with directed tests for specific corner cases.",
    inChip: "Nearly all block-level DV: random stimulus finds the corner cases nobody thought to write a directed test for.",
    breaks: "Coverage holes hidden by over-constrained random; unreproducible failures.",
    tested: "Coverage reports and bug-rate curves.",
    prereqs: ["sv-random", "self-checking-tb"],
    objectives: ["Describe the coverage-driven loop", "Decide when to use directed vs random", "Analyze a coverage hole"],
    terms: [["Coverage hole", "Planned scenario never exercised"], ["Seed", "Random starting value for reproducibility"]],
    mistakes: ["Running more seeds instead of analyzing why coverage plateaued"],
    practice: ["Run 100 seeds on your FIFO test and chart which coverage bins remain empty"],
    interview: [{ q: "When would you still write directed tests?", a: "For specific corner cases random rarely reaches, for bring-up and smoke tests, for spec examples, and to reproduce and lock in fixed bugs.", level: 2 }],
    resources: ["va-courses", "spear-sv"],
  },
  {
    id: "layered-tb", title: "Layered testbench: drivers, monitors, scoreboards", phase: "p6", module: "m6b",
    priority: "must", depth: "advanced", difficulty: 3, days: 2, hours: 5, kind: "coding", skills: ["verification"],
    why: "This architecture is the skeleton of UVM and of most professional testbenches. Knowing it makes UVM make sense.",
    problem: "Monolithic testbenches mix stimulus, protocol timing and checking, so they are hard to reuse. Layering separates concerns.",
    eli12: "A layered testbench is a newsroom: a writer decides what stories to write (generator), a typist turns them into exact keystrokes (driver), a reporter watches what actually got printed (monitor), and an editor checks it against the plan (scoreboard).",
    tech: "Transaction/sequence layer creates abstract transactions; driver converts them into pin wiggles per protocol; monitor passively observes pins and reconstructs transactions; scoreboard compares with the reference model; coverage collector samples transactions. Agents bundle driver, monitor and sequencer per interface; active and passive modes.",
    inChip: "Basis of UVM agents and environments.",
    breaks: "Monitors that depend on driver internals (then they miss DUT-driven behaviour); duplicated protocol logic.",
    tested: "Reusing the monitor at a higher level (passive mode) verifies its independence.",
    prereqs: ["sv-concurrency", "self-checking-tb"],
    objectives: ["Build a non-UVM layered testbench", "Keep monitors independent of drivers", "Explain active vs passive agents"],
    terms: [["Driver", "Converts transactions to signal activity"], ["Monitor", "Observes signals and reconstructs transactions"], ["Agent", "Driver + monitor + sequencer for one interface"]],
    visuals: [{ title: "Layered testbench", art: "[sequence/generator] -> [driver] -> DUT pins -> [monitor] -> [scoreboard]\n                                                   \\-> [coverage]\n                     reference model ----------------^" }],
    mistakes: ["Checking inside the driver"],
    practice: ["Build a layered testbench for your APB register block with mailboxes"],
    interview: [{ q: "Why should the monitor not use information from the driver?", a: "The monitor must observe only the interface so it can check real DUT behaviour, work in passive mode when another block drives the interface, and be reused at higher integration levels.", level: 2 }],
    resources: ["spear-sv", "chipverify"],
  },
  {
    id: "cocotb", title: "Python verification with cocotb", phase: "p6", module: "m6b",
    priority: "should", depth: "working", difficulty: 2, days: 2, hours: 4, kind: "coding", skills: ["verification", "python"],
    why: "cocotb lets you verify RTL in Python with open-source simulators. It is used in open-source projects and some companies, and it plays to your software strengths.",
    problem: "SystemVerilog verification needs expensive simulators and a steep language. cocotb drives any supported simulator (Icarus, Verilator, commercial) from Python coroutines.",
    eli12: "cocotb lets you write your chip's test robot in Python, a language you already know, while the circuit still runs in a real simulator.",
    tech: "Tests are async Python coroutines decorated with @cocotb.test(); await Clock, RisingEdge, Timer; access signals via dut.signal.value; extension libraries like cocotbext-axi provide bus drivers and monitors; run with the cocotb runner or Makefiles; integrate with pytest. Coverage via cocotb-coverage or custom. Mind that Python ints are unbounded.",
    inChip: "Open-source hardware (many OpenTitan-adjacent and FOSSi projects), startups and some DV teams.",
    breaks: "Slow tests if Python does per-cycle heavy work; X/Z values need explicit handling.",
    tested: "Same principles: scoreboards, random stimulus, coverage.",
    prereqs: ["self-checking-tb", "python-hw"],
    objectives: ["Write cocotb tests with clocks and triggers", "Use a Python reference model in a scoreboard", "Use cocotbext-axi for bus traffic"],
    terms: [["Coroutine", "Async function that can wait on simulation events"], ["Trigger", "Event to await, such as RisingEdge(clk)"]],
    code: { lang: "python", src: "import cocotb, random\nfrom cocotb.clock import Clock\nfrom cocotb.triggers import RisingEdge\n\n@cocotb.test()\nasync def alu_random(dut):\n    cocotb.start_soon(Clock(dut.clk, 10, units=\"ns\").start())\n    for _ in range(1000):\n        a, b = random.getrandbits(32), random.getrandbits(32)\n        dut.a.value, dut.b.value, dut.op.value = a, b, 0\n        await RisingEdge(dut.clk)\n        await RisingEdge(dut.clk)\n        assert dut.y.value == (a + b) & 0xFFFFFFFF" },
    mistakes: ["Forgetting to mask expected values", "Sampling outputs in the same delta as driving inputs"],
    practice: ["Port your FIFO testbench to cocotb with a random producer/consumer and scoreboard"],
    interview: [{ q: "What are the pros and cons of cocotb versus UVM?", a: "cocotb: Python productivity, libraries, open-source simulators, fast to start. UVM: industry standard, reusable VIP ecosystem, SV constraints and coverage built in, better performance for large environments. Many teams use both.", level: 2 }],
    resources: ["cocotb", "cocotbext-axi"],
  },
  {
    id: "sva", title: "SystemVerilog Assertions (SVA)", phase: "p6", module: "m6c",
    priority: "must", depth: "advanced", difficulty: 4, days: 3, hours: 6, kind: "coding", skills: ["verification"],
    why: "Assertions catch bugs at the moment they happen, document design intent, and drive formal verification.",
    problem: "Scoreboards find symptoms at outputs, often far from the root cause. Assertions watch internal rules continuously and fire exactly where a rule breaks.",
    eli12: "An assertion is a smoke detector installed inside the circuit. It watches one rule all the time ('this signal must never do that') and rings the moment the rule is broken.",
    tech: "Immediate assertions (in procedural code) and concurrent assertions (clocked properties). Sequences: ##n delays, ##[m:n] ranges, repetition [*n], [->n], [=n]. Implication |-> (same cycle) and |=> (next cycle). Built-ins: $rose, $fell, $stable, $past, $onehot. disable iff for reset. cover property for coverage. bind files attach assertions without editing RTL. Keep properties simple and local.",
    inChip: "Protocol checkers, FIFO invariants, FSM legality, handshake rules; basis of formal verification.",
    breaks: "Vacuous passes (antecedent never true) give false confidence; overly complex properties are slow and hard to debug.",
    tested: "Check assertions fire on injected bugs; check covers hit (non-vacuity).",
    prereqs: ["sv-random", "valid-ready"],
    objectives: ["Write immediate and concurrent assertions", "Use implication and sequences correctly", "Detect vacuity with cover properties"],
    terms: [["Antecedent", "Left side of an implication"], ["Vacuous pass", "Property passes because its antecedent never occurred"], ["bind", "Attach a checker module to a design instance"]],
    code: { lang: "systemverilog", src: "// FIFO must never be written when full\nassert property (@(posedge clk) disable iff (!rst_n) full |-> !wr_en)\n  else $error(\"write while full\");\n// request is granted within 1 to 4 cycles\nassert property (@(posedge clk) disable iff (!rst_n) req |-> ##[1:4] gnt);\ncover property (@(posedge clk) full && rd_en && wr_en);" },
    mistakes: ["Confusing |-> and |=>", "No reset disable", "Never checking vacuity"],
    senior: ["Which properties belong in the RTL (designer assertions) vs the testbench?", "How do you keep assertion runtime cost manageable in long regressions?"],
    practice: ["Write 10 assertions for your FIFO and bind them without editing RTL", "Inject 5 bugs and record which assertion catches each"],
    interview: [{ q: "What is the difference between |-> and |=>?", a: "|-> (overlapping) checks the consequent starting in the same cycle the antecedent matches; |=> (non-overlapping) starts checking in the next cycle. a |=> b equals a |-> ##1 b.", level: 2 }],
    resources: ["chipverify", "va-formal", "spear-sv"],
    projects: ["fp-async-fifo"],
  },
  {
    id: "coverage", title: "Functional and code coverage", phase: "p6", module: "m6c",
    priority: "must", depth: "advanced", difficulty: 3, days: 2, hours: 5, kind: "coding", skills: ["verification"],
    why: "Coverage is how verification measures completeness. 'How do you know you are done?' is answered with coverage.",
    problem: "Passing tests say nothing about what was not tested. Code coverage measures what RTL was exercised; functional coverage measures whether spec scenarios happened.",
    eli12: "Code coverage checks which rooms of the house you walked through. Functional coverage checks whether you did the things that matter in each room, like opening every window.",
    tech: "Code coverage: line, branch, condition, toggle, FSM state/transition (automatic). Functional coverage: covergroups with coverpoints, bins, illegal/ignore bins, crosses, sampled on transactions; assertion covers. 100% code coverage does not imply correctness; functional coverage quality depends on the plan. Coverage closure: analyze holes, adjust constraints, add directed tests, or justify exclusions.",
    inChip: "Sign-off metrics in every DV project.",
    breaks: "Chasing numbers with meaningless bins; excluding holes without justification.",
    tested: "Coverage reviews mapping bins to plan features.",
    prereqs: ["constrained-random"],
    objectives: ["Write covergroups with crosses", "Explain code vs functional coverage", "Close coverage holes deliberately"],
    terms: [["Covergroup", "Container of coverage points sampled together"], ["Cross", "Coverage of combinations of coverpoints"], ["Toggle coverage", "Whether each bit went 0->1 and 1->0"]],
    code: { lang: "systemverilog", src: "covergroup fifo_cg @(posedge clk);\n  cp_level: coverpoint count { bins empty = {0}; bins mid = {[1:DEPTH-2]};\n                               bins almost = {DEPTH-1}; bins full = {DEPTH}; }\n  cp_ops:   coverpoint {wr_en, rd_en};\n  x_level_ops: cross cp_level, cp_ops;\nendgroup" },
    mistakes: ["Declaring victory at 100% code coverage", "Cross coverage explosion without useful bins"],
    practice: ["Add a covergroup to your FIFO and reach 100% functional coverage with justified exclusions"],
    interview: [{ q: "Why isn't 100% code coverage enough?", a: "It shows lines and branches executed, not that behaviour was checked or that all spec scenarios (combinations, sequences, corner cases) occurred. Missing features have no code to cover. Functional coverage tied to the plan is needed.", level: 2 }],
    resources: ["chipverify", "spear-sv", "va-courses"],
  },
  {
    id: "uvm-architecture", title: "UVM architecture: components, phases, factory", phase: "p6", module: "m6d",
    priority: "must", depth: "working", difficulty: 3, days: 2, hours: 5, kind: "coding", skills: ["verification"],
    why: "UVM appears in most DV job postings. You must be able to read, build and explain a UVM environment.",
    problem: "Each company once built its own testbench framework, so verification IP was not reusable. UVM (IEEE 1800.2) standardizes structure, phasing, configuration and messaging.",
    eli12: "UVM is a standard LEGO system for test robots: every company uses the same brick shapes, so a robot arm built by one team can snap onto another team's robot.",
    tech: "Class library on SystemVerilog. Components (uvm_test, uvm_env, uvm_agent, uvm_driver, uvm_monitor, uvm_scoreboard) form a hierarchy; objects (uvm_sequence_item, uvm_sequence) are transient. Phases: build, connect, end_of_elaboration, run (with sub-phases), extract, check, report. Factory (type_id::create) enables overrides without editing code. Objections control end of test. Messaging via `uvm_info/error. Free options to practise: Verilator (upstream UVM 2017 support), EDA Playground, vendor-free editions.",
    inChip: "Standard in DV teams; VIP from vendors is UVM-based.",
    breaks: "Using new() instead of the factory prevents overrides; objection mistakes end tests early or hang them.",
    tested: "UVM reports, end-of-test checks, and coverage.",
    prereqs: ["layered-tb", "sv-oop"],
    objectives: ["Explain components vs objects", "Walk through the UVM phases", "Use the factory and objections correctly"],
    terms: [["Factory", "Creates objects by type, allowing overrides"], ["Objection", "Mechanism keeping the run phase alive"], ["Phase", "Ordered step of testbench execution"]],
    visuals: [{ title: "UVM hierarchy", art: "uvm_test\n  uvm_env\n    agent (active): sequencer -> driver -> DUT\n                    monitor --analysis--> scoreboard, coverage\n    agent (passive): monitor" }],
    mistakes: ["Creating components with new() instead of create()", "Raising objections in the wrong place"],
    practice: ["Build a minimal UVM environment for your APB block (one agent, scoreboard, one test)", "Run it with Verilator or on EDA Playground"],
    interview: [{ q: "What is the UVM factory and why use it?", a: "A registry that creates objects and components by type. Using type_id::create lets tests override types (for example a different driver or transaction) without modifying environment code, enabling reuse.", level: 2 }],
    resources: ["verilator-uvm", "va-courses", "salemi-uvm", "chipverify", "edaplayground"],
    projects: ["fp-uvm-env"],
  },
  {
    id: "uvm-sequences", title: "UVM sequences, sequencers and drivers", phase: "p6", module: "m6d",
    priority: "must", depth: "working", difficulty: 3, days: 2, hours: 5, kind: "coding", skills: ["verification"],
    why: "Sequences are where test scenarios live. Interviewers ask about the sequence-driver handshake constantly.",
    problem: "Tests need reusable, composable stimulus scenarios separate from protocol timing. Sequences generate items; sequencers arbitrate; drivers apply them.",
    eli12: "A sequence is a playlist of songs, the sequencer is the DJ choosing which playlist plays next, and the driver is the speaker actually making the sound.",
    tech: "uvm_sequence_item defines fields with constraints. Sequences implement body(): start_item, randomize, finish_item (or `uvm_do macros). Driver loop: seq_item_port.get_next_item(req), drive pins, item_done(). Responses via put_response. Layering and virtual sequences coordinate multiple agents. Sequence libraries and default sequences.",
    inChip: "All stimulus in UVM environments.",
    breaks: "Forgetting item_done hangs the sequencer; randomize failures ignored.",
    tested: "Sequence coverage, logs, timeouts.",
    prereqs: ["uvm-architecture"],
    objectives: ["Write sequence items and sequences", "Implement the driver handshake", "Compose sequences"],
    terms: [["Sequence item", "Transaction class"], ["Virtual sequence", "Coordinates sequences on multiple sequencers"]],
    code: { lang: "systemverilog", src: "task run_phase(uvm_phase phase);\n  forever begin\n    seq_item_port.get_next_item(req);\n    drive(req);                 // wiggle pins per protocol\n    seq_item_port.item_done();\n  end\nendtask" },
    mistakes: ["Missing item_done", "Putting protocol timing inside sequences"],
    practice: ["Write read, write and random-mix sequences for your APB agent"],
    interview: [{ q: "Explain the sequence-sequencer-driver handshake.", a: "The sequence calls start_item (waits for sequencer grant), randomizes the item, and finish_item hands it over. The driver calls get_next_item to receive it, drives the interface, then item_done to signal completion, unblocking the sequence.", level: 2 }],
    resources: ["salemi-uvm", "chipverify", "va-courses"],
    projects: ["fp-uvm-env"],
  },
  {
    id: "uvm-env", title: "UVM monitors, scoreboards, TLM and configuration", phase: "p6", module: "m6d",
    priority: "must", depth: "working", difficulty: 3, days: 2, hours: 5, kind: "coding", skills: ["verification"],
    why: "Checking and connectivity are what make a UVM environment useful. The config DB and TLM are common interview topics.",
    problem: "Components must exchange transactions without hard coupling and receive configuration (virtual interfaces, modes) from the test.",
    eli12: "TLM ports are mail slots between rooms; the config database is a noticeboard where the test posts settings every component can read.",
    tech: "Analysis ports (write broadcast) from monitors to scoreboards and coverage subscribers; uvm_tlm_analysis_fifo; `uvm_analysis_imp_decl for multiple inputs. uvm_config_db#(T)::set/get for virtual interfaces and knobs. RAL (register abstraction layer) models registers for front-door/back-door access and prediction.",
    inChip: "Standard environment plumbing; RAL used wherever blocks have register maps.",
    breaks: "Config DB path mismatches (silent get failures), scoreboard comparing wrong ordering.",
    tested: "Checking config get return values; end-of-test scoreboard checks for leftover items.",
    prereqs: ["uvm-sequences"],
    objectives: ["Connect monitors to scoreboards with analysis ports", "Pass virtual interfaces via config DB", "Explain RAL at a high level"],
    terms: [["Analysis port", "Broadcast TLM port for observed transactions"], ["config_db", "Hierarchical configuration database"], ["RAL", "Register abstraction layer"]],
    mistakes: ["Ignoring the return value of config_db::get", "Scoreboards that never check for missing transactions at end of test"],
    practice: ["Complete your APB UVM environment with scoreboard, coverage subscriber and a check_phase"],
    interview: [{ q: "How does a monitor send transactions to a scoreboard in UVM?", a: "Through an analysis port: the monitor calls ap.write(tr), and connected analysis imps or FIFOs in the scoreboard and coverage collector receive it, keeping components decoupled.", level: 2 }],
    resources: ["salemi-uvm", "va-courses", "chipverify"],
    projects: ["fp-uvm-env"],
  },
  {
    id: "formal", title: "Formal verification basics", phase: "p6", module: "m6e",
    priority: "should", depth: "working", difficulty: 3, days: 2, hours: 4, kind: "tool", skills: ["verification"],
    why: "Formal proves properties for all inputs, finding corner-case bugs simulation misses. Demand for formal skills is growing and open tools make it learnable.",
    problem: "Simulation checks only the scenarios you run. Formal tools mathematically explore all reachable states (within bounds) to prove or disprove properties.",
    eli12: "Simulation tries many keys in a lock. Formal verification studies the lock's design to prove which keys can ever open it.",
    tech: "Write assertions (properties) and assumptions (constraints on inputs). Bounded model checking (BMC) searches up to depth N for counterexamples; induction proves properties for all depths. Cover statements show reachability. Tools: SymbiYosys (open source) with solvers; commercial JasperGold, VC Formal, Questa Formal. Keep blocks small; abstract memories and counters.",
    inChip: "Control logic, arbiters, FIFOs, protocol compliance, security properties; formal apps for connectivity and CDC.",
    breaks: "Over-constrained assumptions prove nothing; state explosion limits scale.",
    tested: "Counterexample traces, cover checks for over-constraint.",
    prereqs: ["sva"],
    objectives: ["Run SymbiYosys on a FIFO", "Write assume/assert/cover", "Explain BMC vs induction"],
    terms: [["BMC", "Bounded model checking"], ["Counterexample", "Trace showing a property failure"], ["Assumption", "Constraint on inputs for formal analysis"]],
    mistakes: ["Assumptions that exclude real behaviour"],
    practice: ["Prove your FIFO never overflows with SymbiYosys and add covers to check reachability", "Follow a ZipCPU formal tutorial"],
    interview: [{ q: "When is formal verification better than simulation?", a: "For control-heavy blocks with many interleavings (arbiters, FIFOs, protocol logic), for proving absence of bugs (deadlock, overflow), and for security or safety properties. Simulation is better for large datapaths and full-system scenarios.", level: 2 }],
    resources: ["sby", "zipcpu", "va-formal"],
  },
  {
    id: "cdc-verification", title: "CDC and RDC verification", phase: "p6", module: "m6e",
    priority: "should", depth: "basic", difficulty: 3, days: 1, hours: 2, kind: "theory", skills: ["verification", "rtl"],
    why: "CDC bugs escape normal simulation. Companies run dedicated CDC/RDC sign-off flows, and knowing them is valued.",
    problem: "Simulation does not model metastability realistically, so crossings look fine. Structural analysis and targeted methods are needed.",
    eli12: "Normal tests are like practicing a relay handoff in slow motion; nothing goes wrong. CDC checks inspect every handoff point to make sure the right technique is used at full speed.",
    tech: "Structural CDC: identify crossings, verify synchronizers, detect combinational logic before synchronizers, reconvergence, multi-bit crossings. Functional: assertions for handshake protocols, Gray-code properties. Metastability injection in simulation randomizes synchronizer delays. RDC analysis checks reset crossings. Commercial tools dominate; open-source support is limited, so learn the principles and do manual reviews plus assertions.",
    inChip: "Sign-off step for every multi-clock SoC.",
    breaks: "Waiving violations without understanding them.",
    tested: "CDC reports with justified waivers.",
    prereqs: ["cdc", "sva"],
    objectives: ["List structural CDC checks", "Write assertions for Gray-code pointers", "Explain metastability injection"],
    terms: [["Metastability injection", "Randomly delaying synchronizer outputs in simulation"], ["Waiver", "Documented acceptance of a tool violation"]],
    mistakes: ["Trusting simulation alone for CDC"],
    practice: ["Write an assertion that a Gray pointer changes at most one bit per cycle", "Add random one-cycle delays to synchronizer outputs in your async FIFO test"],
    interview: [{ q: "Why doesn't regular simulation catch CDC bugs?", a: "Simulators use ideal digital behaviour, so synchronizers resolve instantly and crossings look safe. Real metastability adds random delays; structural CDC tools and metastability injection are needed.", level: 2 }],
    resources: ["sunburst"],
  },
  {
    id: "debug-method", title: "Debugging methodology: from failure to root cause", phase: "p6", module: "m6e",
    priority: "must", depth: "advanced", difficulty: 3, days: 2, hours: 4, kind: "theory", skills: ["verification", "rtl", "interview"],
    why: "Debug speed is what separates strong engineers. Interviews increasingly test debugging reasoning, not memorized answers.",
    problem: "Failures show symptoms far from causes. Without a method, engineers wander through waveforms for hours.",
    eli12: "Debugging is detective work. Start at the crime scene (the first failure), collect clues (logs, waveforms), form a suspect (hypothesis), and test it before arresting anyone.",
    tech: "Reproduce (seed, config), minimize (shortest failing test), localize (first divergence between expected and actual), hypothesize, test hypothesis (add assertions or prints), fix root cause, add regression test, check similar code for the same bug. Classify: testbench bug, spec ambiguity, RTL bug, tool issue. Keep a debug log.",
    inChip: "Daily DV and RTL work; bug tracking systems record root causes.",
    breaks: "Fixing symptoms creates new bugs; misclassifying testbench bugs as RTL bugs wastes design time.",
    tested: "Regression re-runs; code review of fixes.",
    prereqs: ["waveform-debug", "self-checking-tb"],
    objectives: ["Apply a repeatable debug procedure", "Classify bug origin", "Write a regression test for every fix"],
    terms: [["Root cause", "Underlying reason, not the visible symptom"], ["Minimal reproducer", "Smallest test that still fails"]],
    mistakes: ["Starting from the last error message instead of the first", "Changing several things at once"],
    senior: ["How do you debug a failure that occurs once per 10,000 seeds?", "When do you suspect the testbench rather than the design?"],
    practice: ["Keep a debug log for three injected bugs: symptom, first divergence, hypothesis, root cause, fix, test"],
    interview: [{ q: "A test fails only with seed 8431 after 2 ms of simulation. How do you debug?", a: "Rerun with that seed, find the first scoreboard or assertion failure, trace back to the first divergence in waveforms, add targeted checks, minimize the stimulus if possible, identify root cause and classify (TB vs RTL), fix, and add a directed test.", level: 3 }],
    resources: ["zipcpu", "gtkwave"],
  },
  {
    id: "regression-ci", title: "Regressions, seeds and CI for hardware", phase: "p6", module: "m6e",
    priority: "should", depth: "working", difficulty: 2, days: 1, hours: 3, kind: "tool", skills: ["verification", "linux", "python"],
    why: "Real verification runs thousands of tests nightly. Showing a CI-driven regression on GitHub is strong portfolio evidence and uses your software skills.",
    problem: "Manual test runs miss regressions when code changes. Automated regressions with tracked seeds and dashboards catch breakage immediately.",
    eli12: "A regression is re-checking all your old homework every time you change one answer, done automatically by a robot every night.",
    tech: "Test lists with seeds, parallel runs, pass/fail parsing, coverage merging, triage buckets by failure signature, flaky-test tracking. GitHub Actions can run Verilator/Icarus/cocotb tests on each push. Publish badges and reports.",
    inChip: "Nightly regressions on compute farms; dashboards track pass rate and coverage.",
    breaks: "Unseeded randomness, silently skipped tests, tests that never fail.",
    tested: "By the CI status on every commit: a green run means the regression passed on that revision, and a failing seed is stored so the bug can be replayed exactly.",
    prereqs: ["cocotb", "linux-shell"],
    objectives: ["Write a regression script with seeds", "Run tests in GitHub Actions", "Group failures by signature"],
    terms: [["Triage", "Sorting failures by cause"], ["Flaky test", "Test that passes and fails without code changes"]],
    mistakes: ["Only running tests locally"],
    practice: ["Add GitHub Actions to your FIFO repo running lint and 50 random seeds per push"],
    interview: [{ q: "How do you manage a nightly regression with hundreds of failures?", a: "Bucket failures by error signature, triage the largest buckets first, reproduce with seeds, assign owners, track trends over time, and fix root causes rather than individual tests.", level: 2 }],
    resources: ["cocotb", "verilator"],
  },
  {
    id: "gls-lec", title: "Gate-level simulation and equivalence checking", phase: "p6", module: "m6e",
    priority: "should", depth: "basic", difficulty: 3, days: 1, hours: 2, kind: "theory", skills: ["verification", "asic"],
    why: "After synthesis, teams must prove the netlist still matches the RTL. GLS and LEC appear in DV and RTL job descriptions.",
    problem: "Synthesis optimizes aggressively and scan insertion changes the netlist. Equivalence checking proves functional equivalence formally; gate-level simulation catches reset, X and timing-annotation issues.",
    eli12: "After a translator rewrites your essay in shorter words, you check that it still says exactly the same thing (equivalence), and you also read it aloud once to catch awkward spots (gate-level simulation).",
    tech: "Logic equivalence checking (LEC) maps registers between RTL and netlist and proves the combinational logic between them equivalent (Formality, Conformal; Yosys has equivalence commands). GLS runs tests on the netlist, optionally with SDF timing, useful for reset sequences, X-pessimism/optimism issues, and power-up behaviour.",
    inChip: "Sign-off checks after synthesis, DFT insertion and ECOs.",
    breaks: "Simulation/synthesis mismatches from coding issues; unintended optimization of logic with don't-cares.",
    tested: "LEC reports with no non-equivalent points; GLS smoke tests pass.",
    prereqs: ["latch-inference"],
    objectives: ["Explain LEC vs GLS", "List bugs GLS catches that RTL simulation misses", "Run a simple equivalence check in Yosys"],
    terms: [["LEC", "Logical equivalence checking"], ["SDF", "Standard delay format for timing back-annotation"], ["X-pessimism", "Simulation showing X where hardware is defined"]],
    mistakes: ["Assuming synthesis is always correct"],
    practice: ["Synthesize your ALU with Yosys and run a gate-level simulation with the same testbench"],
    interview: [{ q: "Why run gate-level simulation if equivalence checking passes?", a: "LEC proves functional equivalence but not dynamic behaviour like reset/initialization with X, timing-annotated behaviour, or issues in untestable assumptions. GLS gives extra confidence on resets, power-up and timing-related scenarios.", level: 3 }],
    resources: ["yosys"],
  },
];
