import type { Topic } from "../schema.ts";

export const P7_P8: Topic[] = [
  {
    id: "asic-flow", title: "The ASIC flow end to end", phase: "p7", module: "m7a",
    priority: "must", depth: "basic", difficulty: 2, days: 1, hours: 2, kind: "theory", skills: ["asic"],
    why: "Every RTL or DV engineer must understand what happens to their code after handoff. Most interviews ask for this flow.",
    problem: "Turning RTL into manufacturable layout involves dozens of tool steps with different data formats. Knowing the flow and its files lets you debug handoff issues and speak with PD, STA and DFT teams.",
    eli12: "RTL is a recipe. Synthesis picks real ingredients from the store (standard cells). Floorplanning plans the kitchen layout, placement puts each ingredient on the counter, clock tree synthesis runs the timer wires, routing connects everything, and signoff is the health inspector.",
    tech: "RTL + SDC -> synthesis (netlist) -> DFT insertion -> floorplan (die, macros, IO, power grid) -> placement -> CTS -> routing -> parasitic extraction (SPEF) -> signoff STA, power/IR/EM, DRC, LVS, antenna -> GDSII. Files: Verilog netlist, Liberty (.lib), LEF/DEF, SDC, SPEF, SDF, GDS. Iterations between stages are normal (timing ECOs).",
    inChip: "The backbone of every ASIC project schedule.",
    breaks: "Bad constraints poison every later stage; late RTL changes force re-runs.",
    tested: "Signoff checks at the end; quality-of-results tracking at each step.",
    prereqs: ["chip-journey", "setup-hold"],
    objectives: ["List each flow step with its inputs and outputs", "Name the key file formats", "Explain why iteration happens"],
    terms: [["LEF", "Library exchange format: abstract cell/macro geometry"], ["DEF", "Design exchange format: placed and routed design"], ["SPEF", "Parasitic extraction output"], ["GDSII", "Final layout database"]],
    visuals: [{ title: "Files through the flow", art: "RTL.v + SDC --synth--> netlist.v --floorplan/place/CTS/route--> design.def\n     lib/lef  -------------^                                   |\n                                     extraction -> SPEF -> STA (signoff)\n                                     DRC/LVS -> GDS -> tapeout" }],
    mistakes: ["Thinking synthesis is the last step that matters for timing"],
    practice: ["Draw the flow with file names at every arrow, then compare with the OpenROAD flow scripts documentation"],
    interview: [{ q: "What inputs does synthesis need and what does it produce?", a: "RTL, timing constraints (SDC), and technology libraries (Liberty); it produces a gate-level netlist plus reports on area, timing and power.", level: 1 }],
    resources: ["orfs", "openroad", "librelane", "fossi-open"],
  },
  {
    id: "std-cells", title: "Standard cells and libraries (.lib, LEF)", phase: "p7", module: "m7a",
    priority: "must", depth: "basic", difficulty: 2, days: 1, hours: 2, kind: "theory", skills: ["asic", "timing"],
    why: "Synthesis and STA are only as good as the cell libraries. Reading a Liberty file demystifies timing reports.",
    problem: "Designers cannot simulate every transistor. Standard cells pre-characterize gates for timing, power and geometry so tools can reason at gate level.",
    eli12: "Standard cells are LEGO bricks of the same height, each doing one logic job. The instruction sheet (library) tells how fast and hungry each brick is and exactly how big it is.",
    tech: "Cells have fixed height, variable width, and sit in rows sharing power rails. Liberty (.lib) files hold timing (NLDM tables indexed by input slew and output load), power, and constraints; separate libraries per PVT corner and Vt flavour. LEF gives abstract geometry and pin locations. Families: inverters/buffers in many drives, NAND/NOR/AOI/OAI, flops with scan, clock gating cells, fillers, tap cells, tie cells.",
    inChip: "Selected by synthesis and PD; library teams characterize them.",
    breaks: "Using the wrong corner library; missing cells for required functions (for example no ICG) limit optimization.",
    tested: "Library QA by foundry/vendor; tool checks on consistency.",
    prereqs: ["gate-delay", "asic-flow"],
    objectives: ["Read a Liberty timing arc", "Explain drive strength variants", "Explain why cells share row height"],
    terms: [["NLDM", "Non-linear delay model lookup tables"], ["Drive strength", "Cell size variant such as X1, X4"], ["Tap cell", "Cell connecting wells to supply"]],
    mistakes: ["Ignoring slew in delay lookup"],
    practice: ["Open a SKY130 standard-cell Liberty file and find the delay table for a NAND2 at two loads"],
    interview: [{ q: "What information is in a Liberty file?", a: "Per-cell pin definitions, timing arcs with delay and slew tables versus input transition and load, setup/hold constraints for sequential cells, power tables, area, and operating conditions for that PVT corner.", level: 2 }],
    resources: ["sky130-pdk", "bhasker-sta"],
  },
  {
    id: "synthesis", title: "Logic synthesis", phase: "p7", module: "m7a",
    priority: "must", depth: "working", difficulty: 3, days: 2, hours: 5, kind: "tool", skills: ["asic", "rtl"],
    why: "Synthesis results tell RTL designers whether their code meets area and timing. Running Yosys yourself is concrete, demonstrable evidence.",
    problem: "Mapping behavioural RTL to optimal gates is a huge optimization problem. Synthesis tools translate, optimize and technology-map under constraints.",
    eli12: "Synthesis is an automatic chef who reads your recipe and chooses the cheapest set of real ingredients that still makes the dish on time.",
    tech: "Stages: parse and elaborate, generic logic (RTLIL in Yosys), optimization (constant propagation, resource sharing, FSM extraction), technology mapping (ABC maps to library cells), timing-driven sizing and buffering (in commercial and OpenROAD-assisted flows). Reports: area, cell counts, timing estimates. Constraints drive effort. Watch for inferred latches, removed logic (unused outputs), and unintended multipliers.",
    inChip: "Front-end or synthesis engineers run DC/Genus; RTL designers iterate on synthesis results.",
    breaks: "Logic optimized away because outputs are unconnected; huge area from unintended arithmetic; bad timing from deep logic.",
    tested: "Equivalence checking; reviewing synthesis logs and reports.",
    prereqs: ["std-cells", "latch-inference"],
    objectives: ["Run Yosys synthesis to a real library", "Read area and cell reports", "Explain resource sharing and FSM extraction"],
    terms: [["Technology mapping", "Mapping generic logic to library cells"], ["ABC", "Logic optimization engine used by Yosys"], ["Resource sharing", "Reusing one operator for mutually exclusive operations"]],
    code: { lang: "tcl", src: "# Yosys script (yosys -s synth.ys)\nread_verilog -sv rtl/alu.sv\nsynth -top alu\ndfflibmap -liberty sky130_fd_sc_hd__tt_025C_1v80.lib\nabc -liberty sky130_fd_sc_hd__tt_025C_1v80.lib\nstat -liberty sky130_fd_sc_hd__tt_025C_1v80.lib\nwrite_verilog -noattr out/alu_netlist.v" },
    mistakes: ["Not reading synthesis warnings", "Comparing area across different libraries or corners"],
    practice: ["Synthesize your ALU and FIFO with SKY130 and record area; change one coding style and compare"],
    interview: [{ q: "Your block's area doubled after a small RTL change. How do you investigate?", a: "Compare synthesis reports (cell types and counts), check for newly inferred multipliers or wide muxes, unintended replication from loops or width growth, lost resource sharing, or constraints forcing upsizing. Inspect the netlist for the changed logic.", level: 3 }],
    resources: ["yosys", "orfs", "sky130-pdk"],
  },
  {
    id: "sdc", title: "Timing constraints (SDC)", phase: "p7", module: "m7a",
    priority: "must", depth: "working", difficulty: 3, days: 2, hours: 4, kind: "tool", skills: ["timing", "tcl"],
    why: "Wrong constraints mean timing sign-off is meaningless. RTL designers are often asked to write or review SDC.",
    problem: "Tools cannot guess clock frequencies, IO timing or which paths do not matter. SDC (Synopsys Design Constraints, a Tcl-based format) tells them.",
    eli12: "SDC is the rulebook for the timing referee: how fast the clock ticks, when inputs arrive from outside, and which races do not count.",
    tech: "create_clock (period, waveform), create_generated_clock, set_clock_uncertainty, set_clock_latency, set_input_delay/set_output_delay relative to clocks, set_false_path, set_multicycle_path, set_max_delay (for CDC), set_clock_groups -asynchronous, set_load, set_driving_cell. Exceptions must be justified; over-using false paths hides real bugs.",
    inChip: "Written by RTL/timing owners, consumed by synthesis, PD and STA.",
    breaks: "Missing input delays make IO paths unconstrained; blanket false paths hide real violations; wrong generated clocks break analysis.",
    tested: "Constraint checks (unconstrained paths reports), reviews, and silicon correlation.",
    prereqs: ["setup-hold", "cdc"],
    objectives: ["Write clocks, IO delays and exceptions", "Explain multicycle path setup/hold adjustment", "Check for unconstrained paths"],
    terms: [["False path", "Path excluded from timing analysis"], ["Multicycle path", "Path allowed more than one cycle"], ["Input delay", "External delay before data reaches the input"]],
    code: { lang: "tcl", src: "create_clock -name clk -period 10.0 [get_ports clk]\nset_clock_uncertainty 0.25 [get_clocks clk]\nset_input_delay  3.0 -clock clk [remove_from_collection [all_inputs] [get_ports clk]]\nset_output_delay 2.5 -clock clk [all_outputs]\nset_clock_groups -asynchronous -group {clk} -group {uart_clk}" },
    mistakes: ["Declaring async clocks false paths without synchronizers", "Forgetting the hold adjustment for multicycle paths"],
    practice: ["Write SDC for your UART design with two clocks and run OpenSTA to list unconstrained paths"],
    interview: [{ q: "What is a multicycle path and what must you remember when constraining one?", a: "A path allowed N cycles for setup because data is captured only every N cycles (for example via enables). With set_multicycle_path -setup N you usually also need -hold N-1 so the hold check moves back to the correct edge.", level: 3 }],
    resources: ["opensta", "bhasker-sta"],
  },
  {
    id: "sta", title: "Static timing analysis: arrival, required, slack", phase: "p7", module: "m7b",
    priority: "must", depth: "advanced", difficulty: 4, days: 2, hours: 5, kind: "tool", skills: ["timing"],
    why: "STA is the timing sign-off method for virtually all digital chips. Reading a timing report is a core skill for RTL, STA and PD roles.",
    problem: "Simulating timing for all input patterns is impossible. STA checks every path's worst case using delays from libraries and parasitics, without vectors.",
    eli12: "STA is checking every possible route in a city map for the slowest travel time, without actually driving any car.",
    tech: "Timing graph: nodes are pins, edges are cell and net delays. Arrival times propagate forward (max for setup, min for hold); required times propagate backward from capture clocks; slack = required - arrival. Reports show startpoint, endpoint, path groups, each stage delay, clock paths, and slack. WNS (worst negative slack) and TNS (total negative slack). Tools: PrimeTime, Tempus, OpenSTA.",
    inChip: "Sign-off STA at every milestone across corners and modes.",
    breaks: "Misreading reports leads to wrong fixes; ignoring clock path details misses skew problems.",
    tested: "Signoff criteria: zero violations across all corners and modes, with justified exceptions.",
    prereqs: ["sdc", "setup-hold"],
    objectives: ["Read a full path report", "Compute arrival, required and slack", "Explain WNS and TNS"],
    terms: [["WNS", "Worst negative slack"], ["TNS", "Sum of all negative slacks"], ["Path group", "Paths grouped by capture clock or type"]],
    visuals: [{ title: "Anatomy of a path report", art: "Startpoint: u_reg_a (rising edge-triggered flip-flop clocked by clk)\nEndpoint:   u_reg_b (rising edge-triggered flip-flop clocked by clk)\n  clock clk (rise edge)         0.00   0.00\n  u_reg_a/CLK -> Q              0.31   0.31 r\n  u_add/...                     1.92   2.23 f\n  u_reg_b/D                     0.05   2.28 f\n  data arrival time                    2.28\n  clock clk (rise edge)         2.50   2.50\n  library setup time           -0.12   2.38\n  data required time                   2.38\n  slack (MET)                          0.10" }],
    mistakes: ["Only reading the slack line", "Ignoring clock latency lines"],
    practice: ["Run OpenSTA on your synthesized ALU at three clock periods and record WNS/TNS", "Annotate every line of one path report"],
    interview: [{ q: "Why is STA preferred over dynamic timing simulation for sign-off?", a: "STA checks all paths exhaustively without test vectors and runs much faster; timing simulation only covers exercised paths. STA assumes synchronous design, so asynchronous crossings need separate checks.", level: 2 }],
    resources: ["opensta", "bhasker-sta", "orfs"],
    projects: ["fp-ppa-arith"],
  },
  {
    id: "clock-effects", title: "Clock skew, jitter, uncertainty and hold fixing", phase: "p7", module: "m7b",
    priority: "must", depth: "advanced", difficulty: 4, days: 2, hours: 4, kind: "theory", skills: ["timing"],
    why: "Clocks are never ideal. Skew and uncertainty change both setup and hold margins, and hold fixing is a large part of timing closure.",
    problem: "Before CTS, tools assume ideal clocks with an uncertainty margin; after CTS, real clock latencies appear. Engineers must understand how clock arrival differences affect each check.",
    eli12: "If the starting whistle reaches one runner later than another, races become unfair. Skew is that delay difference; jitter is the whistle's timing wobbling each time.",
    tech: "Skew = capture clock arrival - launch clock arrival. Positive skew helps setup and hurts hold. Uncertainty models jitter plus pre-CTS skew estimates. Clock reconvergence pessimism removal (CRPR) removes common-path pessimism. Useful skew deliberately adjusts clock arrivals. Hold fixes: delay cells on data paths (usually at the fast corner), careful not to create setup violations at slow corners.",
    inChip: "CTS and STA engineers balance skew; hold fixing happens after CTS and routing.",
    breaks: "Hold violations after CTS, or setup-hold conflicts when a path is tight at both corners.",
    tested: "Post-CTS and post-route STA across corners.",
    prereqs: ["sta"],
    objectives: ["Compute setup and hold slack with skew", "Explain uncertainty pre- and post-CTS", "Explain CRPR and useful skew"],
    terms: [["CRPR", "Clock reconvergence pessimism removal"], ["Useful skew", "Intentional skew to fix timing"], ["Latency", "Clock delay from source to flop"]],
    equations: ["Setup slack = Tclk + skew - uncertainty - Tsu - (Tcq + Tlogic)", "Hold slack = Tcq + Tlogic_min - Th - skew - uncertainty_hold"],
    mistakes: ["Assuming zero skew post-CTS", "Fixing hold at the slow corner"],
    practice: ["Compute setup and hold slack for a path with +0.2 ns skew and see which check it helps"],
    interview: [{ q: "How does positive clock skew affect setup and hold?", a: "If the capture clock arrives later (positive skew), setup gets extra time (helps), but hold gets harder because new data may reach the capture flop before its delayed clock edge (hurts).", level: 2 }],
    resources: ["bhasker-sta"],
  },
  {
    id: "timing-closure", title: "Timing closure techniques", phase: "p7", module: "m7b",
    priority: "must", depth: "advanced", difficulty: 4, days: 2, hours: 5, kind: "theory", skills: ["timing", "rtl", "pd"],
    why: "Closing timing is where RTL, synthesis and PD meet. Interviewers love 'your design fails timing, what do you do?'",
    problem: "Designs rarely meet timing on the first run. Engineers need a toolbox of fixes at each level, from architecture to layout, with known costs.",
    eli12: "If the slowest runner keeps losing, you can train them (upsizing), shorten their leg (restructure logic), add another runner (pipelining), or clear obstacles on the track (better placement).",
    tech: "Architecture/RTL: pipelining, retiming, parallelism, reducing logic depth, one-hot encoding, moving late-arriving signals closer to outputs, precomputation. Synthesis: constraints, effort, path groups, ungrouping. PD: placement optimization, gate sizing, buffering, Vt swapping, useful skew, layer assignment, reducing congestion. Always check that fixes do not break hold, power or area.",
    inChip: "Weekly timing-closure meetings in projects; ECOs late in the flow.",
    breaks: "Fixing symptoms at PD when the root cause is RTL structure wastes weeks.",
    tested: "WNS/TNS trends across iterations.",
    prereqs: ["sta", "clock-effects", "pipelined-rtl"],
    objectives: ["Classify violations by cause", "Choose fixes by level", "Estimate the cost of each fix"],
    terms: [["ECO", "Engineering change order: late, targeted netlist change"], ["Vt swap", "Replacing cells with faster, leakier variants"]],
    mistakes: ["Upsizing everything", "Ignoring wire delay and congestion"],
    senior: ["When is it cheaper to change the architecture than to push PD?", "How do you predict closure risk from early synthesis?"],
    practice: ["Take a failing path from your ALU at an aggressive clock and try three different fixes; record results"],
    interview: [{ q: "Your design fails setup at 800 MHz. Walk me through fixing it.", a: "Analyze worst paths (logic depth, fanout, wire delay, clock skew). If logic-dominated: restructure or pipeline in RTL. If fanout: duplicate or buffer. If placement/wire: floorplan and placement fixes. Also check constraints for false or multicycle paths. Verify fixes do not create hold, area or power problems.", level: 3 }],
    resources: ["bhasker-sta", "orfs"],
  },
  {
    id: "corners-ocv", title: "Corners, OCV and multi-mode multi-corner", phase: "p7", module: "m7b",
    priority: "should", depth: "basic", difficulty: 3, days: 1, hours: 2, kind: "theory", skills: ["timing"],
    why: "Real sign-off runs dozens of corner/mode scenarios. Understanding why keeps you from over- or under-trusting a single report.",
    problem: "A chip must work across process, voltage and temperature, and in several operating modes (functional, test, low-power). Variation even within one die needs extra margin.",
    eli12: "A car must work in summer and winter, uphill and downhill, empty and fully loaded. Engineers test each combination rather than just a sunny, flat, empty road.",
    tech: "Corners combine PVT and interconnect extraction corners (Cbest, Cworst, RCworst). Modes change constraints (functional, scan shift, scan capture). MCMM analyzes all scenarios together. OCV derates, AOCV (depth/distance aware) and POCV/LVF (statistical per-cell variation) reduce pessimism.",
    inChip: "STA engineers manage scenario lists; runtime and pessimism are key tradeoffs.",
    breaks: "Missing a mode (for example scan shift) leaves violations undiscovered until test.",
    tested: "By multi-corner multi-mode sign-off reports, which must be clean in every corner and every operating mode before tapeout.",
    prereqs: ["sta", "wires-variation"],
    objectives: ["List typical corners and modes", "Explain OCV derates", "Explain why scenario count grows"],
    terms: [["MCMM", "Multi-corner multi-mode analysis"], ["Derate", "Multiplier applied to delays for variation margin"], ["LVF", "Liberty variation format for statistical timing"]],
    mistakes: ["Ignoring test modes"],
    practice: ["Run OpenSTA with slow and fast libraries on the same netlist and compare setup vs hold results"],
    interview: [{ q: "What is OCV and why is it applied?", a: "On-chip variation: devices on the same die differ. STA derates launch and capture paths differently (for example slower data, faster clock for setup) to guarantee margin against local variation.", level: 3 }],
    resources: ["bhasker-sta"],
  },
  {
    id: "graphs-in-eda", title: "Graph algorithms inside EDA tools (STA as a DAG)", phase: "p7", module: "m7b",
    priority: "should", depth: "working", difficulty: 3, days: 1, hours: 3, kind: "coding", skills: ["eda", "python"],
    why: "This is where your DSA knowledge meets hardware. EDA and AI-for-EDA roles expect you to see circuits as graphs.",
    problem: "Tools must analyze millions of gates quickly. Representing designs as graphs lets classic algorithms (topological sort, shortest/longest paths, BFS) do the work.",
    eli12: "A circuit is a map of towns (gates) and roads (wires). Timing analysis is finding the longest route; routing is finding a path around obstacles. These are the same puzzles you solve in DSA.",
    tech: "Combinational timing graph is a DAG (registers break cycles): topological sort, then dynamic programming for longest arrival time, reverse pass for required times: O(V+E). Routing: Lee's maze router (BFS on a grid) and A*. Partitioning: min-cut (Kernighan-Lin, Fiduccia-Mattheyses). Placement: quadratic/analytical optimization. Netlists are hypergraphs.",
    inChip: "Inside OpenSTA, OpenROAD, commercial tools; your own scripts analyzing netlists.",
    breaks: "Combinational loops break topological sort; naive algorithms do not scale.",
    tested: "Compare your implementation with OpenSTA on small designs.",
    prereqs: ["sta", "python-hw"],
    objectives: ["Implement arrival-time propagation on a DAG", "Explain maze routing as BFS", "Relate partitioning to min-cut"],
    terms: [["DAG", "Directed acyclic graph"], ["Topological order", "Order where every edge goes forward"], ["Hypergraph", "Graph where an edge connects many nodes (a net)"]],
    code: { lang: "python", src: "from graphlib import TopologicalSorter\n\ndef arrival_times(fanin, delay):\n    # fanin: node -> list of predecessor nodes; delay: (u, v) -> edge delay\n    at = {}\n    for v in TopologicalSorter(fanin).static_order():\n        preds = fanin.get(v, [])\n        at[v] = max((at[u] + delay[(u, v)] for u in preds), default=0.0)\n    return at" },
    mistakes: ["Forgetting that timing needs longest (not shortest) paths"],
    practice: ["Parse a small Yosys JSON netlist into a graph and compute unit-delay depth per output", "Implement Lee's algorithm on a grid with obstacles"],
    interview: [{ q: "How would you compute the longest combinational path in a netlist?", a: "Model gates as nodes and connections as weighted edges, break at registers to get a DAG, topologically sort, then propagate max arrival times in order (dynamic programming). Detect combinational loops as cycles.", level: 2 }],
    resources: ["kahng-pd", "opensta", "yosys"],
    projects: ["fp-dft-atpg"],
  },
  {
    id: "floorplan", title: "Floorplanning and power planning", phase: "p7", module: "m7c",
    priority: "should", depth: "basic", difficulty: 3, days: 1, hours: 2, kind: "theory", skills: ["pd"],
    why: "Floorplan decisions set the ceiling for timing, congestion and power integrity. Even front-end engineers benefit from understanding them.",
    problem: "Placing macros, IOs and power grids badly creates long wires, congestion and IR drop that later steps cannot fix.",
    eli12: "Before furnishing a house, you decide where the big rooms and heavy appliances go and run the electrical wiring. Put the fridge far from the kitchen and every meal takes longer.",
    tech: "Die/core size and utilization targets, aspect ratio, IO placement, macro placement (with halos and channels), power delivery network (rings, straps, rails), blockages, tap and endcap cells. Utilization typically 50-70% to leave room for buffering and routing.",
    inChip: "PD engineers with input from RTL/architecture on data flow.",
    breaks: "Congestion, long critical wires, IR drop hot spots.",
    tested: "Congestion maps, early timing, IR analysis.",
    prereqs: ["asic-flow"],
    objectives: ["Explain utilization and aspect ratio", "Describe macro placement considerations", "Describe a power grid"],
    terms: [["Utilization", "Cell area / core area"], ["PDN", "Power delivery network"], ["Halo", "Keep-out region around a macro"]],
    mistakes: ["Targeting very high utilization to save area"],
    practice: ["Run the ORFS or LibreLane floorplan step on a small design and view it in KLayout or the OpenROAD GUI"],
    interview: [{ q: "What factors decide macro placement?", a: "Data flow and connectivity to logic, pin locations, timing-critical interfaces, routing channels between macros, power grid access, and keeping standard cell area contiguous.", level: 2 }],
    resources: ["orfs", "librelane", "kahng-pd"],
  },
  {
    id: "placement-cts", title: "Placement and clock tree synthesis", phase: "p7", module: "m7c",
    priority: "should", depth: "basic", difficulty: 3, days: 2, hours: 3, kind: "theory", skills: ["pd", "timing"],
    why: "Placement quality drives wirelength and timing; the clock tree drives skew and a large share of power.",
    problem: "Millions of cells must be positioned to minimize wirelength and meet timing without overlaps, and one clock must reach thousands of flops with nearly equal delay.",
    eli12: "Placement is seating guests so friends who talk a lot sit close together. Clock tree synthesis is running speaker wires so every guest hears the music at the same moment.",
    tech: "Global placement (analytical, wirelength and density), legalization into rows, detailed placement; timing- and congestion-driven optimization with sizing and buffering. CTS builds a buffered tree (H-tree-like or balanced) targeting skew, latency, transition limits; then post-CTS optimization including hold fixing.",
    inChip: "PD engineers; tools: Innovus, ICC2/Fusion Compiler, OpenROAD (RePlAce/DREAMPlace-style placement, TritonCTS).",
    breaks: "Congestion from dense placement; large skew causing hold/setup problems; clock power explosion.",
    tested: "Post-placement timing and congestion reports; CTS skew and latency reports.",
    prereqs: ["floorplan", "clock-effects"],
    objectives: ["Describe placement stages", "Explain CTS goals", "Explain why hold fixing happens after CTS"],
    terms: [["Legalization", "Snapping cells into legal row positions"], ["Clock latency", "Delay from clock source to sinks"], ["HPWL", "Half-perimeter wirelength estimate"]],
    mistakes: ["Evaluating timing before CTS as final"],
    practice: ["Compare pre-CTS and post-CTS timing reports in an ORFS run"],
    interview: [{ q: "What are the goals of clock tree synthesis?", a: "Deliver the clock to all sinks with minimal and controlled skew, acceptable latency, good slew, robustness to variation, and reasonable power and area.", level: 2 }],
    resources: ["orfs", "openroad", "dreamplace"],
  },
  {
    id: "routing-signoff", title: "Routing, extraction and signoff (IR, EM, DRC, LVS)", phase: "p7", module: "m7c",
    priority: "should", depth: "basic", difficulty: 3, days: 2, hours: 3, kind: "theory", skills: ["pd"],
    why: "A design is not done until it is routed and clean. Knowing signoff checks lets you talk credibly about tapeout readiness.",
    problem: "Connections must be drawn on real metal layers obeying manufacturing rules, and the final layout must be proven to match the netlist and be electrically sound.",
    eli12: "Routing draws every road in the city on several stacked levels with strict building codes. Signoff is the final inspection: do the roads match the plan, are they wide enough for traffic, and do they follow code?",
    tech: "Global routing (assigns regions), detailed routing (exact tracks, vias). Extraction produces RC parasitics (SPEF) for signoff STA. Signoff: STA with SI, IR drop (static/dynamic), electromigration, DRC (geometry rules), LVS (layout matches schematic/netlist), antenna checks, density fill.",
    inChip: "PD and physical verification engineers; tools Calibre/Pegasus/ICV; open-source Magic, KLayout, Netgen.",
    breaks: "DRC errors block tapeout; LVS mismatches mean the chip is not what you designed; EM failures reduce lifetime.",
    tested: "Clean DRC/LVS decks, signoff STA and power reports.",
    prereqs: ["placement-cts"],
    objectives: ["Describe global vs detailed routing", "Explain DRC and LVS", "Explain IR drop and EM"],
    terms: [["DRC", "Design rule check"], ["LVS", "Layout versus schematic"], ["EM", "Electromigration"], ["Antenna effect", "Charge buildup damaging gates during fabrication"]],
    mistakes: ["Waiving DRC errors without foundry approval"],
    practice: ["Open a routed design's GDS in KLayout and inspect metal layers; read the DRC and LVS summary from a LibreLane run"],
    interview: [{ q: "What is LVS and why is it needed?", a: "Layout versus schematic compares the connectivity extracted from the layout with the netlist, ensuring the physical design implements the intended circuit (no shorts, opens or wrong devices).", level: 1 }],
    resources: ["klayout", "magic", "librelane"],
  },
  {
    id: "tcl-eda", title: "Tcl for EDA automation", phase: "p7", module: "m7c",
    priority: "should", depth: "working", difficulty: 2, days: 1, hours: 3, kind: "coding", skills: ["tcl"],
    why: "Most commercial and open EDA tools are driven by Tcl. PD and STA roles expect Tcl fluency.",
    problem: "EDA tools expose thousands of commands. Tcl scripts make flows repeatable and let engineers query design databases (for example all paths with negative slack).",
    eli12: "Tcl is the language you use to give orders to chip-design robots, like a remote control with programmable buttons.",
    tech: "Syntax: everything is a string; commands with arguments; set/puts; lists; foreach; procs; expr; braces vs quotes (substitution rules); namespaces. EDA usage: collections (get_cells, get_nets), filtering, report parsing, custom procs. You can skip advanced Tcl (Tk GUIs, deep metaprogramming).",
    inChip: "Synthesis, PD and STA scripts; OpenROAD and OpenSTA both accept Tcl.",
    breaks: "Substitution mistakes produce silent wrong constraints.",
    tested: "Script outputs reviewed against GUI checks.",
    prereqs: ["sdc", "linux-shell"],
    objectives: ["Write Tcl procs with loops and lists", "Query cells and paths in OpenSTA", "Avoid quoting and substitution pitfalls"],
    terms: [["Collection", "Tool object list returned by get_* commands"], ["proc", "Tcl procedure"]],
    code: { lang: "tcl", src: "proc report_bad_paths {limit} {\n  foreach path [find_timing_paths -slack_max 0 -group_path_count $limit] {\n    puts \"[get_full_name [get_property $path endpoint]] [get_property $path slack]\"\n  }\n}" },
    mistakes: ["Using quotes where braces are needed (early substitution)"],
    practice: ["Write a Tcl script for OpenSTA that prints the 10 worst endpoints and their slack"],
    interview: [{ q: "What is the difference between braces and quotes in Tcl?", a: "Quotes allow variable and command substitution inside the string; braces prevent substitution and preserve the text literally until evaluated later.", level: 1 }],
    resources: ["tcl-tutorial", "opensta", "openroad"],
  },
  {
    id: "dft", title: "Design for test: scan, ATPG, BIST and JTAG", phase: "p7", module: "m7d",
    priority: "should", depth: "basic", difficulty: 3, days: 2, hours: 4, kind: "theory", skills: ["dft"],
    why: "Every manufactured chip must be tested. DFT awareness is expected of RTL engineers, and DFT is its own career path.",
    problem: "Manufacturing defects are random. Testing a chip only through its normal pins would take far too long. DFT adds structures that make internal state controllable and observable.",
    eli12: "Imagine checking every light bulb in a skyscraper from the street. DFT adds a secret hallway (scan chain) that lets testers walk past every bulb quickly.",
    tech: "Scan: flops replaced by scan flops connected into shift chains; shift in patterns, capture one functional cycle, shift out results. ATPG generates patterns for fault models (stuck-at, transition). Compression reduces test time. Memory BIST tests SRAMs on-chip. JTAG (IEEE 1149.1) provides a standard test access port and boundary scan. Metrics: fault coverage, test time, pattern count.",
    inChip: "DFT engineers insert and verify test logic; RTL engineers must avoid structures that break scan (uncontrolled clocks, asynchronous loops).",
    breaks: "Low coverage lets defective chips ship; test-mode timing issues fail on the tester.",
    tested: "ATPG coverage reports, pattern simulation, tester results.",
    prereqs: ["latches-flipflops", "asic-flow"],
    objectives: ["Explain scan shift and capture", "Explain stuck-at and transition faults", "Describe MBIST and JTAG roles"],
    terms: [["Scan chain", "Flops linked into a shift register for test"], ["Stuck-at fault", "Node permanently at 0 or 1"], ["ATPG", "Automatic test pattern generation"], ["TAP", "JTAG test access port"]],
    visuals: [{ title: "Scan chain", art: "scan_in -> [FF]-> [FF]-> [FF]-> [FF]-> scan_out\n            |      |      |      |\n   functional logic between flops (captured in one cycle)" }],
    mistakes: ["Designing with internally generated clocks that scan cannot control"],
    practice: ["Explain how a stuck-at-0 fault on an AND gate input is detected by a scan pattern"],
    interview: [{ q: "How does scan testing work?", a: "In shift mode, flops form chains; the tester shifts a pattern in. In capture mode, one functional clock applies the logic between flops. Then the captured values are shifted out and compared with expected values to detect faults.", level: 2 }],
    resources: ["bushnell-agrawal", "fault"],
    projects: ["fp-dft-atpg"],
  },
  {
    id: "tapeout", title: "Tapeout, fabrication and post-silicon validation", phase: "p7", module: "m7d",
    priority: "should", depth: "awareness", difficulty: 2, days: 1, hours: 2, kind: "theory", skills: ["asic"],
    why: "Knowing what happens after tapeout explains why teams are so careful, and opens validation as a career path.",
    problem: "After GDS is sent, fabrication takes weeks to months; then chips must be tested, packaged, brought up and characterized before customers get them.",
    eli12: "Tapeout is mailing your blueprint to the factory. Months later, boxes of chips arrive. Then engineers power them up for the first time and check whether reality matches the plan.",
    tech: "Tapeout checklist (signoff clean, documentation, reviews). MPW shuttles share mask costs among many designs (for example Tiny Tapeout for learners, europractice for academia). Wafer sort and final test on ATE. Packaging. Post-silicon validation: bring-up, functional tests, characterization across PVT, debug with on-chip debug features, errata.",
    inChip: "Validation, test and product engineering teams; silicon bugs lead to ECOs, metal fixes or re-spins.",
    breaks: "Missing debug visibility makes silicon bugs nearly impossible to root-cause.",
    tested: "ATE programs, validation plans, characterization reports.",
    prereqs: ["dft"],
    objectives: ["Describe MPW shuttles", "Describe bring-up and validation", "Explain metal-only fixes"],
    terms: [["MPW", "Multi-project wafer shuttle"], ["Bring-up", "First power-on and functional checks of new silicon"], ["Errata", "Documented silicon bugs and workarounds"]],
    mistakes: ["Assuming a successful tapeout means working silicon"],
    practice: ["Read one Tiny Tapeout shuttle page and list what submitters must provide"],
    interview: [{ q: "What is post-silicon validation?", a: "Testing real manufactured chips in a lab and systems to confirm functionality, performance and robustness across conditions, finding bugs that escaped pre-silicon verification and characterizing margins.", level: 1 }],
    resources: ["tinytapeout", "wafer-space-template"],
  },
  {
    id: "open-flow", title: "Open-source RTL-to-GDS flow (Yosys, OpenROAD, LibreLane)", phase: "p7", module: "m7e",
    priority: "must", depth: "working", difficulty: 3, days: 3, hours: 8, kind: "tool", skills: ["asic", "pd", "tcl"],
    why: "Running a real RTL-to-GDS flow yourself is the strongest possible evidence of ASIC flow understanding without commercial tool access.",
    problem: "Commercial flows are licensed. Open flows (OpenROAD flow scripts, LibreLane, the successor to OpenLane 2 under the FOSSi Foundation) with open PDKs (SKY130, GF180MCU, IHP SG13G2) now reach tapeout quality for mature nodes.",
    eli12: "It is like having a real car factory in your garage, a bit simpler than the big ones, where you can build a real (small) car from your own design.",
    tech: "OpenROAD flow scripts: Makefile-driven flow over Yosys synthesis, OpenROAD floorplan/place/CTS/route, OpenSTA, KLayout. LibreLane: Python-based, configurable flows ('Classic' replicates OpenLane), installed via Nix (recommended) with a browser-based Colab option. Run a small design (for example the serial-parallel multiplier example), read the metrics (area, WNS/TNS, power, DRC/LVS), view GDS in KLayout, then run your own ALU or FIFO.",
    inChip: "Research groups, startups and Tiny Tapeout designs use these flows; the concepts transfer directly to commercial tools.",
    breaks: "Mismatched PDK/tool versions, over-aggressive clock targets, high utilization causing routing failures.",
    tested: "Clean flow completion with signoff reports; GDS inspection.",
    prereqs: ["synthesis", "sdc", "routing-signoff", "tcl-eda"],
    objectives: ["Install and run LibreLane or ORFS", "Run your own design to GDS", "Interpret area, timing, power and DRC/LVS results"],
    terms: [["ORFS", "OpenROAD flow scripts"], ["LibreLane", "FOSSi Foundation successor to OpenLane 2"], ["Open PDK", "Publicly available process design kit"]],
    mistakes: ["Starting with a large design", "Changing many flow knobs at once"],
    practice: ["Run the example design, then your FIFO; record metrics in a table and screenshot the GDS"],
    interview: [{ q: "Describe a design you took through an RTL-to-GDS flow.", a: "Give specifics: design, PDK, tool (LibreLane or ORFS), clock target, utilization, WNS/TNS, area, power estimate, DRC/LVS results, what failed and how you fixed it, and what you would do differently.", level: 2 }],
    resources: ["librelane", "librelane-blog", "orfs", "openroad", "yosys", "klayout", "sky130-pdk", "ihp-pdk", "gf180-pdk", "iic-osic-tools"],
    projects: ["m-openroad", "fp-open-silicon"],
  },
  {
    id: "ppa", title: "PPA: thinking in power, performance, area and cost", phase: "p7", module: "m7e",
    priority: "must", depth: "advanced", difficulty: 4, days: 2, hours: 4, kind: "theory", skills: ["asic", "rtl", "arch"],
    why: "PPA reasoning is the core of senior engineering judgment. Every design choice trades these against each other and against schedule and cost.",
    problem: "Optimizing one metric in isolation usually hurts others. Engineers need a way to compare architectures fairly and explain tradeoffs.",
    eli12: "Buying a car, you balance speed, fuel use and size. A sports car is fast but thirsty; a tiny car is cheap but slow. Chip designers make the same kind of choice for every block.",
    tech: "Performance: frequency, throughput, latency. Power: dynamic and leakage, energy per operation. Area: cell and macro area, which drives cost and yield. Cost also includes verification effort and schedule risk. Methods: sweep architectures under identical flows and constraints, plot Pareto fronts, normalize (energy/op, throughput/area), and explain why each change moved each metric. Examples: pipelining (faster, more flops and power), parallelism (throughput for area), clock gating (power for small area and complexity).",
    inChip: "Architecture reviews and block-level design decisions.",
    breaks: "Chasing frequency that the system does not need, or unfair comparisons using different constraints.",
    tested: "Documented PPA studies with reproducible scripts.",
    prereqs: ["timing-closure", "power", "open-flow"],
    objectives: ["Run a fair PPA comparison", "Plot and explain a Pareto front", "Explain three common tradeoffs"],
    terms: [["Pareto front", "Set of designs where no metric can improve without another getting worse"], ["Energy per operation", "Joules spent per useful result"]],
    mistakes: ["Comparing designs synthesized with different clock targets", "Reporting area without timing"],
    senior: ["Why did this architecture become faster but larger?", "Why did this optimization save power but hurt timing?", "What is the cheapest design that meets the requirement, not the best on one axis?"],
    ladder: { beginner: "Faster, smaller and lower power pull against each other.", junior: "Measure area, timing and power for two implementations fairly.", mid: "Explain which structures caused the differences and propose improvements.", senior: "Choose architectures from system requirements and cost, including verification and schedule risk.", research: "Automate design-space exploration with ML or Bayesian optimization." },
    practice: ["Compare ripple-carry, carry-lookahead and synthesis-chosen adders at three clock targets and plot area vs delay"],
    interview: [{ q: "How would you compare two architectures for the same function?", a: "Implement both under identical constraints and flow, sweep clock targets, measure area, timing, power (with realistic activity) and throughput, normalize per operation, and explain differences structurally, including verification and schedule costs.", level: 3 }],
    resources: ["orfs", "yosys", "opensta"],
    projects: ["fp-ppa-arith"],
  },
  {
    id: "spec-writing", title: "Writing a hardware specification", phase: "p8", module: "m8a",
    priority: "must", depth: "working", difficulty: 2, days: 2, hours: 4, kind: "project", skills: ["rtl", "interview"],
    why: "Specs are how teams agree on what to build. Writing one for your project shows professional maturity employers notice.",
    problem: "Without a written spec, design and verification drift apart and 'done' is undefined.",
    eli12: "A spec is the contract you write before building: what it does, how you talk to it, how fast it must be, and what happens when things go wrong.",
    tech: "Sections: overview and use cases, features, interfaces (signals, protocols, timing diagrams), register map, performance targets (frequency, throughput, latency), power/area goals, error handling, reset and clocking, configuration parameters, verification and test considerations, open questions.",
    inChip: "Architecture and design leads write specs; DV derives plans from them.",
    breaks: "Ambiguous specs lead to mismatched implementations and arguments late in the project.",
    tested: "Spec reviews; verification plan traceability.",
    prereqs: ["ppa"],
    objectives: ["Write a complete block spec", "Include timing diagrams and a register map", "Define measurable targets"],
    terms: [["Use case", "Scenario describing how the block is used"], ["Target", "Measurable requirement such as 200 MHz"]],
    mistakes: ["Describing implementation instead of behaviour"],
    practice: ["Write the spec for your end-to-end project (see the Projects page)"],
    interview: [{ q: "What goes into a good block specification?", a: "Features, interfaces with timing, register map, performance and power/area targets, clock/reset behaviour, error handling, configuration, and verification considerations, written as testable requirements.", level: 1 }],
    resources: ["amba"],
    projects: ["fp-open-silicon"],
  },
  {
    id: "microarchitecture", title: "Microarchitecture documents and design reviews", phase: "p8", module: "m8a",
    priority: "must", depth: "working", difficulty: 3, days: 2, hours: 4, kind: "project", skills: ["rtl", "arch"],
    why: "Microarchitecture is where you show engineering judgment before code. Reviewers look for clear tradeoffs and risk thinking.",
    problem: "Jumping from spec to code hides design decisions. A microarchitecture document makes them explicit so others can review timing, area and verification risk.",
    eli12: "After deciding what the machine must do, you draw how it works inside: which parts, how data flows, and why you chose this design over others.",
    tech: "Contents: block diagram, datapath and control, pipeline stages with timing budget, storage (FIFOs, memories) and sizing rationale, interfaces and handshakes, clock domains and CDC plan, reset plan, area/power estimates, alternatives considered with tradeoffs, verification hooks (assertions, debug signals). Hold a review (even a mock one) and record decisions.",
    inChip: "Design reviews are standard gates before RTL coding.",
    breaks: "Undocumented assumptions cause integration bugs.",
    tested: "Review checklists; later comparison of estimates with results.",
    prereqs: ["spec-writing"],
    objectives: ["Write a microarchitecture document with alternatives", "Budget timing per stage", "Plan CDC and verification hooks"],
    terms: [["Timing budget", "Planned delay allocation per stage"], ["Design review", "Structured critique of a design before implementation"]],
    mistakes: ["Presenting only one option"],
    practice: ["Write the microarchitecture document for your end-to-end project and ask for one external review (forum or peer)"],
    interview: [{ q: "Walk me through the microarchitecture of a project you built.", a: "Block diagram, data flow, pipeline and timing budget, storage sizing, interfaces, CDC and reset plan, alternatives you rejected and why, results versus estimates.", level: 3 }],
    resources: ["mutlu-yt"],
    projects: ["fp-open-silicon"],
  },
  {
    id: "e2e-build", title: "End-to-end sprint: RTL and verification", phase: "p8", module: "m8b",
    priority: "must", depth: "advanced", difficulty: 4, days: 3, hours: 14, kind: "project", skills: ["rtl", "verification"],
    why: "This sprint turns everything so far into one coherent, documented design: the backbone of your portfolio.",
    problem: "Separate exercises do not show you can deliver a block. A sprint with milestones proves you can implement, verify and track closure.",
    eli12: "This is the week you actually build your machine and test it seriously, not just its parts.",
    tech: "Implement RTL per the microarchitecture, lint-clean. Build a self-checking testbench (cocotb or SV/UVM) with a reference model, assertions and functional coverage. Run a seeded regression in CI. Track coverage and bugs in the repo (issues or a log). Freeze RTL when coverage goals are met.",
    inChip: "Mirrors a real block's RTL and DV milestones.",
    breaks: "Skipping verification to reach the flow faster produces a pretty GDS of a broken design.",
    tested: "Coverage report, regression status, bug log.",
    prereqs: ["microarchitecture", "coverage", "sva"],
    objectives: ["Deliver lint-clean RTL", "Reach coverage goals with a regression", "Document bugs found and fixed"],
    terms: [["RTL freeze", "RTL is stable for implementation"], ["Bug log", "Record of bugs, root causes and fixes"]],
    mistakes: ["No bug log (bugs found are evidence of good verification)"],
    practice: ["Complete the build milestones of your end-to-end project"],
    interview: [{ q: "What was the hardest bug in your project and how did you find it?", a: "Describe symptom, first divergence, root cause, fix, and the test or assertion you added, plus what it taught you.", level: 2 }],
    resources: ["cocotb", "sby", "verilator"],
    projects: ["fp-open-silicon"],
  },
  {
    id: "e2e-implement", title: "End-to-end sprint: synthesis, timing and place-and-route", phase: "p8", module: "m8c",
    priority: "must", depth: "advanced", difficulty: 4, days: 3, hours: 14, kind: "project", skills: ["asic", "timing", "pd"],
    why: "Taking your own verified RTL through a real flow and closing timing is rare among entry-level candidates.",
    problem: "A design that only simulates is incomplete. Implementation shows whether it meets real frequency, area and power targets.",
    eli12: "Now the factory robots build your machine on a real chip layout and inspectors check it.",
    tech: "Write SDC, synthesize, run STA, iterate on RTL if needed, then run LibreLane or ORFS to GDS on an open PDK. Sweep clock target and utilization. Record WNS/TNS, area, power, DRC/LVS. Run gate-level simulation on the netlist.",
    inChip: "Mirrors synthesis, STA and PD handoffs.",
    breaks: "Unrealistic clock targets; ignoring hold or DRC results.",
    tested: "By clean reports at each flow step plus a gate-level simulation that still passes with back-annotated timing.",
    prereqs: ["e2e-build", "open-flow"],
    objectives: ["Close timing at a justified target", "Produce clean DRC/LVS", "Run GLS on the netlist"],
    terms: [["QoR", "Quality of results: timing, area, power"]],
    mistakes: ["Reporting only the best run without explaining the sweep"],
    practice: ["Complete the implementation milestones and create a results table"],
    interview: [{ q: "How did you pick your clock target?", a: "Start from spec needs, synthesize and run STA to find the natural critical path, sweep targets, and choose one with margin that meets the requirement; explain what limited further improvement.", level: 2 }],
    resources: ["librelane", "orfs", "opensta"],
    projects: ["fp-open-silicon"],
  },
  {
    id: "e2e-report", title: "End-to-end sprint: reports, PPA and retrospective", phase: "p8", module: "m8c",
    priority: "must", depth: "working", difficulty: 3, days: 2, hours: 6, kind: "project", skills: ["interview"],
    why: "Documentation turns work into evidence. A clear report is what reviewers, recruiters and interviewers actually read.",
    problem: "Great projects with no write-up look like nothing. Engineers must communicate results, tradeoffs and limitations honestly.",
    eli12: "You built something amazing; now you write the museum label so visitors understand what it is, why it matters and what you learned.",
    tech: "README (overview, how to run), architecture diagram, verification summary (coverage, bugs), implementation results (tables and plots), PPA discussion, limitations, lessons learned, what you would improve next. Paper-style report optional. Screenshots of waveforms and GDS.",
    inChip: "Design review packages and tapeout reports.",
    breaks: "Overclaiming (for example 'production-ready') damages credibility.",
    tested: "Could a stranger reproduce your results from the repo?",
    prereqs: ["e2e-implement"],
    objectives: ["Write a reproducible README", "Present PPA results honestly", "Write a retrospective"],
    terms: [["Reproducibility", "Others can rerun and get the same results"]],
    mistakes: ["No instructions to reproduce", "Hiding limitations"],
    practice: ["Finish the showcase checklist for your end-to-end project"],
    interview: [{ q: "What would you do differently if you redid your project?", a: "Give concrete, technical improvements (for example earlier assertions, different pipelining, better constraints) that show you learned from data, not generic statements.", level: 2 }],
    resources: [],
    projects: ["fp-open-silicon"],
  },
];
