import type { Topic } from "../schema.ts";

export const P9: Topic[] = [
  {
    id: "specialization-gate", title: "Choosing your specialization", phase: "p9", module: "m9a",
    priority: "must", depth: "basic", difficulty: 2, days: 1, hours: 3, kind: "career", skills: ["interview"],
    why: "Depth in one area plus breadth across the flow is what makes a junior engineer useful. This gate turns your evidence into a deliberate choice.",
    problem: "Learners often pick a specialization on day one from rumours. By now you have quiz scores, projects and a feel for the daily work, which is far better evidence.",
    eli12: "You have tried every sport in the school season. Now you pick the team you enjoyed most and were good at, and still keep playing the others for fun.",
    tech: "Inputs: which topics you enjoyed, mastery-test and interview accuracy by category, project performance, strengths (software, math, debugging, physical intuition), current job demand (Job Readiness page), and preferred work style (building vs breaking vs optimizing vs tooling). Choose one primary track and optionally one secondary. The primary gets 7 plan days; the secondary gets a compressed 4 days.",
    inChip: "Teams hire for a role but value people who understand neighbouring roles.",
    breaks: "Choosing by hype leads to motivation loss; never choosing leads to shallow skills.",
    tested: "The Career Paths page shows an explainable recommendation from your evidence.",
    prereqs: ["e2e-report"],
    objectives: ["Review your evidence", "Choose a primary and optional secondary track", "Write why, in three sentences"],
    terms: [["Primary track", "Where you build depth for applications"], ["Secondary track", "An adjacent area for breadth"]],
    mistakes: ["Choosing a track with no projects supporting it", "Choosing only by salary claims"],
    practice: ["Complete the specialization questionnaire on the Career Paths page", "Write a one-paragraph rationale and save it in notes"],
    interview: [{ q: "Why did you choose verification (or your track) over design?", a: "Tie it to evidence: what you enjoyed, what you did well in projects, and how your background (for example software and OOP) fits the role.", level: 1 }],
    resources: [],
  },
  // RTL track
  {
    id: "rtl-microarch-ppa", title: "Microarchitecture for PPA: pipelining, parallelism and sharing", phase: "p9", module: "m9-rtl",
    priority: "specialization", depth: "advanced", difficulty: 4, days: 3, hours: 8, kind: "theory", skills: ["rtl", "arch"],
    why: "Senior RTL designers are judged on microarchitecture choices, not syntax.",
    problem: "The same function can be built many ways. Choosing among them requires reasoning about throughput, latency, area, power and verification cost together.",
    eli12: "To make more sandwiches per minute you can add workers (parallelism), split the job into stations (pipelining), or share one toaster between two stations (resource sharing). Each has a cost.",
    tech: "Techniques: pipelining and retiming, unrolling vs folding (time-multiplexing), resource sharing, precomputation, speculation, operand isolation, memory banking, FIFO depth sizing from traffic models, and latency-insensitive interfaces. Use throughput = items/cycle x frequency; area and energy per item for comparison.",
    inChip: "Datapath-heavy IP: codecs, crypto, accelerators, network processing.",
    breaks: "Overbuilding (area waste) or underbuilding (missing throughput), and designs too complex to verify.",
    tested: "Performance models before RTL and PPA sweeps after.",
    prereqs: ["ppa", "pipelined-rtl"],
    objectives: ["Fold and unfold a datapath", "Size buffers from traffic", "Compare options with a PPA table"],
    terms: [["Folding", "Reusing hardware over multiple cycles"], ["Banking", "Splitting memory for parallel access"]],
    mistakes: ["Optimizing without a throughput requirement"],
    senior: ["What is the smallest design meeting the throughput requirement?", "Which choice minimizes verification risk?"],
    practice: ["Implement a 16-tap FIR fully parallel and folded 4x; compare area, Fmax and throughput"],
    interview: [{ q: "How would you reduce area of a block that has more throughput than needed?", a: "Fold the datapath (time-multiplex operators), share resources across modes, reduce parallel lanes or buffer depths, and check the latency impact against requirements.", level: 3 }],
    resources: ["hennessy-patterson", "orfs"],
    projects: ["fp-ppa-arith"],
  },
  {
    id: "rtl-interconnect", title: "Interconnect design: crossbars, AXI interconnects and NoC basics", phase: "p9", module: "m9-rtl",
    priority: "specialization", depth: "working", difficulty: 4, days: 2, hours: 6, kind: "coding", skills: ["rtl", "protocols"],
    why: "SoC integration is interconnect work; RTL roles often mention AXI interconnect and integration.",
    problem: "Many managers must reach many subordinates concurrently without deadlock or starvation.",
    eli12: "A crossbar is a railway junction where several trains can pass at the same time if they go to different platforms.",
    tech: "Address decode, arbitration per subordinate, ID remapping, response routing, register slices for timing, width and clock converters, deadlock avoidance (ordering rules), QoS. NoCs packetize traffic over routers for large systems.",
    inChip: "SoC fabrics, accelerator memory systems.",
    breaks: "Deadlock, ID collisions, head-of-line blocking.",
    tested: "Random multi-manager traffic, protocol checkers, performance tests.",
    prereqs: ["axi", "arbiters"],
    objectives: ["Build a 2x2 AXI4-Lite crossbar", "Explain ID remapping", "Explain register slices"],
    terms: [["Register slice", "Pipeline stage on a channel for timing"], ["Head-of-line blocking", "A stalled request blocks those behind it"]],
    mistakes: ["No arbitration fairness"],
    practice: ["Study pulp-platform/axi or verilog-axi crossbar code and draw its structure"],
    interview: [{ q: "How can an AXI interconnect deadlock?", a: "Through circular waits across channels or ordering constraints, for example a write data channel blocked waiting for an address that is stuck behind another manager. Rules on dependencies, buffering and ordering prevent it.", level: 4 }],
    resources: ["pulp-axi", "verilog-axi", "amba"],
  },
  {
    id: "rtl-power-intent", title: "Power intent (UPF) and multi-voltage design", phase: "p9", module: "m9-rtl",
    priority: "specialization", depth: "working", difficulty: 4, days: 2, hours: 5, kind: "theory", skills: ["rtl", "asic"],
    why: "RTL roles increasingly list UPF and low-power methodology.",
    problem: "Power gating and multiple voltages need isolation, retention and level shifting described outside RTL so every tool agrees.",
    eli12: "UPF is the electrical plan of the house: which rooms can be switched off, which keep a night light (retention), and which need adapters between voltages.",
    tech: "IEEE 1801 UPF: power domains, supply nets, power switches, isolation strategies, retention strategies, level shifters, power states. Power-aware simulation and static checks.",
    inChip: "Mobile and AI SoCs with aggressive power management.",
    breaks: "Missing isolation, wrong retention, sequencing errors.",
    tested: "Power-aware simulation, static low-power checks.",
    prereqs: ["low-power-rtl"],
    objectives: ["Read a simple UPF file", "Explain isolation and retention", "Plan a power-down sequence"],
    terms: [["Power domain", "Logic sharing a supply that can be controlled"], ["Retention", "Keeping state while powered down"]],
    mistakes: ["Treating power intent as a PD-only concern"],
    practice: ["Write a UPF sketch for a design with an always-on controller and a gated accelerator"],
    interview: [{ q: "Why do powered-down domains need isolation cells?", a: "Outputs of an off domain float or go to X; isolation clamps them to known values so powered-on logic is not corrupted.", level: 2 }],
    resources: ["chipverify"],
  },
  // DV track
  {
    id: "uvm-advanced", title: "Advanced UVM: virtual sequences, overrides, callbacks, RAL", phase: "p9", module: "m9-dv",
    priority: "specialization", depth: "advanced", difficulty: 4, days: 3, hours: 8, kind: "coding", skills: ["verification"],
    why: "Entry DV roles expect UVM basics; strong candidates show reusable environments with RAL and virtual sequences.",
    problem: "Subsystem environments coordinate several agents and register models; reuse needs overrides and callbacks rather than edits.",
    eli12: "A virtual sequence is a conductor coordinating several orchestras (agents). Overrides let you swap one musician for another without rewriting the score.",
    tech: "Virtual sequencers/sequences, factory type and instance overrides, callbacks for error injection, UVM RAL (register model, adapter, predictor, front/back-door access, built-in register tests), environment configuration objects, reusable agent packaging.",
    inChip: "Subsystem and SoC verification, where one environment has to reuse dozens of block-level agents, sequences and register models.",
    breaks: "Tight coupling that prevents reuse; RAL mirror mismatches.",
    tested: "Environment reuse at a higher level; RAL built-in sequences.",
    prereqs: ["uvm-env"],
    objectives: ["Write a virtual sequence across two agents", "Integrate a RAL model", "Use overrides for error injection"],
    terms: [["Virtual sequencer", "Holds handles to agent sequencers"], ["Predictor", "Updates the RAL mirror from observed bus traffic"]],
    mistakes: ["Hard-coding register addresses in sequences"],
    practice: ["Add RAL and a virtual sequence to your UVM environment"],
    interview: [{ q: "What is the difference between front-door and back-door register access?", a: "Front-door uses the bus protocol through the DUT interface (realistic, slower); back-door accesses the register storage directly through hierarchical paths (fast, bypasses bus logic).", level: 3 }],
    resources: ["salemi-uvm", "va-courses", "core-v-verif"],
    projects: ["fp-uvm-env"],
  },
  {
    id: "coverage-closure", title: "Coverage closure and regression analytics", phase: "p9", module: "m9-dv",
    priority: "specialization", depth: "advanced", difficulty: 3, days: 2, hours: 5, kind: "tool", skills: ["verification", "python"],
    why: "Closing coverage efficiently is a key DV skill; analytics is where your software background stands out.",
    problem: "Late-project coverage plateaus. Engineers must find why holes remain and which tests matter.",
    eli12: "When a jigsaw is almost done, the last pieces are the hardest. Closure is finding exactly which pieces are missing and why.",
    tech: "Hole analysis, constraint tuning, directed tests, test grading (which tests add unique coverage), regression optimization, exclusions with justification, dashboards (Python + plots).",
    inChip: "Late-stage DV sign-off, when the team decides whether the remaining coverage holes are real risks or justified waivers.",
    breaks: "Unjustified exclusions; wasted compute on redundant tests.",
    tested: "By a coverage review with the design team, where every excluded bin needs a written justification someone signs off on.",
    prereqs: ["coverage", "regression-ci"],
    objectives: ["Grade tests by unique coverage", "Build a coverage dashboard", "Justify exclusions"],
    terms: [["Test grading", "Ranking tests by coverage contribution"]],
    mistakes: ["Adding seeds instead of analysis"],
    practice: ["Write a Python script ranking your tests by unique coverage bins"],
    interview: [{ q: "Coverage is stuck at 92%. What do you do?", a: "Analyze holes by bin; classify as unreachable (exclude with justification), constraint-limited (adjust), or needing directed tests; check sampling correctness; review with designers.", level: 3 }],
    resources: ["va-courses", "cocotb"],
  },
  {
    id: "formal-advanced", title: "Formal property verification in practice", phase: "p9", module: "m9-dv",
    priority: "specialization", depth: "advanced", difficulty: 4, days: 2, hours: 6, kind: "tool", skills: ["verification"],
    why: "Formal-capable DV engineers are in demand; proofs are strong portfolio evidence.",
    problem: "Full proofs fail on large designs without abstraction and good assumptions.",
    eli12: "Proving something for every possible input is like proving a maze has no exit: you need clever shortcuts to avoid checking every step.",
    tech: "Induction and k-induction, invariants, abstraction of counters and memories, assume-guarantee, cover-driven checks, formal apps (connectivity, X-propagation, sequential equivalence).",
    inChip: "Control logic, security, protocol compliance.",
    breaks: "Over-constraint, bounded proofs mistaken for full proofs.",
    tested: "Cover properties and proof reports.",
    prereqs: ["formal"],
    objectives: ["Achieve a full induction proof on a FIFO", "Use abstraction", "Distinguish bounded vs full proofs"],
    terms: [["k-induction", "Proof technique over k steps"], ["Invariant", "Property true in all reachable states"]],
    mistakes: ["Reporting BMC depth as a proof"],
    practice: ["Prove your arbiter's fairness and your FIFO's count invariant with SymbiYosys"],
    interview: [{ q: "Why might induction fail even though the property is true?", a: "Induction can start from unreachable states; adding helper invariants that exclude them makes the proof go through.", level: 4 }],
    resources: ["sby", "zipcpu"],
  },
  // PD track
  {
    id: "pd-closure-eco", title: "Timing closure in physical design and ECOs", phase: "p9", module: "m9-pd",
    priority: "specialization", depth: "advanced", difficulty: 4, days: 3, hours: 8, kind: "tool", skills: ["pd", "timing"],
    why: "PD and STA engineers spend most time closing timing and applying ECOs.",
    problem: "Post-route violations must be fixed with minimal disturbance to a nearly finished layout.",
    eli12: "Fixing a finished building by moving a few walls without knocking the whole thing down.",
    tech: "Post-route optimization, sizing, buffering, Vt swaps, useful skew, rerouting, metal-only ECOs using spare cells, SI-aware fixing, MCMM closure.",
    inChip: "The final weeks before tapeout, when only small, carefully checked netlist edits are still allowed.",
    breaks: "Fixes that create new violations elsewhere (hold vs setup, DRC).",
    tested: "Signoff STA and DRC after each ECO.",
    prereqs: ["timing-closure", "open-flow"],
    objectives: ["Fix violations in an OpenROAD run", "Explain spare cells and metal ECOs", "Track closure across iterations"],
    terms: [["Spare cells", "Unused cells placed for later fixes"], ["Metal ECO", "Change using only metal layers"]],
    mistakes: ["Fixing hold at the slow corner"],
    practice: ["Tighten the clock in an ORFS run until violations appear and document your fixes"],
    interview: [{ q: "What is a metal-only ECO?", a: "A late change implemented by rewiring metal layers (often using spare cells), avoiding new base-layer masks and saving cost and time.", level: 3 }],
    resources: ["orfs", "openroad", "bhasker-sta"],
  },
  {
    id: "pd-signoff", title: "Signoff: SI, IR drop, EM and physical verification in depth", phase: "p9", module: "m9-pd",
    priority: "specialization", depth: "working", difficulty: 4, days: 2, hours: 5, kind: "theory", skills: ["pd"],
    why: "Signoff is the final gate before tapeout; PD roles expect depth here.",
    problem: "Layouts that pass basic timing can still fail due to crosstalk, power integrity, reliability or rule violations.",
    eli12: "The final inspection checks noise between wires, power reaching every room, wires not wearing out, and every building code.",
    tech: "SI crosstalk delay and glitch, dynamic IR with vector activity, EM limits, DRC categories, LVS debug, antenna fixes, density and fill.",
    inChip: "Signoff teams, who run the final timing, power, DRC and LVS checks that decide whether the design may be taped out.",
    breaks: "Silicon failures under load or over lifetime.",
    tested: "By signoff tool reports: timing, noise, electromigration and IR drop, DRC and LVS must all be clean or formally waived.",
    prereqs: ["routing-signoff"],
    objectives: ["Explain SI effects", "Read IR/EM reports", "Debug an LVS mismatch conceptually"],
    terms: [["Aggressor/victim", "Switching net affecting a neighbour"], ["Dynamic IR", "Voltage drop from switching activity"]],
    mistakes: ["Static IR only"],
    practice: ["Inspect DRC/LVS/antenna reports from a LibreLane run and explain each check"],
    interview: [{ q: "How does crosstalk affect timing?", a: "Opposite-direction switching on an aggressor increases the victim's delay (hurts setup); same-direction switching speeds it (hurts hold). SI-aware STA includes these deltas.", level: 3 }],
    resources: ["klayout", "magic", "librelane"],
  },
  {
    id: "pd-scripting", title: "Flow automation and reporting for PD and STA", phase: "p9", module: "m9-pd",
    priority: "specialization", depth: "working", difficulty: 3, days: 2, hours: 5, kind: "coding", skills: ["tcl", "python", "pd"],
    why: "PD engineers automate constantly; strong scripting differentiates candidates with software backgrounds.",
    problem: "Manual flows and report reading do not scale across corners and iterations.",
    eli12: "Instead of reading a thousand reports, you build a robot that reads them and draws the summary.",
    tech: "Tcl inside tools, Python for report parsing, metric dashboards, design-space sweeps with LibreLane's Python API or ORFS Makefile variables, reproducible experiment logs.",
    inChip: "Every PD team has flow and methodology engineers.",
    breaks: "Brittle scripts tied to one tool version.",
    tested: "Re-running sweeps reproducibly.",
    prereqs: ["tcl-eda", "open-flow", "python-hw"],
    objectives: ["Automate a clock/utilization sweep", "Parse metrics into a table", "Plot QoR trends"],
    terms: [["QoR", "Quality of results"], ["Sweep", "Running a flow across parameter values"]],
    mistakes: ["Scraping logs with fragile regex instead of metrics files"],
    practice: ["Sweep 3 clocks x 3 utilizations for your design and plot WNS and area"],
    interview: [{ q: "How would you automate timing analysis across 20 corners?", a: "Script the tool (Tcl) to load each corner, generate standard reports, parse them with Python into a table, and flag worst paths and trends; run in parallel on a farm.", level: 2 }],
    resources: ["librelane", "orfs"],
  },
  // DFT track
  {
    id: "dft-scan-compression", title: "Scan insertion and test compression", phase: "p9", module: "m9-dft",
    priority: "specialization", depth: "advanced", difficulty: 4, days: 3, hours: 7, kind: "theory", skills: ["dft"],
    why: "Scan insertion is core DFT work; compression determines test cost.",
    problem: "Long scan chains mean long test times; compression shrinks data and time while keeping coverage.",
    eli12: "Instead of reading every locker one by one, you check many lockers at once with a clever summary code.",
    tech: "Scan stitching, chain balancing, lockup latches across clock domains, scan-enable timing, test clocks, on-chip decompressors and compactors, X-masking, test modes in SDC.",
    inChip: "DFT teams; interacts with PD for scan reordering.",
    breaks: "X sources corrupting compacted responses; scan-shift timing failures.",
    tested: "ATPG coverage and pattern simulation.",
    prereqs: ["dft"],
    objectives: ["Explain chain balancing", "Explain decompressor/compactor", "Explain lockup latches"],
    terms: [["Lockup latch", "Latch preventing hold issues between clock domains in scan"], ["X-masking", "Blocking unknown values from compactors"]],
    mistakes: ["Ignoring X sources"],
    practice: ["Insert scan into a small design with OpenROAD's DFT support or the Fault tool and inspect chains"],
    interview: [{ q: "Why is test compression needed?", a: "Tester memory and time are costly; compression feeds many internal chains from few pins and compacts responses, reducing data and time while keeping coverage.", level: 2 }],
    resources: ["fault", "bushnell-agrawal"],
    projects: ["fp-dft-atpg"],
  },
  {
    id: "dft-atpg", title: "Fault models, ATPG and coverage", phase: "p9", module: "m9-dft",
    priority: "specialization", depth: "advanced", difficulty: 4, days: 2, hours: 6, kind: "coding", skills: ["dft", "eda"],
    why: "ATPG is where DFT meets algorithms; implementing one is outstanding evidence.",
    problem: "Finding input patterns that expose each possible defect is a search problem; algorithms like D-algorithm and PODEM solve it.",
    eli12: "For each possible broken wire, find a test question whose answer changes only if that wire is broken.",
    tech: "Stuck-at, transition, path-delay, bridging faults; fault simulation; PODEM backtracing and implication; fault collapsing; coverage vs test count; ISCAS benchmarks.",
    inChip: "DFT and test engineering; EDA ATPG tool development.",
    breaks: "Low coverage letting defects escape.",
    tested: "By fault simulation: test coverage and pattern count measured against the fault list for the design.",
    prereqs: ["dft-scan-compression", "graphs-in-eda"],
    objectives: ["Run fault simulation", "Explain PODEM", "Compute fault coverage"],
    terms: [["Fault collapsing", "Merging equivalent faults"], ["PODEM", "ATPG algorithm deciding primary inputs by backtracing"]],
    mistakes: ["Confusing fault coverage with test coverage definitions"],
    practice: ["Implement stuck-at fault simulation for ISCAS c17 in Python"],
    interview: [{ q: "What are controllability and observability?", a: "Controllability: how easily a node can be set to 0 or 1 from inputs. Observability: how easily its value can be seen at outputs. Scan improves both.", level: 2 }],
    resources: ["bushnell-agrawal", "fault"],
    projects: ["fp-dft-atpg"],
  },
  {
    id: "dft-mbist-jtag", title: "Memory BIST and IEEE 1149.1 JTAG", phase: "p9", module: "m9-dft",
    priority: "specialization", depth: "working", difficulty: 3, days: 2, hours: 5, kind: "coding", skills: ["dft"],
    why: "Memories are most of the die area; JTAG is universal test and debug access.",
    problem: "Memory defects have special patterns; external testing of embedded memories is impractical, so memories test themselves.",
    eli12: "Memory BIST is the memory running its own fitness test; JTAG is a universal service port on every chip.",
    tech: "March algorithms (March C-), MBIST controllers, repair with redundancy; JTAG TAP controller FSM (16 states), instruction and data registers, boundary scan.",
    inChip: "Every SoC with SRAM; board test and debug.",
    breaks: "Missed coupling faults; TAP FSM bugs.",
    tested: "Pattern simulation; board-level boundary scan tests.",
    prereqs: ["dft", "fsm"],
    objectives: ["Implement a March C- test", "Implement the JTAG TAP FSM"],
    terms: [["March test", "Sequence of read/write passes over memory"], ["TAP", "Test access port"]],
    mistakes: ["Testing only with all-0/all-1 patterns"],
    practice: ["Write the 16-state TAP FSM and verify transitions"],
    interview: [{ q: "Why do memories need special test algorithms?", a: "Their faults include coupling and address decoder faults that simple patterns miss; March algorithms systematically read and write in address orders to expose them.", level: 3 }],
    resources: ["bushnell-agrawal"],
  },
  // FPGA track
  {
    id: "fpga-architecture", title: "FPGA architecture: LUTs, BRAM, DSP and routing", phase: "p9", module: "m9-fpga",
    priority: "specialization", depth: "working", difficulty: 3, days: 2, hours: 5, kind: "theory", skills: ["rtl"],
    why: "FPGA roles and prototyping need you to map designs to real FPGA resources.",
    problem: "FPGAs implement logic in configurable blocks; efficient designs match the fabric.",
    eli12: "An FPGA is a box of reprogrammable LEGO: small logic tables, memory blocks and fast math blocks connected by switchable wires.",
    tech: "LUTs, carry chains, flip-flops, BRAM, DSP slices, clocking resources (PLLs, global buffers), routing delay dominance, vendor flows (Vivado, Quartus) and open flows (Yosys + nextpnr for Lattice/Gowin).",
    inChip: "Prototyping, networking, trading systems, defence, AI inference.",
    breaks: "Ignoring routing delay; not using DSP/BRAM leading to huge LUT usage.",
    tested: "Utilization and timing reports.",
    prereqs: ["rtl-guidelines"],
    objectives: ["Map arithmetic to DSPs", "Infer BRAM", "Read utilization reports"],
    terms: [["LUT", "Look-up table implementing small logic functions"], ["DSP slice", "Hard multiply-accumulate block"]],
    mistakes: ["Asynchronous resets everywhere on FPGAs where vendors recommend otherwise"],
    practice: ["Synthesize your FIFO with Yosys for iCE40/ECP5 via nextpnr and read the report"],
    interview: [{ q: "How is FPGA timing different from ASIC timing?", a: "Routing through programmable interconnect dominates delay, resources are fixed, and clocking uses dedicated networks; you close timing by mapping to hard blocks and pipelining more.", level: 2 }],
    resources: ["nextpnr", "apicula", "coursera-fpga"],
  },
  {
    id: "fpga-timing", title: "FPGA timing constraints and closure", phase: "p9", module: "m9-fpga",
    priority: "specialization", depth: "working", difficulty: 3, days: 2, hours: 5, kind: "tool", skills: ["timing"],
    why: "Real FPGA work lives in timing reports and constraints.",
    problem: "FPGA designs fail timing through routing congestion and IO constraints.",
    eli12: "Same timing rules as chips, but the roads are pre-built, so you choose routes wisely.",
    tech: "XDC/SDC constraints, IO timing, clock domain constraints, physical constraints (pblocks), pipelining for routing, retiming options.",
    inChip: "FPGA product teams, where timing closure decides whether the design can actually run at the required clock rate on the chosen device.",
    breaks: "Unconstrained IO; clock crossings without constraints.",
    tested: "By the vendor's post-implementation timing reports: worst negative slack and failing paths for each clock domain.",
    prereqs: ["fpga-architecture", "sdc"],
    objectives: ["Write FPGA constraints", "Close timing on a pipelined design"],
    terms: [["XDC", "Xilinx design constraints (SDC-based)"], ["pblock", "Placement region constraint"]],
    mistakes: ["Unconstrained inputs"],
    practice: ["Close timing on a UART + FIFO design at the highest clock you can"],
    interview: [{ q: "A design fails timing only on routing delay. What do you try?", a: "Pipeline across long routes, reduce fanout with replication, floorplan with placement constraints, and simplify logic near congested regions.", level: 3 }],
    resources: ["nextpnr", "coursera-fpga"],
  },
  {
    id: "fpga-hls-prototype", title: "HLS and FPGA prototyping", phase: "p9", module: "m9-fpga",
    priority: "specialization", depth: "working", difficulty: 3, days: 3, hours: 8, kind: "project", skills: ["rtl", "cpp", "aihw"],
    why: "HLS and prototyping bridge software and hardware, a natural fit for your background.",
    problem: "Writing RTL for complex algorithms is slow; HLS generates RTL from C/C++; prototyping validates designs with real software.",
    eli12: "HLS is writing a recipe in a familiar language and letting a tool design the kitchen.",
    tech: "HLS pragmas (pipeline, unroll, array partition), interface synthesis, co-simulation; LiteX for quickly building SoCs with soft CPUs on FPGAs; hls4ml and FINN for ML inference on FPGAs.",
    inChip: "Accelerator prototyping, ML inference on FPGAs.",
    breaks: "HLS code with unintended serialization; resource blow-up.",
    tested: "C/RTL co-simulation; on-board tests.",
    prereqs: ["fpga-architecture"],
    objectives: ["Build a LiteX SoC", "Explain key HLS pragmas"],
    terms: [["HLS", "High-level synthesis"], ["Initiation interval", "Cycles between new inputs to a pipelined loop"]],
    mistakes: ["Treating HLS as automatic optimization"],
    practice: ["Build a LiteX SoC in simulation and run a C program on it"],
    interview: [{ q: "What is initiation interval in HLS?", a: "The number of cycles between accepting successive inputs in a pipelined loop; II=1 means a new input every cycle.", level: 2 }],
    resources: ["litex", "hls4ml", "finn"],
    projects: ["fp-fpga-accel"],
  },
  // AMS
  {
    id: "analog-blocks", title: "Analog building blocks: current mirrors and amplifiers", phase: "p9", module: "m9-ams",
    priority: "specialization", depth: "basic", difficulty: 4, days: 3, hours: 8, kind: "theory", skills: ["digital"],
    why: "An honest starting point for analog; deep analog roles usually expect formal study (often an M.Tech), so this track is for awareness and exploration.",
    problem: "Real-world signals are continuous; amplifiers, references and filters condition them before conversion.",
    eli12: "Analog circuits are like volume knobs and water taps: they shape smooth signals rather than switching on and off.",
    tech: "MOSFET small-signal model, common-source amplifier, current mirrors, differential pairs, op-amp basics, bandgap references, noise and mismatch. Tools: ngspice, Xschem, Magic with SKY130 (in IIC-OSIC-TOOLS).",
    inChip: "PMICs, sensors, PLLs, SerDes front-ends.",
    breaks: "Mismatch, offset, noise and stability problems.",
    tested: "SPICE simulation across corners; silicon characterization.",
    prereqs: ["mosfet", "cmos-inverter"],
    objectives: ["Simulate a current mirror", "Explain gain of a common-source stage"],
    terms: [["Current mirror", "Copies a reference current"], ["Differential pair", "Amplifies the difference of two inputs"]],
    mistakes: ["Underestimating the depth required for analog roles"],
    practice: ["Simulate a current mirror in ngspice with SKY130 models"],
    interview: [{ q: "What is a current mirror?", a: "Two matched transistors sharing gate voltage so the output transistor copies the reference current, used for biasing.", level: 2 }],
    resources: ["razavi-analog", "iic-osic-tools"],
  },
  {
    id: "data-converters", title: "Data converters and mixed-signal verification", phase: "p9", module: "m9-ams",
    priority: "specialization", depth: "basic", difficulty: 4, days: 4, hours: 8, kind: "theory", skills: ["digital", "verification"],
    why: "Mixed-signal verification is a place where digital verification skills meet analog.",
    problem: "Analog and digital parts must work together; verifying them requires models of analog behaviour.",
    eli12: "An ADC is a translator from smooth sound to numbers; a DAC translates back.",
    tech: "ADC architectures (SAR, pipeline, sigma-delta), resolution, ENOB, sampling; DAC basics; real-number models (SV real, wreal), Verilog-A, mixed-signal co-simulation.",
    inChip: "Sensors, audio, communications.",
    breaks: "Digital calibration bugs; interface timing between domains.",
    tested: "Real-number modeling and co-simulation.",
    prereqs: ["analog-blocks"],
    objectives: ["Explain SAR ADC operation", "Write a real-number model"],
    terms: [["ENOB", "Effective number of bits"], ["RNM", "Real-number modeling"]],
    mistakes: ["Assuming digital-only verification covers mixed-signal"],
    practice: ["Model a SAR ADC in SystemVerilog with real values and verify its digital controller"],
    interview: [{ q: "How does a SAR ADC work?", a: "It performs a binary search with a DAC and comparator, deciding one bit per cycle from MSB to LSB.", level: 2 }],
    resources: ["razavi-analog"],
  },
  // Validation
  {
    id: "silicon-validation", title: "Post-silicon validation and bring-up", phase: "p9", module: "m9-val",
    priority: "specialization", depth: "working", difficulty: 3, days: 4, hours: 8, kind: "theory", skills: ["python", "cpp"],
    why: "Validation roles often hire EE graduates with strong software skills.",
    problem: "Real silicon behaves differently from models; bugs must be found and debugged with limited visibility.",
    eli12: "Validation engineers are the first people to take a new car on real roads and find out what the test track missed.",
    tech: "Bring-up plans, board setup, JTAG debug, on-chip debug and trace, validation test content, characterization across PVT, failure analysis workflows, errata.",
    inChip: "Product validation teams, who are the first to run real software on real silicon and find what simulation missed.",
    breaks: "Poor debug visibility slowing root cause.",
    tested: "Validation plans and coverage.",
    prereqs: ["tapeout", "c-for-hw"],
    objectives: ["Write a bring-up plan", "Describe silicon debug techniques"],
    terms: [["Characterization", "Measuring behaviour across conditions"], ["Shmoo plot", "Pass/fail map over voltage and frequency"]],
    mistakes: ["Assuming the lab reproduces bugs easily"],
    practice: ["Write a bring-up checklist for your FPGA SoC"],
    interview: [{ q: "What is a shmoo plot?", a: "A grid of pass/fail results across two parameters (often voltage and frequency) showing the operating region of a chip.", level: 2 }],
    resources: [],
  },
  {
    id: "validation-automation", title: "Lab automation with Python", phase: "p9", module: "m9-val",
    priority: "specialization", depth: "working", difficulty: 2, days: 3, hours: 6, kind: "coding", skills: ["python"],
    why: "Validation is automation-heavy; your software skills are a direct advantage.",
    problem: "Manual lab measurements are slow and error-prone.",
    eli12: "Instead of turning knobs by hand, a script turns them and records results.",
    tech: "Instrument control (SCPI via PyVISA), serial/JTAG scripting, test frameworks, data logging, analysis and dashboards.",
    inChip: "Validation labs, where racks of boards run automated test suites day and night without an engineer watching.",
    breaks: "Manual steps nobody can repeat: a failure that cannot be reproduced on demand cannot be debugged, and a fix cannot be proven.",
    tested: "Automated regression in the lab.",
    prereqs: ["silicon-validation", "python-hw"],
    objectives: ["Script a test over a serial interface", "Log and plot results"],
    terms: [["SCPI", "Standard commands for programmable instruments"]],
    mistakes: ["No data provenance"],
    practice: ["Automate tests of your FPGA UART design from Python and plot results"],
    interview: [{ q: "How would you automate a voltage-frequency sweep?", a: "Control supply and clock via instrument APIs, run the test at each point, log pass/fail and measurements, and plot a shmoo.", level: 2 }],
    resources: ["python-docs"],
  },
  // EDA
  {
    id: "eda-algorithms", title: "Core EDA algorithms: partitioning, placement, routing", phase: "p9", module: "m9-eda",
    priority: "specialization", depth: "advanced", difficulty: 4, days: 4, hours: 10, kind: "coding", skills: ["eda", "python", "cpp"],
    why: "EDA companies hire software engineers who understand hardware; this is a strong fit for your background.",
    problem: "Chip design problems are NP-hard at huge scale; heuristics and numerical optimization make them tractable.",
    eli12: "EDA algorithms solve giant puzzles: cutting circuits into pieces, seating millions of gates, and drawing all the wires.",
    tech: "Fiduccia-Mattheyses partitioning, simulated annealing, analytical (quadratic and nonlinear) placement, maze and pattern routing, Steiner trees, static timing algorithms, logic optimization with AIGs.",
    inChip: "Synopsys, Cadence, Siemens EDA and open-source tool teams.",
    breaks: "Algorithms that do not scale or produce poor QoR.",
    tested: "Benchmarks (ISPD contest suites) and QoR comparisons.",
    prereqs: ["graphs-in-eda"],
    objectives: ["Implement FM partitioning", "Implement a simple annealing placer", "Explain analytical placement"],
    terms: [["Simulated annealing", "Randomized optimization accepting some worse moves"], ["Steiner tree", "Minimal network connecting points with extra junctions"]],
    mistakes: ["Ignoring runtime complexity"],
    practice: ["Implement FM partitioning on a small hypergraph and compare cut sizes"],
    interview: [{ q: "How does simulated annealing avoid local minima?", a: "It sometimes accepts worse solutions with a probability that decreases as the temperature cools, allowing escape from local minima early on.", level: 2 }],
    resources: ["kahng-pd", "dreamplace", "openroad"],
    projects: ["fp-macro-placement"],
  },
  {
    id: "eda-tooling", title: "Building on open-source EDA (Yosys, OpenROAD Python APIs)", phase: "p9", module: "m9-eda",
    priority: "specialization", depth: "working", difficulty: 3, days: 3, hours: 8, kind: "coding", skills: ["eda", "python", "cpp"],
    why: "Contributions to open-source EDA are highly visible evidence for EDA roles.",
    problem: "Real EDA tools are large codebases; learning to extend them is a practical skill.",
    eli12: "Instead of only using the chip-design robots, you learn to upgrade them.",
    tech: "Yosys passes and plugins, Yosys JSON netlists, OpenROAD Python/Tcl APIs and database (OpenDB), LibreLane custom steps, contributing via issues and pull requests with tests.",
    inChip: "EDA engineering and CAD/methodology teams.",
    breaks: "Patches without tests are rejected.",
    tested: "By upstream CI and code review: your change must pass the project's own test suite before maintainers will merge it.",
    prereqs: ["eda-algorithms", "open-flow"],
    objectives: ["Write a Yosys script-based analysis", "Query OpenDB with Python", "Open a good-first-issue contribution"],
    terms: [["OpenDB", "OpenROAD's design database"], ["Pass", "A Yosys transformation step"]],
    mistakes: ["Large first pull requests"],
    practice: ["Write a LibreLane custom step or an OpenROAD Python script that reports fanout statistics"],
    interview: [{ q: "How would you add a custom check to a flow?", a: "Implement it as a script or plugin using the tool API (for example OpenDB), integrate it as a flow step, test it on small designs, and report metrics.", level: 2 }],
    resources: ["yosys", "openroad", "librelane"],
  },
  // Architecture
  {
    id: "perf-modeling", title: "Performance modeling and simulation (gem5, trace-driven)", phase: "p9", module: "m9-arch",
    priority: "specialization", depth: "working", difficulty: 4, days: 4, hours: 10, kind: "coding", skills: ["arch", "cpp", "python"],
    why: "Architecture roles evaluate ideas with simulators before RTL.",
    problem: "Building RTL to evaluate every idea is too slow; models answer 'is it worth it?' quickly.",
    eli12: "Before building a new road, planners simulate traffic on a computer to see if it helps.",
    tech: "Trace-driven vs execution-driven simulation, cycle-level models, gem5 configuration, ChampSim for branch/cache research, statistical sampling, validating models against RTL.",
    inChip: "CPU/GPU/accelerator architecture teams.",
    breaks: "Unvalidated models producing misleading conclusions.",
    tested: "Correlation against RTL or hardware.",
    prereqs: ["caches", "branch-prediction", "c-for-hw"],
    objectives: ["Run a gem5 or ChampSim experiment", "Compare two cache configurations"],
    terms: [["Trace-driven", "Simulation replaying recorded instruction or address streams"]],
    mistakes: ["Reporting simulation results without methodology"],
    practice: ["Run ChampSim with two predictors and compare MPKI"],
    interview: [{ q: "Why use a performance model instead of RTL?", a: "Models are faster to change and run, enabling design-space exploration early; RTL comes after the architecture is chosen.", level: 2 }],
    resources: ["gem5", "champsim"],
    projects: ["fp-branch-pred"],
  },
  {
    id: "arch-memory-systems", title: "Advanced memory systems: prefetching and DRAM", phase: "p9", module: "m9-arch",
    priority: "specialization", depth: "working", difficulty: 4, days: 3, hours: 7, kind: "theory", skills: ["arch"],
    why: "Memory systems dominate performance for CPUs and AI hardware.",
    problem: "Caches alone cannot hide DRAM latency; prefetching and smart memory controllers help.",
    eli12: "A prefetcher guesses what you will ask for next and fetches it early.",
    tech: "Stride and stream prefetchers, accuracy and coverage, DRAM organization (banks, rows), row-buffer hits, scheduling (FR-FCFS), bandwidth vs latency.",
    inChip: "Memory controller and cache design.",
    breaks: "Prefetchers polluting caches and wasting bandwidth.",
    tested: "By simulation with real workloads and traces, comparing miss rates, bandwidth and latency against a known baseline.",
    prereqs: ["caches", "memory-hierarchy"],
    objectives: ["Implement a stride prefetcher in a simulator", "Explain row-buffer locality"],
    terms: [["Row buffer", "DRAM's open-row cache"], ["Prefetch accuracy", "Useful prefetches / all prefetches"]],
    mistakes: ["Measuring coverage without accuracy"],
    practice: ["Add a stride prefetcher to your Python cache simulator"],
    interview: [{ q: "What makes a prefetcher harmful?", a: "Low accuracy wastes bandwidth and evicts useful lines (pollution); mistimed prefetches arrive too late or too early.", level: 3 }],
    resources: ["mutlu-yt", "hennessy-patterson"],
  },
];
