import type { CareerPath } from "./schema.ts";

export const CAREERS: CareerPath[] = [
  {
    id: "rtl", title: "RTL design", track: "rtl", roleTarget: "rtl",
    does: "Turns specifications into microarchitecture and synthesizable Verilog/SystemVerilog, then works with verification, synthesis, STA, DFT and PD until the block is clean.",
    builds: "IP blocks: controllers, datapaths, bus interfaces, FIFOs, accelerators.",
    skills: ["Digital design", "Verilog/SystemVerilog", "Microarchitecture", "CDC and resets", "Timing awareness", "Lint and synthesis", "Protocols (AMBA)"],
    tools: ["Simulators (VCS, Xcelium, Questa; Verilator/Icarus)", "Lint/CDC (SpyGlass, Questa CDC)", "Synthesis (DC/Genus; Yosys)", "STA (PrimeTime/Tempus; OpenSTA)"],
    programming: ["SystemVerilog", "Python", "Tcl", "Perl/shell"], interviewTopics: ["FSM design", "FIFOs", "CDC", "setup/hold", "pipelining", "protocols", "coding on whiteboard"],
    eeFit: "Strong: EE digital and circuits background maps directly.", mtech: "Many large-company RTL roles prefer an M.Tech or experience; startups and services companies weigh portfolios more. Sampled 2026 postings for experienced RTL roles accepted B.E./B.Tech with experience.",
    entryPath: "Strong fundamentals, 2-3 RTL flagships with verification and synthesis results, then trainee/graduate roles, services companies, or internships.",
    advanced: ["Microarchitecture ownership", "PPA optimization", "Low-power design (UPF)", "Subsystem integration"],
    projects: ["fp-rv-pipeline", "fp-async-fifo", "fp-axi-apb", "fp-cache", "fp-ppa-arith"], companies: ["Semiconductor product companies", "IP vendors", "Design services firms", "AI hardware startups"],
  },
  {
    id: "dv", title: "Design verification", track: "dv", roleTarget: "dv",
    does: "Plans and builds testbenches that prove designs match the spec: constrained-random stimulus, checkers, assertions, coverage and debugging with designers.",
    builds: "UVM environments, verification IP, reference models, regressions and coverage closure.",
    skills: ["SystemVerilog", "UVM", "SVA", "Functional coverage", "Debugging", "Protocols", "Scripting"],
    tools: ["Simulators", "UVM", "Formal tools", "Coverage and regression tools"], programming: ["SystemVerilog", "Python", "C/C++ (DPI)", "Perl/shell"],
    interviewTopics: ["OOP in SV", "randomization", "UVM phases/factory", "SVA", "coverage", "testbench architecture", "debug scenarios"],
    eeFit: "Strong, especially with software experience (OOP, testing discipline).", mtech: "Often not required for entry roles; new-graduate postings sampled in 2026 asked for BS with coursework or projects in design/verification and Verilog/SV familiarity.",
    entryPath: "UVM and cocotb flagships with coverage and bug logs, mock interviews, then DV trainee/NCG roles or services companies.",
    advanced: ["Subsystem/SoC verification", "Formal", "Verification methodology", "Performance verification"],
    projects: ["fp-uvm-env", "fp-async-fifo", "fp-rv-pipeline", "fp-llm-hw"], companies: ["Product companies", "Verification services firms", "EDA vendors (application engineering)"],
  },
  {
    id: "pd", title: "Physical design", track: "pd", roleTarget: "pd",
    does: "Implements netlists into layout: floorplan, placement, clock tree, routing, timing and power closure, and signoff checks.",
    builds: "Timing-closed, DRC/LVS-clean blocks and chips ready for tapeout.",
    skills: ["ASIC flow", "STA", "Floorplanning", "CTS", "Routing", "IR/EM", "Tcl scripting"],
    tools: ["Innovus / ICC2 / Fusion Compiler", "PrimeTime / Tempus", "Calibre/Pegasus", "OpenROAD, LibreLane (open)"], programming: ["Tcl", "Python", "Perl/shell"],
    interviewTopics: ["Setup/hold fixing", "CTS", "congestion", "floorplan decisions", "IR drop", "DRC/LVS", "OCV"],
    eeFit: "Good: circuits and physics intuition help.", mtech: "Frequently preferred for large-company PD roles; commercial tool experience matters, which is why structured programmes with licences (for example C-DAC) are relevant.",
    entryPath: "Open-flow projects with PPA analysis, strong STA fundamentals, Tcl automation; consider programmes with licensed tools.",
    advanced: ["Full-chip integration", "Low-power implementation", "Advanced-node signoff"],
    projects: ["fp-open-silicon", "fp-ppa-arith", "fp-macro-placement"], companies: ["Product companies", "Design services firms", "Foundry design enablement"],
  },
  {
    id: "sta", title: "Static timing analysis", track: "pd",
    does: "Owns timing constraints and signoff across corners and modes, guiding RTL and PD teams to closure.",
    builds: "Constraint sets, timing signoff reports, ECO guidance.",
    skills: ["STA theory", "SDC", "Corners/OCV", "Clocking", "Tcl"], tools: ["PrimeTime/Tempus", "OpenSTA"], programming: ["Tcl", "Python"],
    interviewTopics: ["Slack computation", "multicycle/false paths", "clock groups", "OCV/CRPR", "SI"], eeFit: "Good.", mtech: "Often grown from PD or RTL experience; entry via PD roles is common.",
    entryPath: "Master STA fundamentals and SDC through open-tool projects; enter via PD or RTL roles.",
    advanced: ["Signoff methodology", "Timing ECO flows"], projects: ["fp-ppa-arith", "fp-open-silicon"], companies: ["Product companies", "Services firms"],
  },
  {
    id: "dft", title: "Design for test (DFT)", track: "dft", roleTarget: "dft",
    does: "Makes chips testable: scan insertion, compression, ATPG, MBIST, JTAG, and works with test engineering on coverage and test time.",
    builds: "Test architectures, pattern sets, coverage reports.",
    skills: ["Scan and compression", "Fault models", "ATPG", "MBIST", "JTAG", "STA in test modes"], tools: ["Tessent / Modus / TestMAX", "Simulation", "Open tools for learning (Fault, OpenROAD DFT)"],
    programming: ["Tcl", "Python", "Verilog"], interviewTopics: ["Scan shift/capture", "stuck-at vs transition", "compression", "lockup latches", "MBIST algorithms"],
    eeFit: "Good.", mtech: "Frequently entered through training programmes; commercial tools are central.",
    entryPath: "DFT flagship with ATPG implementation plus scan insertion; structured programmes for tool exposure.",
    advanced: ["Hierarchical DFT", "In-system test", "Silicon debug"], projects: ["fp-dft-atpg"], companies: ["Product companies", "Services firms", "EDA vendors"],
  },
  {
    id: "fpga", title: "FPGA design", track: "fpga", roleTarget: "fpga",
    does: "Designs and closes timing on FPGA implementations for products, prototypes or acceleration.",
    builds: "FPGA IP, prototypes, accelerators, interfaces.",
    skills: ["RTL", "FPGA architecture", "Timing constraints", "Interfaces", "HLS (optional)", "Lab debug"], tools: ["Vivado, Quartus", "Yosys/nextpnr", "Logic analyzers (ILA/SignalTap)"],
    programming: ["Verilog/VHDL", "C/C++", "Python", "Tcl"], interviewTopics: ["Timing closure", "CDC", "resource mapping", "protocols", "debug on hardware"],
    eeFit: "Strong.", mtech: "Often not required; demos on real boards are persuasive.",
    entryPath: "FPGA accelerator and UART/SoC demos on real hardware; embedded or FPGA roles.",
    advanced: ["High-speed interfaces", "Partial reconfiguration", "Prototyping for ASIC"], projects: ["fp-fpga-accel", "fp-capstone"], companies: ["Defence and aerospace", "Networking", "Test equipment", "AI inference startups"],
  },
  {
    id: "analog", title: "Analog IC design", track: "ams",
    does: "Designs amplifiers, references, data converters, PLLs and IO circuits at transistor level.",
    builds: "Analog blocks and characterization data.",
    skills: ["Device physics", "Small-signal analysis", "Feedback and stability", "Noise", "Layout awareness"], tools: ["Virtuoso/Spectre", "ngspice/Xschem/Magic (open)"], programming: ["SKILL", "Python", "Verilog-A"],
    interviewTopics: ["Amplifier design", "current mirrors", "stability", "noise", "matching"], eeFit: "Strong theoretical fit.", mtech: "Usually strongly preferred or required; self-study alone is rarely enough for analog roles.",
    entryPath: "If this is your passion, plan for formal study (M.Tech) or research positions; build open-PDK analog projects.",
    advanced: ["Data converter and PLL design"], projects: ["fp-open-silicon"], companies: ["Analog/mixed-signal product companies"],
  },
  {
    id: "mixed", title: "Mixed-signal design and verification", track: "ams",
    does: "Integrates and verifies analog and digital parts: real-number models, co-simulation, calibration logic.",
    builds: "Mixed-signal verification environments, behavioural models.",
    skills: ["Digital verification", "Analog basics", "Real-number modeling", "Verilog-A"], tools: ["Mixed-signal simulators"], programming: ["SystemVerilog", "Verilog-A", "Python"],
    interviewTopics: ["RNM", "ADC basics", "co-simulation"], eeFit: "Good.", mtech: "Often preferred; mixed-signal verification can be entered from DV.",
    entryPath: "Strong DV skills plus a real-number modeling project.", advanced: ["AMS methodology"], projects: ["fp-uvm-env"], companies: ["AMS product companies"],
  },
  {
    id: "validation", title: "Silicon validation", track: "validation",
    does: "Brings up new silicon in the lab, runs validation content, characterizes across conditions, and debugs failures with design teams.",
    builds: "Validation plans, lab automation, debug reports.",
    skills: ["Lab instruments", "Board bring-up", "C/Python", "Debug", "Protocols"], tools: ["Oscilloscopes, logic analyzers", "JTAG debuggers", "Python automation"], programming: ["Python", "C"],
    interviewTopics: ["Bring-up steps", "debug approach", "protocol basics", "automation"], eeFit: "Strong: EE lab skills plus software.", mtech: "Often not required.",
    entryPath: "FPGA demos, automation scripts, capstone bring-up story.", advanced: ["System validation", "Characterization methodology"], projects: ["fp-capstone", "fp-fpga-accel"], companies: ["Product companies with post-silicon teams"],
  },
  {
    id: "eda", title: "EDA engineering", track: "eda", roleTarget: "eda",
    does: "Builds and maintains the software that designs chips: algorithms, tool features, flows, and customer support engineering.",
    builds: "Tool features, algorithms, flow infrastructure.",
    skills: ["Algorithms and data structures", "C++/Python", "Graph algorithms", "Optimization", "Hardware understanding"], tools: ["C++ toolchains", "Open-source EDA (Yosys, OpenROAD)"], programming: ["C++", "Python", "Tcl"],
    interviewTopics: ["DSA", "graph algorithms", "system design", "EDA basics (STA, placement)"], eeFit: "Excellent with a software background.", mtech: "Varies; strong software skills and relevant projects can compensate.",
    entryPath: "DSA + EDA algorithm projects (ATPG, placement), open-source EDA contributions.",
    advanced: ["Algorithm R&D", "Tool architecture"], projects: ["fp-dft-atpg", "fp-macro-placement", "fp-ppa-arith"], companies: ["EDA vendors", "CAD teams at chip companies", "Open-source EDA companies"],
  },
  {
    id: "arch", title: "Computer architecture / performance modeling", track: "arch",
    does: "Evaluates and defines processor and accelerator architectures using models and simulators before RTL.",
    builds: "Performance models, studies, architecture specs.",
    skills: ["Architecture", "Simulation", "C++/Python", "Statistics"], tools: ["gem5", "ChampSim", "In-house simulators"], programming: ["C++", "Python"],
    interviewTopics: ["Caches", "pipelines", "branch prediction", "memory systems", "performance analysis"], eeFit: "Good.", mtech: "Often preferred (MS/PhD common in research-heavy teams).",
    entryPath: "Research-style studies (branch predictor, cache) with rigorous methodology.", advanced: ["Architecture definition"], projects: ["fp-branch-pred", "fp-cache", "fp-rv-pipeline"], companies: ["CPU/GPU/accelerator companies"],
  },
  {
    id: "aihw", title: "AI hardware", track: "rtl", roleTarget: "aihw",
    does: "Designs, models and verifies accelerators for neural networks: dataflows, memory systems, numerics.",
    builds: "Accelerator RTL, performance models, quantization-aware datapaths.",
    skills: ["RTL", "Architecture", "Numerics/quantization", "Roofline", "ML basics"], tools: ["Simulators", "Python/PyTorch", "FPGA tools"], programming: ["SystemVerilog", "Python", "C++"],
    interviewTopics: ["MAC arrays", "dataflows", "memory bandwidth", "quantization", "transformers"], eeFit: "Good, especially combined with ML interest.", mtech: "Research-heavy roles prefer advanced degrees; RTL/DV roles on accelerators hire from those tracks.",
    entryPath: "Enter via RTL or DV with accelerator flagships; grow into architecture.", advanced: ["Accelerator architecture", "Compiler/hardware co-design"], projects: ["fp-fpga-accel", "fp-attention", "fp-capstone"], companies: ["AI accelerator startups", "GPU/NPU companies", "Cloud providers' silicon teams"],
  },
  {
    id: "aieda", title: "AI for EDA", track: "eda",
    does: "Applies ML and LLMs to chip design problems: prediction, optimization, generation and verification assistance.",
    builds: "Models, datasets, flow integrations, evaluation harnesses.",
    skills: ["ML", "EDA flow knowledge", "Python", "Evaluation methodology"], tools: ["PyTorch", "OpenROAD", "CircuitNet"], programming: ["Python", "C++"],
    interviewTopics: ["ML fundamentals", "data leakage", "EDA basics", "research papers"], eeFit: "Good with software and ML skills.", mtech: "Research roles usually prefer MS/PhD; engineering roles value strong projects.",
    entryPath: "Research-style flagship (ML-for-EDA or LLM evaluation) plus EDA fundamentals. Treat as specialization, not a shortcut.",
    advanced: ["Research", "Tool productization"], projects: ["fp-ml-eda", "fp-llm-hw", "fp-macro-placement"], companies: ["EDA vendors", "Chip companies' CAD/AI groups", "Research labs"],
  },
];

export const CAREER_MAP: Record<string, CareerPath> = Object.fromEntries(CAREERS.map((c) => [c.id, c]));
