import type { CertClass, Certification } from "./schema.ts";

const V = "2026-09-22";

export const CERT_CLASSES: Record<CertClass, { label: string; meaning: string }> = {
  high: { label: "High value", meaning: "Strong, verifiable evidence of useful professional capability." },
  useful: { label: "Useful", meaning: "Can complement a strong portfolio; low cost relative to value." },
  optional: { label: "Optional", meaning: "May help for specific paths or if you already have access." },
  low: { label: "Low priority", meaning: "Little benefit compared with spending the same time on projects." },
  "not-recommended": { label: "Not recommended", meaning: "Do not spend money or time unless you have a specific reason." },
};

export const CERTIFICATIONS: Certification[] = [
  {
    id: "cdac-pgdvlsi", name: "C-DAC PG Diploma / PG Certificate Programme in VLSI Design (PG-DVLSI)", issuer: "C-DAC (Ministry of Electronics and IT, Govt. of India)",
    url: "https://cdac.in/?id=DVLSI", verified: true, lastVerified: V,
    status: "Active. C-DAC states its 900-hour PG Diploma courses are being upgraded to 1200-hour (24-week) Post Graduate Certificate Programmes; admission via C-CAT (January and July cycles).",
    cost: "Paid. Check the official brochure; older secondary sources (2019) cited about Rs 90,000 + GST, likely higher now.", pricing: "paid",
    format: "Full-time course with entrance exam (C-CAT), labs and project; campus placement programme", prerequisites: "C-CAT covers digital electronics, computer architecture, C, data structures, aptitude",
    eligibility: "Engineering graduate (BE/B.Tech in relevant branches) with minimum marks (about 55% per secondary sources; confirm in brochure)",
    degreeRequired: "Yes, an engineering degree (your B.Tech EE qualifies subject to marks)", mtechRequired: "No",
    depth: "Broad industry-oriented VLSI coverage: digital design, HDLs, verification, ASIC flow, FPGA, analog basics", recognition: "Well known in India; runs for over two decades with a common campus placement programme",
    roles: ["rtl", "dv", "fpga", "pd"], employerMentions: "Rarely named as a requirement in postings, but a common hiring pipeline in India via C-DAC placement drives",
    toolExposure: "Typically includes lab access to industry EDA tools (verify for your centre)", labs: "Yes", time: "About 6 months full-time", difficulty: "Moderate", renewal: "None", geography: "India",
    classification: "high",
    rationale: "For an EE graduate in India without an M.Tech, this is one of the few structured routes combining licensed-tool labs, a project and a placement pipeline. It costs 6 months full-time and a significant fee, so pursue it if self-study momentum or tool access is your bottleneck. Keep building your flagship projects either way.",
    chain: { skill: "Commercial-tool workflow (simulation, synthesis, STA)", project: "Course project + your flagship repos", evidence: "Diploma + project report + GitHub", role: "RTL/DV/PD trainee or graduate engineer" },
  },
  {
    id: "nptel-cert", name: "NPTEL proctored certificates (for example Hardware Modeling using Verilog, IIT Kharagpur)", issuer: "NPTEL (IITs and IISc)",
    url: "https://onlinecourses.nptel.ac.in/noc22_cs94/preview", verified: true, lastVerified: V,
    status: "Active; courses run in semesters with proctored exams in India.", cost: "Content free; proctored exam fee historically about Rs 1,000 (Careers360 cites Rs 500-1,000 in 2026).", pricing: "free-to-audit",
    format: "Online course (weekly assignments) + in-person proctored exam", prerequisites: "Course-specific (for Verilog: digital basics and some programming)", eligibility: "Open to all",
    degreeRequired: "No", mtechRequired: "No", depth: "Academic, solid fundamentals; limited industry tool exposure", recognition: "Widely recognized in Indian academia; scored certificate with name and photo",
    roles: ["rtl", "dv"], employerMentions: "Rarely required; occasionally noted favourably by Indian recruiters", toolExposure: "Low", labs: "Assignments only", time: "4-12 weeks per course", difficulty: "Easy to moderate", renewal: "None", geography: "India",
    classification: "useful",
    rationale: "Very low cost, IIT-faculty content, and a proctored score. It will not replace projects, but a strong score in Verilog or VLSI courses is cheap supporting evidence of fundamentals for an Indian resume.",
    chain: { skill: "Verilog fundamentals", project: "ALU, FSM and FIFO micro-projects", evidence: "Scored certificate + repos", role: "Fresher RTL/DV screening" },
  },
  {
    id: "tiny-tapeout", name: "Design fabricated through Tiny Tapeout (public shuttle)", issuer: "Tiny Tapeout",
    url: "https://tinytapeout.com/", verified: true, lastVerified: V,
    status: "Active shuttles in 2025-2026 on SkyWater 130 (via ChipFoundry) and IHP SG13G2; check open shuttles.", cost: "Paid per tile; use the official price calculator (a 2025 report cited about EUR 70 per tile planned).", pricing: "paid",
    format: "Design submission to a multi-project shuttle; public chip page lists your design", prerequisites: "A working, verified design that fits a tile", eligibility: "Open to all",
    degreeRequired: "No", mtechRequired: "No", depth: "Real end-to-end flow on an open PDK; depth depends on your design", recognition: "Publicly verifiable; well known in open-silicon community and education",
    roles: ["rtl", "pd", "dv"], employerMentions: "Not a certification; interviewers value real tapeout artifacts", toolExposure: "Open-source flow (LibreLane-based)", labs: "Hands-on", time: "Weeks of design; months until silicon", difficulty: "Moderate", renewal: "None", geography: "Global",
    classification: "high",
    rationale: "Not a certificate but a verifiable piece of silicon with your name on a public chip map. For a candidate without a VLSI degree this is unusually strong proof of end-to-end capability. Budget and timing permitting, submit your Phase 8 design.",
    chain: { skill: "RTL-to-GDS flow", project: "fp-open-silicon", evidence: "Public shuttle page + repo + GDS", role: "RTL/PD/DV entry roles" },
  },
  {
    id: "lfd111x", name: "Building a RISC-V CPU Core (LFD111x)", issuer: "Linux Foundation and RISC-V International (on edX)",
    verified: false, lastVerified: V,
    status: "Listed by the Linux Foundation as free to audit on edX (per 2022 announcement); confirm current availability on edX.", cost: "Free to audit; optional paid verified certificate", pricing: "free-to-audit",
    format: "Self-paced online course using Makerchip and TL-Verilog", prerequisites: "Digital logic basics", eligibility: "Open to all",
    degreeRequired: "No", mtechRequired: "No", depth: "Hands-on CPU construction; introductory to intermediate", recognition: "Known in RISC-V education",
    roles: ["rtl", "arch"], employerMentions: "Not typically named", toolExposure: "Makerchip (browser)", labs: "Yes", time: "A few weeks", difficulty: "Moderate", renewal: "None", geography: "Global",
    classification: "useful",
    rationale: "Free, practical and aligned with Phase 3. Take the course for the learning; skip the paid certificate unless it is cheap for you.",
    chain: { skill: "CPU datapath design", project: "fp-rv-pipeline", evidence: "Your own core repo", role: "RTL/architecture" },
  },
  {
    id: "rvfa", name: "RISC-V Foundational Associate (RVFA)", issuer: "Linux Foundation with RISC-V International",
    url: "https://training.linuxfoundation.org/certification/linux-foundation-risc-v-foundational-associate/", verified: true, lastVerified: V,
    status: "Active", cost: "US$250 exam only; US$299 with LFS210 course; US$495 with THRIVE-ONE subscription (official page)", pricing: "paid",
    format: "90-minute multiple-choice online exam", prerequisites: "Familiarity with Git, C, GDB and system architecture", eligibility: "Open to all",
    degreeRequired: "No", mtechRequired: "No", depth: "Foundational: ISA, assembly, C on RISC-V, toolchains", recognition: "Official RISC-V credential; employer adoption not evident in the postings we reviewed",
    roles: ["rtl", "dv", "arch"], employerMentions: "Not found in the sampled 2026 job postings", toolExposure: "Toolchain knowledge, no hardware tools", labs: "No", time: "2-4 weeks of study", difficulty: "Easy to moderate", renewal: "Check official terms", geography: "Global",
    classification: "optional",
    rationale: "Multiple-choice and software-leaning; a working RISC-V core with co-simulation is far stronger evidence. Consider only if you target RISC-V companies and the fee is easy to absorb.",
    chain: { skill: "RISC-V ISA", project: "fp-rv-pipeline", evidence: "Badge + core repo", role: "RISC-V DV/RTL" },
  },
  {
    id: "verification-academy", name: "Verification Academy courses (free)", issuer: "Siemens EDA",
    url: "https://verificationacademy.com/courses", verified: true, lastVerified: V,
    status: "Active; free registration", cost: "Free", pricing: "free",
    format: "Video tracks, cookbook, forums (not a certification)", prerequisites: "Varies", eligibility: "Open with registration",
    degreeRequired: "No", mtechRequired: "No", depth: "Deep and industry-authored (UVM, formal, coverage)", recognition: "Widely used by DV engineers",
    roles: ["dv"], employerMentions: "Not a credential; knowledge is what interviews test", toolExposure: "Questa concepts", labs: "Limited", time: "Self-paced", difficulty: "Moderate to advanced", renewal: "None", geography: "Global",
    classification: "useful",
    rationale: "One of the best free DV learning sources. Treat it as learning, not a credential.",
  },
  {
    id: "siemens-badges", name: "Siemens Xcelerator Academy digital badges (for example Questa Verification IP)", issuer: "Siemens Digital Industries Software",
    verified: true, lastVerified: V,
    status: "Active; badges issued via Credly", cost: "Some badge exams listed as free; full self-paced training subscriptions are paid", pricing: "paid",
    format: "Online exam (for example 50 questions, 90% pass) after training", prerequisites: "Siemens Support Center account; course content", eligibility: "Typically customers or academic users",
    degreeRequired: "No", mtechRequired: "No", depth: "Tool- and methodology-specific", recognition: "Vendor badge; verifiable on Credly",
    roles: ["dv"], employerMentions: "Rare", toolExposure: "Questa (in training environments)", labs: "Yes in paid courses", time: "Days to weeks", difficulty: "Moderate", renewal: "Check badge terms", geography: "Global",
    classification: "optional",
    rationale: "Worth it only if you already have access through an employer, university or programme. Not a priority to pay for independently.",
  },
  {
    id: "cadence-badges", name: "Cadence Training digital badges", issuer: "Cadence Design Systems",
    verified: true, lastVerified: V,
    status: "Active; 75+ badges across Cadence courses, verified via Credly", cost: "Badge exams free after completing a Cadence course; course access needs a Cadence support account (customers) or university program", pricing: "paid",
    format: "About 50-question exam after an online or instructor-led course", prerequisites: "Cadence Learning and Support access (host ID) or university enrolment with professor approval", eligibility: "Customers and academic users",
    degreeRequired: "No, but access usually comes through an employer or university", mtechRequired: "No", depth: "Tool-specific (Genus, Innovus, Tempus, Xcelium, Virtuoso, and more)", recognition: "Vendor badge",
    roles: ["pd", "rtl", "dv", "dft"], employerMentions: "Rare in postings; tool experience itself is often requested", toolExposure: "High (with course labs)", labs: "Yes", time: "Days per course", difficulty: "Moderate", renewal: "Check badge terms", geography: "Global",
    classification: "optional",
    rationale: "Genuine tool exposure, but not independently accessible. If a finishing school, C-DAC centre or university gives you access, earn relevant badges; otherwise invest in open-source flow projects.",
  },
  {
    id: "coursera-fpga-cert", name: "FPGA Design for Embedded Systems Specialization", issuer: "University of Colorado Boulder (Coursera)",
    url: "https://coursera.org/specializations/fpga-design", verified: true, lastVerified: V,
    status: "Active", cost: "Coursera Plus subscription (listed at US$399/year, with promotions)", pricing: "paid",
    format: "4-course online specialization with shareable certificate", prerequisites: "Intermediate; digital design basics", eligibility: "Open to all",
    degreeRequired: "No", mtechRequired: "No", depth: "Intermediate FPGA flow (Intel/Altera tools, Nios II soft processor)", recognition: "University-branded online certificate",
    roles: ["fpga"], employerMentions: "Not found in sampled postings", toolExposure: "Vendor FPGA tools", labs: "Yes", time: "About 2 months at 10 h/week", difficulty: "Moderate", renewal: "None", geography: "Global",
    classification: "optional",
    rationale: "Reasonable structured FPGA content if you choose the FPGA track and prefer guided labs; an FPGA accelerator project demonstrates more.",
  },
  {
    id: "c2s", name: "Chips to Startup (C2S) programme courses and SMART labs", issuer: "MeitY / C-DAC (India Semiconductor Mission)",
    url: "https://static.pib.gov.in/WriteReadData/specificdocs/documents/2026/jan/doc2026118760301.pdf", verified: true, lastVerified: V,
    status: "Active; about 68,000 trained and 175 designs taped out at SCL Mohali per government statements (2026)", cost: "Free EDA access for participating institutions", pricing: "free",
    format: "Institution-based training, EDA access through the ChipIN Centre, chip fabrication for student designs", prerequisites: "Enrolment at a participating institution", eligibility: "Mainly students and faculty of supported institutions",
    degreeRequired: "Via institutions", mtechRequired: "No (programmes span B.Tech to PhD)", depth: "Varies by institution", recognition: "Government programme; visibility increasing",
    roles: ["rtl", "dv", "pd"], employerMentions: "Not typically named", toolExposure: "Industry EDA tools via ChipIN", labs: "Yes", time: "Varies", difficulty: "Varies", renewal: "None", geography: "India",
    classification: "optional",
    rationale: "Excellent if you can join through an institution (for example as a project associate or through a college lab); not directly open to independent graduates. Worth checking whether a nearby institution in Odisha participates.",
  },
  {
    id: "finishing-schools", name: "Private VLSI training institutes ('finishing schools')", issuer: "Various private companies",
    verified: false, lastVerified: V,
    status: "Many active providers in India with varying quality", cost: "Often substantial; varies widely", pricing: "paid",
    format: "Classroom or online course with labs and placement assistance", prerequisites: "Engineering degree typically", eligibility: "Varies",
    degreeRequired: "Usually an engineering degree", mtechRequired: "No", depth: "Varies from shallow to strong", recognition: "Depends entirely on the institute's track record",
    roles: ["dv", "rtl", "pd"], employerMentions: "Not named in postings; some institutes have hiring partnerships", toolExposure: "Often includes commercial tool licences", labs: "Varies", time: "3-6 months typical", difficulty: "Varies", renewal: "None", geography: "India",
    classification: "optional",
    rationale: "Can provide licensed-tool practice and hiring networks, but marketing claims are common. Before paying: ask for audited placement data by batch, speak with recent alumni, confirm lab hours on real tools, and compare the syllabus with this roadmap. Never pay for a certificate alone.",
  },
  {
    id: "lfcs", name: "Linux Foundation Certified System Administrator (LFCS)", issuer: "Linux Foundation",
    verified: false, lastVerified: V,
    status: "Active (details not re-verified in this research pass)", cost: "Paid; check official page", pricing: "paid",
    format: "Performance-based exam", prerequisites: "Linux administration", eligibility: "Open",
    degreeRequired: "No", mtechRequired: "No", depth: "Sysadmin skills beyond what VLSI roles need", recognition: "Strong in IT, not in VLSI hiring",
    roles: [], employerMentions: "Not in VLSI postings sampled", toolExposure: "Linux", labs: "Exam is hands-on", time: "Weeks", difficulty: "Moderate", renewal: "Time-limited validity", geography: "Global",
    classification: "low",
    rationale: "VLSI jobs need shell fluency, not sysadmin certification. Learn Linux through your projects and scripts instead.",
  },
  {
    id: "generic-mooc-certs", name: "Generic paid 'VLSI certificate' courses on marketplaces", issuer: "Various",
    verified: false, lastVerified: V,
    status: "Many", cost: "Varies", pricing: "paid",
    format: "Recorded videos with completion certificates", prerequisites: "None", eligibility: "Open",
    degreeRequired: "No", mtechRequired: "No", depth: "Usually shallow", recognition: "Low; completion certificates are not assessments",
    roles: [], employerMentions: "None found", toolExposure: "Low", labs: "Rarely", time: "Hours to weeks", difficulty: "Easy", renewal: "None", geography: "Global",
    classification: "not-recommended",
    rationale: "Completion certificates without proctored assessment or projects add almost nothing to a resume. Use good free courses for learning and spend money on hardware (FPGA board) or a tapeout instead.",
  },
];

export const CERT_MAP: Record<string, Certification> = Object.fromEntries(CERTIFICATIONS.map((c) => [c.id, c]));

export const DEGREE_GAP = {
  title: "Degree gap compensation strategy",
  honest: [
    "An M.Tech (or MS) in VLSI still matters for some employers: some campus programmes and job postings list VLSI or computer architecture coursework, a master's degree, or GPA cut-offs (for example a 2026 new-graduate DV posting required VLSI and architecture as a primary part of the curriculum). Analog and some architecture roles lean strongly toward advanced degrees.",
    "Other postings accept 'Bachelor's degree or equivalent practical experience' or list a B.Tech with more experience instead of an M.Tech. Verification, FPGA, validation and EDA software roles are generally more open to evidence-based candidates.",
    "A certificate does not substitute for engineering experience. Its only job is to add verifiable proof of competence where your portfolio cannot.",
  ],
  pillars: [
    "Strong fundamentals you can explain aloud (digital, timing, architecture)",
    "Three to five flagship projects with verification, measurements and documentation",
    "One end-to-end RTL-to-GDS project (ideally fabricated on a shuttle)",
    "Open-source contributions reviewed by maintainers",
    "Technical writing: reports and posts with evidence",
    "Interview performance built with weekly mock practice",
    "Selective credentials: NPTEL scores for fundamentals; C-DAC PG-DVLSI if you need structured tool access and placement support",
    "Internships or project associate roles (C2S-affiliated labs, startups, services companies)",
  ],
  path: [
    "Foundation credential (optional, cheap): NPTEL Verilog/VLSI proctored certificate",
    "Specialization learning: free Verification Academy / NPTEL / ETH courses",
    "Tool exposure: open-source flows (LibreLane, OpenROAD, Verilator UVM) or licensed tools via C-DAC/institution",
    "Project: flagship repos that use those tools",
    "Portfolio: showcase checklists complete",
    "Interview: mock mode until weak categories reach 80%",
  ],
};
