// Additions from the 2026-09-24 research pass: the Embedded Engineering track, plus VLSI resources found
// while researching the ChipCamp VLSI roadmap video and the GitHub leads. Merged into the base content files.
import type { BankQuestion, CareerPath, GlossaryTerm, InterviewCat, MasteryTest, OpenSourceProject, PracticeItem, Resource, ResourceType } from "./schema.ts";

const CHECKED = "2026-09-24";

// gh(): existence verified with `git ls-remote`, archive status and license read from the GitHub page on CHECKED.
const gh = (id: string, repo: string, title: string, type: ResourceType, note?: string): Resource => ({
  id, title, type, url: `https://github.com/${repo}`, source: "GitHub", free: true, verified: true, lastChecked: CHECKED, note,
});
// web(): verified = the URL appeared in a search or fetch result on CHECKED; otherwise shown as Unverified.
const web = (id: string, title: string, type: ResourceType, url: string, source: string, verified: boolean, note?: string, free = true): Resource => ({
  id, title, type, url, source, free, verified, lastChecked: verified ? CHECKED : "never", note,
});
const book = (id: string, title: string, source: string, note?: string): Resource => ({
  id, title, type: "textbook", source, free: false, verified: false, lastChecked: "n/a", note,
});

export const EXTRA_RESOURCES: Resource[] = [
  // The two source videos (content verified through their published descriptions and third-party summaries).
  web("chipcamp-embedded", "The Ultimate Roadmap for Embedded Systems (ChipCamp, Jan 2025)", "video", "https://www.youtube.com/watch?v=D7L1SmjQ3fo", "ChipCamp / YouTube", true, "Source video for the Embedded track: C first, bit manipulation, RTOS, digital and architecture basics, Arduino -> MSP430 -> Cortex-M, QEMU + GDB, FreeRTOS."),
  web("chipcamp-vlsi", "The ULTIMATE VLSI ROADMAP (Sanchit Kulkarni, Nov 2024)", "video", "https://www.youtube.com/watch?v=8WdYWx48ac8", "Sanchit Kulkarni / YouTube", true, "Source video: ten foundations, domain-specific hiring, Verilog-to-hardware mapping table, one complete-flow project."),
  web("freertos-guide", "FreeRTOS beginner's guide: RTOS fundamentals", "docs", "https://www.freertos.org/Documentation/01-FreeRTOS-quick-start/01-Beginners-guide/01-RTOS-fundamentals", "FreeRTOS (official)", true, "Linked from the ChipCamp embedded video description."),
  web("freertos-first-project", "FreeRTOS beginner's guide: build your first project", "docs", "https://www.freertos.org/Documentation/01-FreeRTOS-quick-start/01-Beginners-guide/03-Build-your-first-project", "FreeRTOS (official)", true),
  web("qemu-blinky-video", "Installing QEMU and running a blinking-LED program", "video", "https://youtu.be/Zvbarf1CSGs", "YouTube (linked by ChipCamp)", true, "Emulator-first start recommended in the embedded video description."),
  web("cheddar-video", "Cheddar: scheduling analysis for real-time task sets", "video", "https://youtu.be/sUgvErCWee4", "YouTube (linked by ChipCamp)", true, "Use to check RMS/EDF schedulability of your task sets."),
  web("gfg-bits", "Bit manipulation: important tactics", "practice", "https://www.geeksforgeeks.org/bits-manipulation-important-tactics/", "GeeksforGeeks", true, "Linked by the ChipCamp embedded video; drill after the bit-manipulation topic."),
  web("neso-academy", "Neso Academy (C programming, digital electronics, computer architecture playlists)", "video", "https://www.youtube.com/@nesoacademy", "Neso Academy / YouTube", false, "Recommended by both ChipCamp videos for C and digital basics."),
  web("indiabix", "IndiaBIX aptitude practice", "practice", "https://www.indiabix.com/", "IndiaBIX", false, "Aptitude with a timer, as the VLSI video recommends (one set daily)."),
  web("gfg-puzzles", "GeeksforGeeks puzzles (previously asked)", "practice", "https://www.geeksforgeeks.org/puzzles/", "GeeksforGeeks", false),
  web("nand2tetris", "Nand2Tetris: build a computer from NAND gates", "course", "https://www.nand2tetris.org/", "Nisan and Schocken", false, "Optional: projects 1-5 build gates -> ALU -> CPU -> computer, a strong mental model before RTL and MCU work."),
  // Courses and official documentation
  web("nordic-academy", "Nordic Developer Academy: nRF Connect SDK Fundamentals (free)", "course", "https://academy.nordicsemi.com/courses/nrf-connect-sdk-fundamentals/", "Nordic Semiconductor", true, "Free, self-paced: Zephyr execution model, threads, devicetree and Kconfig with hands-on exercises."),
  web("nordic-academy-int", "Nordic Developer Academy: nRF Connect SDK Intermediate (free)", "course", "https://academy.nordicsemi.com/courses/nrf-connect-sdk-intermediate/", "Nordic Semiconductor", true, "Zephyr threads and scheduling, debugging, custom boards, device drivers, secure firmware update."),
  web("zephyr-docs", "Zephyr Project documentation: Getting Started", "docs", "https://docs.zephyrproject.org/latest/develop/getting_started/index.html", "Zephyr Project", false, "Use the documentation version matching your Zephyr release (latest tag verified v4.4.2)."),
  web("esp-idf-docs", "ESP-IDF Programming Guide (stable)", "docs", "https://docs.espressif.com/projects/esp-idf/en/stable/esp32/", "Espressif", false, "Select your chip and ESP-IDF version (latest tag verified v6.1)."),
  web("yocto-docs", "Yocto Project documentation", "docs", "https://docs.yoctoproject.org/", "Yocto Project", true),
  web("yocto-wrynose", "Yocto Project 6.0 'Wrynose' release announcement (May 2026)", "reading", "https://www.yoctoproject.org/blog/2026/05/13/yocto-project-6-0-wrynose-is-here/", "Yocto Project", true, "Current LTS; introduces bitbake-setup and deprecates the combined poky repository."),
  web("bitbake-setup", "BitBake environment setup (bitbake-setup)", "docs", "https://docs.yoctoproject.org/bitbake/bitbake-user-manual/bitbake-user-manual-environment-setup.html", "Yocto Project", true),
  web("bootlin-yocto-wrynose", "Bootlin's Yocto training updated to Wrynose", "reading", "https://bootlin.com/blog/bootlins-yocto-training-course-updated-to-wrynose/", "Bootlin", true, "Bootlin publishes its training slides and labs freely; see bootlin/training-materials."),
  web("buildroot-manual", "The Buildroot user manual", "docs", "https://buildroot.org/downloads/manual/manual.html", "Buildroot", false),
  web("uboot-docs", "U-Boot documentation", "docs", "https://docs.u-boot.org/en/latest/", "U-Boot", false),
  web("kernel-driver-api", "Linux kernel driver implementer's API guide", "docs", "https://docs.kernel.org/driver-api/index.html", "kernel.org", false),
  web("devicetree-spec", "Devicetree specification", "docs", "https://www.devicetree.org/specifications/", "devicetree.org", false),
  web("linux-kernel-labs", "Linux Kernel Teaching labs", "course", "https://linux-kernel-labs.github.io/", "UPB (community)", false, "Hands-on kernel module and driver labs in QEMU."),
  web("interrupt-blog", "Interrupt: embedded engineering blog by Memfault", "reading", "https://interrupt.memfault.com/", "Memfault", false, "Deep articles on HardFault debugging, linker scripts, bootloaders, CI and more; source repository memfault/interrupt exists."),
  web("openocd-docs", "OpenOCD User's Guide", "docs", "https://openocd.org/doc/html/index.html", "OpenOCD", false),
  web("renode-docs", "Renode documentation", "docs", "https://renode.readthedocs.io/", "Antmicro", false),
  web("qemu-arm-docs", "QEMU Arm system emulator documentation", "docs", "https://www.qemu.org/docs/master/system/target-arm.html", "QEMU", false),
  web("wokwi", "Wokwi: browser simulator for Pico, ESP32 and Arduino", "tool", "https://wokwi.com/", "Wokwi", false, "Zero-hardware start; not a substitute for a debugger on real silicon."),
  web("sigrok-pulseview", "sigrok PulseView: open-source logic analyzer software", "tool", "https://sigrok.org/wiki/PulseView", "sigrok", false, "Works with inexpensive fx2-based analyzers; has UART/SPI/I2C/CAN decoders."),
  web("arm-gnu-toolchain", "Arm GNU Toolchain downloads (arm-none-eabi)", "tool", "https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads", "Arm", false),
  web("arm-armv7m", "Armv7-M Architecture Reference Manual", "docs", "https://developer.arm.com/documentation/ddi0403/latest", "Arm", false, "The exception model, NVIC, SysTick and fault registers."),
  web("arm-armv8m", "Armv8-M Architecture Reference Manual", "docs", "https://developer.arm.com/documentation/ddi0553/latest", "Arm", false, "TrustZone for Armv8-M, SAU, secure gateways."),
  web("misra", "MISRA (C coding guidelines)", "reading", "https://misra.org.uk/", "MISRA", false, "The guidelines are sold; the site explains scope and publishes amendments.", false),
  web("sei-cert-c", "SEI CERT C Coding Standard", "reading", "https://wiki.sei.cmu.edu/confluence/display/c", "Carnegie Mellon SEI", false),
  web("can-intro", "CAN bus explained: a simple intro", "reading", "https://www.csselectronics.com/pages/can-bus-simple-intro-tutorial", "CSS Electronics", false),
  web("usb-nutshell", "USB in a NutShell", "reading", "https://www.beyondlogic.org/usbnutshell/usb1.shtml", "Beyond Logic", false, "Old but still a clear conceptual introduction."),
  web("mqtt-org", "MQTT specification and resources", "docs", "https://mqtt.org/", "MQTT.org", false),
  web("mcuboot-docs", "MCUboot documentation", "docs", "https://docs.mcuboot.com/", "MCUboot project", false),
  web("tfm-docs", "Trusted Firmware-M documentation", "docs", "https://trustedfirmware-m.readthedocs.io/", "Trusted Firmware", false),
  web("edge-impulse-docs", "Edge Impulse documentation", "docs", "https://docs.edgeimpulse.com/", "Edge Impulse", false),
  // GitHub: Embedded
  gh("gh-zephyr", "zephyrproject-rtos/zephyr", "Zephyr RTOS", "tool", "Apache-2.0. Study: drivers/gpio, drivers/i2c, samples/basic, doc/. Latest tag v4.4.2."),
  gh("gh-freertos", "FreeRTOS/FreeRTOS-Kernel", "FreeRTOS kernel", "tool", "MIT. Study: tasks.c (scheduler), queue.c, portable/GCC/ARM_CM4F/port.c (PendSV context switch). Latest tag V11.3.1."),
  gh("gh-nuttx", "apache/nuttx", "Apache NuttX RTOS", "tool", "Apache-2.0. POSIX-style RTOS; advanced OS-architecture reference. Latest tag nuttx-13.0.1."),
  gh("gh-threadx", "eclipse-threadx/threadx", "Eclipse ThreadX RTOS", "tool", "MIT. Reference only: the former Azure RTOS kernel, now at the Eclipse Foundation."),
  gh("gh-openocd", "openocd-org/openocd", "OpenOCD", "tool", "GPL-2.0. Last tagged release v0.12.0 is from 2023 but development continues; distributions and xPack builds ship newer snapshots."),
  gh("gh-mcuboot", "mcu-tools/mcuboot", "MCUboot secure bootloader", "tool", "Apache-2.0. Study: boot/bootutil/src (image validation, swap), scripts/imgtool. Latest tag v2.4.0."),
  gh("gh-buildroot", "buildroot/buildroot", "Buildroot (GitHub mirror)", "tool", "GPL-2.0. Latest tag 2026.08; the yearly .02 release is long-term support."),
  gh("gh-uboot", "u-boot/u-boot", "U-Boot (GitHub mirror)", "tool", "GPL-2.0+. Latest tag v2026.07."),
  gh("gh-linux", "torvalds/linux", "Linux kernel", "tool", "GPL-2.0. Read small drivers under drivers/misc, drivers/iio and Documentation/devicetree/bindings; do not start with PCI."),
  gh("gh-littlefs", "littlefs-project/littlefs", "littlefs: power-loss-resilient filesystem", "tool", "BSD-3-Clause. Latest tag v2.11.3. Read DESIGN.md."),
  gh("gh-lwip", "lwip-tcpip/lwip", "lwIP TCP/IP stack (GitHub mirror)", "tool", "BSD-style licence. Official development is on Savannah; this is a mirror."),
  gh("gh-nanopb", "nanopb/nanopb", "nanopb: Protocol Buffers for embedded C", "tool", "zlib licence."),
  gh("gh-mbedtls", "Mbed-TLS/mbedtls", "Mbed TLS", "tool", "Apache-2.0 or GPL-2.0-or-later. Latest tag v4.2.0; the 4.x line reorganised crypto around TF-PSA-Crypto, so check which version your SDK uses."),
  gh("gh-cmsis6", "ARM-software/CMSIS_6", "CMSIS 6 (CMSIS-Core, CMSIS-RTOS2)", "tool", "Apache-2.0. Latest tag v6.3.0."),
  gh("gh-cmsis-dsp", "ARM-software/CMSIS-DSP", "CMSIS-DSP", "tool", "Apache-2.0."),
  gh("gh-cmsis-nn", "ARM-software/CMSIS-NN", "CMSIS-NN", "tool", "Apache-2.0."),
  gh("gh-tflm", "tensorflow/tflite-micro", "TensorFlow Lite for Microcontrollers", "tool", "Apache-2.0. Check the README for current LiteRT naming."),
  gh("gh-renode", "renode/renode", "Renode simulator", "tool", "MIT. Latest tag v1.17.0."),
  gh("gh-unity", "ThrowTheSwitch/Unity", "Unity unit-test framework for C", "tool", "MIT."),
  gh("gh-ceedling", "ThrowTheSwitch/Ceedling", "Ceedling build/test runner", "tool", "MIT."),
  gh("gh-cpputest", "cpputest/cpputest", "CppUTest", "tool", "BSD-3-Clause."),
  gh("gh-cppcheck", "danmar/cppcheck", "cppcheck static analyzer", "tool", "GPL-3.0 (tool licence does not affect analysed code)."),
  gh("gh-tinyusb", "hathach/tinyusb", "TinyUSB", "tool", "MIT. Latest tag 0.21.0."),
  gh("gh-esp-idf", "espressif/esp-idf", "ESP-IDF", "tool", "Apache-2.0. Latest tag v6.1."),
  gh("gh-tfm", "TrustedFirmware-M/trusted-firmware-m", "Trusted Firmware-M (GitHub mirror)", "tool", "BSD-3-Clause per project docs (GitHub shows 'Other')."),
  gh("gh-libopencm3", "libopencm3/libopencm3", "libopencm3", "tool", "LGPL-3.0 per its README (GitHub's detector shows GPL-3.0; read the COPYING files). Study: include/libopencm3/stm32/ register definitions."),
  gh("gh-libopencm3-ex", "libopencm3/libopencm3-examples", "libopencm3 examples", "tool", "Minimal register-level examples with GCC + OpenOCD."),
  gh("gh-pico-sdk", "raspberrypi/pico-sdk", "Raspberry Pi Pico SDK", "tool", "BSD-3-Clause. Study: src/rp2_common/hardware_gpio, hardware_pio, hardware_dma. Latest tag 2.3.1."),
  gh("gh-pico-examples", "raspberrypi/pico-examples", "Raspberry Pi Pico examples", "tool", "BSD-3-Clause. Examples for GPIO, UART, SPI, I2C, DMA, PIO, USB, multicore."),
  gh("gh-stm32cubef4", "STMicroelectronics/STM32CubeF4", "STM32CubeF4 MCU package", "tool", "Mixed licences per component (see its License.md). Study: Drivers/CMSIS, Drivers/STM32F4xx_HAL_Driver (HAL and LL), Projects/<board>/Examples_LL."),
  gh("gh-bare-metal-guide", "cpq/bare-metal-programming-guide", "Bare metal programming guide (Cortex-M, no IDE)", "reading", "MIT. Register-level blinky to web server with GCC, linker scripts and startup code."),
  gh("gh-shape-world", "GuillaumeGalasso/Embedded_Systems--Shape_The_World", "Embedded Systems: Shape the World (UT Austin) lab code mirror", "practice", "No licence file: study only. Labs cover C, I/O, interrupts, FSMs, UART, ADC/DAC, motors and debugging on TM4C."),
  gh("gh-emb-roadmap", "m3y54m/Embedded-Engineering-Roadmap", "Embedded Engineering Roadmap (community)", "reading", "CC-BY-SA-4.0. Useful second map for gap-checking this track; not a learning sequence on its own."),
  gh("gh-bootlin-training", "bootlin/training-materials", "Bootlin training materials (embedded Linux, kernel, Yocto, Buildroot)", "course", "Free slides and labs (CC-BY-SA). High-quality embedded Linux path."),
  gh("gh-micro-ros", "micro-ROS/micro_ros_setup", "micro-ROS setup", "tool", "Apache-2.0. ROS 2 on microcontrollers."),
  gh("gh-sdk-nrf", "nrfconnect/sdk-nrf", "nRF Connect SDK", "tool", "Nordic's Zephyr-based SDK."),
  gh("gh-qemu", "qemu/qemu", "QEMU (GitHub mirror)", "tool", "GPL-2.0."),
  // GitHub: VLSI leads investigated
  gh("gh-skillsurf-sv", "SkillSurf/SystemVerilog", "SkillSurf SystemVerilog (RTL, testbenches, flows)", "practice", "MIT. Read as example code: compare its parameterised RTL and testbenches with your own."),
  gh("gh-taxi", "fpganinja/taxi", "Taxi: AXI, AXI-Stream, Ethernet and more (Alex Forencich)", "reading", "CERN-OHL-S-2.0 (strongly reciprocal): fine to read and learn from; copying code into your design brings reciprocal obligations."),
  gh("gh-veer-el2", "chipsalliance/Cores-VeeR-EL2", "VeeR EL2 RISC-V core (CHIPS Alliance)", "reading", "Apache-2.0. Maintained, small embedded-class core; a better primary study core than archived PicoRV32."),
  gh("gh-veer-eh1", "chipsalliance/Cores-VeeR-EH1", "VeeR EH1 RISC-V core", "reading", "Apache-2.0. Dual-issue, more complex."),
  gh("gh-sv-tests", "chipsalliance/sv-tests", "sv-tests: SystemVerilog compliance tests", "reading", "ISC. Advanced: see which SV features each open tool supports."),
  gh("gh-surelog", "chipsalliance/Surelog", "Surelog SystemVerilog parser and UHDM", "tool", "Apache-2.0. Advanced EDA-track material only."),
  gh("gh-rocket-chip", "chipsalliance/rocket-chip", "Rocket Chip generator", "reading", "Licence 'Other' on GitHub (BSD-style per repository). Advanced SoC architecture study only, after the core RISC-V topics."),
  gh("gh-verible", "chipsalliance/verible", "Verible SystemVerilog linter and formatter", "tool", "Apache-2.0 per repository. Add to CI next to Verilator lint."),
  // Books
  book("making-embedded", "Making Embedded Systems, 2nd ed. (Elecia White)", "O'Reilly", "Primary reference for the Embedded track's design and debugging mindset."),
  book("yiu-cortexm", "The Definitive Guide to Arm Cortex-M3 and Cortex-M4 Processors (Joseph Yiu)", "Newnes", "Also see his Armv8-M (Cortex-M23/M33) book for TrustZone."),
  book("k-r-c", "The C Programming Language, 2nd ed. (Kernighan and Ritchie)", "Prentice Hall"),
  book("grenning-tdd", "Test-Driven Development for Embedded C (James Grenning)", "Pragmatic Bookshelf"),
  book("mastering-emb-linux", "Mastering Embedded Linux Programming, 3rd ed. (Frank Vasquez and Chris Simmonds)", "Packt"),
  book("ldd3", "Linux Device Drivers, 3rd ed. (Corbet, Rubini, Kroah-Hartman)", "O'Reilly", "Free online but written for kernel 2.6; concepts hold, APIs have changed. Pair with current kernel docs."),
  book("kerrisk-tlpi", "The Linux Programming Interface (Michael Kerrisk)", "No Starch Press"),
  book("li-yao-rt", "Real-Time Concepts for Embedded Systems (Qing Li and Caroline Yao)", "CMP Books"),
  book("lyons-dsp", "Understanding Digital Signal Processing (Richard Lyons)", "Pearson"),
  book("warden-tinyml", "TinyML (Pete Warden and Daniel Situnayake)", "O'Reilly", "Framework APIs have moved on; the deployment reasoning still applies."),
  book("morris-mano", "Digital Design (M. Morris Mano)", "Pearson", "The VLSI video's all-time reference for digital electronics."),
  book("palnitkar-verilog", "Verilog HDL: A Guide to Digital Design and Synthesis (Samir Palnitkar)", "Pearson", "Recommended by the VLSI video with Prof. Sengupta's NPTEL course."),
];

export const EXTRA_CAREERS: CareerPath[] = [
  {
    id: "emb-firmware", title: "Firmware / embedded software engineer (MCU and RTOS)",
    does: "Writes and owns microcontroller firmware: drivers, interrupt and DMA handling, RTOS tasks, protocols, bootloaders and tests, and debugs it with probes and instruments.",
    builds: "Sensor devices, wearables, industrial controllers, motor drives, consumer electronics, validation firmware for new chips.",
    skills: ["C (and often C++)", "Cortex-M architecture", "Interrupts, DMA, timers", "UART/SPI/I2C/CAN", "FreeRTOS or Zephyr", "GDB + SWD/JTAG", "Logic analyzer and oscilloscope", "Unit tests and CI"],
    tools: ["arm-none-eabi GCC", "CMake/Ninja", "OpenOCD / probe tools", "STM32Cube / Pico SDK / nRF Connect SDK", "Unity/Ceedling", "cppcheck"],
    programming: ["C", "C++ (subset)", "Python for tooling and tests", "Assembly reading"],
    interviewTopics: ["Reset to main", "volatile", "Interrupt entry", "Mutex vs semaphore", "Priority inversion", "HardFault debugging", "UART/timer numericals"],
    eeFit: "Excellent: schematic reading, electronics and measurement are strengths firmware teams value, and a software background speeds up the C and tooling side.",
    mtech: "Not required. Projects with measurements, tests and clean repositories carry most of the weight.",
    entryPath: "Core Embedded road E0-E7, two weekend projects and one flagship (RTOS gateway or custom firmware stack), then apply to device makers, MCU vendors' application teams and services companies.",
    advanced: ["RTOS internals", "Low power", "Secure boot and OTA", "Safety standards"],
    projects: ["w-uart-cli", "w-freertos-sensor", "fe-rtos-gateway", "fe-fw-stack"],
    companies: ["MCU vendors (application and SDK teams)", "Consumer and wearable device makers", "Industrial automation and medical devices", "Engineering services firms"],
  },
  {
    id: "emb-linux", title: "Embedded Linux / BSP engineer",
    does: "Brings up Linux on boards: bootloader, kernel configuration, device trees, drivers, root filesystems with Buildroot or Yocto, and the update and security story.",
    builds: "Gateways, cameras, routers, vehicle head units, industrial HMIs and SoC evaluation kits.",
    skills: ["C", "Linux kernel and drivers", "Device tree", "U-Boot", "Buildroot/Yocto", "Cross-compilation", "Shell and Python", "JTAG and serial debugging"],
    tools: ["Yocto/BitBake", "Buildroot", "U-Boot", "QEMU", "git", "systemd"],
    programming: ["C", "Shell", "Python", "Some C++"],
    interviewTopics: ["Boot chain", "Device tree binding", "Platform drivers", "Buildroot vs Yocto", "Spinlock vs mutex", "Cross toolchains"],
    eeFit: "Strong, especially with board bring-up and schematic skills.",
    mtech: "Not required; kernel patches, BSP projects and clean Yocto layers are convincing evidence.",
    entryPath: "Core road through E9, the Linux char driver and Buildroot weekend projects, then the Embedded Linux BSP flagship.",
    advanced: ["Upstream kernel contributions", "Secure/verified boot", "Real-time Linux (PREEMPT_RT)", "Update frameworks"],
    projects: ["w-linux-chardrv", "w-buildroot-image", "fe-linux-bsp"],
    companies: ["SoC vendors (BSP teams)", "Networking and camera makers", "Automotive infotainment suppliers", "Embedded Linux consultancies"],
  },
  {
    id: "emb-automotive", title: "Automotive embedded engineer",
    does: "Develops ECU software: CAN communication, diagnostics (UDS), bootloaders, AUTOSAR components, following ISO 26262 and ASPICE processes and MISRA C.",
    builds: "Body, powertrain, battery-management, chassis and ADAS ECUs.",
    skills: ["C (MISRA)", "CAN/CAN FD, LIN", "UDS and ISO-TP", "AUTOSAR concepts", "RTOS", "Functional safety awareness", "Requirements traceability"],
    tools: ["Vector tools (industry)", "SocketCAN/python-can for learning", "Static analysis and MISRA checkers", "Debuggers and trace"],
    programming: ["C", "Python", "Some C++ (Adaptive AUTOSAR)"],
    interviewTopics: ["CAN arbitration", "UDS services", "Bootloader over CAN", "ASIL levels", "MISRA rules"],
    eeFit: "Good: automotive suppliers hire many EE graduates into ECU software and validation.",
    mtech: "Not required for many roles; process discipline and CAN/UDS projects matter.",
    entryPath: "Core road through E7, the automotive branch, the UDS simulator and the CAN ECU flagship.",
    advanced: ["Safety architecture", "Automotive cybersecurity", "Adaptive AUTOSAR"],
    projects: ["w-can-logger", "w-uds-sim", "fe-can-ecu"],
    companies: ["Tier-1 automotive suppliers", "Vehicle manufacturers' software units", "Automotive engineering services"],
  },
  {
    id: "emb-iot", title: "IoT / connected-device engineer",
    does: "Builds networked devices end to end: sensors, low-power firmware, Wi-Fi/BLE/cellular connectivity, MQTT/TLS, OTA and cloud integration.",
    builds: "Smart home, asset tracking, industrial monitoring and wearable products.",
    skills: ["C", "RTOS (FreeRTOS/Zephyr)", "Wi-Fi/BLE", "MQTT, TLS, certificates", "OTA and secure boot", "Low power", "Python tooling"],
    tools: ["ESP-IDF", "nRF Connect SDK", "MCUboot", "Mosquitto", "Wireshark"],
    programming: ["C", "Python", "Some cloud scripting"],
    interviewTopics: ["MQTT QoS", "TLS on MCUs", "OTA rollback", "Battery life calculation", "Reconnect strategies"],
    eeFit: "Good, especially with power measurement and RF awareness.",
    mtech: "Not required.",
    entryPath: "Core road through E8, MQTT and BLE weekend projects, then the secure OTA flagship.",
    advanced: ["Matter/Thread", "Cellular IoT", "Fleet telemetry"],
    projects: ["w-mqtt-node", "w-ble-sensor", "fe-secure-ota"],
    companies: ["IoT product companies", "Radio SoC vendors' application teams", "Industrial IoT integrators"],
  },
  {
    id: "emb-edge-ai", title: "Edge AI / TinyML engineer",
    does: "Deploys machine-learning inference on microcontrollers and edge SoCs under memory, latency and power limits.",
    builds: "Keyword spotting, predictive maintenance, gesture and vision sensors.",
    skills: ["Embedded C/C++", "DSP and feature extraction", "Quantisation", "TFLite Micro / CMSIS-NN", "Performance measurement", "Python ML tooling"],
    tools: ["TFLite Micro", "CMSIS-NN / CMSIS-DSP", "Edge Impulse", "Python (NumPy, training frameworks)"],
    programming: ["C/C++", "Python"],
    interviewTopics: ["Int8 quantisation", "Tensor arena sizing", "Latency/energy trade-offs", "Feature parity"],
    eeFit: "Good with DSP background; connects to the AI-hardware phase of the VLSI road.",
    mtech: "Helps for research roles, not required for deployment roles.",
    entryPath: "Core road, DSP and TinyML branches, then the TinyML weekend project extended into a flagship-quality write-up.",
    advanced: ["NPU integration", "Model compression", "Hardware/software co-design of accelerators"],
    projects: ["w-dsp-filter", "w-tinyml"],
    companies: ["MCU/NPU vendors", "Industrial monitoring companies", "Consumer device makers"],
  },
];

const bq = (id: string, cat: InterviewCat, level: 1 | 2 | 3 | 4, concept: string, question: string, a: string, reasoning: string, trap: string, topics: string[]): BankQuestion => ({ id, cat, q: question, level, concept, a, reasoning, trap, topics });

export const EXTRA_BANK: BankQuestion[] = [
  bq("eb-reset-main", "firmware", 2, "Startup", "What happens from reset to main() on a Cortex-M?", "Hardware loads MSP from vector 0 and PC from vector 1; Reset_Handler copies .data from flash to RAM, zeroes .bss, runs SystemInit (clocks, FPU), runs static constructors, then calls main.", "C assumes initialised globals and zeroed statics; startup code provides that.", "Forgetting the .data copy or saying the OS loads the program.", ["emb-linker-startup"]),
  bq("eb-vector", "firmware", 1, "Vector table", "What is in the vector table?", "Initial stack pointer, then handler addresses for reset, NMI, faults, SVC, PendSV, SysTick and each device interrupt.", "The core indexes the table by exception number.", "Omitting the initial stack pointer entry.", ["emb-exceptions"]),
  bq("eb-volatile", "firmware", 2, "volatile", "Why is volatile required for registers and ISR flags, and when is it not enough?", "It forces every access to be emitted. It does not make read-modify-write atomic, does not order memory for DMA or other cores, and does not protect multi-word data.", "The optimizer may cache or remove accesses without it.", "Calling volatile thread-safe.", ["emb-c-bits", "emb-interrupts"]),
  bq("eb-irq-entry", "firmware", 3, "Exception entry", "What happens during interrupt entry on Cortex-M?", "Priority check, stacking of R0-R3, R12, LR, PC, xPSR (plus FPU state if active), vector fetch, LR = EXC_RETURN, switch to Handler mode on MSP, jump to handler.", "Hardware stacking lets handlers be plain C functions.", "Saying the CPU saves all registers.", ["emb-exceptions"]),
  bq("eb-why-dma", "firmware", 2, "DMA", "Why use DMA, and why can DMA corrupt data?", "To move data without CPU work per byte, reducing load, jitter and power. Corruption comes from cache incoherence, buffers processed while DMA writes them, stack buffers going out of scope and misalignment.", "DMA and CPU are two bus masters sharing memory.", "Only listing the benefits.", ["emb-dma"]),
  bq("eb-mutex-sem", "rtos", 2, "Synchronisation", "How does a mutex differ from a semaphore?", "Mutex: ownership, released by the holder, usually priority inheritance, for mutual exclusion. Semaphore: no owner, used for signalling or counting resources, can be given from ISRs.", "Different intents lead to different kernel features.", "Calling a binary semaphore a mutex.", ["emb-rtos-sync"]),
  bq("eb-prio-inv", "rtos", 3, "Priority inversion", "What is priority inversion and how is it fixed?", "High-priority task waits on a mutex held by a low-priority task that is preempted by medium tasks. Fix with priority inheritance or ceiling, shorter critical sections, or no sharing.", "Unbounded blocking breaks real-time guarantees (Mars Pathfinder, 1997).", "Suggesting 'raise the high task's priority further'.", ["emb-rtos-sync"]),
  bq("eb-stack-size", "rtos", 3, "Stack sizing", "How do you calculate a task's stack size?", "Estimate deepest call chain locals plus exception stacking (32 bytes, 104 with FPU context) plus library use; measure the high-water mark under worst case; add 25-50% margin; use -fstack-usage for call graphs.", "Stacks are static budgets; overflow corrupts neighbours silently.", "Picking 1 KB for every task.", ["emb-freertos", "emb-faults"]),
  bq("eb-hardfault", "firmware", 3, "Fault analysis", "How do you debug a HardFault?", "Read HFSR and CFSR, fault address registers, determine MSP/PSP from EXC_RETURN, read stacked PC/LR, map with addr2line, reproduce; make imprecise faults precise if needed.", "The core records cause and context; use them.", "Only stepping through code.", ["emb-faults"]),
  bq("eb-wdt", "firmware", 2, "Watchdog", "Why does a watchdog reset happen and how do you avoid false confidence?", "The watchdog was not refreshed in time. Kick only when all tasks have checked in, not from a timer ISR, and log the reset cause and a breadcrumb.", "A timer-ISR kick keeps a hung system 'alive'.", "Kicking from SysTick.", ["emb-wdt-flash"]),
  bq("eb-i2c-lock", "firmware", 3, "I2C recovery", "How do you debug and fix an I2C bus lock?", "Observe SDA held low; switch pins to GPIO, clock SCL up to nine times until SDA is released, send STOP, reinitialise; add timeouts and boot-time recovery.", "A slave interrupted mid-byte keeps driving SDA.", "Only resetting the MCU's I2C peripheral.", ["emb-spi-i2c"]),
  bq("eb-linker", "firmware", 2, "Linker scripts", "What does a linker script do?", "Defines memory regions and places input sections into output sections at addresses, sets load versus run addresses (.data), exports symbols for startup code and reserves stack/heap.", "Firmware has no loader; addresses are fixed at link time.", "Saying it 'links libraries'.", ["emb-linker-startup"]),
  bq("eb-bootloader", "firmware", 2, "Bootloaders", "What is a bootloader and how does it start the application?", "Code that validates and optionally updates firmware, then disables interrupts, resets peripherals, sets VTOR, loads MSP from the app's vector table and jumps to its reset handler.", "It must hand over a clean CPU state.", "Forgetting VTOR and MSP.", ["emb-bootloader"]),
  bq("eb-ota-rollback", "firmware", 3, "OTA", "How does OTA rollback work with MCUboot?", "The new image boots in test mode and must confirm itself; if not confirmed before the next reset, the bootloader swaps back. A security counter blocks deliberate downgrades.", "Test-then-confirm makes updates recoverable.", "Assuming the bootloader can judge app health by itself.", ["emb-ota"]),
  bq("eb-secure-boot", "firmware", 2, "Secure boot", "What are secure boot and a root of trust?", "Each stage verifies the signature of the next, anchored in immutable code and fused keys that are trusted without verification: the root of trust.", "Trust must start somewhere that cannot be modified.", "Equating CRC checks with secure boot.", ["emb-security"]),
  bq("eb-buildroot-yocto", "emblinux", 2, "Build systems", "Buildroot or Yocto?", "Buildroot: simple, fast, single image. Yocto: layered, scalable, SDKs, package feeds, SBOM and compliance, much steeper and heavier. Yocto 6.0 uses bitbake-setup; the poky repo is deprecated.", "Match tool complexity to product-line needs.", "Saying one is simply 'better'.", ["emb-buildroot", "emb-yocto"]),
  bq("eb-devicetree", "emblinux", 2, "Device tree", "How does the device tree work?", "A hardware description (nodes and properties) compiled to a DTB and passed by the bootloader; the kernel creates devices from nodes and binds drivers by compatible strings.", "It separates board description from driver code.", "Saying drivers read the DTS source file.", ["emb-devicetree"]),
  bq("eb-bind", "emblinux", 3, "Driver binding", "How does a Linux driver bind to hardware, and what is a platform driver?", "The bus matches devices and drivers; for SoC peripherals, platform devices from DT nodes match drivers via of_match_table compatible strings and probe() is called. A platform driver handles non-discoverable memory-mapped devices.", "Matching and probe are the device model's core.", "Confusing module loading with binding.", ["emb-linux-drivers"]),
  bq("eb-boot-chain", "emblinux", 2, "Boot chain", "Describe the embedded Linux boot chain.", "Boot ROM, first-stage loader (SPL, often with TF-A on arm64), U-Boot, kernel plus DTB (plus initramfs), init, root filesystem services.", "Each stage initialises just enough for the next.", "Skipping the DTB.", ["emb-linux-boot"]),
  bq("en-uart", "firmware", 1, "Numerical: UART", "At 9600 baud 8N1, how long does a 64-byte message take?", "10 bits per byte: 640 bits / 9600 = 66.7 ms.", "Start and stop bits count.", "Using 8 bits per byte.", ["emb-uart"]),
  bq("en-timer", "firmware", 2, "Numerical: timer", "A 16-bit timer runs at 1 MHz. What is its overflow period, and how do you measure a 200 ms pulse?", "65536 us = 65.5 ms, so count overflows in software or prescale to 100 kHz (655 ms range, 10 us resolution).", "Range = 2^N / f_tick.", "Ignoring overflow.", ["emb-timers"]),
  bq("en-adc-rate", "firmware", 2, "Numerical: sampling", "Four ADC channels at 10 kHz each, 12-bit samples in 16-bit words, processed every 10 ms with double buffering. Buffer size and interrupt rate?", "Per half: 4 x 100 x 2 bytes = 800 bytes; total 1600 bytes; one half-complete interrupt every 10 ms, i.e. 100 interrupts per second.", "Size buffers from rate x period.", "Forgetting the second half of the double buffer.", ["emb-dma", "emb-adc"]),
  bq("en-cpu-irq", "firmware", 2, "Numerical: interrupt load", "An ISR takes 2 us and fires at 50 kHz. What CPU fraction does it use?", "2 us x 50,000/s = 0.1 s per second: 10% of the CPU, before entry/exit overhead.", "Utilisation = time per event x rate.", "Ignoring entry overhead at high rates.", ["emb-interrupts", "emb-realtime"]),
  bq("en-can", "firmware", 3, "Numerical: CAN timing", "CAN clock 80 MHz, 500 kbit/s. Choose prescaler and segments for an 87.5% sample point.", "Prescaler 10 gives 8 MHz time quanta, 16 tq per bit: sync 1, prop+phase1 13, phase2 2; sample point (1 + 13) / 16 = 87.5%.", "Bit time = tq count x tq period.", "Forgetting the sync segment.", ["emb-can"]),
  bq("en-rms", "rtos", 3, "Numerical: schedulability", "Tasks (C, T) in ms: (2, 10), (3, 15), (5, 30). Schedulable under RMS?", "U = 0.2 + 0.2 + 0.167 = 0.567 < 0.780 (3-task bound): yes.", "The Liu-Layland bound is sufficient, not necessary.", "Using the bound as a necessary test.", ["emb-realtime"]),
  bq("en-battery", "firmware", 2, "Numerical: battery", "Sensor: 8 mA for 100 ms every 60 s, 4 uA otherwise, 1200 mAh battery. Life?", "I_avg = 8 x 0.1/60 + 0.004 x 59.9/60 = 0.0133 + 0.0040 = 0.0173 mA; 1200 / 0.0173 = about 69,000 h, roughly 7.9 years before derating.", "Average current over one period.", "Ignoring sleep current.", ["emb-power"]),
];

type Q = MasteryTest["questions"][number];
const mc = (id: string, type: Q["type"], question: string, options: string[], answer: number, explain: string): Q => ({ id, type, q: question, options, answer, explain });
const op = (id: string, type: Q["type"], question: string, answer: string, explain = ""): Q => ({ id, type, q: question, answer, explain });

export const EXTRA_MASTERY: MasteryTest[] = [
  { phase: "e0", title: "Embedded E0: orientation and electronics", questions: [
    mc("e0-1", "concept", "Which runs a full Linux OS?", ["Cortex-M0+ MCU", "Cortex-A application processor", "An 8-bit AVR", "A CAN transceiver"], 1, "Application processors have an MMU and external DRAM."),
    mc("e0-2", "numerical", "LED: 3.3 V supply, Vf 2.1 V, 4 mA. Resistor?", ["300 ohm", "825 ohm", "1.2 kohm", "3.3 kohm"], 0, "(3.3 - 2.1) / 0.004 = 300 ohm."),
    mc("e0-3", "concept", "Why does I2C need pull-up resistors?", ["To limit current into the MCU", "Outputs are open-drain and only pull low", "To filter noise", "To set the address"], 1, "Wired-AND bus."),
    op("e0-4", "design", "Describe two ways to debounce a push button.", "RC filter plus Schmitt-trigger input; or periodic sampling with a stable-for-N-samples state machine."),
    op("e0-5", "interview", "Which embedded role family are you aiming for and what evidence will you build?", "Self-assessment linked to the Level map."),
  ]},
  { phase: "e1", title: "Embedded E1: C for embedded", questions: [
    mc("e1-1", "concept", "sizeof(struct { uint8_t a; uint32_t b; }) on Cortex-M?", ["5", "6", "8", "4"], 2, "3 bytes of padding align b to 4."),
    mc("e1-2", "concept", "What does volatile guarantee?", ["Atomicity", "Every access is performed", "Memory ordering across cores", "Thread safety"], 1, "Only that accesses are not optimised away or merged."),
    mc("e1-3", "concept", "Which is undefined behaviour for 32-bit int x?", ["x >> 3 for x = 16", "1U << 31", "1 << 31", "x & 0xFF"], 2, "Shifting 1 into the sign bit of int is undefined; use 1U."),
    op("e1-4", "coding", "Write an expression setting bits [11:8] of reg to v.", "reg = (reg & ~(0xFU << 8)) | ((v & 0xFU) << 8);"),
    op("e1-5", "design", "How do you tell full from empty in a ring buffer?", "Keep one slot empty (full when next(head) == tail) or keep a count."),
  ]},
  { phase: "e2", title: "Embedded E2: MCU architecture and toolchain", questions: [
    mc("e2-1", "concept", "The first word of a Cortex-M vector table is:", ["Reset handler address", "Initial main stack pointer", "NMI handler", "Boot mode"], 1, "Word 0 is the initial MSP."),
    mc("e2-2", "concept", "On Cortex-M NVIC, a lower priority number means:", ["Lower urgency", "Higher urgency", "Nothing", "Disabled"], 1, "0 is the most urgent configurable priority."),
    mc("e2-3", "numerical", "text 20 KB, data 1 KB, bss 3 KB. Flash and static RAM?", ["21 KB / 4 KB", "24 KB / 4 KB", "20 KB / 3 KB", "21 KB / 3 KB"], 0, "Flash = text + data; RAM = data + bss."),
    op("e2-4", "interview", "Walk through reset to main().", "MSP and PC from vectors, copy .data, zero .bss, SystemInit, constructors, main."),
    op("e2-5", "debug", "A peripheral ignores writes. First check?", "Its clock enable (and reset) in the clock controller."),
  ]},
  { phase: "e3", title: "Embedded E3: bare-metal peripherals", questions: [
    mc("e3-1", "numerical", "Timer clock 84 MHz, PSC 83, ARR 999. Update frequency?", ["84 kHz", "1 kHz", "10 kHz", "1 MHz"], 1, "84e6 / (84 x 1000) = 1 kHz."),
    mc("e3-2", "numerical", "Byte time at 115200 8N1?", ["69 us", "86.8 us", "8.7 us", "115 us"], 1, "10 bits / 115200."),
    mc("e3-3", "concept", "SPI mode 0 means:", ["Clock idles high, sample on falling", "Clock idles low, sample on rising", "Clock idles low, sample on falling", "Half duplex"], 1, "CPOL 0, CPHA 0."),
    mc("e3-4", "numerical", "12-bit ADC, 3.3 V reference: LSB size?", ["0.8 mV", "3.2 mV", "0.08 mV", "12.9 mV"], 0, "3.3 / 4096 = 0.806 mV."),
    op("e3-5", "debug", "An I2C sensor NACKs its address. List three causes.", "Wrong address (7-bit vs 8-bit form), missing pull-ups or power, device held in reset or bus stuck."),
  ]},
  { phase: "e4", title: "Embedded E4: interrupts, DMA, drivers, power", questions: [
    mc("e4-1", "concept", "Best way to hand ISR data to the main loop?", ["printf inside the ISR", "SPSC ring buffer or queue", "Global variable without volatile", "malloc a buffer"], 1, "Short ISR, deferred processing."),
    mc("e4-2", "concept", "On a Cortex-M7, after DMA receives into a cached buffer you must:", ["Clean the cache", "Invalidate the buffer's cache lines", "Disable the MPU", "Nothing"], 1, "Discard stale lines before the CPU reads."),
    mc("e4-3", "numerical", "ISR 5 us at 20 kHz uses what CPU fraction?", ["1%", "10%", "5%", "20%"], 1, "5 us x 20,000 = 0.1."),
    op("e4-4", "design", "Outline a layered I2C sensor driver API.", "Handle struct, injected transport, init with ID check, read/convert, error codes, timeouts, optional IRQ/DMA, host tests with a fake."),
    op("e4-5", "numerical", "10 mA for 10 ms every 1 s, 2 uA otherwise. Average current?", "0.1 mA + 0.00198 mA = about 0.102 mA."),
  ]},
  { phase: "e5", title: "Embedded E5: debugging and testing", questions: [
    mc("e5-1", "concept", "Which finds the instruction that corrupts a variable?", ["printf", "Hardware watchpoint", "Reset", "Map file"], 1, "DWT comparators halt on write."),
    mc("e5-2", "debug", "CFSR = 0x00008200 indicates:", ["Divide by zero", "Precise bus fault with valid BFAR", "Stack overflow", "Undefined instruction"], 1, "BFARVALID (bit 15) and PRECISERR (bit 9)."),
    mc("e5-3", "concept", "What can an emulator NOT show reliably?", ["Startup code bugs", "Real interrupt latency and analog behaviour", "Logic errors", "RTOS API misuse"], 1, "Timing and analog are rarely modelled."),
    op("e5-4", "design", "What stages belong in a firmware CI pipeline?", "Pinned toolchain build, warnings as errors, unit tests, static analysis, size report, artifacts, optional emulator/HIL tests."),
    op("e5-5", "debug", "Your UART output is garbage. How do you tell a baud problem from a wiring problem?", "Logic analyzer: measure bit width versus expected, check idle level and voltage; loop back TX to RX."),
  ]},
  { phase: "e6", title: "Embedded E6: real-time and RTOS", questions: [
    mc("e6-1", "numerical", "Tasks U = 0.25, 0.25, 0.2. RMS bound for 3 tasks is 0.78. Result?", ["Guaranteed schedulable", "Not schedulable", "Unknown", "Needs EDF"], 0, "0.70 < 0.78."),
    mc("e6-2", "concept", "Priority inheritance is a property of:", ["Binary semaphores", "Mutexes", "Queues", "Event groups"], 1, "Owners can be boosted."),
    mc("e6-3", "concept", "Cortex-M RTOS ports switch context in:", ["SysTick", "PendSV", "NMI", "HardFault"], 1, "Lowest-priority deferred exception."),
    op("e6-4", "design", "How do you pass a reading from an ISR to a task in FreeRTOS?", "xQueueSendFromISR (or a task notification), then portYIELD_FROM_ISR if a higher-priority task woke."),
    op("e6-5", "interview", "Describe the Zephyr way to get a GPIO device.", "Devicetree node or alias, GPIO_DT_SPEC_GET, device_is_ready, gpio API; enabled via Kconfig."),
  ]},
  { phase: "e7", title: "Embedded E7: communication and networking", questions: [
    mc("e7-1", "concept", "Which CAN ID wins arbitration?", ["0x300", "0x0F0", "0x7FF", "The first to start"], 1, "Lowest ID wins."),
    mc("e7-2", "concept", "MQTT QoS 1 guarantees:", ["At most once", "At least once", "Exactly once", "Ordering"], 1, "Duplicates possible."),
    mc("e7-3", "concept", "Why does an embedded TLS client need correct time?", ["For DHCP", "To check certificate validity", "For ARP", "For MQTT keepalive only"], 1, "Validity periods."),
    op("e7-4", "design", "Design an ESP32 partition table supporting OTA.", "nvs, otadata, ota_0, ota_1 (plus optional factory and storage)."),
    op("e7-5", "numerical", "Frame time of a 500 kbit/s CAN frame with 8 data bytes (about 111 bits before stuffing)?", "About 222 us before stuffing, up to about 270 us worst case."),
  ]},
  { phase: "e8", title: "Embedded E8: boot, update, security, production", questions: [
    mc("e8-1", "concept", "Before jumping to an application, a bootloader must set:", ["The UART baud", "VTOR and MSP from the app's vector table", "The flash wait states to zero", "The RTC"], 1, "Plus disabling interrupts and peripherals."),
    mc("e8-2", "concept", "What makes an MCUboot update revert?", ["A CRC error in the old image", "The new image not confirming itself before reset", "A full slot", "Low battery"], 1, "Test-then-confirm."),
    mc("e8-3", "concept", "Which storage approach is power-loss resilient by design?", ["FAT", "littlefs", "Raw writes in place", "A single config copy"], 1, "Copy-on-write metadata."),
    op("e8-4", "design", "List four items in a secure-by-design MCU product.", "Secure boot from a root of trust, signed OTA with rollback protection, locked debug port, keys in secure storage (plus MPU/TrustZone isolation)."),
    op("e8-5", "interview", "How do you diagnose field reboots?", "Reset causes, coredumps in no-init RAM uploaded later, symbolised with the archived ELF for the build ID, soak tests."),
  ]},
  { phase: "e9", title: "Embedded E9: embedded Linux and BSP", questions: [
    mc("e9-1", "concept", "The kernel matches a DT node to a driver using:", ["The node name", "The compatible string", "The reg address", "The module file name"], 1, "of_match_table."),
    mc("e9-2", "concept", "Inside an interrupt handler you may use:", ["mutex_lock", "spin_lock", "msleep", "copy_to_user"], 1, "No sleeping in atomic context."),
    mc("e9-3", "concept", "In Yocto 6.0, the recommended way to fetch layers and set up a build is:", ["git clone poky", "bitbake-setup", "repo init only", "Buildroot"], 1, "The poky combo repo is deprecated."),
    op("e9-4", "design", "Order the boot chain stages.", "Boot ROM, SPL (and TF-A on many arm64 SoCs), U-Boot, kernel + DTB (+ initramfs), init, rootfs services."),
    op("e9-5", "debug", "Board stops after 'Starting kernel'. Two checks?", "console/earlycon bootargs; DTB matches board and kernel build."),
  ]},
  { phase: "e10", title: "Embedded E10: crossover, specialization and job readiness", questions: [
    mc("e10-1", "concept", "Best way to keep RTL and firmware register definitions in sync?", ["Copy by hand", "Generate both from SystemRDL/IP-XACT", "Use comments", "Test on hardware only"], 1, "Single source of truth."),
    mc("e10-2", "concept", "UDS positive response to service 0x22 starts with:", ["0x7F", "0x62", "0x22", "0x40"], 1, "SID + 0x40."),
    mc("e10-3", "numerical", "8 kHz sampling, 256-point FFT: bin width?", ["31.25 Hz", "8 Hz", "256 Hz", "62.5 Hz"], 0, "8000 / 256."),
    op("e10-4", "design", "Give the crossover workflow from spec to validation.", "Spec, register map, RTL, verification, synthesis, SoC integration, C driver, firmware, co-simulation, FPGA validation, documentation."),
    op("e10-5", "interview", "Present one project in 90 seconds with numbers.", "Goal, architecture, hardest bug and how measured, tests/CI, metrics, what you would change."),
  ]},
];

export const EXTRA_PRACTICE: PracticeItem[] = [
  { id: "pr-mtbf", title: "MTBF of one versus two synchronizer flops", type: "timing", level: "intermediate", phase: "p5",
    prompt: "tau = 30 ps, T0 = 50 ps, f_clk = 1 GHz, f_data = 100 MHz, setup overhead 0.1 ns. Compute MTBF with one resolving cycle (t_r = 0.9 ns) and with a second flop (t_r = 1.9 ns). MTBF = e^(t_r / tau) / (T0 * f_clk * f_data).",
    hints: ["Compute the denominator once: 50e-12 x 1e9 x 1e8.", "e^30 is about 1.07e13."],
    solution: "Denominator = 5e6 per second. One flop: e^30 / 5e6 = about 2.1e6 s, roughly 25 days: unacceptable. Two flops: e^63.3 / 5e6 = about 6e20 s, roughly 2e13 years. Each extra resolution cycle multiplies MTBF by e^(T/tau).",
    topics: ["metastability", "cdc"] },
  { id: "pr-pulse-sync", title: "Crossing a single-cycle pulse from fast to slow clock", type: "rtl", level: "intermediate", phase: "p5",
    prompt: "A 1-cycle pulse in a 200 MHz domain must be seen exactly once in a 50 MHz domain. Why does a 2-flop synchronizer fail, and what do you build instead?",
    hints: ["Could the slow clock miss the pulse entirely?", "Convert the event into a level change."],
    solution: "The pulse (5 ns) can fall between slow edges (20 ns) and be missed. Use a toggle synchronizer: toggle a flop on each pulse in the source domain, synchronize the level with two flops, and XOR successive synchronized values to regenerate one pulse. Events must be spaced at least about three destination cycles apart, or use a handshake or async FIFO.",
    topics: ["cdc"] },
  { id: "pr-emb-baud", title: "UART divisor and error budget", type: "timing", level: "beginner", phase: "e3",
    prompt: "Peripheral clock 48 MHz, oversampling by 16. Compute the divisor and error for 115200 and 921600 baud. Are both usable for 8N1?",
    hints: ["divisor = f_clk / baud with this style of peripheral.", "Keep total error well under about 2%."],
    solution: "115200: 416.67, round to 417, actual 115108, error -0.08%: fine. 921600: 52.08, round to 52, actual 923077, error +0.16%: fine. Check the other end's error too.",
    topics: ["emb-uart"] },
  { id: "pr-emb-timer", title: "Timer and PWM register values", type: "timing", level: "beginner", phase: "e3",
    prompt: "Timer clock 84 MHz. Configure a 10 kHz periodic interrupt, then 25 kHz PWM with 40% duty on another timer. Give PSC, ARR and CCR.",
    hints: ["f = f_clk / ((PSC + 1)(ARR + 1)).", "Pick PSC first for a round tick."],
    solution: "10 kHz: PSC = 83 (1 MHz), ARR = 99. 25 kHz PWM: PSC = 0, ARR = 3359 (84e6 / 25e3 = 3360), CCR = 1344 (40%).",
    topics: ["emb-timers"] },
  { id: "pr-emb-dma", title: "Sizing a DMA double buffer", type: "architecture", level: "intermediate", phase: "e4",
    prompt: "An audio codec streams stereo 16-bit samples at 48 kHz over I2S. Processing runs every 5 ms. Size a circular DMA double buffer and state the interrupt rate and deadline.",
    hints: ["Samples per 5 ms per channel?", "Half-transfer and complete each mark one half."],
    solution: "240 frames x 2 channels x 2 bytes = 960 bytes per half, 1920 bytes total; one interrupt every 5 ms (200 per second); processing each half must finish within 5 ms including worst-case jitter.",
    topics: ["emb-dma"] },
  { id: "pr-emb-fault", title: "Decode the fault status registers", type: "debug", level: "advanced", phase: "e5",
    prompt: "After a crash: HFSR = 0x40000000, CFSR = 0x00020000, stacked PC = 0x00000000, LR = 0x08001235. What happened and what do you check in the code?",
    hints: ["HFSR bit 30 is FORCED.", "UFSR bits start at CFSR bit 16; bit 17 is INVSTATE."],
    solution: "A usage fault escalated to HardFault (FORCED). INVSTATE: execution tried to leave Thumb state, typically calling a null or even-address function pointer; PC = 0 confirms a call through a null pointer. LR 0x08001235 points just after the call site: addr2line it and check the callback registration.",
    topics: ["emb-faults"] },
  { id: "pr-emb-rms", title: "Is this task set schedulable?", type: "thinking", level: "intermediate", phase: "e6",
    prompt: "Tasks (C, T) ms: A (1, 5), B (2, 10), C (4, 20), D (3, 40). Check with the RMS bound, then with response-time analysis for task D.",
    hints: ["U = sum C/T.", "R_D = C_D + sum ceil(R_D / T_j) C_j over higher-priority tasks."],
    solution: "U = 0.2 + 0.2 + 0.2 + 0.075 = 0.675 < 0.757 (4-task bound): schedulable. Response-time analysis for D: R0 = 3 + 1 + 2 + 4 = 10; R1 = 3 + ceil(10/5)x1 + ceil(10/10)x2 + ceil(10/20)x4 = 11; R2 = 3 + 3 + 4 + 4 = 14; R3 = 14 (converged). 14 ms is within D's 40 ms deadline.",
    topics: ["emb-realtime"] },
  { id: "pr-emb-stack", title: "Estimate a task stack", type: "debug", level: "intermediate", phase: "e6",
    prompt: "A task's deepest call chain uses 120, 80 and 256 bytes of locals; it calls snprintf (budget 400 bytes); the core has an FPU and the task uses floats. Estimate the stack and describe how to verify it.",
    hints: ["Exception stacking with FPU context is 104 bytes.", "Add a margin."],
    solution: "456 + 400 + 104 = 960 bytes; with a 30% margin, about 1.25 KB. Verify with stack painting / uxTaskGetStackHighWaterMark under worst-case load and -fstack-usage output; enable the overflow hook in debug builds.",
    topics: ["emb-freertos", "emb-faults"] },
];

export const EXTRA_GLOSSARY: GlossaryTerm[] = [
  { term: "MCU", full: "Microcontroller unit", simple: "A small computer on one chip with memory and peripherals.", technical: "CPU core plus flash, SRAM and peripherals, no MMU, typically bare-metal or RTOS.", topic: "emb-orientation" },
  { term: "BSP", full: "Board support package", simple: "Everything needed to make an OS run on one board.", technical: "Bootloader, kernel configuration, device tree and drivers for a specific board.", topic: "emb-linux-boot" },
  { term: "MMIO", full: "Memory-mapped I/O", simple: "Controlling hardware by reading and writing special addresses.", technical: "Peripheral registers at fixed addresses accessed through volatile pointers.", topic: "emb-c-bits" },
  { term: "NVIC", full: "Nested Vectored Interrupt Controller", simple: "The Cortex-M interrupt manager.", technical: "Per-IRQ enable, pending, active and priority with nesting and tail-chaining.", topic: "emb-exceptions" },
  { term: "VTOR", full: "Vector table offset register", simple: "Tells the CPU where the interrupt address list is.", technical: "SCB register relocating the vector table; used by bootloaders.", topic: "emb-bootloader" },
  { term: "SWD", full: "Serial Wire Debug", simple: "Two-wire debug connection to Arm chips.", technical: "SWDIO/SWCLK access to the debug port for halting, memory access and flashing.", topic: "emb-gdb-openocd" },
  { term: "HardFault", simple: "The Cortex-M 'something went badly wrong' exception.", technical: "Catch-all fault, including escalated MemManage, BusFault and UsageFault; diagnose with HFSR/CFSR and the stacked frame.", topic: "emb-faults" },
  { term: "DMA", full: "Direct memory access", simple: "Hardware that copies data without the CPU.", technical: "Bus master moving blocks between peripherals and memory; circular and double-buffered modes.", topic: "emb-dma" },
  { term: "RTOS", full: "Real-time operating system", simple: "A small OS that keeps important jobs on time.", technical: "Preemptive priority scheduler with deterministic kernel services.", topic: "emb-rtos-kernel" },
  { term: "PendSV", simple: "The quiet exception an RTOS uses to switch tasks.", technical: "Lowest-priority pendable exception used for context switches on Cortex-M.", topic: "emb-rtos-kernel" },
  { term: "Priority inversion", simple: "An urgent task waits behind a less urgent one.", technical: "High-priority task blocked on a resource held by a low-priority task preempted by medium tasks.", topic: "emb-rtos-sync" },
  { term: "Devicetree", simple: "A text description of a board's hardware.", technical: "Node/property tree compiled to a DTB; drivers match compatible strings.", topic: "emb-devicetree" },
  { term: "Platform driver", simple: "A Linux driver for built-in chip peripherals.", technical: "Driver for non-discoverable devices matched through the device tree and probed by the platform bus.", topic: "emb-linux-drivers" },
  { term: "U-Boot", simple: "The common bootloader for embedded Linux boards.", technical: "Loads kernel, DTB and initramfs from storage or network; environment, scripts, FIT images.", topic: "emb-uboot" },
  { term: "Buildroot", simple: "A tool that builds a whole small Linux system.", technical: "Kconfig/Make-based generator of toolchain, bootloader, kernel and rootfs.", topic: "emb-buildroot" },
  { term: "Yocto", simple: "A factory for custom Linux distributions.", technical: "BitBake and OpenEmbedded layers producing images, SDKs and package feeds; 6.0 Wrynose is the current LTS.", topic: "emb-yocto" },
  { term: "MCUboot", simple: "An open secure bootloader for microcontrollers.", technical: "Verifies signed images and manages swap-based updates with rollback.", topic: "emb-ota" },
  { term: "TrustZone-M", simple: "Hardware walls between secure and normal code on newer Cortex-M chips.", technical: "Armv8-M security extension: SAU/IDAU attribution, non-secure-callable entry via SG.", topic: "emb-security" },
  { term: "UDS", full: "Unified Diagnostic Services", simple: "How a mechanic's tester talks to car computers.", technical: "ISO 14229 request/response services over ISO-TP on CAN.", topic: "emb-automotive" },
  { term: "HIL", full: "Hardware-in-the-loop", simple: "Automatic tests on the real board.", technical: "Rig that flashes, drives inputs and checks outputs of target hardware from test scripts.", topic: "emb-emulation-hil" },
];

type OS = OpenSourceProject;
const os = (o: OS): OS => o;

export const EXTRA_OPEN_SOURCE: OpenSourceProject[] = [
  os({ id: "os-zephyr", name: "Zephyr RTOS", url: "https://github.com/zephyrproject-rtos/zephyr", what: "Vendor-neutral RTOS with devicetree, Kconfig, drivers, networking and Bluetooth.", why: "Modern embedded ecosystem used by many silicon vendors.", difficulty: "intermediate", prereqs: ["emb-zephyr"], beginnerUse: "Build samples/basic/blinky and samples/sensor for your board.", contribute: "Board support, documentation, driver fixes with Twister tests.", portfolio: "Merged board or driver patches are strong firmware evidence.", license: "Apache-2.0", study: "drivers/gpio/ (one vendor driver: init, device struct, API table, ISR), include/zephyr/drivers/gpio.h, samples/basic/blinky", exercise: "Read one GPIO driver and write a one-page note on initialization, the device struct, the API, interrupt handling and callbacks." }),
  os({ id: "os-freertos", name: "FreeRTOS kernel", url: "https://github.com/FreeRTOS/FreeRTOS-Kernel", what: "The most widely used MCU RTOS kernel.", why: "Small enough to read the scheduler in an afternoon.", difficulty: "intermediate", prereqs: ["emb-rtos-kernel"], beginnerUse: "Run the beginner's-guide demos, then read the port.", contribute: "Ports, tests, documentation.", portfolio: "Explaining the context switch from source impresses interviewers.", license: "MIT", study: "tasks.c (ready lists, vTaskSwitchContext), queue.c, portable/GCC/ARM_CM4F/port.c (PendSV handler)", exercise: "Trace xQueueSend from API to a blocked task waking; annotate the PendSV assembly line by line." }),
  os({ id: "os-mcuboot", name: "MCUboot", url: "https://github.com/mcu-tools/mcuboot", what: "Secure bootloader for 32-bit MCUs.", why: "Reference implementation of signed updates and rollback.", difficulty: "advanced", prereqs: ["emb-ota"], beginnerUse: "Use it through Zephyr sysbuild; sign images with imgtool.", contribute: "Documentation, tests, platform ports.", portfolio: "A documented secure-update demo.", license: "Apache-2.0", study: "boot/bootutil/src/loader.c (boot decision), image_validate.c, swap_*.c; scripts/imgtool", exercise: "Explain in your own words how the boot decision is made after an interrupted swap." }),
  os({ id: "os-littlefs", name: "littlefs", url: "https://github.com/littlefs-project/littlefs", what: "Power-loss-resilient filesystem for small flash.", why: "Beautifully documented design with real trade-offs.", difficulty: "intermediate", prereqs: ["emb-storage"], beginnerUse: "Port it to your SPI NOR driver.", contribute: "Tests, porting notes.", portfolio: "Power-cut test results.", license: "BSD-3-Clause", study: "DESIGN.md, SPEC.md, lfs.c metadata commit path", exercise: "Summarise how a metadata pair survives power loss, then run a power-cut test." }),
  os({ id: "os-openocd", name: "OpenOCD", url: "https://github.com/openocd-org/openocd", what: "On-chip debugger bridging GDB to SWD/JTAG probes.", why: "Vendor-neutral debug backbone.", difficulty: "advanced", prereqs: ["emb-gdb-openocd"], beginnerUse: "Write your own board config file.", contribute: "Target/board configs, flash drivers (via its Gerrit review).", portfolio: "Understanding debug infrastructure.", license: "GPL-2.0", study: "tcl/target/stm32f4x.cfg, tcl/interface/, src/flash/nor/stm32f2x.c", exercise: "Read the STM32F4 target config and explain each command." }),
  os({ id: "os-pico-sdk", name: "Raspberry Pi Pico SDK", url: "https://github.com/raspberrypi/pico-sdk", what: "C SDK for RP2040/RP2350.", why: "Clean layering from registers to high-level APIs, plus PIO.", difficulty: "beginner", prereqs: ["emb-gpio"], beginnerUse: "Build pico-examples; step into hardware_gpio functions.", contribute: "Examples and docs.", portfolio: "PIO-based custom interfaces stand out.", license: "BSD-3-Clause", study: "src/rp2_common/hardware_gpio/gpio.c, hardware_dma/dma.c, hardware_pio/", exercise: "Trace gpio_put() to the register it writes; implement a PIO program for a custom protocol." }),
  os({ id: "os-libopencm3", name: "libopencm3", url: "https://github.com/libopencm3/libopencm3", what: "Open register-level firmware library for many Cortex-M families.", why: "Readable register definitions without a vendor HAL.", difficulty: "intermediate", prereqs: ["emb-cmsis-hal"], beginnerUse: "Build libopencm3-examples with GCC and flash with OpenOCD.", contribute: "Peripheral support, fixes.", portfolio: "Register-level fluency.", license: "LGPL-3.0 (see COPYING files)", study: "include/libopencm3/stm32/common/gpio_common_f24.h, lib/stm32/common/usart_common_all.c", exercise: "Compare its USART driver with STM32Cube LL for the same operation." }),
  os({ id: "os-stm32cube", name: "STM32CubeF4", url: "https://github.com/STMicroelectronics/STM32CubeF4", what: "ST's official HAL/LL, CMSIS and examples for STM32F4.", why: "The real vendor ecosystem you will meet in jobs.", difficulty: "beginner", prereqs: ["emb-cmsis-hal"], beginnerUse: "Run Projects/<your board>/Examples_LL.", contribute: "Issues and discussions (vendor-maintained).", portfolio: "Shows vendor-SDK fluency when paired with register-level work.", license: "Per component (see License.md)", study: "Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c, Drivers/CMSIS/Device/ST/", exercise: "Follow HAL_UART_Transmit_IT through to the registers and ISR callbacks." }),
  os({ id: "os-linux", name: "Linux kernel (drivers)", url: "https://github.com/torvalds/linux", what: "The kernel; read small drivers as code-reading practice.", why: "BSP roles live here.", difficulty: "advanced", prereqs: ["emb-linux-drivers"], beginnerUse: "Read a small platform driver and its binding.", contribute: "Start with documentation or driver cleanups via the mailing-list process.", portfolio: "An accepted patch is outstanding evidence.", license: "GPL-2.0", study: "A small IIO or misc driver: probe/remove, of_match_table, devm_* use; its binding in Documentation/devicetree/bindings/", exercise: "Identify probe, remove, platform device, device-tree matching and sysfs in one driver." }),
  os({ id: "os-buildroot", name: "Buildroot", url: "https://github.com/buildroot/buildroot", what: "Embedded Linux build system.", why: "Most approachable complete Linux build.", difficulty: "intermediate", prereqs: ["emb-buildroot"], beginnerUse: "Build a QEMU defconfig; add a package in BR2_EXTERNAL.", contribute: "Package updates via its mailing list.", portfolio: "A clean external tree for your product.", license: "GPL-2.0", study: "configs/qemu_aarch64_virt_defconfig, package/pkg-generic.mk, docs/manual", exercise: "Package your own daemon and add an init script." }),
  os({ id: "os-uboot", name: "U-Boot", url: "https://github.com/u-boot/u-boot", what: "Bootloader for embedded Linux.", why: "Boot-chain knowledge for BSP roles.", difficulty: "advanced", prereqs: ["emb-uboot"], beginnerUse: "Build for QEMU and use the console.", contribute: "Board support and docs via its mailing list.", portfolio: "Boot-flow customisation evidence.", license: "GPL-2.0+", study: "boot/ (bootstd), cmd/, configs/qemu_arm64_defconfig", exercise: "Write a boot script with A/B fallback using bootcount." }),
  os({ id: "os-renode", name: "Renode", url: "https://github.com/renode/renode", what: "Simulator for embedded boards with test automation.", why: "Emulator-first learning and firmware CI.", difficulty: "intermediate", prereqs: ["emb-emulation-hil"], beginnerUse: "Run a STM32 or nRF demo script.", contribute: "Platform descriptions and peripheral models.", portfolio: "CI with simulated hardware tests.", license: "MIT", study: "platforms/ (.repl files), scripts/ (.resc demos), tests/", exercise: "Run your UART-shell firmware in Renode with an automated Robot Framework test." }),
  os({ id: "os-tinyusb", name: "TinyUSB", url: "https://github.com/hathach/tinyusb", what: "Portable USB host/device stack.", why: "Readable USB device implementation.", difficulty: "intermediate", prereqs: ["emb-usb"], beginnerUse: "Run the CDC example on your board.", contribute: "Ports and examples.", portfolio: "Custom USB devices.", license: "MIT", study: "src/device/usbd.c (enumeration), src/class/cdc/", exercise: "Trace enumeration requests in the code while watching lsusb/dmesg." }),
  os({ id: "os-veer", name: "VeeR EL2 (CHIPS Alliance)", url: "https://github.com/chipsalliance/Cores-VeeR-EL2", what: "Maintained embedded-class RISC-V core in SystemVerilog.", why: "Industrial RTL that is smaller than Ibex's DV environment; a maintained alternative to archived PicoRV32.", difficulty: "advanced", prereqs: ["riscv-isa", "pipelined-rtl"], beginnerUse: "Read the pipeline top level and run the provided simulation.", contribute: "Docs and tests following CHIPS Alliance process.", portfolio: "Comparing your core with VeeR's design choices.", license: "Apache-2.0", study: "design/ (top-level and pipeline files), testbench/, docs/", exercise: "Draw VeeR EL2's pipeline stages and compare hazard handling with your RV32I core." }),
  os({ id: "os-taxi", name: "Taxi (Alex Forencich)", url: "https://github.com/fpganinja/taxi", what: "Library of AXI, AXI-Stream, Ethernet and other FPGA/ASIC IP with cocotb tests.", why: "Real, heavily used protocol RTL with Python verification.", difficulty: "advanced", prereqs: ["axi", "axi-stream", "cocotb"], beginnerUse: "Read one AXI-Stream FIFO and its cocotb test.", contribute: "Issue reports with reproducers.", portfolio: "Understanding production protocol IP.", license: "CERN-OHL-S-2.0 (reciprocal)", study: "AXI-Stream FIFO and async FIFO sources and their tb/ cocotb tests; UART and Ethernet MAC blocks later", exercise: "Compare its async FIFO with your Cummings-style FIFO: pointer sync, full/empty, reset." }),
  os({ id: "os-skillsurf", name: "SkillSurf SystemVerilog", url: "https://github.com/SkillSurf/SystemVerilog", what: "SystemVerilog RTL, testbench and flow examples.", why: "Beginner-friendly real code to compare against your own.", difficulty: "beginner", prereqs: ["sv-design", "testbench-basics"], beginnerUse: "Pick one parameterised design and its testbench; rewrite it from the spec, then diff.", contribute: "Fixes and examples.", portfolio: "Not a portfolio piece itself; a study aid.", license: "MIT", study: "Parameterised RTL modules and their testbenches; any ASIC/FPGA/formal flow scripts included", exercise: "Re-implement one module blind, then compare structure, parameters and test coverage." }),
  os({ id: "os-sv-tests", name: "sv-tests", url: "https://github.com/chipsalliance/sv-tests", what: "SystemVerilog compliance suite across open tools.", why: "Shows which SV features each open tool supports.", difficulty: "advanced", prereqs: ["sv-oop", "eda-tooling"], beginnerUse: "Check the report before assuming an open tool supports a construct.", contribute: "New tests for uncovered features.", portfolio: "EDA-track credibility.", license: "ISC", study: "tests/chapter-*/ organised by IEEE 1800 chapter; the published report", exercise: "Find three constructs you used that an open simulator does not support yet." }),
];
