import type { Flagship } from "./schema.ts";

const ms = (id: string, title: string, detail: string, evidence?: string) => ({ id, title, detail, evidence });

export const FLAGSHIP_B: Flagship[] = [
  {
    id: "fp-dft-atpg", title: "DFT from first principles: scan insertion, fault simulation and PODEM ATPG", tier: "flagship",
    categories: ["G. DFT", "EDA engineering"], difficulty: 4, duration: "5-6 weeks part-time", phase: "p9",
    roles: ["dft", "eda"],
    exceptional: "You implement the algorithms DFT tools use (fault simulation, fault collapsing, PODEM) on ISCAS benchmarks, then insert real scan into a design with open tools and compare coverage.",
    problem: "Understand and quantify how test patterns detect manufacturing defects.",
    motivation: "DFT roles value algorithmic understanding; EDA roles value implementation skill. This project serves both and uses your software strength.",
    researchBasis: ["Bushnell & Agrawal, Essentials of Electronic Testing (PODEM, fault simulation)", "ISCAS'85 benchmark circuits"],
    prereqs: ["dft", "graphs-in-eda", "python-hw"],
    skills: ["Fault models", "Fault simulation", "ATPG algorithms", "Scan insertion", "Performance engineering"],
    architecture: "Netlist parser (ISCAS .bench or Yosys JSON) -> levelized graph -> parallel-pattern fault simulator -> fault collapsing -> PODEM with backtrace/implication -> compaction; separately, scan insertion on your FIFO/ALU with OpenROAD DFT support or the Fault toolchain.",
    diagram: "netlist --> graph --> [fault list] --> random patterns --> fault sim\n                               remaining faults --> PODEM --> patterns\n                               coverage report",
    requirements: ["Correct fault simulation on c17 and larger ISCAS circuits", "PODEM finds tests or proves redundancy with a backtrack limit", "Coverage vs pattern count curves", "Scan chain inserted on a real design"],
    milestones: [ms("m1", "Parser and simulator", "Logic simulation of ISCAS circuits."), ms("m2", "Fault simulation", "Stuck-at, parallel patterns."), ms("m3", "Collapsing", "Equivalence collapsing."), ms("m4", "PODEM", "Deterministic ATPG."), ms("m5", "Experiments", "Coverage curves, runtime."), ms("m6", "Scan on real RTL", "Insert scan with open tools; shift/capture test."), ms("m7", "Report", "Results and comparison.")],
    implementation: ["Bit-parallel simulation with Python ints or NumPy", "Write unit tests on tiny circuits"],
    verification: ["Cross-check fault detection by brute force on small circuits"],
    failureInjection: ["Deliberately wrong implication rule; show missed detections"],
    metrics: ["Fault coverage", "Pattern count", "Runtime", "Redundant faults found"],
    ppa: "Report scan area overhead on your design.",
    timing: "Discuss scan-shift timing and test clocks.",
    benchmark: "ISCAS'85 circuits (c17, c432, c880, ...).",
    expected: "High coverage with random patterns first, then PODEM for hard faults; exact numbers depend on implementation.",
    tools: ["Python or C++", "Yosys", "OpenROAD/Fault for scan"],
    openSource: ["Fault (AUCOHL)", "OpenROAD"],
    repo: "atpg/  benchmarks/  tests/  scan_demo/  results/  report/",
    docs: ["Algorithm notes", "Experiment report"],
    demo: ["Coverage vs patterns chart", "Scan shift waveform"],
    linkedinAngle: "I wrote a tiny ATPG engine to understand how chips are tested.",
    resume: ["Implemented stuck-at fault simulation and PODEM ATPG, reaching high fault coverage on ISCAS'85 circuits; inserted scan into an RTL design with open tools"],
    interview: [{ q: "How does PODEM work?", followups: ["What is backtrace?", "How do you prove a fault is redundant?"] }],
    extensions: ["Transition faults", "Test compaction", "Compression model"],
    researchOps: ["ML-guided ATPG heuristics"],
    contribOps: ["Contribute to open DFT tooling"],
    certs: ["cadence-badges"],
    proof: ["spec", "architecture", "verification", "simulation", "synthesis", "documentation", "github", "demo", "linkedin", "interview"],
    resources: ["bushnell-agrawal", "fault", "openroad"],
  },
  {
    id: "fp-fpga-accel", title: "Quantized neural-network accelerator on FPGA (systolic array)", tier: "flagship",
    categories: ["H. FPGA", "I. AI hardware"], difficulty: 4, duration: "6-8 weeks part-time", phase: "p11",
    roles: ["fpga", "aihw", "rtl"],
    exceptional: "An end-to-end INT8 inference path: quantized model in Python, bit-exact golden outputs, RTL systolic array with on-chip buffers, measured throughput and resource use, and a roofline explaining the results.",
    problem: "Accelerate a small quantized network (MLP or CNN layer) and explain performance with data.",
    motivation: "AI hardware roles want people who understand both the model math and the hardware constraints.",
    researchBasis: ["Kung, Why Systolic Architectures? (1982)", "Jouppi et al., TPU (ISCA 2017)", "Jacob et al., integer-only quantization (CVPR 2018)", "Sze et al., DNN processing tutorial"],
    prereqs: ["systolic", "quantization-sparsity", "fpga-architecture"],
    skills: ["Quantization", "Systolic RTL", "On-chip buffering", "FPGA timing closure", "Roofline analysis"],
    architecture: "Weight-stationary NxN INT8 systolic array with INT32 accumulators, input/weight/output BRAM buffers, DMA-like loader, control FSM, AXI-Lite control registers; host (soft CPU or PC over UART) loads data.",
    diagram: "weights --> [PE][PE][PE][PE]\nacts ---->  [PE][PE][PE][PE] --> psum --> requant --> out buf\n            (skewed inputs)\ncontrol regs (AXI-Lite) + buffers (BRAM)",
    requirements: ["Bit-exact match with the Python quantized reference", "Resource and timing report on a target FPGA (or open flow for iCE40/ECP5)", "Throughput (GOPS) and utilization", "Roofline plot"],
    milestones: [ms("m1", "Model and quantization", "INT8 model with golden vectors."), ms("m2", "Python systolic model", "Cycle-level."), ms("m3", "PE and array RTL", "Verified vs model."), ms("m4", "Buffers and control", "Tiled matmul."), ms("m5", "Integration", "Registers, loader, host path."), ms("m6", "FPGA", "Synthesis, timing, on-board or simulated run."), ms("m7", "Analysis", "Throughput, roofline, bottlenecks.", "Roofline chart")],
    implementation: ["Match rounding exactly with the model", "Map MACs to DSP blocks"],
    verification: ["Bit-exact comparison", "Random matrices", "Tile boundary tests"],
    failureInjection: ["Wrong skew by one cycle", "Accumulator overflow with narrow width"],
    metrics: ["GOPS", "Utilization", "LUT/DSP/BRAM use", "Fmax", "Accuracy vs FP32"],
    ppa: "Array size vs resources vs throughput tradeoff.",
    timing: "Pipelining in PEs to close timing.",
    benchmark: "Layer latency vs CPU (NumPy) baseline, reported honestly including data transfer.",
    expected: "Compute-bound for large tiles, IO-bound when data transfer dominates; explain with the roofline.",
    tools: ["Python/NumPy", "Verilator/cocotb", "Vivado or Quartus free editions, or Yosys + nextpnr"],
    openSource: ["Compare with Gemmini, hls4ml and FINN approaches"],
    dataset: "MNIST or a small public dataset for a demo MLP",
    repo: "model/  golden/  rtl/  tb/  fpga/  host/  results/  docs/",
    docs: ["Architecture doc", "Quantization notes", "Performance report"],
    demo: ["Board or simulation video classifying digits", "Roofline chart"],
    linkedinAngle: "Building an INT8 systolic accelerator and explaining its performance with a roofline.",
    resume: ["Designed an INT8 systolic-array accelerator with bit-exact verification against a quantized Python model; reported throughput, resources and roofline analysis on FPGA"],
    interview: [{ q: "Why weight-stationary?", followups: ["When is your design memory-bound?", "How did you choose accumulator width?"] }],
    extensions: ["Sparsity skipping", "INT4", "Custom RISC-V instruction interface (capstone)"],
    researchOps: ["Dataflow comparison per Eyeriss analysis"],
    contribOps: ["hls4ml or FINN examples"],
    certs: ["coursera-fpga-cert"],
    resources: ["gemmini", "hls4ml", "finn", "sze-book"],
  },
  {
    id: "fp-attention", title: "Attention accelerator with streaming (online) softmax", tier: "research",
    categories: ["I. AI hardware", "L. Research reproduction"], difficulty: 5, duration: "6-8 weeks part-time", phase: "p11",
    roles: ["aihw", "arch", "rtl"],
    exceptional: "Implements a tiled attention block with online softmax in fixed point, quantifies numerical error against floating point, and models memory traffic for prefill vs decode.",
    problem: "Make attention hardware-friendly: tiling, numerics and bandwidth.",
    motivation: "LLM inference hardware is a leading AI-hardware topic; this project shows depth beyond CNN accelerators.",
    researchBasis: ["Dao et al., FlashAttention (NeurIPS 2022) for IO-aware tiling and online softmax", "Wang et al., SpAtten (HPCA 2021) for attention hardware ideas"],
    prereqs: ["transformer-hw", "fixed-point", "matmul-mac"],
    skills: ["Numerics", "Tiled dataflow", "Memory traffic modeling", "RTL datapaths"],
    architecture: "Single-head attention for short sequences: QK^T tile engine, running max and sum registers for online softmax, exp approximation (LUT + interpolation), weighted-V accumulation, fixed-point formats chosen from error analysis.",
    diagram: "Q tile x K^T tile --> scores --> [running max, rescale] --> exp LUT --> sum\n                                          |\n                              weights x V tile --> acc --> normalize --> out",
    requirements: ["Error within a stated bound vs FP32", "Traffic model for prefill and decode", "Synthesis results"],
    milestones: [ms("m1", "Python reference", "FP32 and fixed-point online softmax."), ms("m2", "Error study", "Format choice."), ms("m3", "RTL", "Tile engine and softmax unit."), ms("m4", "Verification", "Bit-exact vs fixed-point model."), ms("m5", "Traffic model", "Bytes moved vs sequence length."), ms("m6", "Report", "Numerics, PPA, roofline.")],
    implementation: ["Model first; hardware second", "Keep sequence length small"],
    verification: ["Bit-exact to fixed-point model", "Statistical error vs FP32"],
    failureInjection: ["Omit max subtraction and show overflow"],
    metrics: ["Max/mean error", "Cycles per head", "Area", "Bytes moved"],
    ppa: "Exp approximation accuracy vs area.",
    timing: "Pipeline the exp and divide paths.",
    benchmark: "Random and real attention inputs (for example extracted from a small open model).",
    expected: "Online softmax removes the need to store full score rows; exact savings depend on tile size.",
    tools: ["Python/NumPy/PyTorch", "Verilator/cocotb", "Yosys"],
    openSource: ["Small open transformer models for inputs"],
    repo: "ref/  rtl/  tb/  analysis/  report/",
    docs: ["Paper-style report"],
    demo: ["Error histograms", "Traffic plots"],
    linkedinAngle: "Online softmax in fixed point: what it takes to put attention in hardware.",
    resume: ["Implemented a tiled attention unit with fixed-point online softmax, bounding error vs FP32 and modeling memory traffic for prefill and decode"],
    interview: [{ q: "Why online softmax?", followups: ["How did you choose formats?", "What limits decode performance?"] }],
    extensions: ["Multi-head", "KV-cache compression"],
    researchOps: ["Approximate attention accuracy/area tradeoffs"],
    contribOps: [],
    certs: [],
    resources: ["sze-book"],
  },
  {
    id: "fp-ml-eda", title: "ML-based congestion or timing prediction on open EDA data", tier: "research",
    categories: ["J. AI for EDA", "L. Research reproduction"], difficulty: 4, duration: "5-6 weeks part-time", phase: "p11",
    roles: ["eda", "aieda"],
    exceptional: "A reproducible ML pipeline: dataset from CircuitNet or your own ORFS sweeps, honest baselines, held-out-design evaluation, and a check of whether predictions would change a flow decision.",
    problem: "Predict routing congestion or post-route slack early, and measure whether it is useful.",
    motivation: "AI-for-EDA roles need people who understand both the flow and ML evaluation pitfalls.",
    researchBasis: ["Chai et al., CircuitNet dataset", "Xie et al., RouteNet (ICCAD 2018)", "Guo et al., timing-engine-inspired GNN (DAC 2022)"],
    prereqs: ["ml-prediction", "open-flow"],
    skills: ["Dataset building", "CNN/GNN modeling", "Evaluation methodology", "Flow automation"],
    architecture: "Data: CircuitNet features or ORFS runs over designs x configurations; features: placement density maps or netlist graphs; models: baseline (gradient boosting) + CNN or GNN; evaluation on held-out designs.",
    diagram: "designs x configs --> ORFS runs --> features + labels --> train/test split by design --> models --> metrics",
    requirements: ["Held-out design split", "Simple baseline", "Clear metric definitions", "Reproducible scripts"],
    milestones: [ms("m1", "Problem framing", "Target and metric."), ms("m2", "Data", "CircuitNet subset or own sweeps."), ms("m3", "Baseline", "Simple model."), ms("m4", "Deep model", "CNN or GNN."), ms("m5", "Evaluation", "Held-out designs, ablations."), ms("m6", "Report", "Limitations included.")],
    implementation: ["Version datasets", "Fix random seeds"],
    verification: ["Leakage checks", "Baseline sanity"],
    failureInjection: ["Random split vs design split to show leakage"],
    metrics: ["Correlation / error", "Top-k hotspot accuracy", "Runtime saving estimate"],
    ppa: "Not applicable; report compute cost.",
    timing: "If predicting slack, report error on critical endpoints.",
    benchmark: "CircuitNet public splits or your own documented split.",
    expected: "Deep models may beat baselines on some metrics; generalization to new designs is the hard part.",
    tools: ["Python", "PyTorch", "OpenROAD flow scripts", "pandas"],
    openSource: ["CircuitNet", "TimingPredict"],
    dataset: "CircuitNet (public) or self-generated ORFS data",
    repo: "data/  features/  models/  eval/  notebooks/  report/",
    docs: ["Paper-style report with limitations"],
    demo: ["Predicted vs actual congestion maps"],
    linkedinAngle: "Why my first ML-for-EDA model looked great and then failed on unseen designs.",
    resume: ["Built a reproducible congestion-prediction pipeline on CircuitNet with design-level held-out evaluation and baseline comparisons"],
    interview: [{ q: "How did you avoid data leakage?", followups: ["Why a design-level split?", "Would your model change a flow decision?"] }],
    extensions: ["Active learning for flow tuning"],
    researchOps: ["Transfer across PDKs"],
    contribOps: ["CircuitNet issues and examples"],
    certs: [],
    proof: ["spec", "architecture", "verification", "documentation", "github", "demo", "linkedin", "interview"],
    resources: ["circuitnet", "timingpredict", "orfs"],
  },
  {
    id: "fp-llm-hw", title: "LLM-for-hardware evaluation harness: RTL generation and assertion mutation testing", tier: "research",
    categories: ["J. AI for EDA", "B. Verification"], difficulty: 4, duration: "4-6 weeks part-time", phase: "p11",
    roles: ["dv", "eda", "aieda"],
    exceptional: "Rigorous, reproducible evaluation: pass@k on VerilogEval/RTLLM subsets with lint and synthesis checks, and mutation testing that measures whether LLM-written assertions catch real bugs compared with your own.",
    problem: "How useful are LLMs for RTL and verification, measured honestly?",
    motivation: "Companies are exploring AI assistance; people who can evaluate it rigorously are valuable.",
    researchBasis: ["Liu et al., VerilogEval (ICCAD 2023)", "Lu et al., RTLLM (ASP-DAC 2024)", "Liu et al., ChipNeMo (2023)", "Blocklove et al., Chip-Chat (2023)"],
    prereqs: ["llm-hardware", "sva", "regression-ci"],
    skills: ["Evaluation design", "Automation", "Mutation testing", "SVA"],
    architecture: "Harness: prompts -> model API or local model -> generated RTL/SVA -> lint (Verilator) -> simulate against reference tests -> synthesize (Yosys) -> metrics; mutation engine injects bugs into reference RTL to score assertion sets.",
    diagram: "problems --> LLM --> code --> lint --> sim --> synth --> results.csv\nref RTL --> mutants --> [LLM SVA | your SVA] --> detection matrix",
    requirements: ["Documented prompts and settings", "pass@1 and pass@k", "Failure taxonomy", "Mutation detection comparison"],
    milestones: [ms("m1", "Harness", "Run 20 problems end to end."), ms("m2", "Scale", "Full subset with seeds."), ms("m3", "Failure analysis", "Taxonomy."), ms("m4", "Assertions", "LLM SVA vs yours."), ms("m5", "Mutation engine", "Operators and runs."), ms("m6", "Report", "Limitations and contamination discussion.")],
    implementation: ["Cache generations", "Record model versions"],
    verification: ["Harness self-tests with known-good solutions"],
    failureInjection: ["Mutation operators: inverted conditions, off-by-one, wrong widths, stuck signals"],
    metrics: ["pass@k", "Lint/synth pass rate", "Mutation score"],
    ppa: "Synthesized area of generated vs reference designs (optional).",
    timing: "Not central.",
    benchmark: "VerilogEval and RTLLM problem sets.",
    expected: "Results vary by model and prompt; the value is in rigorous methodology and honest analysis.",
    tools: ["Python", "Verilator", "Icarus", "Yosys", "SymbiYosys (optional)"],
    openSource: ["VerilogEval", "RTLLM"],
    dataset: "VerilogEval, RTLLM",
    repo: "harness/  problems/  generations/  mutants/  results/  report/",
    docs: ["Methodology and results report"],
    demo: ["Results dashboard"],
    linkedinAngle: "Do LLM-written assertions actually catch bugs? A mutation-testing experiment.",
    resume: ["Built an automated harness evaluating LLM-generated RTL (pass@k with lint and synthesis) and assertion quality via mutation testing"],
    interview: [{ q: "What was the most common failure mode?", followups: ["How did you handle contamination?", "Would you use LLMs in production verification?"] }],
    extensions: ["Formal equivalence checks of generated RTL", "Feedback loops with simulator errors"],
    researchOps: ["Publishable benchmark extensions"],
    contribOps: ["Contribute problems or fixes to benchmark repos"],
    certs: [],
    proof: ["spec", "architecture", "verification", "assertions", "simulation", "synthesis", "documentation", "github", "demo", "linkedin", "interview"],
    resources: ["verilog-eval", "rtllm", "verilator", "yosys"],
  },
  {
    id: "fp-macro-placement", title: "Macro placement reproduction study (classical vs learned methods)", tier: "research",
    categories: ["J. AI for EDA", "F. Physical design", "L. Research reproduction"], difficulty: 5, duration: "6-8 weeks part-time (Research / Optional)", phase: "p11",
    roles: ["eda", "pd", "aieda"],
    exceptional: "Engages with a real research debate using open artifacts: run classical placers and an open learned method on public testcases, evaluate with full-flow metrics, and write a balanced analysis.",
    problem: "How do macro placement methods compare on realistic, reproducible benchmarks?",
    motivation: "Research literacy and reproduction skill are rare and valuable for EDA and AI-for-EDA roles.",
    researchBasis: ["Mirhoseini et al., graph placement methodology (Nature 2021)", "Cheng, Kahng et al., assessment of RL for macro placement (ISPD 2023) and the TILOS MacroPlacement repository", "Kahng et al., VLSI Physical Design (textbook)"],
    prereqs: ["rl-placement", "eda-algorithms", "open-flow"],
    skills: ["Placement algorithms", "Experimental design", "Full-flow evaluation", "Scientific writing"],
    architecture: "Use MacroPlacement testcases and scripts; implement a simulated-annealing macro placer; run OpenROAD's macro placement and, if feasible, Circuit Training on a small case; evaluate wirelength, congestion and timing after full flow.",
    diagram: "testcase --> {SA placer | OpenROAD macro placer | learned method} --> ORFS completion --> metrics --> comparison",
    requirements: ["Same testcases and budgets for all methods", "Full-flow metrics", "Balanced discussion of limitations"],
    milestones: [ms("m1", "Read papers and repo", "Summary of claims."), ms("m2", "Setup", "Run provided scripts."), ms("m3", "SA placer", "Your implementation."), ms("m4", "Comparisons", "Full-flow runs."), ms("m5", "Report", "Balanced analysis.")],
    implementation: ["Start with the smallest testcase", "Track compute budgets"],
    verification: ["Legality checks for placements"],
    failureInjection: ["Unequal budgets to show evaluation bias"],
    metrics: ["HPWL", "Routed wirelength", "Congestion overflow", "WNS/TNS", "Runtime"],
    ppa: "Report power/timing after full flow if available.",
    timing: "Post-route timing comparison.",
    benchmark: "TILOS MacroPlacement testcases.",
    expected: "Unknown in advance; the point is methodology. Report what you find with uncertainty.",
    tools: ["OpenROAD", "ORFS", "Python", "Circuit Training (optional)"],
    openSource: ["TILOS MacroPlacement", "Circuit Training", "DREAMPlace"],
    repo: "cases/  placers/  flow/  results/  report/",
    docs: ["Reproduction report"],
    demo: ["Placement visuals", "Metrics table"],
    linkedinAngle: "What I learned reproducing part of the macro placement debate.",
    resume: ["Reproduced macro placement comparisons on public testcases with full-flow evaluation and wrote a balanced analysis"],
    interview: [{ q: "What makes a placement comparison fair?", followups: ["Why full-flow metrics?", "What surprised you?"] }],
    extensions: ["Bayesian optimization of placer parameters"],
    researchOps: ["Workshop-style write-up"],
    contribOps: ["Issues or docs to MacroPlacement"],
    certs: [],
    proof: ["spec", "architecture", "verification", "timing", "ppa", "documentation", "github", "demo", "linkedin", "interview"],
    resources: ["macroplacement", "circuit-training", "openroad", "dreamplace", "kahng-pd"],
  },
  {
    id: "fp-capstone", title: "Capstone: edge-AI RISC-V SoC (core + accelerator + driver + flow)", tier: "flagship", capstone: true,
    categories: ["K. HW/SW co-design", "D. RISC-V", "I. AI hardware", "H. FPGA", "E. ASIC flow"], difficulty: 5, duration: "10-14 weeks part-time", phase: "p12",
    roles: ["rtl", "dv", "aihw", "fpga"],
    exceptional: "The centerpiece that ties your journey together: your pipelined RISC-V core (or an established open core) plus your INT8 accelerator on an AXI-Lite/APB fabric, a C driver, end-to-end benchmarks, UVM or cocotb verification, FPGA demo, and an optional GDS of the accelerator tile.",
    problem: "Deliver a small but complete system and measure real end-to-end speedup.",
    motivation: "Shows system-level thinking: architecture, RTL, verification, software, measurement, implementation and communication.",
    researchBasis: ["Gemmini full-stack integration approach", "Hennessy & Patterson on domain-specific architectures", "Amdahl's law for end-to-end speedup"],
    prereqs: ["hw-sw-codesign", "fp-rv-pipeline", "fp-fpga-accel"],
    skills: ["SoC integration", "HW/SW interface design", "System verification", "Benchmarking", "Technical writing"],
    architecture: "RV32 core, instruction/data SRAM, AXI4-Lite interconnect, APB peripherals (UART, timer), accelerator with control registers and a simple DMA, optional custom instruction; firmware in C; FPGA build via LiteX or your own top level; optional accelerator tile through LibreLane.",
    diagram: "[RV32 core] --AXI-Lite--> [interconnect] --> SRAM\n                              +--> [accelerator + DMA]\n                              +--> APB bridge --> UART, timer\nC firmware + driver --> benchmark --> UART output",
    requirements: ["Firmware runs a benchmark on the core with and without the accelerator", "Verification at block and system level", "FPGA or full-system simulation demo", "Paper-style report with PPA and speedup"],
    milestones: [ms("m1", "System spec", "Use cases and targets."), ms("m2", "Integration plan", "Address map, interfaces."), ms("m3", "Fabric and peripherals", "Reuse flagship blocks."), ms("m4", "Accelerator integration", "Registers and DMA."), ms("m5", "Driver and firmware", "C API and benchmark."), ms("m6", "System verification", "Firmware-driven tests in simulation."), ms("m7", "FPGA demo", "Board or LiteX simulation."), ms("m8", "Implementation", "Synthesis and optional GDS for accelerator."), ms("m9", "Report and showcase", "Paper, video, posts.", "Paper-style PDF or Markdown report")],
    implementation: ["Reuse and harden earlier flagship blocks", "Freeze interfaces early"],
    verification: ["Block-level regressions", "System tests driven by firmware", "Performance counters"],
    failureInjection: ["DMA boundary bug", "Interrupt race"],
    metrics: ["End-to-end speedup", "Energy estimate", "Area breakdown", "Fmax", "Accuracy"],
    ppa: "Area and power breakdown by block; speedup per added area.",
    timing: "System critical path and fixes.",
    benchmark: "Software-only vs accelerated inference of a small model, including data movement.",
    expected: "Kernel speedups larger than end-to-end speedups; explain with Amdahl's law.",
    tools: ["Verilator", "cocotb/UVM", "riscv-gnu-toolchain", "LiteX (optional)", "FPGA tools", "LibreLane (optional)"],
    openSource: ["LiteX", "VexRiscv or your own core", "Gemmini as reference"],
    repo: "hw/  sw/  tb/  fpga/  asic/  docs/  results/  paper/",
    docs: ["System spec", "Architecture", "Verification report", "Performance and PPA report", "Paper-style write-up"],
    demo: ["Video of the benchmark running", "Speedup chart", "Floorplan/GDS image (optional)"],
    linkedinAngle: "A year of learning in one system: RISC-V + INT8 accelerator, measured end to end.",
    resume: ["Built an edge-AI SoC integrating a RISC-V core with an INT8 systolic accelerator; wrote the C driver, verified at block and system level, and measured end-to-end speedup on FPGA"],
    interview: [{ q: "Why is end-to-end speedup lower than kernel speedup?", followups: ["What would you change in the interface?", "What was the hardest integration bug?"] }],
    extensions: ["Custom RISC-V instruction", "Interrupt-driven DMA", "Tiny Tapeout-size accelerator tile"],
    researchOps: ["Compare MMIO vs custom-instruction offload"],
    contribOps: ["Share as an open reference design"],
    certs: ["rvfa"],
    resources: ["litex", "gemmini", "vexriscv", "riscv-gnu-toolchain"],
  },
];
