import type { Flagship, ProofStage } from "./schema.ts";

// Embedded and VLSI + Embedded crossover flagships (added 2026-09-24).
const ms = (id: string, title: string, detail: string, evidence?: string) => ({ id, title, detail, evidence });
const EMB_PROOF: ProofStage[] = ["spec", "architecture", "firmware", "verification", "measurement", "ci", "documentation", "github", "demo", "release", "interview"];

export const FLAGSHIP_EMBEDDED: Flagship[] = [
  {
    id: "fe-fw-stack", title: "Custom Cortex-M firmware stack: bare metal versus FreeRTOS versus Zephyr", tier: "flagship", categories: ["Embedded", "Firmware", "RTOS"], difficulty: 4, duration: "4-6 weeks", phase: "e6",
    roles: ["emb-firmware"],
    exceptional: "The same sensor application built three ways on one board, from your own startup code and drivers up, with measured size, latency, jitter and power for each.",
    problem: "Engineers pick bare metal or an RTOS by habit. Few can show, with numbers, what each choice costs and buys.",
    motivation: "Demonstrates every layer: linker script, startup, register drivers, interrupts, DMA, scheduling and measurement.",
    researchBasis: ["Rate-monotonic analysis (Liu and Layland)", "Vendor RTOS documentation", "Your own measurements"],
    prereqs: ["emb-linker-startup", "emb-dma", "emb-freertos", "emb-zephyr"],
    skills: ["Startup code and linker scripts", "Register-level drivers", "Interrupts and DMA", "FreeRTOS and Zephyr", "Measurement and profiling"],
    architecture: "Shared hardware-independent application core (sensor processing, CLI, telemetry format) compiled against three platform layers: (1) bare-metal superloop plus interrupts with your own startup and drivers, (2) FreeRTOS tasks and queues on the same drivers, (3) Zephyr with devicetree and native drivers.",
    diagram: `+----------------------------- application core (host-tested) -----------------------------+
|  sensor processing  |  CLI commands  |  telemetry encoder  |  health / watchdog policy     |
+-------------+-------------------------+-------------------------+--------------------------+
| bare metal  | FreeRTOS                | Zephyr                  |  <- platform layer        |
| superloop + | tasks, queues,          | threads, work queues,   |                           |
| IRQs + DMA  | notifications           | devicetree drivers      |                           |
+-------------+-------------------------+-------------------------+--------------------------+
|        own startup + linker script + register drivers (UART, I2C, timer, DMA)             |
+--------------------------------------------------------------------------------------------+`,
    requirements: ["Identical externally visible behaviour in all three builds", "Sensor sampled at a fixed rate via timer trigger", "CLI over interrupt/DMA UART", "Watchdog with check-ins", "Host unit tests for the application core"],
    milestones: [ms("a", "Bare-metal base", "Own startup, linker script and drivers; sensor + CLI working.", "Map file and size report"), ms("b", "FreeRTOS port", "Tasks and queues on the same drivers.", "Task table and stack high-water marks"), ms("c", "Zephyr port", "Devicetree overlay and Zephyr drivers.", "Twister results"), ms("d", "Measurement campaign", "Flash/RAM, ISR latency, sampling jitter, CPU load, current.", "Comparison table with method"), ms("e", "Write-up", "When to choose each approach, with evidence.", "Published README and article")],
    implementation: ["Keep the application core free of platform headers", "Share drivers between bare metal and FreeRTOS builds", "One CMake option per platform", "GPIO markers compiled into all builds for timing"],
    verification: ["Host tests for the core in CI", "Scripted CLI tests over serial for each build", "24-hour soak per build"],
    failureInjection: ["Sensor unplugged", "UART flood", "Hung task to trigger the watchdog"],
    metrics: ["Flash and RAM per build", "ISR latency and jitter", "Sample-period jitter", "CPU load", "Average current"],
    ppa: "Embedded equivalent of PPA: footprint (flash/RAM), timing (latency/jitter) and energy for each build.",
    timing: "Sampling at 1 kHz with jitter measured by logic analyzer; CLI response under load.",
    benchmark: "Same workload and inputs across builds; results table with standard deviations.",
    expected: "Bare metal smallest and lowest latency; RTOS builds easier to extend with modest overhead; Zephyr largest footprint with the most features.",
    tools: ["arm-none-eabi-gcc", "CMake/Ninja", "OpenOCD/GDB", "FreeRTOS", "Zephyr", "Logic analyzer", "Power measurement"],
    openSource: ["FreeRTOS-Kernel", "Zephyr", "CMSIS 6", "Unity"],
    repo: "fw-stack-compare: core/, platform/{baremetal,freertos,zephyr}/, drivers/, tests/, docs/, results/",
    docs: ["Architecture and layering diagram", "Timing and memory budget", "Measurement method", "Results and recommendation"],
    demo: ["Side-by-side logic analyzer captures", "Short video switching builds"],
    linkedinAngle: "What an RTOS really costs on a Cortex-M4: numbers from three builds of the same application.",
    resume: ["Built one sensor application on bare metal, FreeRTOS and Zephyr from custom startup code and drivers; measured footprint, ISR latency and jitter to guide platform choice."],
    interview: [{ q: "When would you not use an RTOS?", followups: ["What did your measurements show?", "How would requirements change your answer?"] }, { q: "How did you measure jitter?", followups: ["What was the worst case and why?"] }],
    extensions: ["Add tickless low-power modes", "Add a TrustZone-M secure partition"],
    researchOps: ["Compare scheduling overhead with published RTOS benchmarks"],
    contribOps: ["Upstream a board overlay or documentation fix to Zephyr"],
    certs: [], proof: EMB_PROOF, resources: ["gh-freertos", "gh-zephyr", "gh-bare-metal-guide"],
  },
  {
    id: "fe-rtos-gateway", title: "RTOS-based industrial telemetry gateway", tier: "flagship", categories: ["Embedded", "RTOS", "IoT"], difficulty: 4, duration: "5-7 weeks", phase: "e7",
    roles: ["emb-firmware", "emb-iot"],
    exceptional: "Meets the portfolio quality bar exactly: interrupt/DMA acquisition, ring buffers, RTOS processing, MQTT over TLS, a diagnostics CLI, watchdog recovery, unit tests, CI and documented architecture.",
    problem: "Industrial sensors need a small, robust gateway that never silently stops publishing.",
    motivation: "Integrates most of the core road into one production-shaped system.",
    researchBasis: ["MQTT specification", "Vendor RTOS and networking docs", "Industrial reliability practice"],
    prereqs: ["emb-freertos", "emb-dma", "emb-iot-proto", "emb-testing"],
    skills: ["RTOS architecture", "DMA acquisition", "MQTT/TLS", "Robustness engineering", "Testing and CI"],
    architecture: "Acquisition (I2C/SPI sensors + ADC via DMA) -> ring buffers -> processing task (filtering, thresholds) -> telemetry task (MQTT/TLS with offline buffer) + CLI task + health/watchdog task; configuration in flash; OTA hook.",
    diagram: `sensors --I2C/SPI--> driver --\\
ADC --timer+DMA--> ring buffer ----> processing task --> telemetry queue --> MQTT/TLS task --> broker
                                          |                                   |
                                     CLI task <--UART                  offline buffer
                     health task: check-ins -> watchdog kick, reset-cause + crash record`,
    requirements: ["At least two sensors, one via DMA", "MQTT over TLS with certificate validation", "Offline buffering and reconnect with backoff", "Diagnostics CLI", "Watchdog with task check-ins and crash records", "CI with unit tests and static analysis"],
    milestones: [ms("a", "Architecture", "Task table, timing and memory budget.", "Architecture document"), ms("b", "Acquisition", "Drivers and DMA with tests.", "Captures"), ms("c", "Connectivity", "Secure MQTT and offline buffer.", "Broker logs"), ms("d", "Robustness", "Watchdog, crash records, fault injection.", "Fault-injection table"), ms("e", "CI and docs", "Pipeline, README, measurements.", "CI badge and report")],
    implementation: ["Static allocation only", "Driver layer host-tested with fakes", "Configuration with A/B records and CRC"],
    verification: ["Unit tests in CI", "72-hour soak with broker restarts", "Network outage tests"],
    failureInjection: ["Broker down 30 minutes", "Sensor disconnect", "Queue overflow", "Task hang"],
    metrics: ["Message loss rate", "End-to-end latency", "CPU load", "Stack/heap margins", "Recovery time"],
    ppa: "Footprint, CPU load and power budget per subsystem.",
    timing: "Sampling deadlines met under network retries.",
    benchmark: "Throughput and latency at 1, 10 and 100 messages per second.",
    expected: "Zero silent failures: every fault is recovered or reported.",
    tools: ["FreeRTOS or Zephyr", "lwIP/Zephyr net", "Mbed TLS", "Mosquitto", "Unity", "GitHub Actions"],
    openSource: ["FreeRTOS-Kernel or Zephyr", "Mbed TLS", "lwIP", "nanopb"],
    repo: "rtos-gateway: app/, drivers/, net/, tests/, ci/, docs/",
    docs: ["Hardware and pinout", "Firmware architecture and state machines", "Protocol/topic design", "Build, flash, test", "Debugging guide", "Known issues"],
    demo: ["Dashboard of live telemetry", "Video of an outage and automatic recovery"],
    linkedinAngle: "Designing firmware that never fails silently: what fault injection taught me.",
    resume: ["Designed an RTOS telemetry gateway with DMA acquisition, MQTT over TLS, offline buffering and watchdog-backed crash recovery; zero message loss over a 72-hour soak with injected outages."],
    interview: [{ q: "Walk me through your task design.", followups: ["Why these priorities?", "What happens when the broker is down for an hour?"] }, { q: "How do you know the gateway is healthy?", followups: ["What does the watchdog actually check?"] }],
    extensions: ["Add MCUboot OTA (see the secure OTA flagship)", "Add Modbus RTU sensors"],
    researchOps: [], contribOps: ["Documentation or example contributions to the RTOS or MQTT library you used"],
    certs: [], proof: EMB_PROOF, resources: ["gh-freertos", "gh-mbedtls", "mqtt-org"],
  },
  {
    id: "fe-secure-ota", title: "Secure boot + signed OTA + crash recovery platform", tier: "flagship", categories: ["Embedded", "Security", "Production"], difficulty: 5, duration: "5-7 weeks", phase: "e8",
    roles: ["emb-firmware", "emb-iot"],
    exceptional: "Production-level thinking in one project: MCU, bootloader, signed firmware, secure fail-safe update with rollback, watchdog, telemetry, logging and crash recovery.",
    problem: "Connected devices need updates that cannot be forged, cannot brick the device and can be diagnosed when they fail in the field.",
    motivation: "Security and update engineering are among the most valued firmware skills, and few candidates can demonstrate them end to end.",
    researchBasis: ["MCUboot design documentation", "PSA and Trusted Firmware-M concepts", "EU Cyber Resilience Act expectations for update and vulnerability handling"],
    prereqs: ["emb-ota", "emb-security", "emb-production"],
    skills: ["MCUboot and image signing", "Update transport", "Rollback and anti-rollback", "Crash reporting", "Threat modelling"],
    architecture: "MCUboot (swap with confirmation) + application with OTA client (HTTP or MQTT) writing the secondary slot, health checks before confirmation, crash records in no-init RAM uploaded as telemetry, locked debug port in the release configuration.",
    diagram: `[boot ROM] -> [MCUboot: verify signature, swap/revert] -> [app vN]
                                                   | OTA client downloads vN+1 -> secondary slot
                                                   | reboot -> test boot -> health checks -> confirm
                                                   | no confirm -> automatic revert to vN
crash handler -> no-init RAM record -> uploaded at next boot -> symbolised with archived ELF`,
    requirements: ["Signed images (ECDSA P-256 or Ed25519)", "Power-loss-safe swap", "Confirm only after health checks", "Security counter (anti-rollback)", "Crash records uploaded", "Threat model document"],
    milestones: [ms("a", "Threat model", "Assets, attackers, mitigations.", "Threat model"), ms("b", "Signed boot", "MCUboot with your key; unsigned image rejected.", "Rejection log"), ms("c", "OTA client", "Download, verify, reboot, confirm.", "Update log"), ms("d", "Failure testing", "Power cuts, bad images, unconfirmed images.", "Test matrix"), ms("e", "Field diagnostics", "Crash records and telemetry.", "Decoded coredump example")],
    implementation: ["Keys generated and stored outside the repository", "Build ID in every image", "Release configuration locks debug"],
    verification: ["Automated update loop with random power cuts", "Negative tests: wrong key, downgrade, truncated image"],
    failureInjection: ["Power cut during download and during swap", "Image that crashes at boot", "Image that never confirms"],
    metrics: ["Update success rate", "Recovery time after bad image", "Update time and energy"],
    ppa: "Slot sizing versus flash budget; update energy.",
    timing: "Boot time with and without swap.",
    benchmark: "1000 update cycles with injected faults.",
    expected: "No bricked devices; every bad image reverted; every crash diagnosed.",
    tools: ["MCUboot", "Zephyr sysbuild or your RTOS", "imgtool", "Python test harness"],
    openSource: ["MCUboot", "Zephyr", "Mbed TLS", "littlefs"],
    repo: "secure-ota: bootloader/, app/, keys/ (placeholders only), tools/, tests/, docs/threat-model.md",
    docs: ["Threat model", "Flash map", "Update state machine", "Key management", "Release checklist"],
    demo: ["Video: update, pull power mid-swap, device recovers", "Rejected malicious image log"],
    linkedinAngle: "I tried to brick my own device 1000 times: building fail-safe signed firmware updates.",
    resume: ["Built a secure update platform with MCUboot-signed images, health-checked confirmation, anti-rollback and crash telemetry; 1000 fault-injected update cycles without a bricked device."],
    interview: [{ q: "How does your device decide to roll back?", followups: ["What if power fails during the revert?", "How do you prevent downgrade attacks?"] }, { q: "Where are your keys?", followups: ["How would you rotate them?"] }],
    extensions: ["TrustZone-M with Trusted Firmware-M secure services", "Delta updates"],
    researchOps: ["Fault-injection resistance of signature checks"], contribOps: ["MCUboot documentation or test contributions"],
    certs: [], proof: EMB_PROOF, resources: ["gh-mcuboot", "mcuboot-docs", "tfm-docs"],
  },
  {
    id: "fe-linux-bsp", title: "Embedded Linux BSP: Yocto image, device tree and a custom driver", tier: "flagship", categories: ["Embedded", "Embedded Linux"], difficulty: 5, duration: "6-8 weeks", phase: "e9",
    roles: ["emb-linux"],
    exceptional: "A product-style Linux image built with the current Yocto release (bitbake-setup), a custom layer, a device-tree node and a platform/I2C driver you wrote, with A/B boot fallback.",
    problem: "BSP roles need proof you can own the whole stack from bootloader to user-space service.",
    motivation: "Directly matches recurring embedded Linux job requirements: Yocto/Buildroot, device tree, drivers, U-Boot.",
    researchBasis: ["Yocto Project 6.0 documentation and migration notes", "Kernel driver API docs", "Bootlin training materials"],
    prereqs: ["emb-yocto", "emb-linux-drivers", "emb-uboot"],
    skills: ["Yocto layers and recipes", "Device tree", "Kernel drivers", "U-Boot scripting", "systemd services"],
    architecture: "Board (Raspberry Pi, BeagleBone or QEMU) + meta-myproduct layer: machine config fragment, kernel bbappend with your driver and DT overlay, image recipe with your daemon as a systemd service, U-Boot boot script with A/B fallback.",
    diagram: `bitbake-setup -> openembedded-core + meta-yocto + BSP layer + meta-myproduct
meta-myproduct: recipes-kernel/ (driver + DT overlay bbappend)
                recipes-apps/   (sensor daemon + systemd unit)
                recipes-core/images/myproduct-image.bb
boot: ROM -> U-Boot (boot.scr, A/B + bootcount) -> kernel + DTB -> systemd -> daemon`,
    requirements: ["Builds from a fresh clone with documented commands", "Driver probes from device tree", "Daemon exposes data over a socket or MQTT", "A/B boot fallback demonstrated", "SBOM generated"],
    milestones: [ms("a", "Buildroot prototype", "Quick image to de-risk the board.", "Boot log"), ms("b", "Yocto baseline", "Current release image boots.", "Build log"), ms("c", "Driver + DT", "Custom driver and overlay in the layer.", "dmesg probe log"), ms("d", "Product image", "Daemon, systemd, A/B boot.", "Fallback demo"), ms("e", "Docs", "Layer README, build and flash guide.", "Published repository")],
    implementation: ["No edits to upstream layers", "devtool for recipe iteration", "Kernel config fragments"],
    verification: ["Image boots in CI (QEMU)", "Driver load/unload stress", "Fallback after deliberately broken slot"],
    failureInjection: ["Corrupt root filesystem slot", "Sensor missing at boot"],
    metrics: ["Image size", "Boot time", "Build time with and without sstate"],
    ppa: "Image footprint and boot time.",
    timing: "Boot to service-ready time.",
    benchmark: "Buildroot versus Yocto image size and build time for the same function.",
    expected: "A reproducible product image and a driver you can explain line by line.",
    tools: ["Yocto 6.0 (Wrynose)", "bitbake-setup", "U-Boot", "QEMU", "Linux kernel"],
    openSource: ["openembedded-core", "U-Boot", "Linux kernel", "Buildroot"],
    repo: "meta-myproduct + bsp-notes: layer, kas or bitbake-setup config, docs/",
    docs: ["Boot chain diagram", "Layer structure", "Driver design and binding", "Build/flash/recovery guide"],
    demo: ["Boot video with fallback", "Sensor data from user space"],
    linkedinAngle: "From Buildroot prototype to Yocto product image: what changed with Wrynose and bitbake-setup.",
    resume: ["Built a Yocto 6.0 product image with a custom layer, device-tree overlay and I2C platform driver, plus U-Boot A/B fallback; reproducible from a fresh clone."],
    interview: [{ q: "How does your driver get bound?", followups: ["What happens if the compatible string is wrong?", "How did you handle probe errors?"] }, { q: "Why Yocto rather than Buildroot here?", followups: ["What did it cost you?"] }],
    extensions: ["Verified boot with signed FIT images", "RAUC or SWUpdate for A/B updates"],
    researchOps: [], contribOps: ["Upstream a small kernel or layer fix"],
    certs: [], proof: EMB_PROOF, resources: ["yocto-docs", "gh-bootlin-training", "kernel-driver-api"],
  },
  {
    id: "fe-can-ecu", title: "CAN ECU simulator with UDS diagnostics and a CAN bootloader", tier: "flagship", categories: ["Embedded", "Automotive"], difficulty: 5, duration: "5-7 weeks", phase: "e10",
    roles: ["emb-automotive"],
    exceptional: "An MCU ECU that publishes cyclic CAN signals, answers UDS diagnostics over ISO-TP, supports security access and reflashing over CAN, and follows MISRA-style static analysis.",
    problem: "Automotive interviews expect CAN, UDS and bootloader experience that is hard to get without an employer.",
    motivation: "Builds the automotive branch skills with open tools, honestly scoped (no proprietary AUTOSAR stack).",
    researchBasis: ["ISO 14229 (UDS) and ISO 15765-2 (ISO-TP) public summaries", "SocketCAN documentation"],
    prereqs: ["emb-automotive", "emb-can", "emb-bootloader"],
    skills: ["CAN and ISO-TP", "UDS server", "Bootloader over CAN", "Static analysis discipline"],
    architecture: "ECU firmware: CAN driver with filters, cyclic signal scheduler, ISO-TP layer, UDS dispatcher (sessions, DIDs, security access, routine control, download), bootloader sharing the ISO-TP/UDS stack; PC tester in Python over a USB-CAN adapter or SocketCAN.",
    diagram: `PC tester (python-can / UDS client) <==CAN 500k==> ECU
ECU: CAN driver -> ISO-TP -> UDS dispatcher -> {DIDs, sessions, security access, routines}
     cyclic signal task (10/100 ms)            programming session -> bootloader -> flash`,
    requirements: ["Cyclic frames with correct periods", "UDS 0x10/0x11/0x22/0x2E/0x27/0x31/0x34/0x36/0x37/0x3E", "Negative responses with correct codes", "Reflash via UDS with verification", "Static analysis clean"],
    milestones: [ms("a", "CAN base", "Driver, filters, cyclic signals.", "candump trace"), ms("b", "ISO-TP + UDS", "Diagnostics services.", "Tester trace"), ms("c", "Bootloader", "Programming session and flashing.", "Reflash log"), ms("d", "Quality", "Static analysis and tests.", "Analysis report")],
    implementation: ["Shared transport between app and bootloader", "Timeouts per ISO-TP and UDS timing parameters"],
    verification: ["Python test suite covering every service and NRC", "Bus-off and error tests"],
    failureInjection: ["Interrupted download", "Wrong security key", "Bus errors during flashing"],
    metrics: ["Reflash time", "Timing accuracy of cyclic frames", "Test coverage of services"],
    ppa: "Flash/RAM of stack; CPU load at full bus load.",
    timing: "Cyclic period jitter; diagnostic response times.",
    benchmark: "Bus load versus response time.",
    expected: "A tester-verified ECU and reflash flow.",
    tools: ["MCU with CAN", "SocketCAN/python-can", "cppcheck (MISRA addon awareness)"],
    openSource: ["can-utils", "python-can"],
    repo: "can-ecu-sim: ecu/, bootloader/, tester/, tests/, docs/",
    docs: ["Communication matrix", "Diagnostic specification (DIDs, sessions)", "Bootloader flow"],
    demo: ["Tester session video", "Reflash with power interruption and recovery"],
    linkedinAngle: "Building a UDS-capable ECU and CAN bootloader with open tools.",
    resume: ["Implemented a CAN ECU simulator with ISO-TP, UDS diagnostics, security access and a UDS-driven bootloader; verified by an automated Python tester."],
    interview: [{ q: "Explain how a flashing session works over UDS.", followups: ["Where does security access fit?", "What happens on an interrupted download?"] }],
    extensions: ["CAN FD", "Add SecOC-style message authentication (conceptual)"],
    researchOps: [], contribOps: ["Examples or docs for open CAN tooling"],
    certs: [], proof: EMB_PROOF, resources: ["can-intro", "misra"],
  },
  {
    id: "fx-soc-peripheral", title: "Crossover: custom peripheral from SystemRDL and RTL to Linux/bare-metal driver on an FPGA SoC", tier: "flagship", categories: ["Crossover", "Embedded", "RTL", "Verification"], difficulty: 5, duration: "6-8 weeks", phase: "e10",
    roles: ["emb-firmware", "validation", "rtl"],
    exceptional: "One engineer, one register map, both sides: a peripheral designed and verified in RTL, integrated into a RISC-V SoC on an FPGA, driven by firmware you wrote, validated with instruments.",
    problem: "Hardware and firmware teams collide at the register interface; engineers who can work across it are valuable in SoC, pre-silicon firmware and validation roles.",
    motivation: "This repository's signature project: it joins the VLSI road and the Embedded road.",
    researchBasis: ["SystemRDL 2.0", "AMBA APB/AXI-Lite specifications", "LiteX SoC builder documentation"],
    prereqs: ["emb-hwsw-crossover", "apb", "cocotb", "emb-drivers"],
    skills: ["Register-map design", "SystemVerilog RTL", "cocotb/SVA verification", "SoC integration", "C driver and interrupts", "FPGA validation"],
    architecture: "SystemRDL register map -> PeakRDL generates the register block and C header; your PWM/timer or small DMA engine RTL behind it; integrated into a LiteX SoC (VexRiscv) on an FPGA; bare-metal driver with interrupt handler; optional Linux platform driver if the SoC runs Linux.",
    diagram: `regs.rdl --PeakRDL--> regblock.sv + regs.h + docs.html
peripheral.sv (APB/Wishbone/AXI-Lite slave, IRQ) --cocotb + SVA--> verified RTL
LiteX SoC: VexRiscv + bus + UART + peripheral --> FPGA bitstream
firmware: driver.c (regs.h) + ISR --> runs in Verilator co-sim and on FPGA --> logic analyzer`,
    requirements: ["Single source of truth for registers", "RTL verified with coverage and assertions", "Interrupt with documented clear semantics", "Firmware test passes in co-simulation and on FPGA", "Synthesis report (Fmax, resources)"],
    milestones: [ms("a", "Spec and register map", "SystemRDL and generated artifacts.", "Generated docs"), ms("b", "RTL and verification", "cocotb tests, SVA, coverage.", "Coverage report"), ms("c", "SoC integration", "LiteX build and simulation.", "Simulation log"), ms("d", "Driver and firmware", "Driver, ISR, example app.", "Co-sim trace"), ms("e", "FPGA validation", "Measurements on hardware.", "Logic analyzer captures"), ms("f", "Documentation", "End-to-end write-up using the crossover template.", "Published report")],
    implementation: ["Generate, never hand-edit, the header", "Same register test in cocotb and in firmware", "CI job regenerating artifacts and running both test suites"],
    verification: ["cocotb unit tests + SVA", "Firmware on Verilator co-simulation", "On-board tests with instrument captures"],
    failureInjection: ["Interrupt storm (clear not done)", "Register write during active operation", "Bus error on invalid address"],
    metrics: ["Coverage", "Fmax and LUT/FF usage", "Interrupt latency end to end", "Driver code size"],
    ppa: "FPGA resources and Fmax for the peripheral; optional sky130 synthesis for area.",
    timing: "Meets the SoC clock on the FPGA with margin.",
    benchmark: "Hardware peripheral versus software implementation (for example PWM or CRC) in CPU load.",
    expected: "A hardware/software feature that works identically in simulation and on silicon-like hardware.",
    tools: ["SystemRDL/PeakRDL", "Verilator", "cocotb", "LiteX", "Yosys/nextpnr or vendor tools", "arm/riscv GCC", "Logic analyzer"],
    openSource: ["PeakRDL-regblock", "LiteX", "VexRiscv", "cocotb", "Verilator"],
    repo: "soc-peripheral: rdl/, rtl/, tb/, soc/, fw/, linux/ (optional), docs/, ci/",
    docs: ["Hardware spec", "Register map", "RTL microarchitecture", "Verification plan and results", "Driver API", "Validation report"],
    demo: ["FPGA demo video with captures", "Side-by-side co-sim and hardware logs"],
    linkedinAngle: "From SystemVerilog to C driver: designing a peripheral and the firmware that uses it.",
    resume: ["Designed, verified and integrated a custom peripheral into a RISC-V FPGA SoC from a single SystemRDL register map, and wrote its interrupt-driven driver; identical tests passed in co-simulation and on hardware."],
    interview: [{ q: "How did you keep hardware and firmware in sync?", followups: ["What happens when a register changes?", "How are interrupts cleared?"] }, { q: "What bug crossed the boundary?", followups: ["Which side fixed it and why?"] }],
    extensions: ["Add a DMA engine and scatter-gather driver", "RISC-V custom instruction experiment", "Tiny Tapeout version of the peripheral"],
    researchOps: ["Hardware/software partitioning study for an accelerator"], contribOps: ["LiteX or PeakRDL examples and documentation"],
    certs: [], proof: ["spec", "architecture", "rtl", "verification", "assertions", "coverage", "synthesis", "firmware", "measurement", "documentation", "github", "demo", "interview"],
    resources: ["peakrdl", "litex", "cocotb", "verilator"],
  },
];
