import type { Flagship } from "./schema.ts";

const ms = (id: string, title: string, detail: string, evidence?: string) => ({ id, title, detail, evidence });

export const FLAGSHIP_A: Flagship[] = [
  {
    id: "fp-rv-pipeline", title: "RV32I five-stage pipelined core with lockstep co-simulation", tier: "flagship",
    categories: ["C. Computer architecture", "D. RISC-V", "A. Advanced RTL", "B. Verification"], difficulty: 4, duration: "6-8 weeks part-time", phase: "p6",
    roles: ["rtl", "dv", "arch"],
    exceptional: "Most student cores stop at 'it runs a program'. This one is checked instruction-by-instruction against Spike, stress-tested with a random instruction generator, and reports a CPI breakdown by stall cause.",
    problem: "Build a correct, measurable pipelined RISC-V core and prove it with industry-style verification.",
    motivation: "CPU verification teams use exactly this approach: a golden ISS, compliance suites and random streams. It demonstrates design, verification and performance analysis in one project.",
    researchBasis: ["Harris & Harris pipelined RISC-V microarchitecture", "Patterson & Hennessy hazard handling", "riscv-dv random instruction generation", "RISCOF architectural test framework"],
    prereqs: ["hazards", "sv-design", "self-checking-tb", "c-for-hw"],
    skills: ["Pipelined datapath and hazard unit", "Forwarding, stalls and flushes", "Co-simulation with a golden model", "Performance counters and CPI analysis", "Verilator testbenches in C++ or cocotb"],
    architecture: "Classic IF/ID/EX/MEM/WB with a hazard unit, forwarding muxes, static not-taken prediction (later a small BHT), Zicsr subset for cycle/instret counters, and a retirement trace port that emits PC, instruction and register write for comparison.",
    diagram: "IF --> ID --> EX --> MEM --> WB\n |      |     ^ ^     |      |\n |   hazard   | +--fwd MEM/WB-+\n |   unit ----+--fwd EX/MEM\n +<-- flush/redirect (branch in EX)\nretire trace --> compare with Spike log",
    requirements: ["Pass rv32ui riscv-tests and a RISCOF RV32I run", "Zero mismatches against Spike over 10M random instructions", "Report CPI on CoreMark and a stall breakdown", "Synthesize with Yosys and report Fmax estimate and area"],
    milestones: [ms("m1", "Spec and microarchitecture doc", "Stages, hazards, trace format.", "docs/uarch.md"), ms("m2", "Pipeline without hazards", "Program with NOPs runs."), ms("m3", "Hazard unit and forwarding", "Directed dependency tests pass."), ms("m4", "Branches and flushes", "Control hazard tests."), ms("m5", "Lockstep co-simulation", "Retirement trace compared with Spike."), ms("m6", "Random streams", "riscv-dv or a custom generator; bugs logged.", "Bug log with root causes"), ms("m7", "Performance", "Counters, CoreMark CPI, breakdown chart."), ms("m8", "Synthesis and report", "Area, timing, README, write-up.")],
    implementation: ["Start from your single-cycle core and insert pipeline registers", "Carry a valid bit and instruction PC through every stage", "Add a retirement interface early; it is your debug lifeline", "Keep the trace format identical to Spike's commit log"],
    verification: ["Directed hazard tests (every forwarding path, load-use)", "riscv-tests and RISCOF", "Lockstep comparison with Spike on each retirement", "Random instruction streams with seeds in CI", "SVA: no two writes to x0, valid-bit invariants"],
    failureInjection: ["Remove MEM/WB forwarding priority", "Break load-use stall", "Wrong branch offset sign-extension", "Record which check catches each bug and after how many instructions"],
    metrics: ["CPI (CoreMark)", "Stall cycles by cause", "Instructions to first mismatch for injected bugs", "Fmax estimate and cell area"],
    ppa: "Compare area and critical path with and without forwarding; report the cost of the hazard unit.",
    timing: "Identify the critical path (usually EX forwarding into ALU or branch compare) and try one fix.",
    benchmark: "CoreMark (eembc/coremark) compiled for RV32I; Dhrystone optional.",
    expected: "CPI around 1.2-1.5 on CoreMark depending on branch handling; exact numbers depend on your memory model and predictor.",
    tools: ["Verilator", "Spike", "riscv-gnu-toolchain", "riscv-tests", "RISCOF", "riscv-dv (or custom Python generator)", "Yosys", "GitHub Actions"],
    openSource: ["All tools above are open source"],
    repo: "rtl/  tb/  sim/ (verilator harness)  sw/ (tests, CoreMark port)  scripts/ (trace compare)  docs/ (uarch, verification report)  results/",
    docs: ["Microarchitecture document", "Verification plan and report", "Bug log", "Performance analysis with charts"],
    demo: ["Terminal recording of a passing co-simulation run", "CPI chart", "Waveform of a forwarding case"],
    linkedinAngle: "How lockstep co-simulation found N bugs that directed tests missed.",
    resume: ["Designed a 5-stage RV32I pipeline with full forwarding and hazard detection; passed riscv-tests and RISCOF", "Built lockstep co-simulation against Spike; ran 10M random instructions in CI with zero mismatches", "Measured CPI on CoreMark and attributed stalls by cause"],
    interview: [{ q: "How did you verify your core?", followups: ["What did random streams catch that riscv-tests did not?", "How did you handle interrupts or CSRs in comparison?", "What is your critical path?"] }, { q: "Explain your forwarding priority.", followups: ["What happens with a load followed by a store using the loaded value?"] }],
    extensions: ["M extension with a multi-cycle divider", "Small BHT/BTB (links to the branch predictor flagship)", "Interrupts via CLINT", "Instruction cache (links to the cache flagship)"],
    researchOps: ["Compare predictor choices on CPI", "Explore formal verification of the hazard unit"],
    contribOps: ["Contribute tests or documentation to RISCOF or riscv-tests", "Study CORE-V-VERIF for industrial verification patterns"],
    certs: ["rvfa", "lfd111x"],
    resources: ["spike", "riscv-tests", "riscof", "riscv-dv", "coremark", "ripes", "core-v-verif"],
  },
  {
    id: "fp-async-fifo", title: "Async FIFO and CDC verification kit with a bug-injection study", tier: "flagship",
    categories: ["A. Advanced RTL", "B. Verification"], difficulty: 4, duration: "3-4 weeks part-time", phase: "p5",
    roles: ["rtl", "dv"],
    exceptional: "Instead of 'I built an async FIFO', you show which verification technique catches which CDC bug: simulation, assertions, formal and metastability injection, measured on deliberately broken variants.",
    problem: "Build a correct, parameterized dual-clock FIFO and quantify how well different verification methods detect realistic CDC mistakes.",
    motivation: "CDC bugs escape normal simulation and cause silicon failures; interviewers ask about async FIFOs constantly.",
    researchBasis: ["Cummings, Simulation and Synthesis Techniques for Asynchronous FIFO Design (SNUG 2002)", "Cummings CDC paper (SNUG 2008)", "Ginosar, Metastability and Synchronizers: A Tutorial"],
    prereqs: ["async-fifo", "sva", "formal"],
    skills: ["Gray-code pointer logic", "Multi-clock verification", "SVA and formal", "Metastability injection", "Experimental methodology"],
    architecture: "Dual-port memory, Gray-coded write/read pointers, two-flop synchronizers per direction, full logic in write domain and empty logic in read domain, per-domain reset synchronizers, optional almost-full/empty.",
    diagram: "wclk domain                 rclk domain\n wptr(bin->gray) --sync2--> wptr_gray_s --> empty\n full <-- rptr_gray_s <--sync2-- rptr(bin->gray)\n        [ dual-port RAM ]",
    requirements: ["Any power-of-two depth, any width", "Correct at clock ratios from 1:10 to 10:1", "No overflow/underflow by construction", "Assertions bound without editing RTL", "At least 6 injected bug variants with results"],
    milestones: [ms("m1", "Spec", "Interface and flag semantics."), ms("m2", "RTL", "Cummings-style design."), ms("m3", "Multi-clock testbench", "Random bursts, many ratios, scoreboard."), ms("m4", "Assertions", "Gray one-bit-change, no write when full, no read when empty."), ms("m5", "Formal", "SymbiYosys proofs of flag safety."), ms("m6", "Metastability injection", "Random extra cycle on synchronizer outputs."), ms("m7", "Bug study", "6+ mutants, detection matrix.", "Detection matrix table"), ms("m8", "Write-up", "Report with results and lessons.")],
    implementation: ["Keep pointer width = log2(depth)+1", "Register Gray pointers before crossing", "Separate files for sync, pointer logic and memory"],
    verification: ["Scoreboard with a Python or SV queue model", "Clock-ratio sweep with seeds", "SVA bound per domain", "Formal proof of no overflow/underflow", "Metastability injection model"],
    failureInjection: ["Synchronize binary instead of Gray pointers", "Single-flop synchronizer", "Full computed from unsynchronized pointer", "Missing MSB inversion in full compare", "Reset released asynchronously in one domain", "Combinational logic before synchronizer"],
    metrics: ["Detection rate per technique", "Time/seeds to detection", "Throughput at various ratios", "Area vs depth"],
    ppa: "Area and max frequency vs depth and width; flop-based vs inferred memory.",
    timing: "Constrain crossings (set_max_delay / clock groups) and show clean STA per domain.",
    benchmark: "Throughput in words per cycle of the slower clock under continuous traffic.",
    expected: "Some bugs (binary pointers) are caught quickly in simulation only with injection; formal catches flag bugs deterministically. Report whatever your data shows.",
    tools: ["Verilator or Icarus", "cocotb", "SymbiYosys", "Yosys", "OpenSTA"],
    openSource: ["All open source"],
    repo: "rtl/  tb/ (cocotb)  formal/ (sby)  mutants/  scripts/ (sweep + matrix)  docs/  results/",
    docs: ["Design note", "Verification plan", "Detection matrix report"],
    demo: ["Waveform of a crossing", "Formal counterexample for a mutant", "Detection matrix"],
    linkedinAngle: "Which verification method catches which CDC bug? An experiment with six broken async FIFOs.",
    resume: ["Designed a parameterized async FIFO with Gray-code pointers verified across 1:10 to 10:1 clock ratios", "Quantified detection of 6 injected CDC bugs across simulation, SVA, formal and metastability injection"],
    interview: [{ q: "Why Gray code?", followups: ["What if depth is not a power of two?", "Why are flags pessimistic?"] }, { q: "Which bug was hardest to catch and why?", followups: ["How would a CDC tool report it?"] }],
    extensions: ["Non-power-of-two depth", "Handshake-based bus synchronizer comparison", "Low-power gating"],
    researchOps: ["Statistical MTBF analysis of your synchronizer model"],
    contribOps: ["Share mutants as a teaching resource"],
    certs: [],
    resources: ["sunburst", "sby", "cocotb"],
  },
  {
    id: "fp-axi-apb", title: "AXI4-Lite to APB subsystem with generated register blocks", tier: "flagship",
    categories: ["A. Advanced RTL", "K. HW/SW co-design", "B. Verification"], difficulty: 4, duration: "4-5 weeks part-time", phase: "p6",
    roles: ["rtl", "dv"],
    exceptional: "A single SystemRDL source generates RTL registers, C headers and documentation, so hardware and software never disagree. The bridge is proven with protocol assertions under random backpressure.",
    problem: "Connect a high-performance bus to simple peripherals and keep register definitions consistent across RTL, software and docs.",
    motivation: "This is everyday SoC integration work; AMBA protocols appear in most RTL and DV job postings.",
    researchBasis: ["Arm AMBA AXI and APB specifications", "Accellera SystemRDL standard (via PeakRDL tools)"],
    prereqs: ["axi", "apb", "io-interrupts", "cocotb"],
    skills: ["AXI4-Lite and APB protocols", "Bridges and address decoding", "Register generation flows", "Protocol assertions", "C driver development"],
    architecture: "AXI4-Lite subordinate front-end with skid buffers, bridge FSM converting to APB, APB decoder to peripherals (your timer and UART plus a GPIO), registers generated from SystemRDL with PeakRDL-regblock, C header generation.",
    diagram: "AXI4-Lite --> [skid bufs] --> [bridge FSM] --> APB --> decoder --+--> timer regs\n                                                          +--> uart regs\n                                                          +--> gpio regs\nSystemRDL --> PeakRDL --> RTL regs + C header + docs",
    requirements: ["Correct AXI4-Lite handshakes including simultaneous AW/W and out-of-order arrival", "SLVERR/DECERR for unmapped addresses", "Random backpressure on every channel", "Generated C header used by a test program"],
    milestones: [ms("m1", "Register spec in SystemRDL", "Timer, UART, GPIO maps."), ms("m2", "Generation flow", "Make target for RTL, header, docs."), ms("m3", "APB side", "Decoder and peripherals."), ms("m4", "AXI4-Lite front-end", "Handshake-correct with skid buffers."), ms("m5", "Bridge", "FSM with wait states and errors."), ms("m6", "Verification", "cocotbext-axi random traffic, protocol SVA, register tests."), ms("m7", "Software", "C test using generated header (on your RISC-V core or in simulation)."), ms("m8", "Report", "Latency, area, coverage.")],
    implementation: ["Write AXI assertions first (valid stability, no valid-on-ready dependency)", "Handle AW and W arriving in any order", "Generate everything from one source"],
    verification: ["Random AXI traffic with backpressure", "Register access-type tests (RO, RW, W1C)", "Protocol SVA on both buses", "Coverage of wait states and error responses"],
    failureInjection: ["Deassert valid early", "Ignore WSTRB", "Wrong decode boundary", "Missing PREADY wait handling"],
    metrics: ["Read/write latency in cycles", "Throughput under backpressure", "Area of bridge vs registers", "Coverage"],
    ppa: "Area cost of skid buffers vs timing benefit.",
    timing: "Show that registering ready improves Fmax.",
    benchmark: "Transactions per 1,000 cycles under random backpressure.",
    expected: "AXI4-Lite to APB adds a few cycles of latency per access; quantify it.",
    tools: ["PeakRDL (SystemRDL)", "cocotb", "cocotbext-axi", "Verilator", "Yosys"],
    openSource: ["All open source; compare your bridge with verilog-axi or PULP AXI components"],
    repo: "rdl/  gen/ (generated, ignored or checked)  rtl/  tb/  sw/  docs/  results/",
    docs: ["Register map (generated)", "Bridge design note", "Verification report"],
    demo: ["Generated docs page", "Waveform of an AXI write with backpressure", "C test output"],
    linkedinAngle: "One source of truth for registers: SystemRDL to RTL, C and docs.",
    resume: ["Built an AXI4-Lite to APB subsystem with registers generated from SystemRDL, verified with random backpressure and protocol assertions"],
    interview: [{ q: "What happens if W arrives before AW?", followups: ["How did you buffer it?", "Which AXI dependencies must you respect?"] }],
    extensions: ["UVM environment (next flagship)", "AXI4 full bursts", "Interrupt controller"],
    researchOps: [],
    contribOps: ["Report issues or examples to PeakRDL projects"],
    certs: [],
    resources: ["peakrdl", "cocotbext-axi", "verilog-axi", "pulp-axi", "amba"],
  },
  {
    id: "fp-uvm-env", title: "Reusable UVM environment with RAL and coverage closure", tier: "flagship",
    categories: ["B. Design verification"], difficulty: 4, duration: "5-6 weeks part-time", phase: "p9",
    roles: ["dv"],
    exceptional: "A layered, reusable UVM environment for your AXI-APB subsystem with a register model, virtual sequences, coverage closure report and a mutation-based quality score, runnable on free tools.",
    problem: "Demonstrate industrial verification methodology without commercial licenses.",
    motivation: "Most DV job postings require SystemVerilog and UVM; a real, reusable environment is the strongest evidence.",
    researchBasis: ["IEEE 1800.2 UVM", "Verification Academy UVM Cookbook concepts", "Antmicro/CHIPS Alliance UVM on Verilator"],
    prereqs: ["uvm-env", "coverage", "fp-axi-apb"],
    skills: ["UVM agents, env, tests", "RAL", "Virtual sequences", "Functional coverage and closure", "Regression automation"],
    architecture: "AXI4-Lite active agent, APB passive monitors per peripheral, RAL model generated or hand-written, scoreboard predicting register state, coverage subscribers, virtual sequencer, config objects, test library.",
    diagram: "uvm_test\n  env\n   axi_agent (active) --> DUT --> apb monitors (passive)\n   reg_model + predictor\n   scoreboard  coverage\n   virtual_sequencer",
    requirements: ["Runs on Verilator (UVM 2017) or EDA Playground", "At least 6 tests including error and reset scenarios", "Functional coverage with plan traceability", "Mutation score on 10 injected bugs"],
    milestones: [ms("m1", "Verification plan", "Features, checks, coverage."), ms("m2", "AXI agent", "Driver, monitor, sequences."), ms("m3", "Env and scoreboard", "Predictor and comparison."), ms("m4", "RAL", "Register model and built-in tests."), ms("m5", "Virtual sequences", "Multi-peripheral scenarios."), ms("m6", "Coverage closure", "Hole analysis and fixes.", "Coverage report"), ms("m7", "Mutation study", "10 bugs, detection results."), ms("m8", "Docs and CI", "README, regression script.")],
    implementation: ["Use the factory everywhere", "Keep monitors independent", "Configuration objects over hard-coded knobs"],
    verification: ["Directed and random tests", "RAL built-in sequences", "Coverage-driven closure", "End-of-test checks"],
    failureInjection: ["Register reset value bug", "W1C bug", "Decode error bug", "Bridge wait-state bug"],
    metrics: ["Functional coverage %", "Mutation detection %", "Regression runtime"],
    ppa: "Not applicable (verification project); report simulation performance instead.",
    timing: "Not applicable.",
    benchmark: "Regression wall time per 100 seeds.",
    expected: "Coverage near plan goals with justified exclusions; not all mutants may be caught, and explaining why is valuable.",
    tools: ["Verilator with UVM", "EDA Playground", "Python for regression scripts"],
    openSource: ["Study openhwgroup/core-v-verif for patterns"],
    repo: "tb/uvm/{agents,env,seq,tests,ral}  plan/  scripts/  results/  docs/",
    docs: ["Verification plan", "Architecture diagram", "Coverage and mutation report"],
    demo: ["UVM report summary", "Coverage chart"],
    linkedinAngle: "Building a UVM environment entirely on free tools.",
    resume: ["Developed a reusable UVM environment with RAL, virtual sequences and coverage closure for an AXI-APB subsystem; detected 9/10 injected bugs"],
    interview: [{ q: "Walk me through your environment.", followups: ["How does your predictor work?", "How did you close coverage holes?"] }],
    extensions: ["Formal on the bridge", "Assertion-based VIP"],
    researchOps: ["Compare with the cocotb version for effort and bugs found"],
    contribOps: ["Report Verilator UVM issues with minimal reproducers"],
    certs: ["siemens-badges"],
    proof: ["spec", "architecture", "verification", "assertions", "coverage", "simulation", "documentation", "github", "demo", "linkedin", "interview"],
    resources: ["verilator-uvm", "va-courses", "salemi-uvm", "core-v-verif"],
  },
  {
    id: "fp-cache", title: "Configurable cache subsystem with a performance and PPA design-space study", tier: "flagship",
    categories: ["C. Computer architecture", "A. Advanced RTL", "E. ASIC flow"], difficulty: 5, duration: "6-8 weeks part-time", phase: "p9",
    roles: ["rtl", "arch"],
    exceptional: "Connects architecture to silicon: the same RTL is swept across associativity and policies, measured on real traces for hit rate and AMAT, and taken through synthesis for area and timing, producing a Pareto chart.",
    problem: "Choose a cache configuration with data rather than rules of thumb.",
    motivation: "Cache design is common in RTL and architecture roles; PPA-aware reasoning is senior-level thinking.",
    researchBasis: ["Hennessy & Patterson memory hierarchy chapter", "Jouppi, victim caches (ISCA 1990)"],
    prereqs: ["caches", "ppa", "m-cache-sim"],
    skills: ["Cache controller RTL", "Refill/writeback FSMs", "Performance measurement", "PPA sweeps"],
    architecture: "Parameterized sets/ways/line size, tag and data arrays, PLRU or random replacement, write-back write-allocate, refill FSM over a simple memory interface or AXI, performance counters.",
    diagram: "core req --> [tag compare x ways] --hit--> data array --> resp\n                 |miss\n              [refill/writeback FSM] <--> memory (AXI)",
    requirements: ["Direct-mapped, 2-way and 4-way configurations", "Reference-model checking against your Python simulator", "Hit rate and AMAT on at least two traces", "Synthesis area and timing per configuration"],
    milestones: [ms("m1", "Spec and model", "Reuse your Python simulator as reference."), ms("m2", "Direct-mapped RTL", "Hit path."), ms("m3", "Miss handling", "Refill and writeback."), ms("m4", "Associativity", "Parameterized ways and replacement."), ms("m5", "Verification", "Random traffic vs model, assertions."), ms("m6", "Integration", "Attach to your RISC-V core (optional)."), ms("m7", "Sweep", "Performance + synthesis for each config."), ms("m8", "Pareto report", "Charts and discussion.", "Pareto chart")],
    implementation: ["Separate tag/data arrays for memory inference", "Keep the refill FSM simple first"],
    verification: ["Model-based scoreboard", "Conflict patterns", "Dirty eviction tests", "Assertions on single hit per set"],
    failureInjection: ["Index bit off by one", "Dirty bit not cleared", "Replacement pointer not updated"],
    metrics: ["Hit rate", "AMAT", "Area", "Fmax", "Energy estimate per access (optional)"],
    ppa: "Plot AMAT vs area for all configurations; identify Pareto-optimal points.",
    timing: "Explain how associativity lengthens the hit path (compare + mux).",
    benchmark: "Address traces from your CPU running CoreMark and a matrix multiply.",
    expected: "Diminishing hit-rate returns beyond 2-4 ways with growing area and hit latency.",
    tools: ["Verilator", "cocotb", "Python", "Yosys", "OpenSTA", "ORFS (optional)"],
    openSource: ["Compare with caches in open cores (for example CVA6)"],
    repo: "rtl/  model/  tb/  traces/  sweep/  results/  docs/",
    docs: ["Design doc", "Verification report", "PPA study"],
    demo: ["Pareto chart", "Waveform of a miss with writeback"],
    linkedinAngle: "Is 4-way worth it? A cache design-space study from RTL to timing.",
    resume: ["Designed a parameterized write-back cache and ran a PPA/performance sweep across 6 configurations, producing a Pareto analysis"],
    interview: [{ q: "Why did you pick PLRU?", followups: ["How does associativity affect timing?", "How did you verify replacement?"] }],
    extensions: ["Victim cache", "Non-blocking cache with MSHRs", "Prefetcher"],
    researchOps: ["Reproduce Jouppi's victim cache benefit on your traces"],
    contribOps: [],
    certs: [],
    resources: ["champsim", "hennessy-patterson"],
  },
  {
    id: "fp-branch-pred", title: "Branch predictor study: from MPKI to silicon cost", tier: "research",
    categories: ["C. Computer architecture", "L. Research reproduction"], difficulty: 4, duration: "4-6 weeks part-time", phase: "p10",
    roles: ["arch", "rtl"],
    exceptional: "Reproduces classic predictor results in a trace-driven simulator, then implements the best candidates in RTL to measure area and timing, bridging research metrics and hardware cost.",
    problem: "Which predictor gives the best accuracy per unit area and timing budget?",
    motivation: "Architecture roles value this bridge; it also improves your pipelined core.",
    researchBasis: ["McFarling, Combining Branch Predictors (1993)", "Jimenez and Lin, Dynamic Branch Prediction with Perceptrons (HPCA 2001)", "Seznec and Michaud, TAGE (JILP 2006) as reading"],
    prereqs: ["branch-prediction", "perf-modeling"],
    skills: ["Trace-driven simulation", "Experimental methodology", "Predictor RTL", "Hardware cost analysis"],
    architecture: "C++/Python models of bimodal, gshare, tournament and perceptron predictors with equal storage budgets; RTL of bimodal, gshare and tournament integrated into the fetch stage.",
    diagram: "PC ---> [index hash] --> table --> prediction\nhistory ^         update <-- resolved branch",
    requirements: ["Equal-budget comparison (for example 4 KB)", "MPKI on several traces", "RTL area/timing for three predictors", "CPI impact on your core"],
    milestones: [ms("m1", "Trace setup", "ChampSim traces or your own."), ms("m2", "Models", "Four predictors."), ms("m3", "Sweeps", "Budget and history-length sweeps."), ms("m4", "RTL", "Three predictors."), ms("m5", "Integration", "In the pipelined core."), ms("m6", "Report", "Accuracy vs area vs timing.")],
    implementation: ["Validate models on synthetic patterns first", "Match RTL behaviour to the model exactly"],
    verification: ["Model vs RTL prediction comparison on traces"],
    failureInjection: ["Wrong history update on misprediction"],
    metrics: ["MPKI", "Accuracy", "Storage bits", "Area", "Critical path", "CPI"],
    ppa: "Accuracy per mm2 and per ns of fetch-path delay.",
    timing: "Perceptron adder trees may not fit a single cycle; discuss pipelining.",
    benchmark: "ChampSim-compatible traces and CoreMark on your core.",
    expected: "Qualitatively, history-based and combined predictors beat bimodal at equal budgets; report what you observe.",
    tools: ["ChampSim", "Python/C++", "Verilator", "Yosys"],
    openSource: ["ChampSim"],
    repo: "models/  traces/  rtl/  results/  paper/",
    docs: ["Paper-style report"],
    demo: ["MPKI vs budget chart"],
    linkedinAngle: "Reproducing 30 years of branch prediction on my own core.",
    resume: ["Reproduced classic branch predictor comparisons at equal budgets and implemented three predictors in RTL, reporting MPKI, area and timing"],
    interview: [{ q: "Why does gshare help?", followups: ["What is aliasing?", "How would you pipeline a perceptron predictor?"] }],
    extensions: ["TAGE-lite", "Loop predictor"],
    researchOps: ["Explore ML-inspired predictors"],
    contribOps: ["ChampSim predictor modules"],
    certs: [],
    resources: ["champsim"],
  },
  {
    id: "fp-ppa-arith", title: "Datapath PPA architecture study: adders and multipliers through a real flow", tier: "flagship",
    categories: ["E. ASIC flow", "A. Advanced RTL"], difficulty: 3, duration: "3-4 weeks part-time", phase: "p7",
    roles: ["rtl", "pd"],
    exceptional: "A rigorous, reproducible comparison of arithmetic architectures (ripple, carry-lookahead, Kogge-Stone, Brent-Kung; array vs Booth-Wallace vs sequential multipliers) under identical constraints through synthesis, STA and place-and-route.",
    problem: "Show quantitatively why architecture choices trade area, delay and power.",
    motivation: "PPA reasoning is what distinguishes senior engineers; this project makes it concrete.",
    researchBasis: ["Weste & Harris datapath chapter (adder and multiplier architectures)", "Kogge-Stone and Brent-Kung prefix adder structures"],
    prereqs: ["adders", "ppa", "open-flow"],
    skills: ["Arithmetic architectures", "Constraint-driven synthesis", "STA", "PPA methodology", "Automation"],
    architecture: "Parameterized generators for each adder and multiplier; common wrapper with registered inputs/outputs; automated sweep over widths and clock targets.",
    diagram: "for arch in [ripple, cla, ks, bk, synth]:\n  for width in [16, 32, 64]:\n    for clk in targets:\n      yosys -> opensta -> (orfs) -> metrics.csv",
    requirements: ["Equivalence proven between architectures", "Identical constraints", "Area, delay, power estimates per point", "Automated plots"],
    milestones: [ms("m1", "Generators", "Adders and multipliers."), ms("m2", "Equivalence", "Formal/random equivalence."), ms("m3", "Sweep flow", "Scripts and CSV."), ms("m4", "Place and route", "Selected points through ORFS."), ms("m5", "Analysis", "Pareto and discussion.", "Charts")],
    implementation: ["Register boundaries for clean timing", "Automate everything"],
    verification: ["Exhaustive for 8-bit, random for wider", "Yosys equivalence checks"],
    failureInjection: ["Swap a prefix connection and show equivalence failure"],
    metrics: ["Area", "Critical path delay", "Power estimate", "Cells", "Wirelength post-route"],
    ppa: "Pareto fronts per width; explain wiring effects in Kogge-Stone.",
    timing: "Delay scaling with width (linear vs logarithmic).",
    benchmark: "Metrics CSV reproducible from one command.",
    expected: "Prefix adders win delay at larger widths with more area and wiring; synthesis-chosen adders are often competitive.",
    tools: ["Yosys", "OpenSTA", "OpenROAD flow scripts", "Python"],
    openSource: ["All open source"],
    repo: "gen/  rtl/  flow/  scripts/  results/  report/",
    docs: ["Study report"],
    demo: ["Pareto charts"],
    linkedinAngle: "Ripple vs Kogge-Stone through a real flow: what the numbers say.",
    resume: ["Automated a PPA study of 5 adder and 3 multiplier architectures across widths and clock targets using Yosys, OpenSTA and OpenROAD"],
    interview: [{ q: "Why did synthesis beat your hand-written CLA?", followups: ["What does ABC optimize?", "How did wires affect results?"] }],
    extensions: ["Power with realistic activity", "Approximate arithmetic"],
    researchOps: ["Design-space exploration with Bayesian optimization"],
    contribOps: [],
    certs: [],
    resources: ["yosys", "opensta", "orfs"],
  },
  {
    id: "fp-open-silicon", title: "Tapeout-ready open-silicon design (RTL to GDS, shuttle-compatible)", tier: "open-silicon",
    categories: ["M. Open-source silicon", "F. Physical design", "E. ASIC flow"], difficulty: 4, duration: "6-8 weeks (Phase 8 end-to-end project)", phase: "p8",
    roles: ["rtl", "pd", "dv"],
    exceptional: "A complete spec-to-GDS project that meets a real shuttle's constraints (for example Tiny Tapeout tile size and pinout), with verification, signoff reports and optionally actual fabrication.",
    problem: "Demonstrate the whole ASIC flow on your own design.",
    motivation: "End-to-end evidence is rare among candidates without a VLSI degree, and open shuttles make real silicon possible.",
    researchBasis: ["LibreLane/OpenLane flow", "Tiny Tapeout submission requirements"],
    prereqs: ["spec-writing", "microarchitecture", "open-flow"],
    skills: ["Specification", "RTL and verification", "Constraints and STA", "Place and route", "Signoff reading", "Documentation"],
    architecture: "Choose a meaningful block that fits: for example a UART-controlled 8-bit MAC unit, a small systolic tile, a PWM/LED controller with SPI, or a tiny RISC-V subset. Must include a clean interface and self-test mode.",
    diagram: "pins --> [interface ctrl] --> [your datapath] --> [status/out]\n              ^ self-test / BIST mode",
    requirements: ["Fits the target shuttle area and IO constraints", "Clean DRC/LVS", "Timing met at the chosen clock", "GLS passes", "Documentation complete"],
    milestones: [ms("m1", "Spec", "Written spec."), ms("m2", "Microarchitecture", "Doc and review."), ms("m3", "RTL + verification", "Coverage goals."), ms("m4", "Synthesis/STA", "Constraints, closure."), ms("m5", "PnR", "LibreLane or ORFS to GDS."), ms("m6", "Signoff", "DRC/LVS/STA reports.", "Reports in repo"), ms("m7", "GLS", "Netlist simulation."), ms("m8", "Report and optional submission", "Write-up; submit to a shuttle if budget allows.")],
    implementation: ["Keep scope small enough to finish", "Add a debug/self-test mode"],
    verification: ["cocotb tests, SVA, coverage, GLS"],
    failureInjection: ["Timing too aggressive, then fix", "Intentional DRC issue in a custom block (if any) and fix"],
    metrics: ["Area/utilization", "WNS/TNS", "Power estimate", "DRC/LVS status", "Coverage"],
    ppa: "Report utilization and timing margin; discuss what limits frequency.",
    timing: "Multi-corner STA if the PDK provides corners.",
    benchmark: "Throughput of your datapath at the achieved frequency.",
    expected: "Small designs close easily at modest frequencies on 130/180 nm; the value is completeness.",
    tools: ["LibreLane or ORFS", "Yosys", "OpenSTA", "KLayout", "Magic/Netgen", "cocotb"],
    openSource: ["Tiny Tapeout templates", "wafer.space GF180MCU template"],
    repo: "src/  test/  docs/  librelane/ or flow/  results/  gds/",
    docs: ["Spec", "Microarchitecture", "Verification report", "Implementation report"],
    demo: ["GDS render", "Timing summary", "(If fabricated) board demo video"],
    linkedinAngle: "From spec to GDS on an open PDK: what each step taught me.",
    resume: ["Took an original design from specification to DRC/LVS-clean GDS on an open PDK using LibreLane, closing timing and verifying with cocotb and gate-level simulation"],
    interview: [{ q: "Walk through your flow and results.", followups: ["What did DRC flag?", "How did you choose utilization?", "What would change on a commercial flow?"] }],
    extensions: ["Actual tapeout on Tiny Tapeout", "Analog block on IHP"],
    researchOps: [],
    contribOps: ["Share your design on a Tiny Tapeout shuttle", "Improve LibreLane docs"],
    certs: [],
    resources: ["librelane", "tinytapeout", "wafer-space-template", "orfs", "klayout"],
  },
];
