import type { GlossaryTerm } from "./schema.ts";
import { EXTRA_GLOSSARY } from "./embedded-extra.ts";

const g = (term: string, full: string | undefined, simple: string, technical: string, topic?: string, art?: string): GlossaryTerm => ({ term, full, simple, technical, topic, art });

const BASE_GLOSSARY: GlossaryTerm[] = [
  g("RTL", "Register-transfer level", "A description of a chip as memory boxes and the logic between them.", "Abstraction describing registers and combinational transfers per clock, written in Verilog/SystemVerilog/VHDL and synthesized to gates.", "hdl-mindset"),
  g("FSM", "Finite state machine", "A machine that is always in one of a few states and follows rules to move between them.", "Sequential circuit with a state register, next-state logic and output logic (Moore or Mealy).", "fsm"),
  g("STA", "Static timing analysis", "Checking every route through a circuit for being too slow or too fast, without running it.", "Vectorless timing verification computing arrival, required times and slack across all paths, corners and modes.", "sta"),
  g("Slack", undefined, "How much spare time a signal has. Negative means late.", "Required time minus arrival time for a timing check.", "setup-hold"),
  g("Setup time", undefined, "Data must be steady a little before the clock ticks.", "Minimum interval before the active clock edge during which a sequential element's data input must be stable.", "setup-hold", "D ====X=====stable===|clk edge\n        |<-- Tsu -->|"),
  g("Hold time", undefined, "Data must stay steady a little after the clock ticks.", "Minimum interval after the active clock edge during which data must remain stable.", "setup-hold"),
  g("Metastability", undefined, "A flip-flop stuck between 0 and 1 for a while after being surprised.", "Unstable equilibrium after a setup/hold violation with exponentially distributed resolution time.", "metastability"),
  g("CDC", "Clock domain crossing", "Passing a signal between parts of the chip that tick at different speeds.", "Transfer of signals between asynchronous or unrelated clock domains, requiring synchronizers, handshakes or async FIFOs.", "cdc"),
  g("RDC", "Reset domain crossing", "Passing signals between parts that restart at different times.", "Paths between flops in different reset domains where asynchronous reset assertion can corrupt the receiver.", "reset-architecture"),
  g("Synchronizer", undefined, "A couple of flip-flops that give a surprised signal time to settle.", "Series flops in the destination domain that reduce metastability failure probability.", "metastability"),
  g("Gray code", undefined, "Counting where only one digit changes at a time.", "Binary encoding with Hamming distance 1 between consecutive values; used for CDC pointers.", "async-fifo"),
  g("DFT", "Design for test", "Extra circuits that let factories test each chip quickly.", "Scan chains, compression, BIST and test access logic added to improve controllability and observability.", "dft"),
  g("ATPG", "Automatic test pattern generation", "A program that invents test inputs to find broken wires.", "Algorithms (D-algorithm, PODEM, FAN) generating patterns detecting modeled faults.", "dft"),
  g("Scan chain", undefined, "Flip-flops linked into a line so testers can load and read them.", "Serially connected scan flops enabling shift-in/capture/shift-out testing.", "dft"),
  g("BIST", "Built-in self-test", "A chip testing itself.", "On-chip pattern generation and response analysis (for example MBIST, LBIST).", "dft-mbist-jtag"),
  g("JTAG", "IEEE 1149.1", "A standard service port for testing and debugging chips.", "Test access port with a 16-state TAP controller, instruction and data registers, boundary scan.", "dft-mbist-jtag"),
  g("UVM", "Universal Verification Methodology", "A standard toolkit for building test robots for chips.", "IEEE 1800.2 SystemVerilog class library defining components, phases, factory, TLM and register layer.", "uvm-architecture"),
  g("SVA", "SystemVerilog Assertions", "Rules that watch a circuit and shout when broken.", "Temporal property language for immediate and concurrent assertions and cover properties.", "sva"),
  g("Coverage", undefined, "A measure of how much of the design was actually tested.", "Code coverage (line, branch, toggle, FSM) and functional coverage (covergroups, assertion covers).", "coverage"),
  g("PPA", "Power, performance, area", "The three things every design balances: energy, speed and size.", "Primary quality metrics of a design; cost and schedule are often added.", "ppa"),
  g("CTS", "Clock tree synthesis", "Running the clock wires so every flip-flop hears the tick at nearly the same time.", "Building a buffered clock distribution network meeting skew, latency and transition targets.", "placement-cts"),
  g("ECO", "Engineering change order", "A small, late fix to an almost finished design.", "Targeted netlist/layout modification, often metal-only, after main implementation.", "pd-closure-eco"),
  g("LEF", "Library exchange format", "The outline and pin locations of each cell.", "Abstract physical view of cells/macros and technology routing rules.", "std-cells"),
  g("DEF", "Design exchange format", "A file describing where everything was placed and routed.", "Physical design database exchange format with components, nets and routing.", "asic-flow"),
  g("GDSII", undefined, "The final picture of every layer, sent to the factory.", "Binary layout database format used for mask making.", "asic-flow"),
  g("SDC", "Synopsys Design Constraints", "The rulebook telling tools how fast things must be.", "Tcl-based timing constraint format: clocks, IO delays, exceptions.", "sdc"),
  g("SDF", "Standard delay format", "A file of delays used to make simulation timing-accurate.", "Back-annotation format for cell and interconnect delays in gate-level simulation.", "gls-lec"),
  g("SPEF", "Standard parasitic exchange format", "A list of wire resistances and capacitances.", "Extracted parasitic RC data consumed by STA.", "routing-signoff"),
  g("Liberty", ".lib", "The speed and power datasheet of every standard cell.", "Library format with timing/power tables per PVT corner.", "std-cells"),
  g("PDK", "Process design kit", "The rulebook and parts catalogue for one chip factory process.", "Foundry-provided design rules, device models, technology files and libraries.", "fabrication"),
  g("DRC", "Design rule check", "Checking the layout follows the factory's building codes.", "Geometric verification against foundry rules.", "routing-signoff"),
  g("LVS", "Layout versus schematic", "Checking the drawing matches the circuit you meant.", "Comparing extracted layout connectivity with the netlist.", "routing-signoff"),
  g("IR drop", undefined, "Voltage lost along power wires.", "Supply voltage reduction from current through resistive power network.", "circuit-laws"),
  g("EM", "Electromigration", "Wires slowly wearing out from too much current.", "Metal atom migration under current density causing opens/shorts over time.", "routing-signoff"),
  g("OCV", "On-chip variation", "Parts of the same chip being slightly faster or slower.", "Within-die variation modeled with derates, AOCV or POCV/LVF.", "corners-ocv"),
  g("MCMM", "Multi-corner multi-mode", "Checking every weather and operating condition at once.", "Simultaneous analysis/optimization over PVT corners and functional/test modes.", "corners-ocv"),
  g("SRAM", "Static RAM", "Fast on-chip memory that keeps data while powered.", "6T bit-cell memory with sense amplifiers; implemented as compiled macros.", "memory-basics"),
  g("DRAM", "Dynamic RAM", "Dense memory that must be refreshed.", "1T1C memory with row buffers and refresh; usually off-chip.", "memory-basics"),
  g("NoC", "Network-on-chip", "A tiny postal network inside a chip.", "Packet-switched interconnect with routers, flits and flow control.", "noc"),
  g("AXI", "Advanced eXtensible Interface", "A fast standard road system for moving data inside chips.", "AMBA protocol with five valid/ready channels, bursts, IDs and outstanding transactions.", "axi"),
  g("APB", "Advanced Peripheral Bus", "A simple bus for slow peripherals.", "AMBA two-phase (setup/access) protocol for register access.", "apb"),
  g("PCIe", "PCI Express", "A very fast link between chips, like between a CPU and a graphics card.", "Layered serial interconnect (PHY, data link, transaction layers).", "high-speed-io"),
  g("DDR", "Double data rate memory", "The main memory chips next to a processor.", "DRAM interface transferring on both clock edges, driven by a memory controller and PHY.", "high-speed-io"),
  g("SerDes", "Serializer/deserializer", "Circuits that squeeze parallel data onto one fast wire and back.", "High-speed transceivers with clock recovery and equalization.", "high-speed-io"),
  g("UPF", "Unified Power Format", "The electrical plan saying which parts can be switched off.", "IEEE 1801 power intent: domains, isolation, retention, level shifting.", "rtl-power-intent"),
  g("ICG", "Integrated clock gating cell", "A safe switch that pauses the clock to idle logic.", "Latch-based glitch-free clock gate cell inserted by tools.", "low-power-rtl"),
  g("MAC", "Multiply-accumulate", "Multiply two numbers and add to a running total.", "Core operation of dot products, filters and neural networks.", "matmul-mac"),
  g("Systolic array", undefined, "A grid of tiny calculators passing data like a bucket brigade.", "Array of PEs with local communication and rhythmic data flow for high reuse.", "systolic"),
  g("Roofline", undefined, "A chart showing whether you are limited by math speed or data speed.", "Performance bound min(peak, bandwidth x arithmetic intensity).", "roofline"),
  g("Quantization", undefined, "Using fewer, simpler numbers to save energy.", "Mapping real values to low-bit integers with scale and zero-point.", "quantization-sparsity"),
  g("ISA", "Instruction set architecture", "The menu of commands a processor understands.", "Programmer-visible contract: instructions, registers, memory model, privilege.", "isa"),
  g("CPI", "Cycles per instruction", "How many ticks an average instruction takes.", "Average clock cycles per retired instruction; with IC and cycle time gives runtime.", "performance"),
  g("Hazard", undefined, "A pipeline traffic conflict.", "Data, control or structural dependency requiring forwarding, stalls or flushes.", "hazards"),
  g("TLB", "Translation lookaside buffer", "A cheat sheet of recent address translations.", "Cache of virtual-to-physical page translations.", "memory-hierarchy"),
  g("Lint", undefined, "A grammar checker for hardware code.", "Static rule checking of RTL for synthesis, style and safety issues.", "verilator-lint"),
  g("LEC", "Logical equivalence checking", "Proving two versions of a circuit do exactly the same thing.", "Formal combinational equivalence between RTL and netlist with register mapping.", "gls-lec"),
  g("GLS", "Gate-level simulation", "Running tests on the synthesized gates instead of the code.", "Netlist simulation, optionally SDF-annotated.", "gls-lec"),
  g("MPW", "Multi-project wafer", "Many designs sharing one wafer to split costs.", "Shuttle service aggregating designs on shared masks.", "tapeout"),
  g("Tapeout", undefined, "Sending the finished chip design to the factory.", "Final release of GDSII to the foundry for mask making.", "tapeout"),
  g("Skew", undefined, "The clock arriving at different flip-flops at different times.", "Difference in clock arrival between launch and capture elements.", "clock-effects"),
  g("Jitter", undefined, "The clock tick wobbling a little each time.", "Temporal variation of clock edges from ideal positions.", "clocking"),
  g("Formal verification", undefined, "Proving with math that a rule can never be broken.", "Exhaustive state-space analysis (model checking, equivalence) against properties.", "formal"),
  g("Scoreboard", undefined, "The part of a testbench that checks answers.", "Component comparing predicted and observed transactions.", "layered-tb"),
  g("Backpressure", undefined, "The receiver saying 'slow down, I'm full'.", "Flow control where a consumer deasserts ready to stall a producer.", "valid-ready"),
];
export const GLOSSARY: GlossaryTerm[] = [...BASE_GLOSSARY, ...EXTRA_GLOSSARY];
