import type { BankQuestion, InterviewCat } from "./schema.ts";

export const INTERVIEW_CATS: Record<InterviewCat, string> = {
  digital: "Digital logic", hdl: "HDL", rtl: "RTL design", verification: "Verification", timing: "Timing", asic: "ASIC flow",
  pd: "Physical design", dft: "DFT", arch: "Computer architecture", riscv: "RISC-V", protocols: "Protocols", linux: "Linux and scripting",
  programming: "Python and C/C++", aihw: "AI hardware", career: "Career and projects",
};

const q = (id: string, cat: InterviewCat, level: 1 | 2 | 3 | 4, concept: string, question: string, a: string, reasoning: string, trap: string, topics: string[]): BankQuestion => ({ id, cat, q: question, level, concept, a, reasoning, trap, topics });

export const BANK: BankQuestion[] = [
  q("b-mux-from-nand", "digital", 1, "Universal gates", "Build a 2:1 mux using only NAND gates.", "Y = NAND(NAND(A, ~S), NAND(B, S)) where ~S = NAND(S, S): four NAND gates total.", "Mux = A·~S + B·S; De Morgan turns the OR of products into NAND of NANDs.", "Forgetting to generate ~S with a NAND.", ["boolean-algebra", "mux-decoder"]),
  q("b-freq-div3", "digital", 3, "Counters and duty cycle", "Design a divide-by-3 clock with 50% duty cycle.", "Use a mod-3 counter on the rising edge and a flop on the falling edge; OR the rising-edge and falling-edge derived signals to get 1.5 cycles high out of 3.", "Odd division with 50% duty requires both edges.", "Producing a 33% duty cycle and calling it done; also using the result as a clock without constraints in real designs.", ["registers-counters", "clocking"]),
  q("b-nba-race", "hdl", 2, "Scheduling", "Two always blocks on the same clock: one does a = b; the other b = a; with blocking assignments. What happens?", "Result depends on which block the simulator runs first: a race. With non-blocking assignments both sample old values and swap correctly.", "Blocking updates are visible immediately to other processes in the same time step.", "Assuming simulation order is defined by file order.", ["blocking-nonblocking", "sim-semantics"]),
  q("b-latch", "hdl", 1, "Latch inference", "Why does this infer a latch: always @(*) if (en) y = a;", "When en is 0, y is not assigned, so it must hold its old value, which needs storage: a latch.", "Combinational blocks must assign outputs on every path.", "Adding y to the sensitivity list as a 'fix'.", ["latch-inference"]),
  q("b-fifo-depth", "rtl", 3, "FIFO sizing", "A producer writes 80 words in bursts of 80 cycles at 100 MHz; the consumer reads 1 word every 2 cycles at 50 MHz. Minimum FIFO depth?", "Burst lasts 800 ns; consumer reads every 40 ns, so 20 words drained. Depth needed = 80 - 20 = 60 words (plus margin for synchronizer latency in async designs).", "Depth = data written during burst minus data read during the same time.", "Ignoring read rate, or ignoring CDC pointer latency.", ["sync-fifo", "async-fifo"]),
  q("b-rr-arbiter", "rtl", 3, "Arbitration", "Design a 4-requester round-robin arbiter and explain how you'd verify fairness.", "Keep last-grant pointer; mask requests at/below it; pick first set bit of masked requests else of all requests; update pointer. Verify with assertions: one-hot grant, grant implies request, and bounded wait (no requester waits more than 3 grants while asserting).", "Rotating priority guarantees bounded waiting.", "Rotating the pointer when no grant is given.", ["arbiters", "sva"]),
  q("b-cdc-bus", "rtl", 3, "CDC", "How do you pass a 32-bit configuration value to another clock domain?", "If it changes rarely: hold it stable, send a req through a synchronizer, capture data on synchronized req, return ack (handshake). For streams, use an async FIFO. Never synchronize bits independently.", "Multi-bit coherence requires stable data during sampling.", "Two-flop synchronizing each bit.", ["cdc"]),
  q("b-800mhz", "timing", 3, "Timing closure", "Your design fails timing at 800 MHz. How would you investigate?", "Get worst paths; check if paths are real (constraints, false/multicycle); classify: logic depth, high fanout, wire/placement, clock skew; fix accordingly (pipeline/retime, restructure, duplicate drivers, placement guidance, useful skew); re-check hold/power/area.", "Diagnosis before fixing; each fix has costs.", "Immediately upsizing cells everywhere.", ["timing-closure", "sta"]),
  q("b-hold-fix", "timing", 2, "Hold", "Why can't hold violations be fixed by lowering the clock frequency?", "Hold compares data arrival after the same edge that launched it with the capture flop's hold requirement; the clock period does not appear in the hold equation.", "Setup depends on period; hold does not.", "Saying 'slow down the clock'.", ["setup-hold", "clock-effects"]),
  q("b-mcp", "timing", 3, "Constraints", "A path is enabled only every 4th cycle. How do you constrain it?", "set_multicycle_path 4 -setup, and set_multicycle_path 3 -hold (relative to the same clocks) so hold returns to the original edge.", "Setup multicycle moves the capture edge; hold must be moved back.", "Forgetting the hold adjustment, creating huge false hold violations.", ["sdc"]),
  q("b-sim-synth", "hdl", 3, "Simulation/synthesis mismatch", "Why can simulation pass but synthesis produce different behaviour?", "Incomplete sensitivity lists, initial blocks, #delays, X-assignments treated as don't-care, full_case/parallel_case pragmas, blocking/non-blocking misuse, or uninitialized registers.", "Synthesis follows hardware semantics; simulators follow language semantics.", "Blaming the tool without checking coding style.", ["latch-inference", "gls-lec"]),
  q("b-uvm-factory", "verification", 2, "UVM factory", "How would you replace the driver in an existing UVM environment for one test without editing the environment?", "Create a derived driver class, register it with the factory, and in the test's build_phase call set_type_override_by_type (or instance override) before the env is built.", "The env creates components through type_id::create, so overrides take effect.", "Editing the environment code.", ["uvm-architecture"]),
  q("b-vacuous", "verification", 3, "Assertions", "An assertion req |-> ##[1:3] gnt never fails in regression. Is the design correct?", "Not necessarily. It may pass vacuously if req is never asserted, or the checker is disabled by reset. Add cover property on req and on the full sequence.", "Absence of failure is not evidence of exercise.", "Treating a passing assertion as coverage.", ["sva", "coverage"]),
  q("b-100cov", "verification", 2, "Coverage", "You have 100% code coverage and all tests pass. Can you tape out?", "Not yet: check functional coverage against the plan, assertion coverage, reviews, bug-rate trends, and gate-level/CDC/low-power checks. Code coverage misses unimplemented features and unchecked behaviour.", "Coverage metrics measure stimulus, not correctness or completeness.", "Equating code coverage with verification completion.", ["coverage", "verification-plan"]),
  q("b-scan", "dft", 2, "Scan", "Explain scan shift and capture in one minute.", "Scan enable high: flops form chains; shift a pattern in (and the previous response out). Scan enable low for one capture clock: functional logic results are captured. Then shift out and compare.", "Scan turns sequential test into combinational test.", "Forgetting that shift and capture use different timing constraints.", ["dft"]),
  q("b-cts", "pd", 2, "CTS", "What happens to setup and hold after CTS compared to ideal clocks?", "Real clock latencies and skew appear: some paths gain setup margin, others lose it; hold violations often appear and are fixed post-CTS at the fast corner.", "Pre-CTS analysis uses ideal clocks plus uncertainty.", "Assuming pre-CTS timing is final.", ["placement-cts", "clock-effects"]),
  q("b-util", "pd", 2, "Floorplan", "Why not floorplan at 90% utilization to save area?", "Little room for buffering, sizing and routing; congestion rises and timing closure may fail. Typical targets leave headroom.", "Area saved is lost to failed routing and schedule.", "Thinking area is the only goal.", ["floorplan"]),
  q("b-cache-bits", "arch", 2, "Caches", "32-bit addresses, 16 KB 2-way cache, 32-byte lines. Tag/index/offset widths?", "Sets = 16K / (32 x 2) = 256 so index = 8 bits; offset = 5 bits; tag = 32 - 8 - 5 = 19 bits.", "Sets = size / (line x ways).", "Using size/line for sets and ignoring ways.", ["caches"]),
  q("b-forward", "arch", 3, "Forwarding", "lw x1, 0(x2) followed by add x3, x1, x4 in a 5-stage pipeline. How many stall cycles and why?", "One stall with forwarding: load data is available at end of MEM; add needs it at start of EX; after one bubble, forward from MEM/WB.", "Load-use hazard.", "Saying zero because 'forwarding fixes everything'.", ["hazards"]),
  q("b-rv-imm", "riscv", 2, "Immediates", "Why is imm[0] missing from RISC-V B-type and J-type immediates?", "Branch/jump targets are multiples of 2 bytes (to support compressed instructions), so bit 0 is always 0 and not encoded, extending range.", "Encoding efficiency.", "Assuming multiples of 4 because base instructions are 32-bit.", ["riscv-isa"]),
  q("b-axi-dep", "protocols", 3, "AXI", "Can a subordinate wait for WVALID before asserting AWREADY?", "Yes. A subordinate is allowed to wait for AWVALID, WVALID or both before asserting AWREADY or WREADY. The manager, however, must not wait for AWREADY or WREADY before asserting AWVALID or WVALID; a source's valid must never depend on the destination's ready.", "The asymmetric dependency rules guarantee progress: sources always offer data, so a waiting destination is never stuck.", "Designing a manager that waits for AWREADY before WVALID and a subordinate that waits for WVALID before AWREADY: deadlock.", ["axi"]),
  q("b-grep-logs", "linux", 1, "Shell", "Find all logs containing UVM_FATAL and count them.", "grep -l UVM_FATAL logs/*.log | wc -l", "grep -l lists matching files.", "Counting matching lines instead of files.", ["linux-shell"]),
  q("b-py-mask", "programming", 2, "Bit-accuracy", "Your Python model of a 16-bit adder disagrees with RTL on large values. Why?", "Python ints are unbounded; the model must mask results to 16 bits (and handle signedness) to match hardware wrap-around.", "Hardware widths are fixed.", "Blaming the RTL first.", ["python-hw"]),
  q("b-int8-acc", "aihw", 2, "Accumulators", "Why do INT8 MAC arrays use 32-bit accumulators?", "Each INT8 x INT8 product needs up to 16 bits; summing many products needs extra guard bits (log2 of the number of terms) to avoid overflow; 32 bits covers typical dot-product lengths.", "Width = 2N + log2(K).", "Using 16-bit accumulators.", ["matmul-mac", "fixed-point"]),
  q("b-roofline", "aihw", 3, "Roofline", "An accelerator has 4 TOPS peak and 50 GB/s bandwidth. A layer has intensity 20 ops/byte. What limits it?", "Ridge point = 4e12 / 50e9 = 80 ops/byte. At 20 ops/byte the layer is memory-bound: attainable ~ 50e9 x 20 = 1 TOPS.", "Compare intensity with ridge point.", "Assuming peak TOPS.", ["roofline"]),
];
