import type { OpenSourceProject } from "./schema.ts";
import { EXTRA_OPEN_SOURCE } from "./embedded-extra.ts";

const gh = (r: string) => `https://github.com/${r}`;

const BASE_OPEN_SOURCE: OpenSourceProject[] = [
  { id: "os-verilator", name: "Verilator", url: gh("verilator/verilator"), what: "Fast open-source SystemVerilog simulator and linter.", why: "Used in industry CI and open cores; now elaborates upstream UVM 2017.", difficulty: "intermediate", prereqs: ["verilator-lint"], beginnerUse: "Lint and simulate all your designs.", contribute: "Report minimal reproducers for bugs; add tests; documentation fixes.", portfolio: "Merged issues or tests show real-world SV knowledge." },
  { id: "os-yosys", name: "Yosys", url: gh("YosysHQ/yosys"), what: "Open synthesis framework.", why: "Core of every open ASIC/FPGA flow.", difficulty: "intermediate", prereqs: ["synthesis"], beginnerUse: "Synthesize your blocks and read stats.", contribute: "Documentation, test cases, small passes.", portfolio: "Shows synthesis internals knowledge." },
  { id: "os-cocotb", name: "cocotb", url: gh("cocotb/cocotb"), what: "Python verification framework.", why: "Python-first DV; strong fit for your background.", difficulty: "beginner", prereqs: ["cocotb"], beginnerUse: "Write all early testbenches in cocotb.", contribute: "Docs, examples, bug reports; extension libraries.", portfolio: "Contributions are visible and reviewed." },
  { id: "os-openroad", name: "OpenROAD and OpenROAD flow scripts", url: gh("The-OpenROAD-Project/OpenROAD-flow-scripts"), what: "Open RTL-to-GDS physical design.", why: "Hands-on PD without licences.", difficulty: "advanced", prereqs: ["open-flow"], beginnerUse: "Run example designs, then your own.", contribute: "Platform/design configs, docs, issue triage with reproducers.", portfolio: "PD and flow credibility." },
  { id: "os-librelane", name: "LibreLane", url: gh("librelane/librelane"), what: "FOSSi Foundation successor to OpenLane 2.", why: "Used by open shuttles including Tiny Tapeout-style flows.", difficulty: "intermediate", prereqs: ["open-flow"], beginnerUse: "Run the Classic flow on your design.", contribute: "Docs, examples, custom steps.", portfolio: "End-to-end flow evidence." },
  { id: "os-tinytapeout", name: "Tiny Tapeout", url: "https://tinytapeout.com/", what: "Shared shuttles letting individuals fabricate small designs.", why: "Real silicon at hobbyist cost.", difficulty: "beginner", prereqs: ["open-flow"], beginnerUse: "Follow a template, submit a small design.", contribute: "Share designs and documentation.", portfolio: "A public chip page with your design." },
  { id: "os-ibex", name: "Ibex (lowRISC)", url: gh("lowRISC/ibex"), what: "Small, production-quality RISC-V core with DV environment.", why: "Study industrial RTL style and verification.", difficulty: "advanced", prereqs: ["riscv-isa", "uvm-env"], beginnerUse: "Read the pipeline and DV docs.", contribute: "Documentation and tests after careful reading of contribution rules.", portfolio: "Reading real code improves your own." },
  { id: "os-opentitan", name: "OpenTitan", url: gh("lowRISC/opentitan"), what: "Open silicon root of trust with extensive DV.", why: "One of the best open examples of industrial verification.", difficulty: "advanced", prereqs: ["uvm-env", "hw-security"], beginnerUse: "Browse DV plans and testbench structure.", contribute: "Docs and small fixes; follow their process.", portfolio: "Strong signal for DV roles." },
  { id: "os-cva6", name: "CVA6 and CORE-V-VERIF (OpenHW Group)", url: gh("openhwgroup/core-v-verif"), what: "Application-class RISC-V core and its UVM verification.", why: "Industrial-style open DV environment.", difficulty: "advanced", prereqs: ["uvm-env", "riscv-isa"], beginnerUse: "Study the verification architecture.", contribute: "Test contributions via their process.", portfolio: "DV depth." },
  { id: "os-chipyard", name: "Chipyard", url: gh("ucb-bar/chipyard"), what: "SoC generator framework (Rocket, BOOM, Gemmini).", why: "See full SoCs and accelerators integrated.", difficulty: "advanced", prereqs: ["soc-buses", "accelerators"], beginnerUse: "Run a simulation of a default SoC.", contribute: "Docs and examples.", portfolio: "System-level knowledge." },
  { id: "os-litex", name: "LiteX", url: gh("enjoy-digital/litex"), what: "Framework for building FPGA SoCs quickly.", why: "Fast path to a working SoC for your capstone.", difficulty: "intermediate", prereqs: ["soc-buses"], beginnerUse: "Build a simulated SoC and run C code.", contribute: "Board support, docs, examples.", portfolio: "Working SoC demos." },
  { id: "os-pdks", name: "Open PDKs (SKY130, GF180MCU, IHP SG13G2)", url: gh("google/skywater-pdk"), what: "Publicly available process design kits.", why: "Real design rules and libraries for learning and tapeout.", difficulty: "intermediate", prereqs: ["fabrication"], beginnerUse: "Read cell libraries and design rules.", contribute: "Documentation improvements.", portfolio: "Understanding of real processes." },
  { id: "os-sby", name: "SymbiYosys", url: gh("YosysHQ/sby"), what: "Formal verification front-end.", why: "Learn formal without licences.", difficulty: "intermediate", prereqs: ["formal"], beginnerUse: "Prove FIFO and arbiter properties.", contribute: "Examples and docs.", portfolio: "Formal proofs in your repos." },
  { id: "os-circuitnet", name: "CircuitNet", url: gh("circuitnet/CircuitNet"), what: "Open dataset for ML in EDA.", why: "Enables AI-for-EDA experiments.", difficulty: "intermediate", prereqs: ["ml-for-eda"], beginnerUse: "Reproduce a baseline.", contribute: "Reproducibility reports and examples.", portfolio: "Research evidence." },
];
export const OPEN_SOURCE: OpenSourceProject[] = [...BASE_OPEN_SOURCE, ...EXTRA_OPEN_SOURCE];

/** Contribution ladder shown on the Open Source page. */
export const CONTRIB_LADDER = [
  "Use the tool on your own projects and keep notes of friction points.",
  "Report a bug with a minimal reproducer (smallest design and exact command).",
  "Improve documentation or an example you struggled with.",
  "Add a test case for a fixed bug.",
  "Fix a small, well-scoped issue labelled for newcomers after discussing it with maintainers.",
];
