import type { Paper } from "./schema.ts";

const ax = (id: string) => `https://arxiv.org/abs/${id}`;
const gh = (r: string) => `https://github.com/${r}`;

export const PAPERS: Paper[] = [
  {
    id: "ginosar-sync", title: "Metastability and Synchronizers: A Tutorial", authors: "Ran Ginosar", venue: "IEEE Design & Test of Computers", year: 2011, area: "circuits", difficulty: 2, verified: false,
    problem: "Engineers misuse synchronizers and misunderstand metastability.", intuition: "A flip-flop sampling a changing signal can balance on a knife edge; waiting reduces failure probability exponentially.",
    contribution: "Clear tutorial on metastability, MTBF and synchronizer design pitfalls.", prereqs: ["metastability", "cdc"],
    reproduction: "Compute MTBF for your async FIFO synchronizers with plausible parameters.", implementation: "Add a metastability-injection model to your CDC testbench.",
    dataset: "None", tools: ["Python", "cocotb"], extension: "Compare 2- and 3-flop synchronizer MTBF at your target frequency.", portfolio: "Strengthens the async FIFO flagship write-up.",
  },
  {
    id: "mcfarling-combining", title: "Combining Branch Predictors", authors: "Scott McFarling", venue: "DEC WRL Technical Note TN-36", year: 1993, area: "arch", difficulty: 2, verified: false,
    problem: "Different branches favour different prediction strategies.", intuition: "Use a chooser to pick, per branch, between a local and a global predictor.",
    contribution: "Introduced gshare and tournament (combining) predictors.", prereqs: ["branch-prediction"],
    reproduction: "Reproduce bimodal vs gshare vs tournament accuracy trends at equal budgets on ChampSim traces.", implementation: "RTL gshare and tournament predictors in your core.",
    dataset: "ChampSim-compatible traces", tools: ["ChampSim", "Python"], extension: "Add hardware cost to the comparison.", portfolio: "Core of the branch predictor flagship.",
  },
  {
    id: "perceptron-bp", title: "Dynamic Branch Prediction with Perceptrons", authors: "Daniel A. Jimenez, Calvin Lin", venue: "HPCA", year: 2001, area: "arch", difficulty: 3, verified: false,
    problem: "Table-based predictors scale poorly with long histories.", intuition: "A tiny neural network (perceptron) per branch learns which history bits matter.",
    contribution: "Showed perceptron predictors exploit longer histories efficiently.", prereqs: ["branch-prediction"],
    reproduction: "Implement a perceptron predictor in your trace simulator and compare MPKI.", implementation: "Discuss timing of the adder tree; pipeline if needed.",
    dataset: "Branch traces", tools: ["ChampSim", "Python"], extension: "Hashed perceptron variants.", portfolio: "Research depth in the branch predictor study.",
  },
  {
    id: "jouppi-victim", title: "Improving Direct-Mapped Cache Performance by the Addition of a Small Fully-Associative Cache and Prefetch Buffers", authors: "Norman P. Jouppi", venue: "ISCA", year: 1990, area: "arch", difficulty: 2, verified: false,
    problem: "Direct-mapped caches suffer conflict misses.", intuition: "Keep a few recently evicted lines in a tiny fully associative buffer.",
    contribution: "Introduced victim caches and stream buffers.", prereqs: ["caches"],
    reproduction: "Add a victim cache to your Python cache simulator; measure conflict-miss reduction.", implementation: "Add a 4-entry victim buffer to your RTL cache.",
    dataset: "Your CPU's address traces", tools: ["Python"], extension: "Compare with increasing associativity at equal area.", portfolio: "Extension for the cache flagship.",
  },
  {
    id: "kung-systolic", title: "Why Systolic Architectures?", authors: "H. T. Kung", venue: "IEEE Computer", year: 1982, area: "aihw", difficulty: 2, verified: false,
    problem: "Computation is limited by memory bandwidth.", intuition: "Pump data rhythmically through an array of simple cells so each fetched value is reused many times.",
    contribution: "Foundational framing of systolic arrays.", prereqs: ["matmul-mac"],
    reproduction: "Cycle-level systolic matmul simulator.", implementation: "4x4 RTL array.",
    dataset: "Random matrices", tools: ["Python", "Verilator"], extension: "Compare dataflows.", portfolio: "Background for the FPGA accelerator flagship.",
  },
  {
    id: "tpu-isca", title: "In-Datacenter Performance Analysis of a Tensor Processing Unit", authors: "Norman P. Jouppi et al.", venue: "ISCA", year: 2017, area: "aihw", difficulty: 3, url: ax("1704.04760"), verified: false,
    problem: "Neural-network inference demand outgrew CPUs and GPUs in datacentres.", intuition: "A large systolic matrix unit with big on-chip buffers, specialized for inference.",
    contribution: "Real deployment data and roofline analysis of a production accelerator.", prereqs: ["systolic", "roofline"],
    reproduction: "Redo a roofline analysis for your accelerator in the paper's style.", implementation: "Weight-stationary array with unified buffer.",
    dataset: "None", tools: ["Python"], extension: "Latency-bound vs throughput-bound workloads.", portfolio: "Grounds the accelerator flagship in real design choices.",
  },
  {
    id: "eyeriss", title: "Eyeriss: A Spatial Architecture for Energy-Efficient Dataflow for Convolutional Neural Networks", authors: "Yu-Hsin Chen, Joel Emer, Vivienne Sze", venue: "ISCA", year: 2016, area: "aihw", difficulty: 4, verified: false,
    problem: "Data movement dominates CNN accelerator energy.", intuition: "Choose a dataflow (row-stationary) that maximizes reuse at every memory level.",
    contribution: "Dataflow taxonomy and energy analysis framework.", prereqs: ["systolic", "roofline"],
    reproduction: "Count memory accesses for weight-, output- and row-stationary mappings of one conv layer.", implementation: "Energy model spreadsheet or Python script.",
    dataset: "Layer shapes of a small CNN", tools: ["Python"], extension: "Apply to your accelerator's mapping.", portfolio: "Shows architecture reasoning.",
  },
  {
    id: "sze-tutorial", title: "Efficient Processing of Deep Neural Networks: A Tutorial and Survey", authors: "Vivienne Sze, Yu-Hsin Chen, Tien-Ju Yang, Joel Emer", venue: "Proceedings of the IEEE", year: 2017, area: "aihw", difficulty: 2, url: ax("1703.09039"), verified: false,
    problem: "The field of DNN hardware is broad and fragmented.", intuition: "A structured map of computation, dataflows, precision and sparsity.",
    contribution: "Widely used survey and tutorial.", prereqs: ["nn-compute"],
    reproduction: "Summarize the key metrics section and apply them to your designs.", implementation: "None required.",
    dataset: "None", tools: [], extension: "Read the book version.", portfolio: "Background reading.",
  },
  {
    id: "roofline", title: "Roofline: An Insightful Visual Performance Model for Multicore Architectures", authors: "Samuel Williams, Andrew Waterman, David Patterson", venue: "Communications of the ACM", year: 2009, area: "arch", difficulty: 2, verified: false,
    problem: "Hard to see whether code is limited by compute or memory.", intuition: "Plot attainable performance vs arithmetic intensity; the roof shows the limit.",
    contribution: "The roofline model.", prereqs: ["roofline"],
    reproduction: "Measure and plot rooflines for your laptop and your FPGA accelerator.", implementation: "Micro-benchmarks for bandwidth and peak compute.",
    dataset: "None", tools: ["Python", "C"], extension: "Hierarchical rooflines per memory level.", portfolio: "Used in every AI hardware report.",
  },
  {
    id: "jacob-quant", title: "Quantization and Training of Neural Networks for Efficient Integer-Arithmetic-Only Inference", authors: "Benoit Jacob et al.", venue: "CVPR", year: 2018, area: "aihw", difficulty: 3, url: ax("1712.05877"), verified: false,
    problem: "Floating-point inference is costly on edge hardware.", intuition: "Represent tensors as integers with scale and zero-point so inference uses only integer math.",
    contribution: "Integer-only inference scheme widely adopted in practice.", prereqs: ["quantization-sparsity", "fixed-point"],
    reproduction: "Implement integer-only inference for a small MLP and compare accuracy.", implementation: "Requantization unit in RTL.",
    dataset: "MNIST", tools: ["Python", "NumPy"], extension: "Per-channel scales.", portfolio: "Bit-exact golden model for the accelerator.",
  },
  {
    id: "deep-compression", title: "Deep Compression: Compressing Deep Neural Networks with Pruning, Trained Quantization and Huffman Coding", authors: "Song Han, Huizi Mao, William J. Dally", venue: "ICLR", year: 2016, area: "aihw", difficulty: 3, url: ax("1510.00149"), verified: false,
    problem: "Models are too large for on-chip memory.", intuition: "Remove small weights, share values, and encode efficiently.",
    contribution: "Large compression ratios with small accuracy loss.", prereqs: ["quantization-sparsity"],
    reproduction: "Prune a small model and measure accuracy vs sparsity.", implementation: "Zero-skipping MAC experiment.",
    dataset: "MNIST", tools: ["Python", "PyTorch"], extension: "Structured vs unstructured sparsity for hardware.", portfolio: "Sparsity extension of the accelerator.",
  },
  {
    id: "gemmini-paper", title: "Gemmini: Enabling Systematic Deep-Learning Architecture Evaluation via Full-Stack Integration", authors: "Hasan Genc et al.", venue: "DAC", year: 2021, area: "aihw", difficulty: 4, url: gh("ucb-bar/gemmini"), verified: true,
    problem: "Accelerator papers often ignore the full system (OS, memory, CPU).", intuition: "Evaluate accelerators inside a complete SoC with real software.",
    contribution: "Open generator and methodology for full-stack evaluation.", prereqs: ["accelerators", "hw-sw-codesign"],
    reproduction: "Study Gemmini's architecture and compare with your capstone design choices.", implementation: "Adopt its end-to-end measurement approach.",
    dataset: "Benchmarks in the repository", tools: ["Chipyard", "Gemmini"], extension: "System-level effects on your accelerator.", portfolio: "Frames the capstone.",
  },
  {
    id: "flashattention", title: "FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness", authors: "Tri Dao et al.", venue: "NeurIPS", year: 2022, area: "aihw", difficulty: 4, url: ax("2205.14135"), verified: false,
    problem: "Attention reads and writes large intermediate matrices.", intuition: "Tile the computation and use online softmax so intermediates stay on-chip.",
    contribution: "IO-aware exact attention algorithm.", prereqs: ["transformer-hw", "roofline"],
    reproduction: "Implement tiled online softmax in NumPy and compare memory traffic.", implementation: "Fixed-point online softmax unit.",
    dataset: "Random or small-model attention inputs", tools: ["Python"], extension: "Hardware tile-size sweep.", portfolio: "Basis of the attention flagship.",
  },
  {
    id: "spatten", title: "SpAtten: Efficient Sparse Attention Architecture with Cascade Token and Head Pruning", authors: "Hanrui Wang, Zhekai Zhang, Song Han", venue: "HPCA", year: 2021, area: "aihw", difficulty: 5, verified: false, researchOnly: true,
    problem: "Attention cost grows with sequence length.", intuition: "Prune unimportant tokens and heads on the fly in hardware.",
    contribution: "Algorithm-architecture co-design for sparse attention.", prereqs: ["transformer-hw"],
    reproduction: "Measure accuracy impact of token pruning on a small model.", implementation: "Top-k selection unit design sketch.",
    dataset: "Small NLP benchmark", tools: ["Python", "PyTorch"], extension: "Combine with online softmax.", portfolio: "Research extension.",
  },
  {
    id: "circuitnet-paper", title: "CircuitNet: An Open-Source Dataset for Machine Learning Applications in Electronic Design Automation", authors: "Zhuomin Chai et al.", venue: "Science China Information Sciences / arXiv", year: 2023, area: "eda", difficulty: 3, url: gh("circuitnet/CircuitNet"), verified: true,
    problem: "ML for EDA lacks open data.", intuition: "Release features and labels from many real flow runs.",
    contribution: "Open dataset with baselines for congestion, DRC and IR drop prediction.", prereqs: ["ml-for-eda"],
    reproduction: "Reproduce one provided baseline and its metrics.", implementation: "Training pipeline with held-out designs.",
    dataset: "CircuitNet", tools: ["Python", "PyTorch"], extension: "Test generalization to a new design split.", portfolio: "Core of the ML-for-EDA flagship.",
  },
  {
    id: "routenet", title: "RouteNet: Routability Prediction for Mixed-Size Designs Using Convolutional Neural Network", authors: "Zhiyao Xie et al.", venue: "ICCAD", year: 2018, area: "eda", difficulty: 3, verified: false,
    problem: "Routability problems appear only after slow routing.", intuition: "Treat placement density maps as images and predict hotspots with a CNN.",
    contribution: "Early CNN-based routability prediction.", prereqs: ["ml-prediction"],
    reproduction: "Train a small CNN on CircuitNet congestion features.", implementation: "Feature maps from ORFS placements.",
    dataset: "CircuitNet or own runs", tools: ["PyTorch"], extension: "Compare with a GNN.", portfolio: "Baseline for congestion work.",
  },
  {
    id: "timing-gnn", title: "A Timing Engine Inspired Graph Neural Network Model for Pre-Routing Slack Prediction", authors: "Zizheng Guo et al.", venue: "DAC", year: 2022, area: "eda", difficulty: 4, url: gh("TimingPredict/TimingPredict"), verified: true, researchOnly: true,
    problem: "Pre-route timing estimates are inaccurate.", intuition: "Build a GNN that mimics how STA propagates arrival times.",
    contribution: "STA-structured GNN for slack prediction with released code.", prereqs: ["ml-prediction", "sta", "graphs-in-eda"],
    reproduction: "Run the released code on the provided data and reproduce a reported metric.", implementation: "Apply to your own ORFS-generated designs.",
    dataset: "Provided with repository", tools: ["Python", "DGL/PyTorch"], extension: "Transfer to another PDK.", portfolio: "Advanced option for the ML-for-EDA flagship.",
  },
  {
    id: "alphachip-nature", title: "A graph placement methodology for fast chip design", authors: "Azalia Mirhoseini et al.", venue: "Nature", year: 2021, area: "pd", difficulty: 5, url: gh("google-research/circuit_training"), verified: true, researchOnly: true,
    problem: "Macro placement is slow and expert-driven.", intuition: "Learn a placement policy with reinforcement learning that transfers across chips.",
    contribution: "RL-based macro placement with open-sourced Circuit Training code; results debated by later studies.", prereqs: ["rl-placement"],
    reproduction: "Run Circuit Training on a small public testcase if compute allows.", implementation: "Compare with classical placers under equal budgets.",
    dataset: "Public testcases", tools: ["Circuit Training", "OpenROAD"], extension: "Fair-evaluation protocol.", portfolio: "Research literacy in the macro placement study.",
  },
  {
    id: "macroplacement-ispd", title: "Assessment of Reinforcement Learning for Macro Placement", authors: "Chung-Kuan Cheng, Andrew B. Kahng et al.", venue: "ISPD", year: 2023, area: "pd", difficulty: 4, url: gh("TILOS-AI-Institute/MacroPlacement"), verified: true, researchOnly: true,
    problem: "Claims about RL placement needed independent, open evaluation.", intuition: "Rebuild open testcases and compare methods with full-flow metrics.",
    contribution: "Open benchmarks, scripts and a critical comparison; part of an ongoing debate.", prereqs: ["rl-placement"],
    reproduction: "Rerun one comparison from the repository.", implementation: "Add your simulated-annealing placer.",
    dataset: "MacroPlacement testcases", tools: ["OpenROAD", "Python"], extension: "Sensitivity to compute budget.", portfolio: "Central to the macro placement flagship.",
  },
  {
    id: "verilogeval", title: "VerilogEval: Evaluating Large Language Models for Verilog Code Generation", authors: "Mingjie Liu, Nathaniel Pinckney, Brucek Khailany, Haoxing Ren", venue: "ICCAD", year: 2023, area: "verification", difficulty: 3, url: gh("NVlabs/verilog-eval"), verified: true, researchOnly: true,
    problem: "No standard way to measure LLM Verilog generation.", intuition: "Problems with reference testbenches; measure pass@k by simulation.",
    contribution: "Benchmark and evaluation methodology (derived largely from HDLBits-style problems).", prereqs: ["llm-hardware"],
    reproduction: "Run a subset with a chosen model and report pass@1.", implementation: "Automated harness with lint and synthesis.",
    dataset: "VerilogEval", tools: ["Python", "Icarus Verilog"], extension: "Add synthesis QoR metrics.", portfolio: "Core of the LLM-for-hardware flagship.",
  },
  {
    id: "rtllm-paper", title: "RTLLM: An Open-Source Benchmark for Design RTL Generation with Large Language Model", authors: "Yao Lu, Shang Liu, Qijun Zhang, Zhiyao Xie", venue: "ASP-DAC", year: 2024, area: "verification", difficulty: 3, url: gh("hkust-zhiyao/RTLLM"), verified: true, researchOnly: true,
    problem: "Benchmarks with larger, design-level RTL tasks were missing.", intuition: "Design-level tasks with syntax, function and quality goals.",
    contribution: "Benchmark with multi-level evaluation.", prereqs: ["llm-hardware"],
    reproduction: "Evaluate a model on several RTLLM designs.", implementation: "Extend your harness.",
    dataset: "RTLLM", tools: ["Python", "Yosys"], extension: "PPA of generated designs.", portfolio: "Complements VerilogEval.",
  },
  {
    id: "chipnemo", title: "ChipNeMo: Domain-Adapted LLMs for Chip Design", authors: "Mingjie Liu et al. (NVIDIA)", venue: "arXiv", year: 2023, area: "eda", difficulty: 4, url: ax("2311.00176"), verified: false, researchOnly: true,
    problem: "General LLMs lack chip-design domain knowledge.", intuition: "Adapt models with domain data for tasks like EDA scripting and bug summarization.",
    contribution: "Industrial case study of domain adaptation for chip design.", prereqs: ["llm-hardware"],
    reproduction: "Not reproducible independently (proprietary data); reproduce the evaluation style on public tasks.", implementation: "Retrieval-augmented assistant over open EDA docs.",
    dataset: "Public EDA documentation", tools: ["Python"], extension: "Measure answer accuracy on your own question set.", portfolio: "Context for LLM work.",
  },
  {
    id: "chip-chat", title: "Chip-Chat: Challenges and Opportunities in Conversational Hardware Design", authors: "Jason Blocklove, Siddharth Garg, Ramesh Karri, Hammond Pearce", venue: "MLCAD / arXiv", year: 2023, area: "verification", difficulty: 2, url: ax("2305.13243"), verified: false, researchOnly: true,
    problem: "Can conversation with an LLM produce a real hardware design?", intuition: "Iterative co-design between engineer and model.",
    contribution: "Case study including a taped-out design written conversationally.", prereqs: ["llm-hardware"],
    reproduction: "Repeat a small conversational design and log every correction you needed.", implementation: "Measure human effort vs model output.",
    dataset: "None", tools: ["Any LLM", "Icarus Verilog"], extension: "Compare conversational vs one-shot generation.", portfolio: "Qualitative section of the LLM flagship.",
  },
];

export const PAPER_MAP: Record<string, Paper> = Object.fromEntries(PAPERS.map((p) => [p.id, p]));
