import type { PracticeItem } from "./schema.ts";

export const PRACTICE: PracticeItem[] = [
  // Beginner RTL
  { id: "pr-edge", title: "Rising-edge detector", type: "rtl", level: "beginner", phase: "p4", topics: ["seq-modeling"],
    prompt: "Write a module that outputs a one-cycle pulse when input `sig` goes from 0 to 1. `sig` is synchronous to clk.",
    hints: ["Store last cycle's value in a flop.", "Pulse = current AND NOT previous."],
    solution: "reg prev; always @(posedge clk) prev <= sig; assign pulse = sig & ~prev; Add reset if prev must start at a known value. If sig were asynchronous, synchronize it first." },
  { id: "pr-mod10", title: "Mod-10 counter with enable and terminal count", type: "rtl", level: "beginner", phase: "p2", topics: ["registers-counters"],
    prompt: "4-bit counter counting 0..9 when en=1, synchronous reset, output tc high when count==9 and en==1.",
    hints: ["Compare against 9, not 10.", "tc is combinational from count and en."],
    solution: "always @(posedge clk) if (rst) cnt<=0; else if (en) cnt <= (cnt==9) ? 0 : cnt+1; assign tc = en && (cnt==9);" },
  { id: "pr-seq-det", title: "Overlapping 1011 detector", type: "rtl", level: "beginner", phase: "p2", topics: ["fsm"],
    prompt: "Moore FSM asserting `det` for one cycle after seeing 1011 on serial input `x`, with overlap.",
    hints: ["States track the longest suffix that is a prefix of 1011.", "After a detection, the last '1' may start a new match."],
    solution: "States S0, S1(1), S2(10), S3(101), S4(1011, det=1). From S4: x=1 -> S1, x=0 -> S2. Test with 1011011 which should detect twice." },
  // Intermediate RTL
  { id: "pr-rr", title: "Round-robin arbiter (4 requesters)", type: "rtl", level: "intermediate", phase: "p5", topics: ["arbiters"],
    prompt: "Implement a 4-way round-robin arbiter with one-hot grant and a pointer updated only when a grant occurs.",
    hints: ["Mask requests above the last grant.", "Fall back to unmasked requests if the masked set is empty.", "Isolate the lowest set bit with req & -req."],
    solution: "masked = req & ~((last_gnt << 1) - 1) style mask; pick = |masked ? lsb(masked) : lsb(req); on |req update last_gnt = pick. Assert $onehot0(gnt) and gnt & ~req == 0." },
  { id: "pr-skid", title: "Skid buffer", type: "rtl", level: "intermediate", phase: "p5", topics: ["valid-ready", "pipelined-rtl"],
    prompt: "Design a valid/ready pipeline stage whose `in_ready` is registered (no combinational path from out_ready to in_ready) without losing data.",
    hints: ["You need one extra storage slot.", "When the output stalls, the beat already accepted goes into the skid register."],
    solution: "Two registers: main and skid. in_ready = !skid_valid (registered). If out stalls while a new beat arrives, store it in skid. Output selects main; when main drains, skid moves to main. Prove with assertions: no drops, order preserved." },
  { id: "pr-gray", title: "Binary to Gray and back", type: "rtl", level: "intermediate", phase: "p5", topics: ["async-fifo"],
    prompt: "Write parameterized bin2gray and gray2bin functions.",
    hints: ["gray = bin ^ (bin >> 1)", "bin[i] = XOR of gray bits from MSB down to i."],
    solution: "bin2gray: return b ^ (b >> 1). gray2bin: loop from MSB: b[N-1]=g[N-1]; b[i]=b[i+1]^g[i]. Test exhaustively for N=4 and randomly for N=16." },
  // Debug
  { id: "db-bnb", title: "Debug: the shift register that isn't", type: "debug", level: "beginner", phase: "p4", topics: ["blocking-nonblocking"],
    prompt: "This 3-stage shift register outputs the input after 1 cycle instead of 3. Why?",
    code: "always @(posedge clk) begin\n  q1 = d;\n  q2 = q1;\n  q3 = q2;\nend",
    hints: ["Which assignment type is used?", "What value does q2 read?"],
    solution: "Blocking assignments update immediately, so q2 and q3 see the new d in the same edge; synthesis builds one flop fanned out. Use non-blocking (<=)." },
  { id: "db-width", title: "Debug: the missing carry", type: "debug", level: "beginner", phase: "p4", topics: ["verilog-operators"],
    prompt: "avg should be the average of a and b, but it is wrong whenever a + b > 255. Find the bug.",
    code: "wire [7:0] a, b, avg;\nassign avg = (a + b) >> 1;",
    hints: ["Which operands decide the width of a + b here?", "Is the carry still there when the shift happens?"],
    solution: "All operands and the target are 8 bits, so the whole expression is evaluated in 8 bits and the carry is lost before the shift. Fix: assign avg = ({1'b0, a} + {1'b0, b}) >> 1; (or compute a 9-bit sum first). Lint width warnings help catch this." },
  { id: "db-signed", title: "Debug: negative numbers compare as huge", type: "debug", level: "intermediate", phase: "p4", topics: ["verilog-operators", "alu"],
    prompt: "SLT returns 0 for a = -1, b = 1. Why?",
    code: "wire [31:0] a, b;\nassign slt = (a < b);",
    hints: ["Are a and b signed?", "What does 32'hFFFFFFFF mean unsigned?"],
    solution: "Both operands are unsigned, so -1 (0xFFFFFFFF) is the largest value. Use $signed(a) < $signed(b) for SLT and keep unsigned for SLTU." },
  { id: "db-fsm-latch", title: "Debug: FSM that sometimes freezes in synthesis", type: "debug", level: "intermediate", phase: "p5", topics: ["fsm-rtl", "latch-inference"],
    prompt: "Simulation passes, but synthesis warns about latches and the gate-level sim hangs in state WAIT.",
    code: "always @(*) begin\n  case (state)\n    IDLE: if (go) next = RUN;\n    RUN:  if (done) next = WAIT;\n    WAIT: if (ack) next = IDLE;\n  endcase\nend",
    hints: ["What is `next` when no condition is true?", "Is there a default?"],
    solution: "`next` is not assigned on every path, so a latch holds it. Add `next = state;` at the top (and a default case). Latch timing and X-initialization caused the GLS hang." },
  { id: "db-reset", title: "Debug: random start-up behaviour", type: "debug", level: "intermediate", phase: "p5", topics: ["resets"],
    prompt: "On FPGA, a design occasionally starts in the wrong state after reset release. Reset is an external button wired directly to async reset pins of all flops. What's wrong?",
    hints: ["Think about reset deassertion timing.", "Different flops see the release at different times."],
    solution: "Asynchronous deassertion near a clock edge violates recovery/removal; some flops leave reset a cycle later or go metastable. Add a reset synchronizer (async assert, sync deassert) and debounce the button." },
  { id: "db-cdc", title: "Debug: find the CDC bug", type: "debug", level: "advanced", phase: "p5", topics: ["cdc", "metastability"],
    prompt: "A 4-bit counter in clk_a is read in clk_b. Values in clk_b occasionally jump (for example 7 -> 0 -> 8). Find the problem.",
    code: "// clk_b domain\nalways @(posedge clk_b) begin\n  cnt_s1 <= cnt_a;   // 4 bits\n  cnt_s2 <= cnt_s1;\nend",
    hints: ["How many bits change from 7 to 8?", "Is each bit resolved independently?"],
    solution: "0111 -> 1000 changes all bits; each bit can resolve on a different cycle, producing values that never existed. Gray-code the counter before crossing (one bit changes), or use a handshake/async FIFO." },
  { id: "db-race", title: "Debug: testbench race", type: "debug", level: "advanced", phase: "p4", topics: ["sim-semantics"],
    prompt: "A test passes in one simulator and fails in another. The TB drives `din` with `@(posedge clk) din = val;` and the DUT samples din in always @(posedge clk). Why?",
    hints: ["Both processes wake on the same edge.", "Which runs first?"],
    solution: "Race: the TB blocking-assigns din at the same edge the DUT samples it; order is undefined. Drive with non-blocking (<=), on the opposite edge, or via a clocking block with an output skew." },
  // Waveform
  { id: "wf-handshake", title: "Waveform: was the beat transferred?", type: "waveform", level: "intermediate", phase: "p5", topics: ["valid-ready"],
    prompt: "Count the transfers and spot the protocol violation.",
    code: "cycle   1 2 3 4 5 6 7\nvalid   1 1 1 0 1 1 1\nready   0 1 1 1 0 0 1\ndata    A A B - C D D",
    hints: ["Transfer = valid && ready at the edge.", "Data must be stable while valid && !ready."],
    solution: "Transfers at cycles 2 (A), 3 (B), 7 (D). Violation at cycle 6: valid was high with ready low in cycle 5 holding C, but data changed to D before C was accepted. C was lost." },
  { id: "wf-setup", title: "Waveform: which flop captured what?", type: "waveform", level: "beginner", phase: "p2", topics: ["setup-hold"],
    prompt: "Data changes 50 ps before the clock edge; setup time is 80 ps. What is captured?",
    hints: ["Compare the arrival with the setup window."],
    solution: "The data arrives inside the setup window, so the capture is not guaranteed: the flop may capture old or new data or go metastable. STA would report a setup violation of -30 ps." },
  // Timing
  { id: "tm-fmax", title: "Timing: compute Fmax", type: "timing", level: "beginner", phase: "p2", topics: ["critical-path"],
    prompt: "Tcq = 0.12 ns, Tsu = 0.08 ns, worst logic = 2.3 ns, uncertainty = 0.1 ns. Maximum frequency?",
    hints: ["Sum all terms for the minimum period."],
    solution: "Tmin = 0.12 + 2.3 + 0.08 + 0.1 = 2.6 ns, so Fmax ~ 385 MHz." },
  { id: "tm-skew", title: "Timing: skew helps and hurts", type: "timing", level: "intermediate", phase: "p7", topics: ["clock-effects"],
    prompt: "Path: Tcq 0.2, logic max 1.5, logic min 0.1, Tsu 0.1, Th 0.15, period 2.0 (ns). Capture clock arrives 0.3 ns later than launch. Compute setup and hold slack.",
    hints: ["Positive skew adds to the setup budget and to the hold requirement."],
    solution: "Setup: required 2.0 + 0.3 - 0.1 = 2.2; arrival 1.7; slack +0.5. Hold: arrival 0.2 + 0.1 = 0.3; required 0.15 + 0.3 = 0.45; slack -0.15 (violation). Add ~0.15 ns delay on the short path." },
  // Architecture / senior
  { id: "ar-fifo-choice", title: "Choose: sync FIFO, async FIFO or handshake?", type: "architecture", level: "advanced", phase: "p5", topics: ["cdc", "sync-fifo", "async-fifo"],
    prompt: "Three crossings: (1) a 32-bit config register written once at boot, (2) a 200 MB/s stream from a 250 MHz ADC domain into a 400 MHz core, (3) data between two stages on the same clock with bursty traffic. Pick a structure for each and justify.",
    hints: ["How often does data change?", "Is there a rate mismatch or burst?"],
    solution: "(1) Quasi-static: handshake or even a synchronized 'update' pulse with stable data. (2) Async FIFO sized for burst and pointer sync latency. (3) Synchronous FIFO sized from burst length; no CDC logic needed." },
  { id: "ar-pipe-vs-par", title: "Choose: pipeline or parallelize?", type: "architecture", level: "senior", phase: "p7", topics: ["ppa", "design-tradeoffs"],
    prompt: "A filter must process 800 Msamples/s. Option A: pipeline to 800 MHz. Option B: two lanes at 400 MHz. Discuss PPA, risk and verification.",
    hints: ["What limits frequency in your technology?", "What does each option cost in area, power and complexity?"],
    solution: "A: fewer datapath copies but aggressive timing, more flops and clock power, harder closure; B: roughly double datapath area but relaxed timing, possibly lower voltage and energy per sample; requires sample demux/mux and lane-ordering verification. Choose by technology speed, power budget and area cost; often B at lower voltage wins energy." },
  { id: "th-synth-hw", title: "Explain why synthesis generated this hardware", type: "thinking", level: "intermediate", phase: "p7", topics: ["synthesis"],
    prompt: "Yosys reports a 32-bit multiplier in a design where you only wanted to multiply by 10. Why, and how would you fix it?",
    hints: ["Is the constant visible to synthesis?", "Is the operand width larger than needed?"],
    solution: "If the constant arrives via a register or port, synthesis cannot constant-fold. Make it a parameter or rewrite as (x << 3) + (x << 1). Also trim widths. Check the netlist again." },
  { id: "th-sim-vs-synth", title: "Simulation passes but synthesis fails", type: "thinking", level: "advanced", phase: "p6", topics: ["gls-lec", "latch-inference"],
    prompt: "RTL simulation passes all tests; gate-level simulation of the netlist fails at time zero with X on many outputs. List hypotheses and how you'd confirm each.",
    hints: ["What does RTL simulation initialize that silicon does not?"],
    solution: "Hypotheses: missing resets (initial blocks ignored by synthesis), latches, X-optimism in RTL if/case hiding X, uninitialized memories, reset synchronizer timing. Confirm: check synthesis warnings, find first X in GLS, compare reset values, run X-propagation checks." },
  { id: "th-reduce-ppa", title: "Reduce power without losing throughput", type: "thinking", level: "senior", phase: "p10", topics: ["ppa", "low-power-rtl", "power"],
    prompt: "An accelerator meets throughput with 30% slack in utilization but exceeds its power budget by 20%. Propose changes and their risks.",
    hints: ["Where is the power going (clock, memory, datapath)?", "Can you trade the spare throughput?"],
    solution: "Measure breakdown first. Options: clock gating idle lanes, operand isolation, lower frequency/voltage using the 30% headroom (biggest lever via V^2), fewer SRAM accesses via better reuse, narrower datapaths via quantization. Risks: timing at lower voltage, verification of gating, accuracy." },
];
