import type { LearningProject } from "./schema.ts";

// Projects added 2026-09-24. Tiers: micro = 30 min to 6 h, weekend = 6 to 16 h (mini = phase consolidation, 15-30 h).
// Embedded projects state the hardware they need and an emulator-only option where one exists.
const ms = (id: string, title: string, detail: string, evidence?: string) => ({ id, title, detail, evidence });
type P = LearningProject;
const p = (x: P): P => x;

export const VLSI_EXTRA_PROJECTS: LearningProject[] = [
  p({ id: "m-rtl-map", title: "RTL-to-hardware mapping lab: predict, synthesize, compare", tier: "micro", phase: "p4", afterTopic: "rtl-hw-mapping", level: "beginner",
    summary: "Write 12 small constructs, predict the hardware for each, then prove it with Yosys. This builds the construct-to-hardware table the VLSI roadmap video recommends.", hours: 5,
    spec: ["Constructs: case mux, if/else priority chain, casez priority encoder, comparator, adder, counter with enable, shift register, one-hot FSM, RAM template, for-loop popcount, generate array, incomplete if (latch)", "For each: a prediction written before synthesis", "Yosys: synth -top, stat and show for each; compare with the prediction"],
    milestones: [ms("a", "Predict", "Table with columns: construct, predicted hardware, predicted cell types."), ms("b", "Synthesize", "Yosys stat for all 12 designs, scripted."), ms("c", "Compare and explain", "Mark each prediction right or wrong and explain every miss.", "Mapping table and Yosys show diagrams in the README")],
    topics: ["rtl-hw-mapping", "latch-inference", "hierarchy-generate"], skills: ["hdl", "rtl"], tools: ["Yosys", "Icarus Verilog or Verilator", "Graphviz"],
    verify: "Every design also simulates against a small self-checking testbench so the mapping is of correct RTL.", expected: "A table you can reuse in interviews: code pattern -> hardware -> cost.",
    concepts: ["case vs if/else", "latch inference", "signedness and width"], stretch: "Add multiple drivers, width truncation and a combinational loop, and record the tool warnings." }),
  p({ id: "m-crc-rtl", title: "Parameterized CRC generator with a Python reference", tier: "micro", phase: "p4", afterTopic: "hierarchy-generate", level: "beginner",
    summary: "Serial and parallel CRC-8/CRC-16 in RTL, checked against a Python model. The same CRC protects the firmware images in the Embedded bootloader projects.", hours: 4,
    spec: ["Polynomial and width as parameters", "Serial (1 bit/cycle) and byte-parallel versions", "Python model generating vectors; testbench compares both RTL versions"],
    milestones: [ms("a", "Serial CRC", "LFSR-style implementation."), ms("b", "Parallel CRC", "Unrolled XOR network from a generate loop."), ms("c", "Cross-check", "10,000 random messages against Python.", "Test log and Yosys cell counts for both versions")],
    topics: ["hierarchy-generate", "registers-counters"], skills: ["rtl", "python"], tools: ["Icarus Verilog or Verilator", "Python", "Yosys"],
    verify: "Match a published CRC check value (for example CRC-16/CCITT of '123456789').", expected: "Serial is tiny and slow; parallel is larger with a longer XOR path.", concepts: ["LFSR", "generate loops", "area vs throughput"] }),
  p({ id: "m-pwm-rtl", title: "PWM generator with a register interface", tier: "micro", phase: "p5", afterTopic: "datapath-control", level: "beginner",
    summary: "A PWM block with period and duty registers and glitch-free updates: the RTL side of the Embedded timers topic.", hours: 4,
    spec: ["Registers: period, duty, enable; shadow registers updated at period end", "Assertions: output never glitches when duty changes mid-period", "Waveforms for 0%, 50%, 100% duty"],
    milestones: [ms("a", "Counter and compare", "Free-running counter and comparator."), ms("b", "Shadow registers", "Updates only at the period boundary."), ms("c", "Checks", "Assertions and a duty-cycle measurement in the testbench.", "Waveform screenshot with a mid-period duty change")],
    topics: ["datapath-control", "registers-counters"], skills: ["rtl"], tools: ["Icarus Verilog or Verilator", "GTKWave or Surfer"],
    verify: "Testbench measures high time over many periods and compares with the programmed duty.", expected: "No glitches at register updates; exact duty at edge values.", concepts: ["shadow registers", "glitch-free update"],
    stretch: "Wrap it with an APB slave and reuse it in the crossover flagship." }),
  p({ id: "m-cdc-sync", title: "CDC synchronizer lab: 2-flop, toggle and handshake", tier: "micro", phase: "p5", afterTopic: "cdc", level: "intermediate",
    summary: "Build the three classic single-signal crossings, break each one on purpose, and show the failure and the fix in simulation.", hours: 6,
    spec: ["2-flop level synchronizer", "Toggle (pulse) synchronizer for fast-to-slow events", "Req/ack handshake for a 32-bit value", "A broken variant of each (missing stage, pulse too short, bus sampled bit by bit)"],
    milestones: [ms("a", "Level sync", "Two-flop synchronizer with reset."), ms("b", "Pulse crossing", "Toggle synchronizer; show a naive 2-flop missing a pulse."), ms("c", "Handshake", "Multi-bit crossing with stable data and req/ack."), ms("d", "Broken versions", "Waveforms showing each failure.", "Before/after waveforms in the README")],
    topics: ["cdc", "metastability"], skills: ["rtl", "verification"], tools: ["Verilator or Icarus Verilog", "cocotb (optional)"],
    verify: "Randomised clock ratios; scoreboard counts events sent versus received.", expected: "No lost or duplicated events in the correct versions; visible loss in the broken ones.", concepts: ["MTBF", "pulse synchronizer", "multi-bit CDC"] }),
  p({ id: "m-mtbf-calc", title: "MTBF calculator and synchronizer-depth advisor", tier: "micro", phase: "p5", afterTopic: "cdc", level: "beginner",
    summary: "A small Python tool that computes synchronizer MTBF and recommends the number of stages for a target lifetime.", hours: 2,
    spec: ["Inputs: tau, T0, f_clk, f_data, setup time, stages", "Output: MTBF per stage count, recommendation for a target such as 1000 years", "Unit tests against hand-calculated values"],
    milestones: [ms("a", "Formula", "MTBF = e^(t_r / tau) / (T0 * f_clk * f_data)."), ms("b", "CLI and tests", "Argument parsing and pytest cases.", "README table for three clock frequencies")],
    topics: ["cdc", "metastability"], skills: ["python", "timing"], tools: ["Python", "pytest"],
    verify: "Reproduce the worked example on the Practice page (about 25 days with one stage).", expected: "Clear evidence why a single flop is never enough at GHz clocks.", concepts: ["metastability", "resolution time"] }),
  p({ id: "m-timing-parser", title: "Timing report parser: worst paths to CSV and a histogram", tier: "micro", phase: "p7", afterTopic: "sta", level: "beginner",
    summary: "Parse OpenSTA (or Yosys/OpenROAD) timing reports with Python regex, export the worst 20 paths and plot the slack distribution: the PPA-scripting skill the VLSI video stresses.", hours: 4,
    spec: ["Parse startpoint, endpoint, slack, path group", "CSV of worst N paths; histogram of slack", "Works on two different designs' reports"],
    milestones: [ms("a", "Parser", "pathlib + re, robust to formatting variations."), ms("b", "Outputs", "CSV and matplotlib histogram.", "Plot and CSV committed with the script")],
    topics: ["sta", "python-hw"], skills: ["python", "timing"], tools: ["Python", "OpenSTA"],
    verify: "Hand-check three paths against the raw report.", expected: "A reusable script for every later flow run.", concepts: ["slack", "path groups", "regex parsing"],
    stretch: "Compare two runs and report which endpoints got worse. A Perl port is optional; read legacy Perl, write new tools in Python." }),
  p({ id: "m-inverter-spice", title: "CMOS inverter VTC, delay and NAND2 sizing in ngspice", tier: "micro", phase: "p1", afterTopic: "cmos-gates", level: "intermediate",
    summary: "Simulate an inverter's transfer curve, noise margins and delay versus load, then size a NAND2 for balanced rise and fall: the CMOS basics every VLSI interview checks.", hours: 6,
    spec: ["Inverter VTC with switching threshold and noise margins", "Delay versus load capacitance sweep", "NAND2 sizing for equal rise/fall versus the inverter"],
    milestones: [ms("a", "VTC", "DC sweep and noise margins."), ms("b", "Delay sweep", "Transient simulation at several loads."), ms("c", "NAND2 sizing", "Choose widths and justify them.", "Plots and a one-page explanation")],
    topics: ["cmos-inverter", "cmos-gates", "gate-delay"], skills: ["digital", "asic"], tools: ["ngspice", "xschem (optional)", "SKY130 PDK models"],
    verify: "Compare simulated threshold and delay trends with hand calculations.", expected: "Wider PMOS moves VM up; delay grows roughly linearly with load.", concepts: ["VTC", "noise margin", "sizing"] }),
  p({ id: "m-scan-chain", title: "Scan chain by hand: shift, capture, detect a stuck-at fault", tier: "micro", phase: "p7", afterTopic: "dft", level: "intermediate",
    summary: "Convert a small sequential design to mux-D scan flops, stitch a chain and show a test pattern detecting an injected stuck-at fault.", hours: 5,
    spec: ["8-16 flop design converted to scan flops with scan_en, scan_in, scan_out", "Shift-capture-shift testbench", "Inject a stuck-at-0 on one net and detect it"],
    milestones: [ms("a", "Scan flops", "Mux-D flops and chain stitching."), ms("b", "Protocol", "Shift, capture and unload sequence."), ms("c", "Fault detection", "Pattern that detects the injected fault.", "Waveform with annotations")],
    topics: ["dft"], skills: ["dft", "rtl"], tools: ["Icarus Verilog or Verilator"],
    verify: "Good circuit and faulty circuit produce different unloaded responses.", expected: "Clear understanding of what ATPG automates.", concepts: ["scan", "stuck-at fault", "controllability and observability"] }),
  p({ id: "m-uart-sva", title: "UART verification: scoreboard, assertions, coverage and bug injection", tier: "weekend", phase: "p6", afterTopic: "coverage", level: "intermediate",
    summary: "Verify your UART the way a DV engineer would: RTL -> verify -> break -> debug -> fix -> prove.", hours: 12,
    spec: ["Layered testbench: driver, monitor, reference model, scoreboard", "SVA for framing, idle level and ready/valid handshakes", "Functional coverage: baud settings, parity modes, data corners, errors", "Five injected bugs, each caught by a test or assertion"],
    milestones: [ms("a", "Testbench", "Transaction-level driver/monitor and scoreboard."), ms("b", "Assertions", "At least six properties bound to the DUT."), ms("c", "Coverage", "Covergroups and a closure report."), ms("d", "Bug injection", "Five bugs, how each was detected and fixed.", "Coverage report and a bug table")],
    topics: ["sva", "coverage", "layered-tb", "uart"], skills: ["verification"], tools: ["Verilator 5 or a commercial simulator on EDA Playground", "cocotb (alternative)"],
    verify: "Random regression with 50 seeds passes; every injected bug is detected.", expected: "Coverage above 90% with a written explanation of any holes.", concepts: ["scoreboard", "reference model", "coverage closure"] }),
  p({ id: "m-opensta-lab", title: "OpenSTA timing lab: constraints, paths and exceptions", tier: "weekend", phase: "p7", afterTopic: "sdc", level: "intermediate",
    summary: "Write SDC for a small two-clock design and study setup, hold, false paths, multicycle paths and clock uncertainty with OpenSTA.", hours: 8,
    spec: ["Synthesize a small design with Yosys to a SKY130 library", "SDC: clocks, uncertainty, input/output delays, one false path, one multicycle path", "Reports before and after each constraint change"],
    milestones: [ms("a", "Baseline", "Synthesis and unconstrained report."), ms("b", "Constraints", "Clocks and I/O delays; interpret the worst setup and hold paths."), ms("c", "Exceptions", "False and multicycle paths with justification.", "Annotated report excerpts")],
    topics: ["sdc", "sta", "clock-effects"], skills: ["timing", "tcl"], tools: ["Yosys", "OpenSTA", "SKY130 liberty files"],
    verify: "Hand-calculate slack for one path and match the report.", expected: "You can explain every line of a timing path report.", concepts: ["setup/hold", "false path", "multicycle path"] }),
  p({ id: "m-jtag-tap", title: "JTAG TAP controller with IDCODE and a boundary-scan register", tier: "weekend", phase: "p7", afterTopic: "dft", level: "advanced",
    summary: "Implement the IEEE 1149.1 TAP state machine with IDCODE, BYPASS and a small boundary-scan register; drive it from a testbench and read it like a debugger would.", hours: 10,
    spec: ["16-state TAP FSM", "Instruction register with IDCODE, BYPASS, SAMPLE/PRELOAD, EXTEST", "Testbench that shifts IR/DR like OpenOCD does"],
    milestones: [ms("a", "TAP FSM", "All transitions with coverage."), ms("b", "Registers", "IR, IDCODE, BYPASS, boundary register."), ms("c", "Host sequence", "Read IDCODE in the testbench.", "Waveform of an IDCODE read")],
    topics: ["dft", "fsm-rtl"], skills: ["dft", "rtl", "verification"], tools: ["Verilator or Icarus Verilog", "cocotb (optional)"],
    verify: "State and transition coverage of the TAP FSM; IDCODE matches the parameter.", expected: "Connects DFT (boundary scan) with Embedded debugging (JTAG probes).", concepts: ["TAP state machine", "boundary scan", "IDCODE"] }),
  p({ id: "m-fpga-uart", title: "FPGA UART echo on real hardware", tier: "weekend", phase: "p5", afterTopic: "uart", level: "intermediate",
    summary: "Put your UART on an FPGA, echo characters from a PC terminal, and measure the bit timing with a logic analyzer.", hours: 8,
    spec: ["UART TX/RX with a small FIFO", "Echo and a simple command (for example LED control)", "Open toolchain (Yosys + nextpnr) on an iCE40/ECP5 board, or vendor tools"],
    milestones: [ms("a", "Synthesis and pinout", "Constraints file and bitstream."), ms("b", "Echo", "PC terminal round trip."), ms("c", "Measure", "Logic analyzer capture of a frame.", "Video or capture in the README")],
    topics: ["uart", "sync-fifo"], skills: ["rtl", "protocols"], tools: ["Yosys", "nextpnr", "FPGA board", "Logic analyzer"],
    verify: "Measured bit time within 2% of nominal; 10 KB transfer with no errors.", expected: "First design running on real hardware.", concepts: ["baud generation", "metastability on RX input"],
    stretch: "Talk to it from a microcontroller UART: the first VLSI + Embedded link." }),
  p({ id: "m-regress-runner", title: "Regression runner: seeds, logs, pass/fail summary and CI", tier: "weekend", phase: "p6", afterTopic: "regression-ci", level: "intermediate",
    summary: "A Python regression runner that launches tests with random seeds in parallel, collects logs, summarises failures and runs in GitHub Actions.", hours: 10,
    spec: ["Test list file with seeds and options", "Parallel runs with subprocess and timeouts", "JSON and HTML summary; rerun-failed command", "GitHub Actions workflow"],
    milestones: [ms("a", "Runner", "Launch, capture, classify."), ms("b", "Reports", "Summary with first error line per failure."), ms("c", "CI", "Workflow that runs on every push.", "CI badge and a sample report")],
    topics: ["regression-ci", "python-hw"], skills: ["python", "verification", "linux"], tools: ["Python", "GitHub Actions", "Verilator or Icarus Verilog"],
    verify: "A deliberately failing seed is reported with its reproduction command.", expected: "The same runner serves every later RTL project.", concepts: ["seeds", "triage", "CI"] }),
];

export const EMBEDDED_PROJECTS: LearningProject[] = [
  // Micro projects
  p({ id: "e-bitfield", title: "Register bitfield helpers with host unit tests", tier: "micro", phase: "e1", afterTopic: "emb-c-bits", level: "beginner",
    summary: "SET/CLEAR/TOGGLE/FIELD macros or inline functions, proven correct with host tests before they ever touch a register.", hours: 2,
    spec: ["Set, clear, toggle, test, field read and field write for 32-bit registers", "Unity tests including bit 31 and full-width fields"],
    milestones: [ms("a", "Helpers", "Macros or static inline functions using unsigned constants."), ms("b", "Tests", "At least 20 test cases.", "Test output in the README")],
    topics: ["emb-c-bits"], skills: ["cpp", "firmware"], tools: ["GCC", "Unity"], hardware: "None (host only).",
    verify: "All tests pass with -Wall -Wextra -Wconversion clean.", expected: "A tiny header reused by every later driver.", concepts: ["masks", "unsigned shifts", "read-modify-write"] }),
  p({ id: "e-crc", title: "CRC-32 utility cross-checked against Python", tier: "micro", phase: "e1", afterTopic: "emb-c-bits", level: "beginner",
    summary: "Bitwise and table-driven CRC-32 in C, validated against Python's zlib.crc32; later used by the bootloader.", hours: 2,
    spec: ["Bitwise and 256-entry table versions", "Test vector '123456789' -> 0xCBF43926", "Speed comparison on the host"],
    milestones: [ms("a", "Implementations", "Both versions."), ms("b", "Validation", "Random buffers compared with Python.", "Benchmark table")],
    topics: ["emb-c-bits"], skills: ["cpp", "firmware"], tools: ["GCC", "Python"], hardware: "None (host only).",
    verify: "Matches zlib on 1000 random buffers.", expected: "Table version several times faster, 1 KB larger.", concepts: ["CRC", "table-driven algorithms"] }),
  p({ id: "e-ringbuf", title: "Ring buffer with full unit tests", tier: "micro", phase: "e1", afterTopic: "emb-c-patterns", level: "beginner",
    summary: "The SPSC ring buffer every UART driver needs, with tests for empty, full and wrap-around.", hours: 3,
    spec: ["Power-of-two size, one slot empty", "put/get/count/free API", "Unity tests with 100% branch coverage"],
    milestones: [ms("a", "Implementation", "Header + source."), ms("b", "Tests", "Edge cases and coverage.", "gcov coverage report")],
    topics: ["emb-c-patterns", "emb-testing"], skills: ["cpp", "firmware"], tools: ["GCC", "Unity", "gcov"], hardware: "None (host only).",
    verify: "100% branch coverage.", expected: "Reused by the UART driver and CLI.", concepts: ["SPSC", "full/empty", "index wrap"] }),
  p({ id: "e-cli-parser", title: "Command parser for a UART shell", tier: "micro", phase: "e1", afterTopic: "emb-c-patterns", level: "beginner",
    summary: "Tokenise a line, look up a command table and dispatch with argc/argv, fully tested on the host.", hours: 4,
    spec: ["Command table with name, help and handler", "strtok_r-style tokenising, quoted strings optional", "help command; unknown-command handling"],
    milestones: [ms("a", "Parser", "Tokeniser and dispatch."), ms("b", "Tests", "Edge cases: empty line, extra spaces, too many args.", "Test log")],
    topics: ["emb-c-patterns"], skills: ["cpp", "firmware"], tools: ["GCC", "Unity"], hardware: "None (host only).",
    verify: "Fuzz with random input for a minute without crashes (host sanitizers on).", expected: "Drop-in CLI core for every later board project.", concepts: ["function pointers", "reentrancy"] }),
  p({ id: "e-startup-scratch", title: "Startup code and linker script from scratch", tier: "micro", phase: "e2", afterTopic: "emb-linker-startup", level: "intermediate",
    summary: "Blink with your own vector table, linker script and Reset_Handler, no vendor files; then read the map file.", hours: 6,
    spec: ["Own linker script with FLASH/RAM, .data/.bss handling", "Own startup and vector table", "Initialised global and zeroed static proven correct in GDB"],
    milestones: [ms("a", "Linker script", "Sections and symbols."), ms("b", "Startup", "Copy .data, zero .bss, call main."), ms("c", "Proof", "GDB session showing memory before and after startup.", "Annotated map file excerpt")],
    topics: ["emb-linker-startup", "emb-toolchain"], skills: ["firmware"], tools: ["arm-none-eabi-gcc", "GDB", "OpenOCD or QEMU/Renode"], hardware: "Nucleo or Pico 2 with probe; emulator-only option: QEMU or Renode Cortex-M machine.",
    verify: "Initialised variables have the right values at main; nm shows the expected layout.", expected: "You can answer 'reset to main' from your own code.", concepts: ["VMA/LMA", "vector table", "startup"] }),
  p({ id: "e-gpio-reg", title: "GPIO blink with registers only, then with the HAL", tier: "micro", phase: "e3", afterTopic: "emb-gpio", level: "beginner",
    summary: "The first rule of this track: do it once with registers, then with the abstraction, and compare.", hours: 2,
    spec: ["Register-level blink (clock enable, mode, BSRR)", "Same with HAL or SDK", "Compare code size and toggle frequency"],
    milestones: [ms("a", "Registers", "Blink with a SysTick delay."), ms("b", "HAL", "Same behaviour through the vendor API."), ms("c", "Compare", "Size and max toggle rate.", "Logic analyzer screenshots")],
    topics: ["emb-gpio", "emb-cmsis-hal"], skills: ["firmware"], tools: ["arm-none-eabi-gcc", "OpenOCD", "Logic analyzer"], hardware: "Nucleo or Pico 2; emulator-only option: Renode or Wokwi (no toggle-rate measurement).",
    verify: "Measured toggle rate and map-file sizes for both versions.", expected: "A concrete sense of what the HAL costs.", concepts: ["clock enable", "atomic set/reset"] }),
  p({ id: "e-debounce", title: "Debounced button with short and long press", tier: "micro", phase: "e3", afterTopic: "emb-gpio", level: "beginner",
    summary: "Timer-sampled debounce state machine that emits short-press and long-press events.", hours: 3,
    spec: ["5 ms sampling from a timer", "Stable-for-N filter", "Short and long press events into a queue"],
    milestones: [ms("a", "Bounce capture", "Logic analyzer capture of raw bounce."), ms("b", "FSM", "Debounce and press-length logic, host-tested."), ms("c", "On target", "Events printed over UART.", "Bounce capture and event log")],
    topics: ["emb-gpio", "emb-c-patterns"], skills: ["firmware"], tools: ["GCC", "Unity", "Logic analyzer"], hardware: "Any board plus a push button.",
    verify: "Host tests with synthetic bounce patterns; 100 presses on target with no false events.", expected: "Clean events regardless of switch quality.", concepts: ["debounce", "state machines"] }),
  p({ id: "e-baud-timer-calc", title: "UART baud and timer/PWM calculator", tier: "micro", phase: "e3", afterTopic: "emb-timers", level: "beginner",
    summary: "A command-line calculator for baud divisors and error, and timer PSC/ARR/CCR values: interview numericals made into a tool.", hours: 2,
    spec: ["Baud: divisor and percentage error for a clock and target baud", "Timer: best PSC/ARR pair for a target frequency, CCR for a duty"],
    milestones: [ms("a", "Calculator", "Python or C CLI."), ms("b", "Validation", "Check against reference manual examples.", "README with examples")],
    topics: ["emb-uart", "emb-timers"], skills: ["python", "firmware"], tools: ["Python"], hardware: "None.",
    verify: "Matches hand calculations on the Practice page.", expected: "Instant sanity checks for every later configuration.", concepts: ["baud error", "prescaler/reload"] }),
  p({ id: "e-i2c-sensor", title: "I2C sensor reader with timeouts and bus recovery", tier: "micro", phase: "e3", afterTopic: "emb-spi-i2c", level: "intermediate",
    summary: "Read a real sensor's ID and measurements with a layered driver, error codes and bus recovery at boot.", hours: 5,
    spec: ["Transport layer (register read/write) with timeouts", "Device layer: init with ID check, read and convert", "Bus recovery routine"],
    milestones: [ms("a", "Transaction", "Read the ID register; decode it on a logic analyzer."), ms("b", "Driver", "Layered API with error codes."), ms("c", "Faults", "Unplug the sensor and recover cleanly.", "Capture and error-handling log")],
    topics: ["emb-spi-i2c", "emb-drivers"], skills: ["firmware", "protocols"], tools: ["arm-none-eabi-gcc", "Logic analyzer"], hardware: "Board plus a 3.3 V I2C sensor (for example BME280 or similar) and pull-ups.",
    verify: "Readings compared with a reference; recovery works after a mid-transfer reset.", expected: "A driver pattern reused for every bus device.", concepts: ["repeated start", "NACK handling", "bus recovery"] }),
  p({ id: "e-adc-logger", title: "Timer-triggered ADC logger", tier: "micro", phase: "e3", afterTopic: "emb-adc", level: "beginner",
    summary: "Sample an analog input at an exact rate from a timer trigger and stream timestamped values over UART.", hours: 4,
    spec: ["Timer-triggered conversions at 1 kHz", "Timestamp and value over UART", "Python script plotting the stream"],
    milestones: [ms("a", "Trigger", "Timer-driven sampling."), ms("b", "Stream", "UART output and host plot.", "Plot of a known input")],
    topics: ["emb-adc", "emb-timers"], skills: ["firmware", "python"], tools: ["arm-none-eabi-gcc", "Python", "Multimeter"], hardware: "Board plus a potentiometer.",
    verify: "Sample interval jitter measured; values compared with a multimeter.", expected: "Exact sample rate independent of CPU load.", concepts: ["sample rate", "LSB size"] }),
  p({ id: "e-wdt-recovery", title: "Watchdog recovery with reset-cause logging", tier: "micro", phase: "e3", afterTopic: "emb-wdt-flash", level: "intermediate",
    summary: "Kick the watchdog only when all work loops check in, hang one on purpose, and log the reset cause after reboot.", hours: 3,
    spec: ["Independent watchdog", "Check-in flags from each loop or task", "Reset cause and a breadcrumb kept in no-init RAM"],
    milestones: [ms("a", "Check-in scheme", "Kick only when all flags are set."), ms("b", "Hang test", "Force a hang; observe reset."), ms("c", "Logging", "Cause and breadcrumb printed at boot.", "Boot log after the forced hang")],
    topics: ["emb-wdt-flash"], skills: ["firmware"], tools: ["arm-none-eabi-gcc"], hardware: "Any MCU board.",
    verify: "Forced hang always produces a watchdog reset and a correct log.", expected: "Production-grade recovery behaviour.", concepts: ["watchdog strategy", "reset causes"] }),
  p({ id: "e-uart-irq", title: "Interrupt-driven, ring-buffered UART driver", tier: "micro", phase: "e4", afterTopic: "emb-interrupts", level: "intermediate",
    summary: "RX and TX interrupts feeding ring buffers, with error counters, surviving a 10 KB burst.", hours: 6,
    spec: ["RX ISR into a ring buffer; TX from a ring buffer on TX-empty", "Overrun/framing error counters", "Non-blocking read/write API"],
    milestones: [ms("a", "RX path", "ISR and buffer."), ms("b", "TX path", "Interrupt-driven transmit."), ms("c", "Stress", "10 KB burst at 921600 baud.", "Lost-byte count and error counters")],
    topics: ["emb-uart", "emb-interrupts", "emb-c-patterns"], skills: ["firmware"], tools: ["arm-none-eabi-gcc", "Python (pyserial)"], hardware: "Board with USB-UART; emulator option: Renode UART.",
    verify: "Zero lost bytes at the tested rate; CRC over the burst matches.", expected: "The console driver for all later projects.", concepts: ["ISR design", "overrun", "SPSC"] }),
  p({ id: "e-can-id-parser", title: "CAN log parser and ID decoder", tier: "micro", phase: "e7", afterTopic: "emb-can", level: "beginner",
    summary: "Parse candump logs, decode standard/extended IDs and DLCs, and summarise traffic by ID.", hours: 2,
    spec: ["Parse candump format", "Classify 11-bit versus 29-bit IDs", "Per-ID counts and periods"],
    milestones: [ms("a", "Parser", "Python or C."), ms("b", "Report", "Table of IDs with rate and payload stats.", "Sample report")],
    topics: ["emb-can"], skills: ["protocols", "python"], tools: ["Python", "can-utils"], hardware: "None (use Linux vcan).",
    verify: "Generated test traffic with known rates is reported correctly.", expected: "Tooling reused by the CAN logger and ECU projects.", concepts: ["arbitration IDs", "DLC"] }),
  p({ id: "e-latency", title: "Measure interrupt latency and jitter", tier: "micro", phase: "e5", afterTopic: "emb-instruments", level: "intermediate",
    summary: "Drive an input edge, toggle a GPIO in the ISR, and measure latency and jitter under different loads and priorities.", hours: 3,
    spec: ["Edge source (signal generator, second board or timer output)", "GPIO toggle as the first ISR instruction", "Measurements idle, under load, with a higher-priority ISR active"],
    milestones: [ms("a", "Setup", "Wiring and capture configuration."), ms("b", "Measurements", "Latency distribution per scenario.", "Histogram or capture table")],
    topics: ["emb-instruments", "emb-interrupts"], skills: ["firmware"], tools: ["Logic analyzer or oscilloscope"], hardware: "Board plus logic analyzer.",
    verify: "Repeat 1000 edges per scenario.", expected: "Numbers you can quote: typical and worst-case latency.", concepts: ["latency", "jitter", "priority"] }),
  // Debugging labs: reproduce -> inspect -> instrument -> diagnose -> fix -> verify
  p({ id: "d-race", title: "Debug lab: race condition between an ISR and main", tier: "micro", phase: "e4", afterTopic: "emb-interrupts", level: "intermediate",
    summary: "Reproduce lost updates on a shared counter, prove the cause, fix it three ways and verify.", hours: 3,
    spec: ["ISR and main both update a counter", "Detect loss by comparing with an independent count", "Fixes: critical section, atomic, redesign with SPSC"],
    milestones: [ms("a", "Reproduce", "Measurable loss rate."), ms("b", "Diagnose", "Disassembly showing the non-atomic read-modify-write."), ms("c", "Fix and verify", "Zero loss over a long run.", "Before/after loss counts")],
    topics: ["emb-interrupts"], skills: ["firmware"], tools: ["GDB", "Logic analyzer"], hardware: "Any board; emulator option: QEMU (less realistic timing).",
    verify: "Zero lost updates over 10 million events.", expected: "You can explain the race from the instruction listing.", concepts: ["atomicity", "critical sections"] }),
  p({ id: "d-dma-cache", title: "Debug lab: DMA data corruption", tier: "micro", phase: "e4", afterTopic: "emb-dma", level: "advanced",
    summary: "Reproduce corruption from a DMA buffer that goes out of scope (any Cortex-M) or from cache incoherence (Cortex-M7), then fix and verify with checksums.", hours: 5,
    spec: ["Pattern data with CRC", "Bug 1: DMA into a stack buffer", "Bug 2 (M7): missing cache invalidate", "Fixes with evidence"],
    milestones: [ms("a", "Reproduce", "CRC mismatches logged."), ms("b", "Diagnose", "Watchpoints and memory dumps."), ms("c", "Fix", "Static buffers, cache maintenance, alignment.", "Mismatch counts before and after")],
    topics: ["emb-dma"], skills: ["firmware"], tools: ["GDB", "OpenOCD"], hardware: "Any Cortex-M board with DMA; a Cortex-M7 board for the cache case.",
    verify: "Zero CRC mismatches in a one-hour run.", expected: "Interview-ready story about DMA pitfalls.", concepts: ["buffer lifetime", "cache coherence"] }),
  p({ id: "d-hardfault", title: "Debug lab: HardFault forensics", tier: "micro", phase: "e5", afterTopic: "emb-faults", level: "intermediate",
    summary: "Trigger four fault types and decode each from fault registers and the stacked frame, then add a crash record that survives reset.", hours: 4,
    spec: ["Null function pointer, divide by zero (trap enabled), unaligned access, invalid address", "Fault handler saving registers to no-init RAM", "Report printed at next boot"],
    milestones: [ms("a", "Trigger", "Four reproducible faults."), ms("b", "Decode", "CFSR/HFSR/BFAR analysis for each."), ms("c", "Crash record", "Persisted and printed after reset.", "Decoded fault table")],
    topics: ["emb-faults", "emb-gdb-openocd"], skills: ["firmware"], tools: ["GDB", "addr2line"], hardware: "Cortex-M3/M4/M7/M33 board (M0 has fewer fault registers); emulator option: QEMU for some cases.",
    verify: "Each fault's PC maps to the right source line.", expected: "A fault handler you reuse everywhere.", concepts: ["CFSR", "exception frame", "EXC_RETURN"] }),
  p({ id: "d-stack-overflow", title: "Debug lab: stack overflow detection", tier: "micro", phase: "e5", afterTopic: "emb-faults", level: "intermediate",
    summary: "Overflow a task stack, then catch it three ways: painting, RTOS hook and MPU guard.", hours: 3,
    spec: ["Recursive or large-local function", "Stack painting high-water mark", "RTOS overflow hook", "MPU guard region (where available)"],
    milestones: [ms("a", "Reproduce", "Corruption observed."), ms("b", "Detect", "Three detection methods."), ms("c", "Size", "Right-size stacks from measurements.", "High-water table per task")],
    topics: ["emb-faults", "emb-freertos"], skills: ["firmware", "rtos"], tools: ["FreeRTOS", "GDB"], hardware: "Cortex-M board (MPU for the guard method).",
    verify: "Each method fires before silent corruption.", expected: "Measured stack budgets for every task.", concepts: ["stack painting", "MPU"] }),
  p({ id: "d-i2c-lock", title: "Debug lab: I2C bus lock", tier: "micro", phase: "e5", afterTopic: "emb-instruments", level: "intermediate",
    summary: "Reset the MCU mid-transfer until a slave holds SDA low, capture it, and implement recovery.", hours: 3,
    spec: ["Trigger resets during reads", "Capture the stuck bus", "9-clock recovery + STOP; run at boot and on timeout"],
    milestones: [ms("a", "Reproduce", "Bus stuck low."), ms("b", "Instrument", "Capture before and after."), ms("c", "Fix", "Recovery routine.", "Captures and recovery log")],
    topics: ["emb-spi-i2c", "emb-instruments"], skills: ["firmware", "protocols"], tools: ["Logic analyzer"], hardware: "Board plus I2C sensor.",
    verify: "100 forced lockups all recovered.", expected: "A classic interview answer backed by evidence.", concepts: ["open-drain", "bus recovery"] }),
  p({ id: "d-prio-inversion", title: "Debug lab: priority inversion", tier: "micro", phase: "e6", afterTopic: "emb-rtos-sync", level: "advanced",
    summary: "Reproduce unbounded priority inversion with three FreeRTOS tasks, trace it, and fix it with a mutex.", hours: 4,
    spec: ["Low task holds a binary semaphore; medium task busy-loops; high task waits", "GPIO markers per task", "Fix with a mutex (inheritance)"],
    milestones: [ms("a", "Reproduce", "High task's wait time explodes."), ms("b", "Trace", "Logic analyzer timeline."), ms("c", "Fix", "Mutex; bounded wait.", "Before/after timelines")],
    topics: ["emb-rtos-sync", "emb-freertos"], skills: ["rtos"], tools: ["FreeRTOS", "Logic analyzer"], hardware: "Any Cortex-M board; emulator option: QEMU with timestamps.",
    verify: "High task's worst wait bounded by the low task's critical section.", expected: "The Mars Pathfinder story, reproduced on your desk.", concepts: ["priority inheritance"] }),
  // Weekend projects
  p({ id: "w-uart-cli", title: "UART driver + command-line shell", tier: "weekend", phase: "e4", afterTopic: "emb-drivers", level: "intermediate",
    summary: "Combine the interrupt UART driver, ring buffer and command parser into a diagnostic shell with peripheral commands.", hours: 10,
    spec: ["Commands: help, version, reg read/write (guarded), gpio, i2c scan, reset-cause, uptime", "Line editing (backspace) and history (optional)", "Host tests for the command layer"],
    milestones: [ms("a", "Integrate", "Driver + parser."), ms("b", "Commands", "At least eight commands."), ms("c", "Tests and docs", "Host tests and a command reference.", "Terminal session recording")],
    topics: ["emb-drivers", "emb-uart", "emb-c-patterns"], skills: ["firmware"], tools: ["arm-none-eabi-gcc", "Unity"], hardware: "Board with USB-UART; emulator option: Renode.",
    verify: "Scripted session via pyserial checks every command.", expected: "Reusable diagnostics for every later project.", concepts: ["driver layering", "command tables"] }),
  p({ id: "w-dma-daq", title: "DMA-based data acquisition with double buffering", tier: "weekend", phase: "e4", afterTopic: "emb-dma", level: "advanced",
    summary: "Timer-triggered multi-channel ADC into circular DMA with half/complete processing, streamed to a PC.", hours: 12,
    spec: ["4 channels at 10 kHz each", "Circular DMA, half/complete callbacks", "Block statistics and UART/USB streaming", "CPU-load measurement"],
    milestones: [ms("a", "Acquisition", "Timer + ADC + DMA."), ms("b", "Processing", "Double-buffer handling within deadline."), ms("c", "Measure", "CPU load and missed-block counter.", "CPU load and timing captures")],
    topics: ["emb-dma", "emb-adc", "emb-timers"], skills: ["firmware"], tools: ["arm-none-eabi-gcc", "Python", "Logic analyzer"], hardware: "STM32 Nucleo (or similar) plus analog sources.",
    verify: "Zero missed blocks over one hour; known input reproduced on the PC.", expected: "CPU load a fraction of the interrupt-per-sample design.", concepts: ["circular DMA", "ping-pong buffers"] }),
  p({ id: "w-ci-firmware", title: "Firmware CI pipeline with emulator tests", tier: "weekend", phase: "e5", afterTopic: "emb-ci-static", level: "intermediate",
    summary: "GitHub Actions that cross-builds, runs unit tests and static analysis, archives artifacts, and runs the firmware in Renode.", hours: 8,
    spec: ["Pinned toolchain container", "Warnings as errors, Unity tests, cppcheck", "Artifacts: ELF, bin, map, size report", "Renode job asserting the UART prompt"],
    milestones: [ms("a", "Build job", "Reproducible cross-build."), ms("b", "Quality jobs", "Tests and analysis."), ms("c", "Emulator job", "Renode test.", "CI badge and a blocked PR with a planted bug")],
    topics: ["emb-ci-static", "emb-emulation-hil", "emb-testing"], skills: ["firmware", "linux"], tools: ["GitHub Actions", "Renode", "cppcheck", "Unity"], hardware: "None required.",
    verify: "A planted bug fails CI.", expected: "Every later project inherits this pipeline.", concepts: ["reproducible builds", "static analysis"] }),
  p({ id: "w-freertos-sensor", title: "FreeRTOS sensor node: acquisition, logging and watchdog tasks", tier: "weekend", phase: "e6", afterTopic: "emb-freertos", level: "intermediate",
    summary: "Sensor, processing, logger, CLI and watchdog tasks communicating through queues and notifications, with measured stacks.", hours: 14,
    spec: ["Sensor task (I2C) posting to a queue", "Processing task (filtering) and logger task", "Watchdog task with check-ins", "Static allocation; stack high-water report command"],
    milestones: [ms("a", "Tasks", "Architecture diagram and task table (priority, period, stack)."), ms("b", "Communication", "Queues, notifications, mutex for the bus."), ms("c", "Robustness", "Watchdog, error handling, stack report.", "Task timing capture and stack table")],
    topics: ["emb-freertos", "emb-rtos-sync", "emb-drivers"], skills: ["rtos", "firmware"], tools: ["FreeRTOS", "arm-none-eabi-gcc", "Logic analyzer"], hardware: "Board plus I2C sensor; emulator option: QEMU with a simulated sensor task.",
    verify: "24-hour soak run with no resets; deadlines measured.", expected: "A clean RTOS reference architecture.", concepts: ["task design", "stack sizing", "watchdog"] }),
  p({ id: "w-zephyr-sensor", title: "Zephyr sensor application with devicetree overlay and Twister tests", tier: "weekend", phase: "e6", afterTopic: "emb-zephyr", level: "intermediate",
    summary: "Re-implement the sensor node the Zephyr way: devicetree, Kconfig, sensor API, logging, shell and Twister tests.", hours: 12,
    spec: ["Overlay adding the sensor", "Sensor API, work queue, logging", "Shell commands", "ztest unit tests run with Twister (native_sim plus board)"],
    milestones: [ms("a", "Board and overlay", "Sensor visible in the final devicetree."), ms("b", "Application", "Periodic reading and shell."), ms("c", "Tests", "Twister run in CI.", "Twister report")],
    topics: ["emb-zephyr", "emb-devicetree"], skills: ["rtos", "firmware"], tools: ["Zephyr", "west", "Twister"], hardware: "A Zephyr-supported board (Nordic DK, STM32 Nucleo, RP2040/RP2350) plus sensor; emulator option: native_sim with an emulated sensor.",
    verify: "Twister passes on native_sim and hardware.", expected: "A comparison note: FreeRTOS versus Zephyr for the same app.", concepts: ["devicetree", "Kconfig", "driver model"] }),
  p({ id: "w-can-logger", title: "CAN logger with timestamps", tier: "weekend", phase: "e7", afterTopic: "emb-can", level: "intermediate",
    summary: "Two CAN nodes (or loopback), acceptance filters, timestamped logging in candump-compatible format, bus-off recovery.", hours: 10,
    spec: ["500 kbit/s bit timing", "Filters and interrupt-driven RX", "Timestamped log to UART or SD", "Error counters and bus-off recovery"],
    milestones: [ms("a", "Link", "Two nodes exchange frames."), ms("b", "Logger", "Timestamped candump-format output."), ms("c", "Errors", "Remove termination; observe and recover.", "Captures and error-state log")],
    topics: ["emb-can"], skills: ["protocols", "firmware"], tools: ["CAN transceivers", "can-utils", "Logic analyzer"], hardware: "Two CAN-capable MCU boards with transceivers, or one board plus a USB-CAN adapter; emulator option: Linux vcan for the host side.",
    verify: "Logs replay correctly with canplayer; error states match theory.", expected: "Foundation for the automotive branch.", concepts: ["bit timing", "error states"] }),
  p({ id: "w-mqtt-node", title: "MQTT sensor node over TLS with reconnection and OTA hooks", tier: "weekend", phase: "e7", afterTopic: "emb-iot-proto", level: "intermediate",
    summary: "ESP32 (ESP-IDF) or a Zephyr board publishing telemetry to a broker over TLS, with reconnect backoff, offline buffering and a command topic.", hours: 14,
    spec: ["Wi-Fi with credentials in NVS", "MQTT over TLS with server certificate validation", "Telemetry and command topics; last will", "Backoff reconnect and offline buffer"],
    milestones: [ms("a", "Connectivity", "Wi-Fi and reconnect."), ms("b", "Secure MQTT", "TLS with CA validation; wrong CA rejected."), ms("c", "Robustness", "Broker restart and Wi-Fi loss tests.", "Broker logs and test notes")],
    topics: ["emb-iot-proto", "emb-wireless", "emb-tcpip"], skills: ["protocols", "firmware"], tools: ["ESP-IDF or Zephyr", "Mosquitto", "Wireshark"], hardware: "ESP32 dev board or a Wi-Fi-capable Zephyr board.",
    verify: "Survives broker restart and 30-minute Wi-Fi outage without manual reset.", expected: "Production-style connectivity layer.", concepts: ["QoS", "TLS validation", "backoff"] }),
  p({ id: "w-ble-sensor", title: "Bluetooth LE sensor peripheral", tier: "weekend", phase: "e7", afterTopic: "emb-wireless", level: "intermediate",
    summary: "A GATT service exposing sensor data with notifications, readable from a phone app, with measured power per connection interval.", hours: 12,
    spec: ["Custom GATT service and characteristics", "Notifications at a configurable rate", "Current measurement at two connection intervals"],
    milestones: [ms("a", "Advertising", "Discoverable device."), ms("b", "GATT", "Service, characteristics and notifications."), ms("c", "Power", "Current per interval.", "Phone screenshots and current table")],
    topics: ["emb-wireless", "emb-power"], skills: ["protocols", "firmware"], tools: ["nRF Connect SDK/Zephyr or ESP-IDF", "nRF Connect mobile app"], hardware: "Nordic DK or ESP32 board.",
    verify: "Notifications received for one hour without disconnects.", expected: "BLE fundamentals with power evidence.", concepts: ["GATT", "connection interval"] }),
  p({ id: "w-uart-bootloader", title: "UART bootloader with CRC, versioning and recovery", tier: "weekend", phase: "e8", afterTopic: "emb-bootloader", level: "advanced",
    summary: "Receive an image over UART, validate header and CRC, program flash, and jump cleanly; recover from corrupt images and power loss.", hours: 14,
    spec: ["Flash map: bootloader, app slot, metadata", "Image header with magic, version, size, CRC-32", "Host upload script with retries", "Recovery on button or invalid image"],
    milestones: [ms("a", "Layout", "Linker scripts for bootloader and app."), ms("b", "Transfer", "Protocol with acknowledgements."), ms("c", "Jump", "Clean handover (VTOR, MSP)."), ms("d", "Faults", "Corrupt image and power-cut tests.", "Test matrix results")],
    topics: ["emb-bootloader", "emb-wdt-flash", "emb-uart"], skills: ["firmware"], tools: ["arm-none-eabi-gcc", "Python (pyserial)"], hardware: "STM32 Nucleo or similar.",
    verify: "100 update cycles with random power cuts never brick the board.", expected: "Deep understanding before adopting MCUboot.", concepts: ["image header", "VTOR", "fail-safe update"] }),
  p({ id: "w-spi-flash-fs", title: "SPI NOR flash driver + littlefs configuration store", tier: "weekend", phase: "e8", afterTopic: "emb-storage", level: "intermediate",
    summary: "Driver for an external SPI NOR chip, littlefs on top, and a power-fail-safe configuration store with random power-cut testing.", hours: 12,
    spec: ["JEDEC ID, read, page program, sector erase, status polling", "littlefs port", "Config store with version and CRC", "Automated power-cut test"],
    milestones: [ms("a", "Driver", "Verified against the datasheet."), ms("b", "Filesystem", "littlefs mounted."), ms("c", "Power-loss", "1000 random cuts.", "Integrity test results")],
    topics: ["emb-storage", "emb-spi-i2c", "emb-drivers"], skills: ["firmware"], tools: ["littlefs", "Logic analyzer"], hardware: "Board plus SPI NOR module; power cutting via a relay or controllable supply.",
    verify: "No corrupted config after 1000 cuts.", expected: "Evidence of production-quality storage.", concepts: ["wear levelling", "copy-on-write"] }),
  p({ id: "w-linux-chardrv", title: "Linux character and platform driver on QEMU", tier: "weekend", phase: "e9", afterTopic: "emb-linux-drivers", level: "advanced",
    summary: "A misc character driver with a ring buffer, then a platform driver bound through a device-tree node, tested from user space.", hours: 14,
    spec: ["Out-of-tree module build against your target kernel", "read/write/poll/ioctl", "Platform driver with of_match_table and a DT node (overlay or modified DTS)", "sysfs attribute and a user-space test program"],
    milestones: [ms("a", "Char driver", "Loads, reads, writes."), ms("b", "Platform driver", "Probes from device tree."), ms("c", "Testing", "Load/unload loops and a user-space test.", "dmesg logs and test output")],
    topics: ["emb-linux-drivers", "emb-devicetree"], skills: ["emblinux"], tools: ["QEMU", "Linux kernel sources", "cross toolchain"], hardware: "None required (QEMU aarch64 virt); optional Raspberry Pi or BeagleBone.",
    verify: "100 load/unload cycles; lockdep clean on a debug kernel.", expected: "BSP-role interview evidence.", concepts: ["probe/remove", "copy_to_user", "locking"] }),
  p({ id: "w-buildroot-image", title: "Buildroot image with a custom package and init script", tier: "weekend", phase: "e9", afterTopic: "emb-buildroot", level: "intermediate",
    summary: "A reproducible Buildroot image in a BR2_EXTERNAL tree, containing your daemon as a package with an init script, booted in QEMU or on a Pi.", hours: 10,
    spec: ["BR2_EXTERNAL with defconfig, package and rootfs overlay", "Custom package for your sensor daemon", "Init script starting it at boot", "CI build of the defconfig"],
    milestones: [ms("a", "Baseline", "QEMU image boots."), ms("b", "Package", "Daemon packaged and started."), ms("c", "Reproducible", "Clean build from the repository.", "Boot log and image size")],
    topics: ["emb-buildroot", "emb-linux-boot"], skills: ["emblinux", "linux"], tools: ["Buildroot", "QEMU"], hardware: "None required; optional Raspberry Pi.",
    verify: "Fresh clone builds and boots with the daemon running.", expected: "Stepping stone to the Yocto BSP flagship.", concepts: ["defconfig", "BR2_EXTERNAL"] }),
  p({ id: "w-uds-sim", title: "UDS over ISO-TP diagnostic simulator (SocketCAN)", tier: "weekend", phase: "e10", afterTopic: "emb-automotive", level: "advanced",
    summary: "An ECU simulator on Linux vcan implementing a few UDS services over ISO-TP, and a tester script that queries it.", hours: 14,
    spec: ["ISO-TP segmentation (single, first, consecutive, flow control)", "Services 0x10, 0x22, 0x2E, 0x3E, 0x11 with negative responses", "Tester client with timeouts"],
    milestones: [ms("a", "Transport", "ISO-TP working both ways."), ms("b", "Services", "UDS dispatcher and DIDs."), ms("c", "Tester", "Automated test script.", "Trace of a full session")],
    topics: ["emb-automotive", "emb-can"], skills: ["protocols"], tools: ["SocketCAN", "Python (python-can)"], hardware: "None required (vcan); optional USB-CAN adapter.",
    verify: "Every service and error path covered by the tester.", expected: "Automotive diagnostics fluency.", concepts: ["UDS", "ISO-TP", "negative responses"] }),
  p({ id: "w-pid-motor", title: "PID motor speed control with an encoder", tier: "weekend", phase: "e10", afterTopic: "emb-control", level: "advanced",
    summary: "Timer encoder mode, PWM output and a fixed-rate PID loop with anti-windup, tuned from logged step responses.", hours: 12,
    spec: ["Encoder speed measurement", "PID at 1 kHz from a timer interrupt or high-priority task", "Anti-windup and output limits", "Logged step responses plotted on the PC"],
    milestones: [ms("a", "Sensing", "Speed from encoder."), ms("b", "Control", "PID with anti-windup."), ms("c", "Tuning", "Three tunings compared.", "Step-response plots")],
    topics: ["emb-control", "emb-timers"], skills: ["firmware"], tools: ["Python (matplotlib)", "Logic analyzer"], hardware: "Board, small DC motor with encoder, motor driver, separate supply.",
    verify: "Loop jitter measured; settling time and overshoot reported.", expected: "Robotics-branch evidence.", concepts: ["PID", "anti-windup", "loop timing"] }),
  p({ id: "w-dsp-filter", title: "FIR/IIR filtering and FFT spectrum with CMSIS-DSP", tier: "weekend", phase: "e10", afterTopic: "emb-dsp", level: "intermediate",
    summary: "Filter ADC data with CMSIS-DSP in float and Q15, compute a spectrum, and compare accuracy and cycles against a Python reference.", hours: 10,
    spec: ["Low-pass FIR and a biquad", "512-point real FFT", "Float versus Q15 accuracy and cycle counts"],
    milestones: [ms("a", "Reference", "SciPy design and test vectors."), ms("b", "On target", "CMSIS-DSP kernels."), ms("c", "Compare", "Error and cycle table.", "Plots and table")],
    topics: ["emb-dsp", "emb-performance"], skills: ["firmware"], tools: ["CMSIS-DSP", "Python (SciPy)"], hardware: "Cortex-M4F/M7 board; emulator option: host build of CMSIS-DSP for accuracy (no cycles).",
    verify: "Output within tolerance of SciPy for the same inputs.", expected: "Concrete fixed-point versus float trade-offs.", concepts: ["FIR/IIR", "Q15", "FFT bins"] }),
  p({ id: "w-tinyml", title: "TinyML vibration anomaly detector or gesture classifier", tier: "weekend", phase: "e10", afterTopic: "emb-tinyml", level: "advanced",
    summary: "Collect accelerometer data, train and quantise a small model, deploy it with TFLite Micro/CMSIS-NN, and report accuracy, latency, RAM and energy.", hours: 14,
    spec: ["Data collection script", "Training and int8 quantisation", "On-device inference with feature parity", "Metrics table"],
    milestones: [ms("a", "Data", "Labelled dataset."), ms("b", "Model", "Quantised model and PC accuracy."), ms("c", "Device", "On-device accuracy, latency, RAM, energy.", "Metrics table and demo video")],
    topics: ["emb-tinyml", "emb-dsp"], skills: ["firmware", "aihw", "python"], tools: ["TFLite Micro or Edge Impulse", "CMSIS-NN", "Python"], hardware: "Cortex-M4F or better with an IMU.",
    verify: "On-device accuracy within a few points of the PC model on held-out data.", expected: "Edge-AI evidence built on real fundamentals.", concepts: ["quantisation", "tensor arena", "feature parity"] }),
];
